### ISSUE TITLE
stopWithApp is not working as intended for Android. 

### ISSUE THREAD

**Issue by Sathyanarayan09** [react-native-kit/react-native-track-player#1000]
while performing any action with Android widget we are receiving n number of calls for n number of force closing of the app. ie instance of the player is not getting killed after closing the app and keeps triggering service methods like (remote-next, previous, play) as many number of time the app was opened and closed. 

- using latest version @1.2.3 
- using stopWithApp: true at setupPlayer()
- calling setupPlayer at root level only once. 
 
Environment (please complete the following information): Android

**Comment by sirakoff** [comment]
Try invoking `TrackPlayer.destroy()` in `componentWillUnmount` of the root Component in your app or in the callback function of `useEffect` of the root component like:

```
useEffect(() => {

   return () => {

        TrackPlayer.destroy();

   }

}, [])
```

**Comment by Sathyanarayan09** [comment]
https://github.com/react-native-kit/react-native-track-player/issues/433#issuecomment-461083012 fixes the issue.
