### ISSUE TITLE
Trying to use the v2 with Expo

### ISSUE THREAD

**Issue by ShivamJoker** [react-native-kit/react-native-track-player#1008]
# Invariant Violation Native module can't be null

1. Create expo project
2. Install the library ` expo install react-native-track-player@next`
3. Tried adding index.js and registered the module

**Environment **
expo version - 3.22.3

**Comment by farshed** [comment]
I don't think you can use react-native-track-player with Expo since this is a native module

**Comment by ShivamJoker** [comment]
Ohh but I thought this has expo support

**Comment by farshed** [comment]
This is from the docs

> **Expo and Expokit support**
> Currently react-native-track-player does not support projects with Expo or Expokit.

Source: https://react-native-track-player.js.org/install/

**Comment by ShivamJoker** [comment]
Oh okay I will close this issue then. Thanks for the confirmation
