### ISSUE TITLE
Couldn't find package "@raydeck/xcode@^2.2.0" required by "react-native-swift" on the "npm" registry.

### ISSUE THREAD

**Issue by simenolav93** [react-native-kit/react-native-track-player#1011]
**Describe the bug**
I cannot install the react-native-swift. The npmjs library seem to be removed or unavailable. I know this is not directly a problem with the react-native-track-player but this makes it unable to use.

If someone have a solution or workaround that would be great. 

**To Reproduce**
- yarn add react-native-track-player
- yarn add react-native-swift (unable to install  with the error: Couldn't find package "@raydeck/xcode@^2.2.0" required by "react-native-swift" on the "npm" registry.)

**Environment**:
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 3.13 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: ~0.61.4 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Code**
yarn add react-native-swift

**Comment by saudahmed** [comment]
I confirm this, It is happening to me as well.

**Comment by irekrog** [comment]
It was global accident with npm / yarn https://github.com/yarnpkg/yarn/issues/8279

**Comment by simenolav93** [comment]
This is no longer a problem. As @irekrog said; it was a global issue with npm /yarn.
