### ISSUE TITLE
react-native-track-player not playing song requested from Express server

### ISSUE THREAD

**Issue by gustavo-dev** [react-native-kit/react-native-track-player#1017]
**Describe the bug**
Music requested from my expressjs server is not being played

**To Reproduce**
I've posted a StackOverflow question with all the details. 
https://stackoverflow.com/questions/63377867/react-native-track-player-not-playing-song-requested-from-express-server

**Environment (please complete the following information):**
System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 6.75 GB / 15.91 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.6.30128.74 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: 3.8.5
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

**Code**
I've posted a StackOverflow question with all the details. 
https://stackoverflow.com/questions/63377867/react-native-track-player-not-playing-song-requested-from-express-server

**Comment by VictorKolb** [comment]
Hey Gustavo!
I think you should use something like this:

```ts
app.get(
  "/music/:fileName",
  async (req: Request, res: Response) => {
    try {
      const { fileName } = req.params;
      const filePath = `music/${fileName}`;
      const stream = fs.createReadStream(filePath);
      const stat = fs.statSync(filePath);

      res.set("content-type", "audio/mpeg");
      res.set("Content-Range", `bytes ${0}-${stat.size - 1}/${stat.size}`);
      res.set("accept-ranges", "bytes");
      res.set("Content-Length", `${stat.size}`);

      stream.pipe(res);
    } catch (err) {
      console.error(err);
    }
  },
);
```

**Comment by gustavo-dev** [comment]
Hi @VictorKolb, I tried it and it didn't work.
When I make the request, the Player enters on "Buffering" State and then return an error:
```
[Mon Aug 31 2020 15:45:56.624]  LOG      Buffering 6
[Mon Aug 31 2020 15:46:31.404]  LOG      {"code": "playback-source", "message": "Unable to connect to http://x.x.x.x:5000/api/songs/song.mp3", "type": "playback-error"}
[Mon Aug 31 2020 15:46:31.471]  LOG      None 0
```

**Comment by gustavo-dev** [comment]
Hey @VictorKolb! Thank you, for your sollution, but there's still a problem. The song is successfully requested, Player state is set to "Playing", but the audio, however, is not played. ProgressBar component shows that the music is playing, but no sound is heard.

**Comment by VictorKolb** [comment]
@gustavo-dev sounds weird. Have you double-check, maybe the sound on the phone was turned off? :D

**Comment by gustavo-dev** [comment]
@VictorKolb hahaha, I actually did check it to see if it was off, but It wasn't :P. Not even my browser is playing the sound.

**Comment by gustavo-dev** [comment]
UPDATE: I tried switching to `ogg` type of file and it works. I wonder why it doesn't with `mp3`. If you know why it doesn't work with `mp3`, let me know.
