### ISSUE TITLE
typescript: usePlaybackState has not exported

### ISSUE THREAD

**Issue by itsgracian** [react-native-kit/react-native-track-player#1026]
**Describe the bug**
I am getting waring (Module '"../../../../node_modules/react-native-track-player"' has no exported member 'useTrackPlayerProgress'.) when I am importing hook like usePlaybackState, useTrackPlayerProgress and  useTrackPlayerEvents.
would you help me how i could fix this problem?

**Code**
`import TrackPlayer, {
  usePlaybackState,
  useTrackPlayerProgress,
  useTrackPlayerEvents,

} from 'react-native-track-player';`

**Comment by TowhidKashem** [comment]
@itsgracian hey did you find a solution to this? I'm getting it also..

**Comment by itsgracian** [comment]
Hello, @TowhidKashem yes. uninstall react-native-track-player and install **yarn add react-native-track-player@next**

**Comment by itsgracian** [comment]
@TowhidKashem  this hooks **useTrackPlayerProgress** was changed to **useProgress**

**Comment by TowhidKashem** [comment]
That will install v2 of the library though and I'm not 100% sure but I think that's still in beta (or at least it doesn't seem to me very stable from some comments). I think I'll just deal with the TS error with a ts-ignore ignore comment for now, although it doesn't make sense how it's even working with the renaming but it is.

**Comment by pachun** [comment]
I'm able to import it by reaching directly into the package's `hooks` directory:

```typescript
import { useTrackPlayerProgress } from "react-native-track-player/lib/hooks"
```

I know the issue is closed, but maybe that will help anyone else who winds up reading this issue.

**Comment by ngocdaothanh** [comment]
Hi, would you please release a new version with the fix?

**Comment by ShivamJoker** [comment]
The full path `"react-native-track-player/lib/hooks"` hook only works in iOS if we directly import then it works in android what to do in such a situation ?
