### ISSUE TITLE
Track-Player appears to loop three times when launching playlist

### ISSUE THREAD

**Issue by BryonConley** [react-native-kit/react-native-track-player#1037]
HI, I am using the react-native-track-player-dev release for my shoutcast radio player project.  I've noticed a somwhat subtle but odd behavior when I do a 'react-native run=andrpod'
on the example code  after making a couple of changes in the playlist.js and the app.js files.  Namely, I changed the default screen from Landingscreen to the PlaylistScreeen,  I then removed all the function related to skip back/previous and skip-forward/next as I am  developing a shoutcase application.  I then put in a console.log("how many times am I looping");  line right after the export section and before the firsts async function,  See the snppet below:

export default function PlaylistScreen() {
  const playbackState = usePlaybackState();

  useEffect(() => {
    setup();
  }, []);

console.log("How many time Playlist.js is looping?");
console.log(" ");

  async function setup() {
 when I run the react-native run-android, I don't get any errors in the bash shell nor do I get any errors in the android studio emulator log window related to my edits.  However, I do see aloop of three of the log print as follows:

[Fri Oct 02 2020 21:20:23.930]  LOG      How many time Playlist.js is looping?
[Fri Oct 02 2020 21:20:23.934]  LOG
[Fri Oct 02 2020 21:20:24.290]  LOG      How many time Playlist.js is looping?
[Fri Oct 02 2020 21:20:24.318]  LOG
[Fri Oct 02 2020 21:20:24.473]  LOG      How many time Playlist.js is looping?
[Fri Oct 02 2020 21:20:24.512]  LOG
[Fri Oct 02 2020 21:20:24.618]  LOG      How many time Playlist.js is looping?
[Fri Oct 02 2020 21:20:24.669]  LOG
[Fri Oct 02 2020 21:20:25.412]  LOG      How many time Playlist.js is looping?
[Fri Oct 02 2020 21:20:25.451]  LOG
[Fri Oct 02 2020 21:20:25.499]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]
[Fri Oct 02 2020 21:20:25.522]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]
[Fri Oct 02 2020 21:20:25.923]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]
[Fri Oct 02 2020 21:20:26.156]  LOG      How many time Playlist.js is looping?
[Fri Oct 02 2020 21:20:26.240]  LOG
[Fri Oct 02 2020 21:21:15.804]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]
[Fri Oct 02 2020 21:24:51.859]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]
[Fri Oct 02 2020 21:28:33.510]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]
[Fri Oct 02 2020 21:33:15.800]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]
[Fri Oct 02 2020 21:36:15.970]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]
[Fri Oct 02 2020 21:39:35.570]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]
[Fri Oct 02 2020 21:43:11.603]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]
[Fri Oct 02 2020 21:46:24.490]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]
[Fri Oct 02 2020 21:49:42.137]  LOG      TrackPlayer.getDuration: [Function promiseMethodWrapper]

I just counted the print loop - it is actually six times not three.  You'll note other warnings later in this pasted log result on getDur and the likes -- Those are separate issues I am tracking as I am not able to get the react-native-track-player to calculate the duration and the position does not reset when new songs start in the shoutcast stream.  I'll file tickets on that issue later once I clean up the issue at hand and fix the output from promise to the actual data --.

You help on this and the two others I will file shortly will be greatly appreciated!  Thanks.

**Comment by puckey** [comment]
Unless you have further information, I am not sure that this is related to this library.. React can call a function component multiple times when rendering, but the effect will be just fired on time..

**Comment by BryonConley** [comment]
Hi Jonathan,  thanks for the explanation.  In the react-native-track-player-example, if you create an interval timer  like the setInterval( () => {}  ) with code in the method. you'll get multiple instances of the interval timer triggered in rapid succession like  three or five times.  It could be a potential performance or unreliable outcome?   Your thoughts on a solution to this?
