### ISSUE TITLE
Issue extension of #636 - Capturing metadata from Shoutcast streaming 

### ISSUE THREAD

**Issue by BryonConley** [react-native-kit/react-native-track-player#1038]
HI,  I thought to capture an issue I am having in modifying the example project.  I am using react-native-track-player-dev version (version 1.2.3 also) .  This is more of a question than an issue.  I've read the issue #636 which confirmed my solution  and wound up just implementing the same from that ticket  only re get the same problem in the player.js

As per:
https://github.com/react-native-kit/react-native-track-player/issues/636

I added the code snoppets into my playlist.js (from the example project), and added the additional line suggested in the #635 ticket to capture the title, artist and artwork in the player.js right after the code involving detecting track changed.   I noticed when I changed the example funtionality to a shoutcast streaming mp3 music player (radio player), the event listener on 'track-changed' no longer wored, so I changed that to detecting metadata-received even. as shown below (note I just commented out the track-changed lines):

  useTrackPlayerEvents(["playback-metadata-received"], async event => {
    if (event.type === TrackPlayer.TrackPlayerEvents.PLAYBACK_METADATA_RECEIVED) {
//  useTrackPlayerEvents(["playback-track-changed"], async event => {
//    if (event.type === TrackPlayer.TrackPlayerEvents.PLAYBACK_TRACK_CHANGED) {

   const {bannerDB, logoDB, artworkDB} =  onImageHash();
// await console.log('ArtworkDB Keys: ', Object.keys(onArtworkHash) );
await console.log('TrackPlayer.getDuration:', TrackPlayer.getDuration);
artwork = 'https://ipmcentre.com/artwork/Parrot.png';
      const track = await TrackPlayer.getTrack(await TrackPlayer.getCurrentTrack());
      const { title, artist  } = track || {};
      setTrackTitle(title);
      setTrackArtist(artist);
      setTrackArtwork(artwork);
 

So as you can see the event listener triggers just fine and the overal functionality works with the android platform, however, if you look at the IOS platform code from #636 you will see that a setInterval loop is used to grab the  JSON file from the Shoutcast server to collect the metadata -- as you stated that IOS does not have the metadata-received listening capability.  So,  in my above code,  logically, it won't work.  So to catch changed metadata we made, how do we make this code to work for both platform in the player.js code?  See the aboe code snippet and read the issue #636 I mentioned  hopefully you'll see my issue.  Your help is much appreciated.  Thank you.

**Comment by puckey** [comment]
For support, please try asking in the discord channel.

**Comment by BryonConley** [comment]
Hi Jonathan,  thanks for this pointer -- what is and where is the 'discord channel'?   Thanks again for the prompt note.

**Comment by thecluff** [comment]
Did you ever get this working?
