### ISSUE TITLE
Audio Playback not stopping even after app close

### ISSUE THREAD

**Issue by RekarBotany** [react-native-kit/react-native-track-player#105]
App plays song even if app closed from task manager on Android
set stopWithApp flag to true but no luck

any idea how to stop music or close the app completely when closed from task manager?

**Comment by ankitsinghania94** [comment]
+1

**Comment by puckey** [comment]
I am also running into this issue – spent the night debugging it without result..

**Comment by puckey** [comment]
[This SO question](https://stackoverflow.com/questions/48020936/strange-behavior-observed-with-ontaskremoved) seems to point to `onTaskRemoved` no longer being called when the service is bound to using `bindService(intent, mConnection, Context.BIND_AUTO_CREATE);`

> Now when starting the service with startService(intent) the onTaskRemoved() method gets called but it is never called when I bind to the service using bindService(intent, mConnection, Context.BIND_AUTO_CREATE);

**Comment by puckey** [comment]
It seems to be fixed for me by changing in [TrackModule](https://github.com/react-native-kit/react-native-track-player/blob/dev/android/src/main/java/guichaguri/trackplayer/TrackModule.java#L84):

onTaskRemoved is being called again in PlayerService when I kill the app from the task manager.

```
        // Binds the service to get a MediaWrapper instance
        Intent intent = new Intent(context, PlayerService.class);
        intent.setAction(PlayerService.ACTION_CONNECT);
        context.bindService(intent, this, Service.BIND_AUTO_CREATE);
```

to


```java
        // Binds the service to get a MediaWrapper instance
        Intent intent = new Intent(context, PlayerService.class);
        context.startService(intent);
        intent.setAction(PlayerService.ACTION_CONNECT);
        context.bindService(intent, this, 0);
```

**Comment by puckey** [comment]
Pull request over here: https://github.com/react-native-kit/react-native-track-player/pull/112

**Comment by hsparihar-systango** [comment]
With latest code as well getting same issue, on android force close application still audio playing.
Please suggest any solution, i am using "react-native-track-player": "^0.2.5" version.

**Comment by Guichaguri** [comment]
@hsparihar-systango does it still happens on 1.0.0?

**Comment by hsparihar-systango** [comment]
@Guichaguri 
it's resolved now,
Thanks

**Comment by naody** [comment]
@Guichaguri, music still continues playing in the background after closing the app. 
Currently using version `react-native-track-player: 1.0.0` on Android PI, any tricks I need to know? :) 

Thanks

**Comment by moonstruck** [comment]
@naody You may give a try setting `stopWithApp` tot `true`.
```
TrackPlayer.updateOptions({
    stopWithApp: true
});
```

**Comment by naody** [comment]
@moonstruck, yup I haven't missed that one :). Here's my setup
```
await TrackPlayer.setupPlayer({
      maxCacheSize: 1024 * 5, // 5 mb
    });
    TrackPlayer.updateOptions({
      stopWithApp: true,
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SEEK_TO,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
      ],
    });
```

**Comment by naody** [comment]
> @moonstruck, yup I haven't missed that one :). Here's my setup
> 
> ```
>    await TrackPlayer.setupPlayer({
>       maxCacheSize: 1024 * 5, // 5 mb
>     });
> 
>     TrackPlayer.updateOptions({
>       stopWithApp: true,
>       capabilities: [
>         TrackPlayer.CAPABILITY_PLAY,
>         TrackPlayer.CAPABILITY_PAUSE,
>         TrackPlayer.CAPABILITY_SEEK_TO,
>         TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
>         TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
>       ],
>     });
> ```

For now this trick worked form me.
```
  componentWillUnmount = async () => {
    AppState.removeEventListener('change', this._handleStateChange);
    await TrackPlayer.reset();
    await TrackPlayer.stop();
  };
```

**Comment by akashsinghalcoder** [comment]
TrackPlayer.updateOptions({
    stopWithApp: true
});
This solves the issue for me guys

**Comment by ithustle** [comment]
This issue still on 1.2.3 version, on IOS.

**Comment by curiousdustin** [comment]
@ithustle, what are you expecting on iOS?

`stopWithApp` is an Android only settings.

Also, are you saying that even after force quitting the app on iOS, by swiping it out of multitasking view, the audio continues to play?

**Comment by ithustle** [comment]
No, forcing quitting the app, stop playing. 
But on previous versions (if my mind don't trick me) after restart app on fast refresh the song playing stopped

**Comment by curiousdustin** [comment]
This could be implemented by your app, but it is not a feature of react-native-track-player. Resuming the app from the background on iOS should have not effect, unless you have implemented something to react to this scenario. If you still think there is a bug, please create a separate issue for iOS, as this issue is specifically for the Android `stopWithApp` setting.
