### ISSUE TITLE
[iOS] Crashes on long URLs

### ISSUE THREAD

**Issue by marksteele** [react-native-kit/react-native-track-player#1052]
**Describe the bug**
Long URLs (in my case they are file:/// paths) crash when adding to `TrackPlayer.add()`.

**To Reproduce**
Create long file paths and try to add them to the queue.

**Environment (please complete the following information):**
```
npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 671.58 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.13.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
Crashing on iPhone SE

**Code**
`TrackPlayer.add()`

I've worked around it by using checksums of the file names in my caching layer but it sucks to have code in there that's only there to deal with these bugs...

**Comment by puckey** [comment]
Please provide an example of a long filename so this bug can be reproduced. Please provide a crash-log. If you are able to fix it yourself pull-requests are appreciated.

**Comment by rdhox** [comment]
Are you sure your URI are valid? If not, use `encodeURI`. Worked for me.

**Comment by puckey** [comment]
Closing until a reproducible example is given.

**Comment by marksteele** [comment]
The repro for this is pretty straight forward. Create a long file path, let's say 500 characters. Then try to load a file from in there. Even better, just look at what buffer is allocated for the file path, that's where you'll find the bug.
