### ISSUE TITLE
[IOS] Can't play Flac file and Urls

### ISSUE THREAD

**Issue by Yu-sooho** [react-native-kit/react-native-track-player#1053]
![스크린샷 2020-10-22 오후 3 42 10](https://user-images.githubusercontent.com/65954682/96834620-42da4380-147d-11eb-8586-dbd85e305031.png)

When I try to play flac audio I get this error.

Track player can't play flac?

**Comment by puckey** [comment]
As far as I know the iOS version of RNTP does indeed not support FLAC. You could try using ALAC instead.
