### ISSUE TITLE
No sound when playing example app

### ISSUE THREAD

**Issue by colinricardo** [react-native-kit/react-native-track-player#1055]
**Describe the bug**
Example builds and runs fine, but playing results in no sound. 

Issue seems to affect iOS simulator and real life device. There's no errors logged. 

**To Reproduce**
Run example app. 

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.

```
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 6.25 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

What `react-native-track-player` version are you using?
Are you testing on a real device or in the simulator? Which OS version are you running?
`react-native-kit/react-native-track-player#dev`

**Comment by mchandleraz** [comment]
Is your device on silent mode?

**Comment by kelvinpompey** [comment]
@colinricardo I had this problem but after adding an event listener it worked.

**Comment by arahman0715** [comment]
@kelvinpompey what are the event listeners? I added some event listeners but still audio not playing on ios simulator
