### ISSUE TITLE
Warnings require cycle

### ISSUE THREAD

**Issue by Cuervo20** [react-native-kit/react-native-track-player#1057]
**Describe the bug**
When i run the app i get these warnings and it takes about 5 seconds to enter the app

Require cycle: node_modules\react-native-track-player\lib\index.js->
node_modules\react-native-track-player\lib\hooks.js->
node_modules\react-native-track-player\lib\index.js

node_modules\react-native-track-player\lib\index.js->node_modules\react-native-track-player\lib\ProgressComponent.js->node_modules\react-native-track-player\lib\index.js

**To Reproduce**

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?
Are you testing on a real device or in the simulator? Which OS version are you running?

**Code**
Please, share the code that is causing the issue

**Comment by rumax** [comment]
```
 "react-native-track-player": "^1.2.3",
 ```
 
 Issue still actual and quite annoying. Any plans to fix it?

**Comment by michaelvitello** [comment]
Hello, I still get these cycle warnings too, that's not ideal. Any plan of fixing them soon? There is other issue opened on the topic that seems to be related. Commenting there too: https://github.com/react-native-kit/react-native-track-player/issues/989

**Comment by Tubaleviao** [comment]
This issue was fixed on PR #1077 and it just need to be merged.

**Comment by ghadeeraqraa1992** [comment]
same issue

**Comment by curiousdustin** [comment]
Fix released in [1.2.4](https://github.com/react-native-kit/react-native-track-player/releases/tag/v1.2.4)

**Comment by federicomiralles** [comment]
The require cycle warning is back again, now on version v4.0.1:
![Simulator Screenshot - iPhone 13 - 2023-11-20 at 13 51 17](https://github.com/doublesymmetry/react-native-track-player/assets/53195495/4828544d-baee-4452-ab0e-19060f47ceea)

**Comment by jvrlpzd** [comment]
Issue still present on version 4.0.1

**Comment by nl-danish** [comment]
Getting the same issue in 4.0.1.

**Comment by karthickraja-saravanan** [comment]
same issue in 4.0.1

**Comment by aaronksaunders** [comment]
curious to why this is closed when it is clearly still present?

```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle. 
  factory (node_modules/react-native-track-player/lib/web/TrackPlayerModule.js:2:1)
  factory (node_modules/react-native-track-player/lib/web/index.js:1:1)
λ  WARN  Require cycle: node_modules/react-native-track-player/lib/src/index.js -> node_modules/react-native-track-player/lib/src/trackPlayer.js -> node_modules/react-native-track-player/lib/src/TrackPlayerModule.web.js -> node_modules/react-native-track-player/lib/web/index.js -> node_modules/react-native-track-player/lib/web/TrackPlayerModule.js -> node_modules/react-native-track-player/lib/web/TrackPlayer/index.js -> node_modules/react-native-track-player/lib/web/TrackPlayer/PlaylistPlayer.js -> node_modules/react-native-track-player/lib/src/index.js
```
