### ISSUE TITLE
Which conditions lead to a natural "skip" event?

### ISSUE THREAD

**Issue by gianpietro-magiqapps** [react-native-kit/react-native-track-player#1062]
Hi, I have this question that can't figure out from the current documentation.

My app plays exactly two tracks, with IDs "1" and "2", each pointing to a radio stream that represents a station that "never ends".

```
  const tracks = [
    {
      id: "1",
      url: STREAM_URL_01,
      type: "default",
      title: "Station 01",
      artist: "Radio",
    },
    {
      id: "2",
      url: STREAM_URL_02,
      type: "default",
      title: "Station 02",
      artist: "Mixtape",
    },
  ];

```

So the way we switch from one "track" (station) to the other, is through a button, that changes the station ID, which maps to the corresponding track (1 or 2). This usually works fine.

However, in certain rare events, usually after a quick network flap, we see that a natural skip occurs, without the radio ID having changed in the app, and without the button having been pressed.

**Question is: under which events the TrackPlayer would "naturally" try to skip a track? (for example, queue empty?) and would there be a way to disable this?**

Thanks!

**Comment by Guichaguri** [comment]
This is a queue, whenever a track finishes playing or an error occurs that makes that track impossible to play, the next one will start playing.
If you want to avoid changing from one station to another, you can add only one track to the queue, if you'd like to switch radios, you can remove the previous one and add the new one, there's no need to have both at the same time in the queue.

**Comment by gianpietro-magiqapps** [comment]
Thanks @Guichaguri , will split the queues then 👍
