### ISSUE TITLE
Doesnt play music in device even the path is right

### ISSUE THREAD

**Issue by ShumGG** [react-native-kit/react-native-track-player#1068]
tried with: `file:///storage/emulated/0/Download/music.mp3` and `file:////storage/emulated/0/Download/music.mp3`, even in the emulator doesnt work, tried with: `file:///storage/emulated/0/Download/music/music.mp3` and `file:///storage/emulated/0/Download/music/music.mp3`

heres the code: 

```
`componentDidMount() {

  init_player = async () => {
        await TrackPlayer.setupPlayer();
        await TrackPlayer.add({
            id: "1",
            url: "file://storage/emulated/0/Download/Yummy.mp3", //path of device
            title: "Dfdf",
            artist: "Dfdf",
        });

        await TrackPlayer.play();
    }
}`
```

**Comment by puckey** [comment]
Did you try the example app? From your example I do not see `init_player` being called anywhere..

**Comment by ShumGG** [comment]
> Did you try the example app? From your example I do not see `init_player` being called anywhere..

Init_player is called in componenDidMount
