### ISSUE TITLE
Not receiving 'remote-seek' event when triggering from headphones

### ISSUE THREAD

**Issue by phil-andrews** [react-native-kit/react-native-track-player#107]
Does this support seeking using headphone commands, one short then press and hold? I'm listening to the event through another library so I know it's coming through but TrackPlayer is not firing `remote-seek`.
  
It doesn't appear to be registered in `index.js`, not sure if that's intentional.

` const events = [
            'playback-state',
            'playback-error',
            'playback-queue-ended',
            'playback-track-changed',
            'remote-play',
            'remote-pause',
            'remote-stop',
            'remote-next',
            'remote-previous',
            'remote-jump-forward',
            'remote-jump-backward',
];`

**Comment by Guichaguri** [comment]
Which platform? If it's iOS, it's not supported yet

**Comment by phil-andrews** [comment]
It is iOS, ok that makes sense. Thought I read in another thread that it was supported, must have misread.

**Comment by malangaveuday** [comment]
'remote-seek' is it supported to iOS?
