### ISSUE TITLE
CANT LOAD LOCA FILES TO PLAY

### ISSUE THREAD

**Issue by ShumGG** [react-native-kit/react-native-track-player#1072]
Im stuck with this for almost a week, tried with `file:///storage/emulated/0/Download/music/music.mp3` and `file:///storage/emulated/0/Download/music/music.mp3`  in the emulator and it doesnt work, heres the code:

```
  componentDidMount() {
        this.init_player();
    }

    init_player = async () => {

        let track = [{
            id: "1",
            url: "file:///storage/emulated/0/Download/music/Yummy.mp3",
            title: "Yummy",
            artist: "Justin Bieber"
        }]

        await TrackPlayer.setupPlayer();
        await TrackPlayer.add(track);
        await TrackPlayer.play();
}
```

**Comment by ShumGG** [comment]
> Im stuck with this for almost a week, tried with `file:///storage/emulated/0/Download/music/music.mp3` and `file:///storage/emulated/0/Download/music/music.mp3` in the emulator and it doesnt work, heres the code:
> 
> ```
>   componentDidMount() {
>         this.init_player();
>     }
> 
>     init_player = async () => {
> 
>         let track = [{
>             id: "1",
>             url: "file:///storage/emulated/0/Download/music/Yummy.mp3",
>             title: "Yummy",
>             artist: "Justin Bieber"
>         }]
> 
>         await TrackPlayer.setupPlayer();
>         await TrackPlayer.add(track);
>         await TrackPlayer.play();
> }
> ```

resolve, if you are using this in Android X you need to add in AndroidManifest.xml in <application> android:requestLegacyExternalStorage="true"

**Comment by cenaHara** [comment]
hi @ShumGG  you can load local file IOS
