### ISSUE TITLE
Type 'Capability' has no member 'skipForward' / 'skipBackward'

### ISSUE THREAD

**Issue by jasongrishkoff** [react-native-kit/react-native-track-player#109]
Just updated to the latest dev branch and when I try to build in Xcode I get the following:

`Type 'Capability' has no member 'skipForward'`

It hones in on these two lines in RNTrackPlayer.swift:

```
        let enableSkipForward = capabilities.contains(.skipForward)
        let enableSkipBackward = capabilities.contains(.skipBackward)
```

**Comment by frenkie** [comment]
Yes, the words 'skip' and 'jump' seem to have been used interchangeably whereas one of these should be chosen.

**Comment by jasongrishkoff** [comment]
If I set both enableSkipForward and enableSkipBackward to false, I can get to the next step, which produces this error.

![simulator screen shot - iphone 7 plus - 2018-01-15 at 11 57 03](https://user-images.githubusercontent.com/375379/34936940-c0f1e8c2-f9eb-11e7-94e0-2efa165d37bd.png)
