### ISSUE TITLE
TypeError: Cannot read property 'STATE_NONE' of undefined

### ISSUE THREAD

**Issue by philosofonusus** [react-native-kit/react-native-track-player#1090]
This happens when i run my app throw expo

App.js
import React, {useCallback, useEffect, useRef, useState} from 'react';
import {
  StyleSheet,
  FlatList,
  Image,
  View,
  SafeAreaView,
  TouchableOpacity,
  Text,
  Dimensions
} from 'react-native';
import { songs } from './temp_songs'
import { Ionicons } from '@expo/vector-icons';
import TrackPlayer from "react-native-track-player";

const {width} = Dimensions.get("window")

const trackPlayerInit = async () => {
  await TrackPlayer.setupPlayer();
  await TrackPlayer.add(songs[0])
  return true
}

export default function App() {

  const [isTrackPlayerInit, setIsTrackPlayerInit] = useState(false)

  useEffect(() => {
    const startPlayer = async () => {
      let isInit =  await trackPlayerInit();
      setIsTrackPlayerInit(isInit);
    }
    startPlayer();
  }, [])

  const FlatListRef = useRef()

  const [current, setCurrent] = useState({item: songs[0]})

  const setCurrentItem = useCallback(({ viewableItems }) => setCurrent(viewableItems[0]), [])

  const renderImage = ({item}) => (
    <View style={styles.coverContainer}>
      <Image style={styles.cover} source={item.artwork} />
    </View>
  )
  return (
    <SafeAreaView style={styles.container}>
      <FlatList
          ref={FlatListRef}
          style={{maxHeight: 340, marginTop: "30%"}}
        data={ songs }
        renderItem={renderImage}
        keyExtractor={item => item.id}
        horizontal
        pagingEnabled
        scrollEventThrottle={16}
        onViewableItemsChanged={setCurrentItem}
        viewabilityConfig={{itemVisiblePercentThreshold: 50}}
        showsHorizontalScrollIndicator={false}
        />
        <View style={styles.infoContainer}>
          <Text style={styles.title}>{current.item.title}</Text>
          <Text style={styles.artist}>{current.item.artist}</Text>
        </View>
        <View style={styles.controlsContainer}>
            <TouchableOpacity
                onPress={() => FlatListRef.current.scrollToIndex({index: +current.item.id + (+current.item.id !== 0 ? -1 : 0)})}
            >
              <Ionicons name="play-skip-back" size={30} color="white"/>
            </TouchableOpacity>
            <TouchableOpacity disabled={!isTrackPlayerInit} onPress={() => TrackPlayer.play()}>
              <Ionicons name="play" size={30} color="white"/>
            </TouchableOpacity>
            <TouchableOpacity
                onPress={() => FlatListRef.current.scrollToIndex({index: +current.item.id + (+current.item.id !== +songs[songs.length - 1].id ? 1 : 0)})} >
              <Ionicons name="play-skip-forward" size={30} color="white" />
            </TouchableOpacity>
        </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black'
  },
  infoContainer: {
    position: 'relative',
    top: 0
  },
  title: {
    fontSize: 28,
    textAlign: 'center',
    fontWeight: '600',
    textTransform: 'capitalize',
    color: '#ffffff',
  },
  artist: {
    fontSize: 18,
    textAlign: 'center',
    color: '#ffffff',
    textTransform: 'capitalize',
  },
  cover: {
    width: 320,
    height: 320,
    borderRadius: 5,
  },
  coverContainer: {
    width: width,
    alignItems: "center"
  },
  controlsContainer: {
    marginTop: 40,
    width: width,
    flexDirection: "row",
    justifyContent: "space-around"
  }
});

Index.js

import { registerRootComponent } from 'expo';
import TrackPlayer from 'react-native-track-player';
import App from './App';

// registerRootComponent calls AppRegistry.registerComponent('main', () => App);
// It also ensures that whether you load the app in the Expo client or in a native build,
// the environment is set up appropriately
registerRootComponent(App);
TrackPlayer.registerPlaybackService(() => require('./service.js'));
`

service.js
`
module.exports = async function () {};
`

package.json
`
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@expo/vector-icons": "^12.0.2",
    "expo": "~40.0.0",
    "expo-font": "^8.4.0",
    "expo-splash-screen": "~0.8.0",
    "expo-status-bar": "~1.0.3",
    "expo-updates": "~0.4.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-screens": "~2.15.0",
    "react-native-track-player": "^1.2.3",
    "react-native-unimodules": "~0.12.0",
    "react-native-vector-icons": "^7.1.0",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.13.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
`

**Comment by Tucker2015** [comment]
Expo is not supported. 

Expo and Expokit support

Currently react-native-track-player does not support projects with Expo or Expokit.

**Comment by philosofonusus** [comment]
Thank you, I have already understooden this.
