### ISSUE TITLE
new release to incorporate #957? (ios togglePlayPause)

### ISSUE THREAD

**Issue by jaredh159** [react-native-kit/react-native-track-player#1094]
Thanks to all the contributors for this amazing library, really appreciate it. 🙏 

Just realized my app is not responding to the wired apple headphones toggle play/pause button events. Looks like #957 is what I need.

I'm not sure what your release cycle is like, or if this complicated for some other reasons, but I'm wondering if we could get a `1.3.0` release made which includes that change. My understanding is that it wasn't breaking at all right?  Or did it only get merged into a branch headed for version 2?

I guess I'm wondering how to incorporate this improvement into my production app -- any pointers would be greatly appreciated.  Thanks!

**Comment by curiousdustin** [comment]
Fix released in [1.2.4](https://github.com/react-native-kit/react-native-track-player/releases/tag/v1.2.4)
