### ISSUE TITLE
How to read from absolute paths?

### ISSUE THREAD

**Issue by phil-andrews** [react-native-kit/react-native-track-player#110]
Does RNTP support absolute paths? I can't get this to read. If they aren't supported, what is the correct way to work with Documents storage?

`"/Users/Parthenon/Library/Developer/CoreSimulator/Devices/3FAD7867-882E-430B-93D8-0334FDAE1DDD/data/Containers/Data/Application/FA4EC1DD-14E2-4DB4-B432-769FB5589428/Documents/7cfe4ef18dd2a793aca8f43b4014e85f.mp3"`

**Comment by phil-andrews** [comment]
This can be closed, proper read is four slashes... `file:////Users...`

**Comment by alfonsodev** [comment]
still not working with url 
```
"file:////Users/alfonso/Library/Developer/CoreSimulator/Devices/12D14D34-06E4-4122-A7CC-D643803015C7/data/Containers/Data/Application/AC9BF956-3EE1-411D-8DB4-B372F84DC6EE/Documents/4ZBLdeB17OsJJNF1gR9r_-Gw9xImHJP-x3jwNJP[e_chapter_1_i.m4a"
```
