### ISSUE TITLE
302 Redirect URL Support

### ISSUE THREAD

**Issue by SatoshiInoue** [react-native-kit/react-native-track-player#111]
I'd like to play mp3 URLs that does HTTP 302 redirect initially (e.g. for authentication) and then returns the audio file with HTTP 200. I was able to play such URL on Android device, however, I couldn't play it on iOS simulator. I have not tested real iOS device yet. Does TrackPlayer handle redirects of the audio source? I am not able to provide any example URLs at the moment that does a redirect for confidentiality.

I've checked Expo's AV library and that can play such URL on both Android and iOS device, FYI (However, Expo can't play HLS on iOS. They said they'll release it in the next release, though: https://github.com/expo/expo/issues/1187)

**Comment by SatoshiInoue** [comment]
I've tested on iPhone 7/iOS 11.2.1 and I confirmed I couldn't play an mp3 file with 302 redirect with TrackPlayer.

**Comment by SatoshiInoue** [comment]
Looking forward to hearing some updates on this. 300s responses are common with podcasts which may go from one server to another CDN.

**Comment by callmetwan** [comment]
I did some testing and I think redirects _are_ working.

We are using SoundCloud hosted MP3s. Typical URI reference is feeds.soundcloud.com/stream/filename.mp3. This redirects to the SoundCloud CDN cf-media.sndcdn.com/hash.

Two things happened for me:
1) I realized that I had not added an App Transport Security Layer Exception Domain for the SoundCloud CDN domain (I had for the main app domain, but not the CDN).

2) I added a mimeType to the track objects when populating Track Player. In the case of MP3 it is `audio/mpeg`.

After doing both of these things audio successfully plays for me.

**Comment by phil-andrews** [comment]
I haven't had any issued with 302 redirects. The problem you're probably running into as @callmetwan stated is the App Transport Security policy. If it isn't set to `AllowAbitraryLoads` iOS will deny the connection. 

However, Apple is almost certainly not going to allow your app into the store with `AllowAbitraryLoads` set to true. So you either need to whitelist specific domains or route your download traffic through an https server.

**Comment by callmetwan** [comment]
In addition, I discovered today that ExoPlayer in Android doesnt
automatically redirect HTTP to HTTPS unless you explicitly set it to do so.
I didn’t have time to explore exactly how to do this but a quick Google
search should give more info.

**Comment by callmetwan** [comment]
Redirects from HTTP -> HTTPS or vice-versa are definitely not working. This is a known configuration requirement for ExoPlayer:

https://google.github.io/ExoPlayer/faqs.html#why-do-some-streams-fail-with-http-response-code-301-or-302

I also found a solution explaining what needs to be done and took a stab at it, but I am not a Java developer and think I likely misconfigured something:

https://stackoverflow.com/questions/41517440/exoplayer2-how-can-i-make-a-http-301-redirect-work

@Guichaguri  It seems like this is relatively simple to do, what do you think?

**Comment by callmetwan** [comment]
Small typo on my part!

I did a bit of testing and verified redirects now work for me!

Pull request opened:
https://github.com/react-native-kit/react-native-track-player/pull/160

**Comment by Guichaguri** [comment]
Closed by #160

**Comment by phil-andrews** [comment]
To be clear for the next person that stumbles into this thread I'm specifically talking about iOS as was flagged as the issue in the OP.

> I was able to play such URL on Android device, however, I couldn't play it on iOS simulator
