### ISSUE TITLE
Could not resolve com.android.tools.build:gradle:3.4.2.

### ISSUE THREAD

**Issue by Warmachine13** [react-native-kit/react-native-track-player#1136]
When I try run on android he show 

**FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-track-player'.
> Could not resolve all artifacts for configuration ':react-native-track-player:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.4.2.
     Required by:
         project :react-native-track-player
      > Could not resolve com.android.tools.build:gradle:3.4.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.4.2/gradle-3.4.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.4.2/gradle-3.4.2.pom'.
               > Read timed out

versions  "react-native-track-player": "^1.2.5",
react-native 0.62.1

**Comment by albinojunior** [comment]
Same issue here.

**Comment by curiousdustin** [comment]
@Warmachine13 @albinojunior , can you try installing from `dev` and see if it resolves this for you?

`"react-native-track-player": "git://github.com/react-native-kit/react-native-track-player.git#dev"`

**Comment by Warmachine13** [comment]
He resolves now the problem is in site o jcenter, has stopped and now returns

**Comment by curiousdustin** [comment]
Migrated from JCenter to Maven Central in version [1.2.6](https://github.com/react-native-kit/react-native-track-player/releases/tag/1.2.6).
