### ISSUE TITLE
Change "s.dependency 'React'" to "s.dependency 'React-Core'"

### ISSUE THREAD

**Issue by ngocdaothanh** [react-native-kit/react-native-track-player#1141]
I'm using this script:
https://gist.github.com/HosseinRashno/4786b289356ad9840b6c087ce8191fe4

to check
https://github.com/react-native-kit/react-native-track-player/blob/dev/react-native-track-player.podspec

and it says:

```
Detected podspec with wrong dependency ----> node_modules/react-native-track-player/react-native-track-player.podspec
Fixed podspec with wrong dependency ----> node_modules/react-native-track-player/react-native-track-player.podspec
```

**Comment by curiousdustin** [comment]
https://github.com/react-native-kit/react-native-track-player/commit/02953da33a681722476b0ba423b76322252f4020
