### ISSUE TITLE
v1.2.6 - iOS Silent Mode suddenly affecting app audio

### ISSUE THREAD

**Issue by mchandleraz** [react-native-kit/react-native-track-player#1145]
**Describe the bug**
We recently upgraded our project from react-native-track-player 1.2.3 to 1.2.6. After upgrading, our app is now affected by the position of the hardware "silent mode" switch on iPhones. If I play a track, then move the switch to the On position, the audio is silenced. Moving the switch back re-enables audio.
I experienced the same behavior early in the development of this app, but fixed it by enabling background processing. I have confirmed that this is still enabled.
I have background modes configured like so:
![Screen Shot 2021-03-22 at 5 02 09 PM](https://user-images.githubusercontent.com/3044608/112068919-7e626200-8b30-11eb-8820-791915d908e1.png)

**To Reproduce**
Play a track and toggle the hardware switch for silent mode. App audio will respect the switch position, where previously it ignored silent mode.

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
```
info Fetching system and libraries information...
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 411.90 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
What `react-native-track-player` version are you using?
```
1.2.6
```
Are you testing on a real device or in the simulator? Which OS version are you running?
```
Real iPhone, iOS 14.4
```
**Code**
```
I can provide code, but I've isolated this issue to a specific commit which only updated the library.
No code changes in that commit, and this issue was not present previously
```

**Comment by curiousdustin** [comment]
Does this behavior when the app is in foreground, background, or both?

Does it happen in debug builds, release builds, or both?

**Comment by curiousdustin** [comment]
Are you using default settings, or have you set one of these?

```
iosCategory
iosCategoryOptions
iosCategoryMode
```

https://react-native-track-player.js.org/documentation/#setupplayeroptions

**Comment by mchandleraz** [comment]
@curiousdustin thank you for the help, and an even bigger thank you for everything you do on this project.

I've triple checked that the issue is not present until 1.2.4, and I saw your comment in the other thread that the mute switch doesn't affect things on the example. I suspect that my app code has a minor issue that just wasn't being exposed prior to 1.2.4.

- The issue happens in both debug and release builds.
- The issue happens in foreground. I have not tested background, but will do so shortly.

Here's the player initialization/setup code:
```
const playerOptions = {
  iosCategory: 'playback',
  iosCategoryOptions: [
    'interruptSpokenAudioAndMixWithOthers',
    'duckOthers',
    'allowAirPlay',
    'allowBluetooth',
    'allowBluetoothA2DP',
  ],
  iosCategoryMode: 'spokenAudio',
};

const metadaOptions = {
  capabilities: [
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
    TrackPlayer.CAPABILITY_SEEK_TO,
    TrackPlayer.CAPABILITY_JUMP_BACKWARD,
    TrackPlayer.CAPABILITY_JUMP_FORWARD,
  ],
  stopWithApp: isAndroid() ? true : false,
  compactCapabilities: [
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
  ],
};

initNotifications();

try {
  PianoSdk.init(Config.PIANO_AID, Config.PIANO_ENDPOINT);
} catch (e) {
  Logger().error(e);
}

TrackPlayer.setupPlayer(playerOptions)
  .then(() => {
    TrackPlayer.updateOptions(metadaOptions);
  })
  .catch((error) => {
    Logger().error('init player error', error);
  });

AppRegistry.registerComponent(appName, () => App);
TrackPlayer.registerPlaybackService(() =>
  require('./services/audio-player.js'),
);
```

**Comment by curiousdustin** [comment]
@mchandleraz, please try [1.2.7](https://github.com/react-native-kit/react-native-track-player/releases/tag/v1.2.7)

**Comment by mchandleraz** [comment]
@curiousdustin Thank you! I was able to upgrade and do some preliminary testing yesterday. The mute switch functionality is behaving like it did prior to 1.2.3 so I believe this is solved.

**Comment by biomancer** [comment]
Just for the future reference - it looks like that mute behaviour is caused by combination of using longFormAudio and iosCategoryOptions. I though that maybe it's some particular option that does it, but I couldn't find any, I've tested few of them and leaving any option was making mute switch to mute playback. Removing iosCategoryOptions at all from options fixes that.
My options look like that now and mute switch does not disable playback:

```
{
  minBuffer: 20 * 60,
  maxBuffer: 120 * 60,
  backBuffer: 35,
  iosCategoryPolicy: 'longFormAudio'
}
```
