### ISSUE TITLE
Android notification icon can't be changed

### ISSUE THREAD

**Issue by puckey** [react-native-kit/react-native-track-player#116]
it seems that in the Android notification screen the smallIcon is hardcoded to be the play icon, while it should be configurable by passing `data.icon` to `Player.updateOptions`

https://github.com/react-native-kit/react-native-track-player/blob/b6d1272118712b2d0928055d7a20dccdb20bef23/android/src/main/java/guichaguri/trackplayer/metadata/components/MediaNotification.java#L69

**Comment by puckey** [comment]
(while we are on this, I am wondering if the default icon for this should be something different from the play icon.. the play icon is confusing to users, because they expect to be able to press on it)

**Comment by Guichaguri** [comment]
That's the constructor, it's only setting it as the default icon. The icon updates in `updateOptions`:

https://github.com/react-native-kit/react-native-track-player/blob/b6d1272118712b2d0928055d7a20dccdb20bef23/android/src/main/java/guichaguri/trackplayer/metadata/components/MediaNotification.java#L90

**Comment by puckey** [comment]
Ahh okay cool – will figure out tomorrow why I couldn't get my icon to display then. Thanks!

**Comment by ithustle** [comment]
I have the same issues using this piece of code:

```
TrackPlayer.setupPlayer();
		TrackPlayer.updateOptions({
			stopWithApp: true,
			capabilities: [
			  TrackPlayer.CAPABILITY_PLAY,
			  TrackPlayer.CAPABILITY_PAUSE,
			  TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
			  TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
			  TrackPlayer.CAPABILITY_STOP
			],
			compactCapabilities: [
			  TrackPlayer.CAPABILITY_PLAY,
			  TrackPlayer.CAPABILITY_PAUSE
            ],
            
            icon: require('./../imgs/ic_logo_notification.png'),
		});
```

**Comment by Guichaguri** [comment]
That's not the same problem. Please, open a new issue instead, this one is over a year old.
