### ISSUE TITLE
do artist and title need to be required?

### ISSUE THREAD

**Issue by puckey** [react-native-kit/react-native-track-player#120]
I am using this library to play radio streams. The android version doesn't complain when I just pass the the station name as title and leave out the artist field – but the iOS version required both to be there. A radio station can have its name as either the title or the artist – but it would be weird to repeat the same name for both artist and title.

I am wondering if it necessary to require both of these values.. Perhaps it would be enough if one of them was around?

**Comment by jdrorrer** [comment]
I agree, neither of these should be required. I ran into an issue where songs being pulled from an apo would not play on iOS because either the title or artist was null. On android, it works fine.

**Comment by Guichaguri** [comment]
This seems to be a requirement from the OS. Now that we have `updateMetadataForTrack`, this shouldn't be a problem for radio stations.
