### ISSUE TITLE
"Method does not override any method from its superclass" error thrown in Xcode

### ISSUE THREAD

**Issue by peterlazar1993** [react-native-kit/react-native-track-player#126]
Cannot get the library installed on iOS:

- using dev branch
- RN version 0.52.0

Library works on android.

<img width="1680" alt="screen shot 2018-01-26 at 7 15 34 pm" src="https://user-images.githubusercontent.com/4848554/35442450-512df568-02cd-11e8-9ba9-2d6e71bf31dc.png">

**Comment by xuezhma** [comment]
I can still reproduce this error on 0.2.4 react-native-track-player, rn 0.44.0

<img width="1365" alt="screen shot 2018-07-11 at 3 31 11 pm" src="https://user-images.githubusercontent.com/14795799/42602741-af28950e-851f-11e8-90b8-c1602543523e.png">
