### ISSUE TITLE
STATE enums returning integers on Android and Strings on iOS

### ISSUE THREAD

**Issue by peterlazar1993** [react-native-kit/react-native-track-player#128]
I would have expected strings in both scenarios. I can send a PR if a standard is fixed.
![](https://user-images.githubusercontent.com/95109/32376097-87dd0906-c082-11e7-9aa4-25db74bb83d6.png)

**Comment by Guichaguri** [comment]
Can you demonstrate one case scenario where it becomes a problem?

**Comment by peterlazar1993** [comment]
Now that I've thought about this, this behaviour is completely fine. Sorry to trouble you with this issue :)
