### ISSUE TITLE
Unable to play array of music files to TrackPlayer

### ISSUE THREAD

**Issue by deva11** [react-native-kit/react-native-track-player#131]
Tried using async as well as  passing whole Jsonarray to the Track player which is showing in console for iteration of data but not playing in TrackPlayer.
Getting the following error while trying to import files 
![screenshot_1517214705](https://user-images.githubusercontent.com/23656789/35500616-12510b14-04fd-11e8-97ee-414f546e9af4.png)

**Comment by Guichaguri** [comment]
Seems like you're putting the require inside a string?
Can you show your code, please?

**Comment by deva11** [comment]
Sure @Guichaguri .

`import SongList from '../../../data/AudioServerDataTest';`

,...
```
data=SongList;
async.eachSeries(data,function (item,finish) {
         TrackPlayer.add([item],null).then(function () {
         console.log(`Curr Item, = ${JSON.stringify(item)}`);


         });
         finish();

         },function () {

         }
         );
```

... 


AudioServerDataTest.js

```
let chaptersInQueueTest =

    [
        {
            'key':"a",
            'id': '11'
            ,'url': "require('../../songstest/veena.mp3')"
            ,"mail":"dv1@gmail.com",
            'title': 'Track1 - Carnival ',
            'artist': 'Vis1',
            'album': 'DV1',
            'genre': 'Melody',
            'date' :'2018-01-20T07:00:00+00:00',
            'artwork': "require('../../images/xyz.jpg')",
        },
]

module.exports =  chaptersInQueueTest;
```

Please give insights about this

**Comment by Guichaguri** [comment]
The lines that are giving you errors are `'url': "require('../../songstest/veena.mp3')"` and `'artwork': "require('../../images/xyz.jpg')"`.

You're putting the require inside a string, replace them with `'url': require('../../songstest/veena.mp3')` and require('../../images/xyz.jpg')`, they should work.
