### ISSUE TITLE
Is there any way to start playing a track at a specific part of the track?

### ISSUE THREAD

**Issue by phil-andrews** [react-native-kit/react-native-track-player#133]
For instance...
`trackPlayer.play('trackid', 54.04)`

**Comment by peterlazar1993** [comment]
Please see here. https://github.com/react-native-kit/react-native-track-player/wiki/API#changing-position-and-volume

**Comment by Guichaguri** [comment]
You can seek and then play, as @peterlazar1993 mentioned.
