### ISSUE TITLE
BUG!! Not giving Audio Output on Physical Device after Generating Release Apk

### ISSUE THREAD

**Issue by deva11** [react-native-kit/react-native-track-player#134]
This is not giving audio output on Real physical device but works fine in Emulator.

Main File
....
  ```
 TrackPlayer.setupPlayer().then(async () => {

            // Adds a track to the queue
            await TrackPlayer.add({
                id: '11',

                // url: 'http://example.com/avaritia.mp3', // Load media from the network
                url: require('./../../AppAssets/songstest/AR.mp3'), // Load media from the app bundle

                title: 'Humpi',
                artist: 'AR',
                album: 'Carnival of Carvings',
                genre: 'Melody',
                date: '2018-01-20T07:00:00+00:00', // RFC 3339


                artwork: require('./../../AppAssets/images/xyz.jpg'), // Load artwork from the app bundle
            });

```
....
```
onPressPlay = () => {
TrackPlayer.play();
}

```
....
index.js

```
AppRegistry.registerComponent('MyProject', () => AppNavigator);
AppRegistry.registerHeadlessTask('TrackPlayer', () => require('./player-handler.js'));
```

**Comment by deva11** [comment]
@Guichaguri Please give a fixing idea

**Comment by Guichaguri** [comment]
iOS or Android?

**Comment by deva11** [comment]
Android only

**Comment by deva11** [comment]
For your information, Its happening with Release Apk.

**Comment by Guichaguri** [comment]
Does URLs work?

**Comment by deva11** [comment]
Yes, URL works Seamlessly . The problem with bundle files and that too after making release apk. 
Not giving audio in both emulator and physical device

**Comment by Guichaguri** [comment]
Can you log the result of the require? Something like `console.log(require('./../../AppAssets/songstest/AR.mp3'));`

**Comment by Guichaguri** [comment]
And even better:

```js
import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';

console.log(resolveAssetSource(require('./../../AppAssets/songstest/AR.mp3')));
```

**Comment by deva11** [comment]
@Guichaguri It is not working and giving expected output.

**Comment by Guichaguri** [comment]
What is it outputting?

**Comment by deva11** [comment]
@Guichaguri I'm trying to replicate your demo project .I will update you the progress with relevant to this

**Comment by deva11** [comment]
`Data ={"key":"a","id":"11","url":3,"mail":"dv1@gmail.com","title":"My Album Title","artist":"AR","album":"Person album","genre":"Melody","date":"2018-01-20T07:00:00+00:00","artwork":4},index = 0`

`C:\MyProject\src\AppScreens\MyPlaySection\TrackPlayDummy.js:141 This File Refers To ::{"__packager_asset":true,"uri":"http://10.0.2.2:8081/assets/src/AppAssets/songstest/ar.mp3?platform=android&hash=c115f2e73bc5417ff393fda331347d63","scale":1}`

**Comment by deva11** [comment]
It will be fine if you could give sample code without redux implementation.

**Comment by Guichaguri** [comment]
And what does it outputs in a release apk?

**Comment by deva11** [comment]
I have added project in a public repository for you.
I feel you can catch with a glimpse over it.

https://deva11@bitbucket.org/deva11/trackplayertest.git

**Comment by deva11** [comment]
Debug : Mode
![screenshot_1518586270](https://user-images.githubusercontent.com/23656789/36189212-0f2bd082-1177-11e8-9d21-f9a132e7ca2c.png)


Release Mode

![screenshot_1518586019](https://user-images.githubusercontent.com/23656789/36189216-19086926-1177-11e8-86d8-122774560dc5.png)

**Comment by deva11** [comment]
Insights please

**Comment by deva11** [comment]
It would be helpful if you cud give a push to the solution

**Comment by cinder92** [comment]
same issue here, with android but with an streaming url, app works fine on debug mode, but on release after init the TrackSetup, it stop working

**Comment by Guichaguri** [comment]
I'll check it out when I have time

**Comment by deva11** [comment]
We are waiting for it!..

**Comment by MohammadElKhatib** [comment]
after my testing the issue appear on release apk even it is returning the same resources id and that's strange, 

I tried to use different source files such as import or require or even i put the files in raw folder and i call using uri such as
{uri:'file:///android_asset/test.mp3'}

and all didn't work on release version

**Comment by deva11** [comment]
@Guichaguri How the uri gets changed !? made the apk with Same code !

**Comment by MohammadElKhatib** [comment]
@deva11 he is closing my issue post as it is same of current one, i said that track url is different and i mean that on release the files location is changed but the track player is returning same resource ID.

**Comment by deva11** [comment]
Okay okay! Fine @MohammadElKhatib .

**Comment by iThinker** [comment]
Looks like the issue happens because react-native changed the way resources are packaged. In the past everything was drawable. But now resources are packaged as raw.
```
ResourceDrawableIdHelper helper = ResourceDrawableIdHelper.getInstance();
int id = helper.getResourceDrawableId(context, uri);
```
This code does not work in release.

**Comment by dcvz** [comment]
Is this still an issue?

**Comment by iThinker** [comment]
@dcvz were there any commits changing the behaviour? Non-image resources are packaged as raw. Although if you want to bundle a lot of audio in APK itself, you might have more issues with the fact that APK can only be 100 mb large, and you need to use expansion files and generate paths for content provider for example.

**Comment by Pushplaybang** [comment]
is this still an issue?

**Comment by iThinker** [comment]
Yes. Because resources are packaged not as drawables in newest RN. https://github.com/react-native-kit/react-native-track-player/blob/e217c74b11772dc32d0d08236ec3feaeb606748a/android/src/main/java/com/guichaguri/trackplayer/service/Utils.java#L65 this code is wrong. It should try to search resource in raw first.

**Comment by przemyslawdziadek** [comment]
Hi, when problem will be solved? There is a way to work around the problem? It is works in dev version of package? Because on 1.0.0 I have this problem (With React Native 0.57.5)

**Comment by Guichaguri** [comment]
Sorry for taking too long to look into this.

In release mode, RN used to copy all resources to the `drawable` directory, and this module used to look up the files there.
It became a problem when RN started to copy non-image files into the `raw` directory.

**Comment by SimerSingh** [comment]
> same issue here, with android but with an streaming url, app works fine on debug mode, but on release after init the TrackSetup, app crashes

Wondering ..Were to able to fix it?

**Comment by PierreSachot** [comment]
Hi, 
I have the same problem on Android with a release apk loading a url live stream, is there a way to fix it ? 

Thanks.

**Comment by PierreSachot** [comment]
Problem solve, due to http instead of https in the streaming url
