### ISSUE TITLE
Missing capabilities on iOS using dev branch

### ISSUE THREAD

**Issue by markv** [react-native-kit/react-native-track-player#137]
<img width="299" alt="capabilities" src="https://user-images.githubusercontent.com/15932045/35655935-69b70c84-0744-11e8-9ce1-1c960d3d6d55.png">

@Guichaguri 

I'm trying to enable seeking in the ios control center using the dev branch but the capabilities seem to be missing

**Comment by Guichaguri** [comment]
That's expected. Those options are not supported on iOS yet
