### ISSUE TITLE
How to hide notification 

### ISSUE THREAD

**Issue by userJayPrajapat** [react-native-kit/react-native-track-player#138]
i am new in react-native and please tell me how to hide notification bar

**Comment by Guichaguri** [comment]
You can't, and that will not be implemented.

To properly use a service to play music, Android requires you to set that service as active ("in background"), and to make sure the user knows it's active and constantly working, it requires you to show a notification.

To remove the notification, you'd have to remove the service from background, which means Android could limit its CPU usage or even kill the service if it needs resources.

The whole point of this project is to be the base module for music/podcast apps. You shouldn't use it for simple playback (such as sound effects)

**Comment by userJayPrajapat** [comment]
notification click and view render
