### ISSUE TITLE
Hello... Got this error on EXPO

### ISSUE THREAD

**Issue by inglesuniversal** [react-native-kit/react-native-track-player#139]
react-native-track-player: undefined is not an object (evaluating 'I.STATE_NONE') imported from null...

both file and audio where provides as URLs

Thanks

**Comment by SatoshiInoue** [comment]
You'll have to detach Expo I believe.

**Comment by moonstruck** [comment]
> If you need to include a library which includes react-native link in its install instructions, there's a good chance you need to eject from CRNA.

[Documentation](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md#react-native-link)

**Comment by SatoshiInoue** [comment]
I had to move away from Expo to use this library. There was an OkHttpClient conflict in Android, and had a CocoaPod problem for iOS upon detaching and linking this library.

**Comment by ludobit** [comment]
@SatoshiInoue do you know if the conflict will be solved?

**Comment by SatoshiInoue** [comment]
@ludobit I got rid of Expo entirely, not even detaching, but started a clean react boilerplate and then linked TrackPlayer. Expo doesn't let you play music in the background anyway, so it really doesn't go well with TrackPlayer.

**Comment by ludobit** [comment]
@SatoshiInoue thank you. I've started new clean project

**Comment by dcvz** [comment]
We don't support expo at the moment and looks like the issue was resolved. Closing.
