### ISSUE TITLE
Some class deprecated in Android API 26

### ISSUE THREAD

**Issue by thinhvo-groove** [react-native-kit/react-native-track-player#140]
I have no way of showing up notification on android API 26, I guess one of the reasons is that android.support.v7.app.NotificationCompat.MediaStyle is now deprecated on API 26. 

https://developer.android.com/reference/android/support/v4/media/app/NotificationCompat.MediaStyle.html

What can I do to make it work?

**Comment by thinhvo-groove** [comment]
Have it solved yet?

**Comment by dcvz** [comment]
This is solved as part of release v1.0.0
