### ISSUE TITLE
ios : error JSONStringify encoutered the fllowing  error 

### ISSUE THREAD

**Issue by maydon** [react-native-kit/react-native-track-player#143]
hello

i have add react-native-track-pkayer ( version 0.2.2 ) in my project  react-native  
`"dependencies": {
    "html-entities": "^1.2.0",
    "jwt-decode": "^2.1.0",
    "moment": "^2.18.1",
    "qs": "^6.3.0",
    "react": "15.4.2",
    "react-addons-shallow-compare": "^15.4.2",
    "react-native": "^0.42.0",`

and i have this error 
![simulator screen shot - iphone 6 - 2018-02-09 at 09 24 47](https://user-images.githubusercontent.com/12683927/36018280-765478e0-0d7b-11e8-96aa-bba3b473291b.png)

**Comment by dcvz** [comment]
Is this still an issue with the latest version @maydon?
