### ISSUE TITLE
iOS MediaWrapper.swift - play() invoked by playNext()/playPrevious()

### ISSUE THREAD

**Issue by SatoshiInoue** [react-native-kit/react-native-track-player#146]
Hi - this is an improvement suggestion.

On iOS, if I pause the player and then call TrackPlayer.skipToNext(), it starts playing the current track.

I checked MediaWrapper.swift and noticed an issue: Both playNext() and playPrevious() invokes play(). play() goes into this block:
```
if player.state == .paused {
    player.resume()
    return
}
```

So it never calls

```
let track = queue[currentIndex]
player.play(track: track)
```
which is the actual skipping part. For now, I created a method, playAfterSkip() in which I just entirely removed the first if block. Let me know if you agree to add this change or something based on this.

**Comment by willcosgrove** [comment]
I think I found the problem.  I just don't have a solution 😬

I posted a comment describing the reason for the problem here: https://github.com/react-native-kit/react-native-track-player/pull/176/comment#issuecomment-411822738
