### ISSUE TITLE
Not playing local files

### ISSUE THREAD

**Issue by sagargheewala** [react-native-kit/react-native-track-player#147]
Hello,

I am using dev branch and try to play local file then give me below error

The operation couldn’t be completed. (RNTrackPlayer.AudioPlayerError error 0.)

I'm currently downloading files in default app path.

file path : /Users/ronit/Library/Developer/CoreSimulator/Devices/E0D347CD-3E4F-4FAA-A5EB-CCE53874A744/data/Containers/Data/Application/F32ECF53-F58A-4A44-914B-BD2903D1C64D/Documents/191plus-jmki-fx.mp3

with or with out use "file://"

**Comment by bearty** [comment]
Same error. Tried with "file://" too.
Do you solved this?

**Comment by phil-andrews** [comment]
Use file:/// + /file name. Needs to be four slashes on iOS.

**Comment by domingowensnsoft** [comment]
the files name don't use chinese, because the plugins don't recognition chinese, it's not about the file slashes problem
