### ISSUE TITLE
Control on iPhone lock screen ?

### ISSUE THREAD

**Issue by donghungx** [react-native-kit/react-native-track-player#156]
I use this 

> TrackPlayer.updateOptions({
    capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SEEK_TO,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS
    ]
});

To get control on android notification, it work, but on iPhone not. Anybody know how to do this stuff?

**Comment by phil-andrews** [comment]
Duplicate #77 

See the final message for a workaround solution.
