### ISSUE TITLE
Duration not being set when downloading from URL. How is duration acquired?

### ISSUE THREAD

**Issue by phil-andrews** [react-native-kit/react-native-track-player#158]
_Platform: iOS
react-native-track-player: 0.2.2
RN: 0.51.0_

I have  my audio downloads routed through an express server. So my download pipe looks like this...

**Request**
```
  request
    .get(url)
    .on('response', (r2) => {
      res.set(r2.headers)
    })
    .pipe(res)
```

The issue is that doing it this way seems to prevent RNTP from calculating the duration of a track. That issue then prevents any seek event from occuring. I can confirm that tracks downloaded to the local cache and then loaded set duration correctly and seek properly. Am I way off base here or is this simply a specific header that the download module is looking for? I've been digging through the native code but I haven't been able to determine what exactly is needed for them to calculate duration.

**Response Header**
```
X-Powered-By | Express
Access-Control-Allow-Origin | *
content-type | audio/mpeg
content-length | 20344112
date | Wed, 07 Mar 2018 10:58:20 GMT
last-modified | Wed, 07 Mar 2018 10:50:55 GMT
etag | "18e83f916aac69698860d7581a5b08cb"
x-amz-meta-generated-by-host | a40a4b847089
x-amz-meta-output-identifier | combined
accept-ranges | bytes
server | AmazonS3
age | 49282
x-cache | Hit from cloudfront
via | 1.1 1319d231d29e40f673d12c073e7b6c38.cloudfront.net (CloudFront)
x-amz-cf-id | qV3hJnG22VeEGo_01Kfz2J7mw-jDP9RUto-v4XwCczJqG3amz1jniA==
```

If I download straight from the original URL duration is set as expected. I don't know that this is an RNTP issue so much as I need to be setting something at the API that I'm currently not.

**Comment by Guichaguri** [comment]
Which platform? Android, iOS or UWP?

**Comment by phil-andrews** [comment]
iOS

Test URL:
https://amma-prod.ngrok.io/episode/download/a19e04f4b9580633386a09baa6ab9f51

**Comment by phil-andrews** [comment]
This doesn't answer the question of where duration is calculated but the solution to the problem of duration not being calculated was to pass on the initial request headers to the re-routed request. This makes plenty of sense. It looks like this...

```
  const options = {
    url: url,
    headers: {
      ...req.headers
    },
    rejectUnauthorized: false
  }
  request
    .get(options)
    .on('response', (r2) => {
      const headers = {
        ...r2.headers,
        Connection: 'Keep-Alive'
      }
      res.set(r2.headers)
    })
    .pipe(res)
```

**Comment by phuongwd** [comment]
@phil-andrews please try with Accept-Ranges https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges

**Comment by dcvz** [comment]
We now handle these cases and it shouldn't be a problem with the latest versions
