### ISSUE TITLE
is there a way to play two audio at once?

### ISSUE THREAD

**Issue by ngrj** [react-native-kit/react-native-track-player#161]
I'm trying to implement song crossfading to my app, I was able to do it using react-native-sound but since the audio module is not registered as a service, the app is being killed by AMS, so I'm hoping to use this module instead . I'm not sure how I can do it using react-native-track-player, any guidance ?

**Comment by Guichaguri** [comment]
No, it used to, but not anymore.
The proper way to implement effects like crossfading is to do it in native code directly, as it will be much smoother and less CPU intensive.

We'll consider this as a suggestion :)

**Comment by ngrj** [comment]
okay thanks a lot .

**Comment by chrismang** [comment]
@ngrj could you or anybody else do this feature? It would be great to have it!

**Comment by Guichaguri** [comment]
#670
