### ISSUE TITLE
[IOS] skipToNext func continues to play current song when player state is STATE_PAUSE

### ISSUE THREAD

**Issue by thinhvo-groove** [react-native-kit/react-native-track-player#163]
On iOS, I call skipToNext func when I pause a song, it continues to play the current song instead of play next. Is it the default dehavior of iOS or is a bug?

**Comment by osiloke** [comment]
Hey, why was this closed? I have the same issue. After the player is paused, sending either skipToNext/skipToPrevious plays the current track
