### ISSUE TITLE
Unable to access TrackPlayer.STATE_PAUSED

### ISSUE THREAD

**Issue by darrenchiu** [react-native-kit/react-native-track-player#168]
I am trying to follow the demo project to setup my project, but it seems that i cannot do the state comparison just like the example:

`this.props.state == TrackPlayer.STATE_PAUSED`

When I try to print out `TrackPlayer.STATE_PAUSED`, it is always null? May I know if this is expected or my usage of this state constant is incorrect?

Thanks a lot.

**Comment by Guichaguri** [comment]
Duplicate of #141
