### ISSUE TITLE
Problems occured when calling TrackPlayer.remove() method

### ISSUE THREAD

**Issue by moonou** [react-native-kit/react-native-track-player#169]
on the iOS, after i removed the track using `TrackPlayer.remove()` method, the system would play the track again automatically, and also I would find related codes in the link below [url](https://github.com/react-native-kit/react-native-track-player/blob/dev/ios/RNTrackPlayer/Logic/MediaWrapper.swift#L102-L122) . But the same situation didnot happen on Android.
I feel confused. Does this feature be removed on the iOS or added to the Android? I think this logic should be handled by the user.

**Comment by stachu2k** [comment]
I think iOS version and Android version are developed by different developers, so there may be some oversight and difference in implementation, what should not happen. I have also noticed some different behaviours in iOS comparing to Android and had to adjust my code to handle different situations.

**Comment by dcvz** [comment]
Sorry @moonou is the issue that you tried to remove the currently playing track?

**Comment by moonou** [comment]
@dcvz Thank you reply, that happened when I remove currently playing track.
