### ISSUE TITLE
Is this module still maintained?

### ISSUE THREAD

**Issue by mnlbox** [react-native-kit/react-native-track-player#171]
Hi guys,
I see many many crash report about this module on many device (**13 issue**). Are you still working on this for more stable module or not?
It's a very important decision for me for using you module in production or not. :thinking: 

crash report issues that open now: (**13 issue**)
https://github.com/react-native-kit/react-native-track-player/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+crash

**Comment by Guichaguri** [comment]
Most of these issues are related to the way they are using the module in their apps. There are a few devs using it in pretty big apps.
I just started working on a Android rework (#165), which should fix most of the current issues.

**Comment by mnlbox** [comment]
Thanks for your reply and for recent commits. I think android support need some fix that I'm so glad that you working on it (#165). I wish we can have that PR as soon as possible. :wink:

**Comment by jasongrishkoff** [comment]
I'm one of those devs using this on a pretty big app with very few issues :)

**Comment by dcvz** [comment]
As this has been addressed, I will close this issue now :) also we just published a new version!
