### ISSUE TITLE
Multitrack Playing?

### ISSUE THREAD

**Issue by ashishpandey001** [react-native-kit/react-native-track-player#172]
Hey, this library looks amazing and I see that you've considered a lot of the recommendations suggested by Google. I would like to know how would you play multiple files using this library. From what I understand, I'd have to import and create TrackPlayer multiple times and alias them but doesn't look feasible when the number of files to be played could be dynamic.
Like this:

```
import TrackPlayer as TrackPlayer1 from 'react-native-track-player'
import TrackPlayer as TrackPlayer2 from 'react-native-track-player'
import TrackPlayer as TrackPlayer3 from 'react-native-track-player'
```

I'm currently using react-native-sound wherein I have to create instances of the audio tracks, and they can be instantiated dynamically. So, multitrack playing simple to implement using react-native-sound.

What would be your approach to play multiple files together using this library?
Thank you!

**Comment by Guichaguri** [comment]
As this module is meant to be used by music/podcast apps only, we don't support or plan to support playing multiple tracks at the same time. The reason for that is that the media controls and status is directly linked to the playing track.

I'd love to hear what use cases you have for multiple players. The only one we know is cross-fading, which should be implemented as a native transition.

**Comment by smkhalsa** [comment]
@Guichaguri I have a use case for multitrack usage. I'm developing a guided meditation app. The app allows users to select music to play and also has a voice guidance feature. If music is playing and a user starts a voice guided meditation, the music volume would be reduced but continue playing in the background.

**Comment by nezaidu** [comment]
lol, have the exact same situation as @smkhalsa

**Comment by aliunco** [comment]
I'm in the same situation as @nezaidu & @smkhalsa 🤣

**Comment by prashen** [comment]
My question is also the same. My app plays 13 songs at a time like clap, drum, guitar and it's working with react-native-sound. But I am getting some sync issue between songs after some time playing it in Android. I am doing caching and creating dynamic instances for each songs and using for loop when play button clicks. 

Can I use this plugin specially for multiple sound play instead of react-native-sound?

**Comment by Guichaguri** [comment]
No, you can't.

I've done track synchronization before, and I remember it being a hard thing to do if you don't have access to low-level APIs, unfortunately, you may need to build your own custom player that syncs the tracks together.

**Comment by AdamGerthel** [comment]
I have the same problem, in my case for a game with separate tracks for music and ambiance. I've tried expo-av, react-native-sound and react-native-audio-toolkit but they're all riddled with bugs :(

**Comment by TowhidKashem** [comment]
> I have the same problem, in my case for a game with separate tracks for music and ambiance. I've tried expo-av, react-native-sound and react-native-audio-toolkit but they're all riddled with bugs :(

Did you figure out a solution to this by any chance, I have a similar requirement..

**Comment by AdamGerthel** [comment]
@TowhidKashem I ended up with this solution: https://github.com/expo/expo/issues/1873#issuecomment-592214795

**Comment by TowhidKashem** [comment]
@AdamGerthel thanks!

**Comment by AdamGerthel** [comment]
Is it still not possible to play multiple tracks in parallell?

**Comment by KrisLau** [comment]
@AdamGerthel nope https://github.com/doublesymmetry/react-native-track-player/issues/1540#issuecomment-1128141634

**Comment by Zain-1998** [comment]
@smkhalsa how did you achieve this? I have the exact same use case as you, I am also developing a guided meditation app, with background music. Let me know how you achieved this. Thanks in advance.

**Comment by smontlouis** [comment]
It's possible to play a main track while using the PlaybackService to trigger other sounds using expo-av.
You'll need to put the additional sounds in a store that can be accessed by the PlaybackService, like for example jotai.

**Comment by linhkiubo98** [comment]
> Hey, this library looks amazing and I see that you've considered a lot of the recommendations suggested by Google. I would like to know how would you play multiple files using this library. From what I understand, I'd have to import and create TrackPlayer multiple times and alias them but doesn't look feasible when the number of files to be played could be dynamic. Like this:
> 
> ```
> import TrackPlayer as TrackPlayer1 from 'react-native-track-player'
> import TrackPlayer as TrackPlayer2 from 'react-native-track-player'
> import TrackPlayer as TrackPlayer3 from 'react-native-track-player'
> ```
> 
> I'm currently using react-native-sound wherein I have to create instances of the audio tracks, and they can be instantiated dynamically. So, multitrack playing simple to implement using react-native-sound.
> 
> What would be your approach to play multiple files together using this library? Thank you!

**Comment by KrisLau** [comment]
@linhkiubo98 From what I last remember of this package, it is not possible to play multiple tracks at the same time so you'll probably want to use to expo-av for that

**Comment by ashishpandey001** [comment]
please use expo-av for low-level access. I did not use this lib due to its API design. Also, keep in mind many device OS implementations have a limit on how many dynamic sounds you can play together at once. This is a problem with low-end devices, so you should probably involve a server, merge tracks, and get a single output to play. If you go that way it wouldn't matter which lib you used unless there's a specific feature that would be unavailable in the others.

**Comment by KrisLau** [comment]
@ashishpandey001 Out of curiosity is there a specific lib you would recommend for merging tracks on a server specifically for node? I ended up using expo-av to just manually control the timing of merging songs but it would be nice to have another option if need be!

**Comment by ashishpandey001** [comment]
@KrisLau [fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) is my preferred choice to play with multimedia using node.js. You can use the ffmpeg `amix` filter to perform the mixing. If you need to make it more latency-sensitive, you could use streams to optimise it. Remember that this needs ffmpeg and the respective encoders/decoders to work.
