### ISSUE TITLE
[Android] App reload on pressing player notification

### ISSUE THREAD

**Issue by peterlazar1993** [react-native-kit/react-native-track-player#175]
After playing a track and moving out of the app, the track continues to play in the background, so far so good.

Now when I tap on the notification for the player, it looks like the js context reloads and hence the app loads to the home/initial screen. Is this the expected behaviour or is there something that I'm missing?

**Comment by peterlazar1993** [comment]
I was able to overcome this by making the app a "singleTop" app, by adding android:launchMode="singleTop" in the manifest, for more info https://inthecheesefactory.com/blog/understand-android-activity-launchmode/en

**Comment by alikazemkhanloo** [comment]
I encountered the same problem as you did, But your solution did not worked for me.
Also I want to open a certain screen on notification tapping, I'm thinking of using a deeplink. Is it possible? if so, how?

**Comment by jariwalabhavesh** [comment]
@peterlazar1993 
I am also facing this issue and in my manifest `android:launchMode="singleTop" ` is already there still app is reluanApp reload on pressing player notification.
I am using react-native-router-flux v3 so that is creating issue?? I don't know what exactly creating a problem.?

**Comment by ishigamii** [comment]
https://github.com/react-native-kit/react-native-track-player/issues/340
