### ISSUE TITLE
Stop the music when shutdown the screen or minimize the app

### ISSUE THREAD

**Issue by Davide57** [react-native-kit/react-native-track-player#178]
I don't understand how to stop the music when shutdown the screen or minimize the app.
I've done this in the constructor of the App:
```
`AppRegistry.registerComponent('backgroundMusic', () => App);
    TrackPlayer.registerEventHandler(module.exports = async (data) => {
      if(data.type == 'playback-state') {
          TrackPlayer.play();
      }
  });
    // Creates the player
    TrackPlayer.setupPlayer().then(async () => {
    
        // Adds a track to the queue
        await TrackPlayer.add({
            id: '1',
            url: require('./music/background.mp3'),
        });
        TrackPlayer.updateOptions({
          stopWithApp: true
      });
```
        TrackPlayer.setVolume(0.5);
        // Starts playing it
        TrackPlayer.play();
        

    });`

The music starts but it is unstoppable, someone can help me?

**Comment by jimthedev** [comment]
Have you tried using React Native's app state to detect when the app goes into the background? https://facebook.github.io/react-native/docs/appstate.html Once that happens you can call TrackPlayer.stop();

**Comment by dcvz** [comment]
As long as you have `stopWithApp: true` it'll stop when you shut down the app.. for doing it after background you'll have to detect that yourself and call `stop`

**Comment by parthsr** [comment]
@dcvz nope this doesnt work. I have stopWithApp: true but it doesnt turn off the music when app is shutted down
