### ISSUE TITLE
Hide notification 

### ISSUE THREAD

**Issue by Davide57** [react-native-kit/react-native-track-player#182]
Using react-native-track-player appears a notification with the buttons to manage the tracks.
Reading the documentation I found how to change options about it but nothing about how to hide it.
How can I do that?

**Comment by Guichaguri** [comment]
There is no way to hide it. This module is dedicated to music/podcast apps, to play long-running tracks smoothly on Android, you need to use a service. Those services need to be declared as "important" or "active" so the OS doesn't kill them, and for that, Android requires you to attach a notification, so the user knows something is running.

If you need a player module for any other use case, please, use `react-native-sound` instead.
