### ISSUE TITLE
iOS build failed  Xcode 9.2 library not found for -lswiftCoreAudio for architecture x86_64

### ISSUE THREAD

**Issue by mydesweb** [react-native-kit/react-native-track-player#184]
`library not found for -lswiftCoreAudio for architecture x86_64`
I think we need a fix, I found something related to this issue [here](https://hackernoon.com/migrating-perfect-project-to-swift-4-3ada7b4a3c1a)
any advice on how to compile this for the moment?

**Comment by jimthedev** [comment]
Two things:

1. I had to be at Xcode 9.3 to be able to get my app on my iPhone 6s (there are updated symbols). This means going to High Sierra.

2. Your specific problem IIRC is that you need to create a single swift file in xcode inside your project. Once you create this file then xcode will enable the xcode functionality.

**Comment by mydesweb** [comment]
@jimthedev  can you be more specific regarding point 2? since I am not an iOS dev..

I just upgraded Xcode to 9.3, init fresh react-native , link react-native-track-player and I am not able to compile the project, I see many issues:

`ld: warning: Auto-Linking library not found for -lswiftCoreAudio
ld: warning: Auto-Linking library not found for -lswiftCoreMedia
ld: warning: Auto-Linking library not found for -lswiftAVFoundation
ld: warning: Auto-Linking library not found for -lswiftSwiftOnoneSupport
ld: warning: Auto-Linking library not found for -lswiftCore
ld: warning: Auto-Linking library not found for -lswiftQuartzCore
ld: warning: Auto-Linking library not found for -lswiftCoreImage
ld: warning: Auto-Linking library not found for -lswiftCoreGraphics
ld: warning: Auto-Linking library not found for -lswiftDispatch
ld: warning: Auto-Linking library not found for -lswiftObjectiveC
ld: warning: Auto-Linking library not found for -lswiftCoreFoundation
ld: warning: Auto-Linking library not found for -lswiftUIKit
ld: warning: Auto-Linking library not found for -lswiftMediaPlayer
ld: warning: Auto-Linking library not found for -lswiftDarwin
ld: warning: Auto-Linking library not found for -lswiftMetal
ld: warning: Auto-Linking library not found for -lswiftsimd
ld: warning: Auto-Linking library not found for -lswiftFoundation
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SwiftObject", referenced from:
      type metadata for RNTrackPlayer.MediaWrapper in libRNTrackPlayer.a(MediaWrapper.o)
  "_OBJC_METACLASS_$_SwiftObject", referenced from:
      metaclass for RNTrackPlayer.MediaWrapper in libRNTrackPlayer.a(MediaWrapper.o)
  "static Foundation.CharacterSet.urlQueryAllowed.getter : Foundation.CharacterSet", referenced from:
      RNTrackPlayer.MediaURL.init(object: Any?) -> RNTrackPlayer.MediaURL? in libRNTrackPlayer.a(MediaURL.o)
  "Foundation._convertErrorToNSError(Swift.Error) -> __ObjC.NSError", referenced from:
      reabstraction thunk helper from @callee_unowned @convention(block) (@unowned __ObjC.NSString?, @unowned __ObjC.NSString?, @unowned __ObjC.NSError?) -> () to @callee_guaranteed (@owned Swift.String?, @owned Swift.String?, @owned Swift.Error?) -> () in libRNTrackPlayer.a(RNTrackPlayer.o)
  "Foundation._convertNSErrorToError(__ObjC.NSError?) -> Swift.Error", referenced from:
      RNTrackPlayer.AudioPlayer.setAudioSession(active: Swift.Bool) -> () in libRNTrackPlayer.a(AudioPlayer.o)
      RNTrackPlayer.RNTrackPlayer.setupPlayer(config: [Swift.String : Any], resolve: (Any?) -> (), reject: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libRNTrackPlayer.a(RNTrackPlayer.o)
  "Foundation.URL._bridgeToObjectiveC() -> __ObjC.NSURL", referenced from:
      @nonobjc __ObjC.AVPlayerItem.init(url: Foundation.URL) -> __ObjC.AVPlayerItem in libRNTrackPlayer.a(AudioPlayer.o)
      RNTrackPlayer.MediaWrapper.play() -> () in libRNTrackPlayer.a(MediaWrapper.o)
  "Foundation.URL.init(string: Swift.String) -> Foundation.URL?", referenced from:
      RNTrackPlayer.MediaURL.init(object: Any?) -> RNTrackPlayer.MediaURL? in libRNTrackPlayer.a(MediaURL.o)
  "type metadata for Foundation.URL", referenced from:
      l_get_field_types_MediaURL in libRNTrackPlayer.a(MediaURL.o)
  "Foundation.Data._bridgeToObjectiveC() -> __ObjC.NSData", referenced from:
      @nonobjc __ObjC.UIImage.init(data: Foundation.Data) -> __ObjC.UIImage? in libRNTrackPlayer.a(MediaWrapper.o)
  "static Foundation.Data._unconditionallyBridgeFromObjectiveC(__ObjC.NSData?) -> Foundation.Data", referenced from:
      reabstraction thunk helper from @escaping @callee_guaranteed (@owned Foundation.Data?, @owned __ObjC.URLResponse?, @owned Swift.Error?) -> () to @escaping @callee_unowned @convention(block) (@unowned __ObjC.NSData?, @unowned __ObjC.URLResponse?, @unowned __ObjC.NSError?) -> () in libRNTrackPlayer.a(MediaWrapper.o)
  "Foundation.Date.addingTimeInterval(Swift.Double) -> Foundation.Date", referenced from:
      RNTrackPlayer.QualityAdjustmentEventProducer.adjustQualityTimeInternal.didset : Swift.Double in libRNTrackPlayer.a(QualityAdjustmentEventProducer.o)
  "Foundation.Date.timeIntervalSinceNow.getter : Swift.Double", referenced from:
      RNTrackPlayer.QualityAdjustmentEventProducer.adjustQualityTimeInternal.didset : Swift.Double in libRNTrackPlayer.a(QualityAdjustmentEventProducer.o)
  "static Foundation.Date._unconditionallyBridgeFromObjectiveC(__ObjC.NSDate?) -> Foundation.Date", referenced from:
      RNTrackPlayer.QualityAdjustmentEventProducer.adjustQualityTimeInternal.didset : Swift.Double in libRNTrackPlayer.a(QualityAdjustmentEventProducer.o)
  "ObjectiveC._convertBoolToObjCBool(Swift.Bool) -> ObjectiveC.ObjCBool", referenced from:
      @objc RNTrackPlayer.BackgroundHandler.beginBackgroundTask() -> Swift.Bool in libRNTrackPlayer.a(BackgroundHandler.o)
      @objc RNTrackPlayer.BackgroundHandler.endBackgroundTask() -> Swift.Bool in libRNTrackPlayer.a(BackgroundHandler.o)
      @objc RNTrackPlayer.Reachability.reachableOnWWAN.getter : Swift.Bool in libRNTrackPlayer.a(Reachability.o)
      @objc RNTrackPlayer.Reachability.startNotifier() -> Swift.Bool in libRNTrackPlayer.a(Reachability.o)
      @objc RNTrackPlayer.Reachability.isReachable() -> Swift.Bool in libRNTrackPlayer.a(Reachability.o)
      @objc RNTrackPlayer.Reachability.isReachableViaWiFi() -> Swift.Bool in libRNTrackPlayer.a(Reachability.o)
      @objc RNTrackPlayer.AudioPlayer.adjustQualityAutomatically.getter : Swift.Bool in libRNTrackPlayer.a(AudioPlayer.o)
      ...
  "ObjectiveC._convertObjCBoolToBool(ObjectiveC.ObjCBool) -> Swift.Bool", referenced from:
      @objc RNTrackPlayer.Reachability.reachableOnWWAN.setter : Swift.Bool in libRNTrackPlayer.a(Reachability.o)
      @objc RNTrackPlayer.AudioPlayer.adjustQualityAutomatically.setter : Swift.Bool in libRNTrackPlayer.a(AudioPlayer.o)
      @objc RNTrackPlayer.AudioPlayer.resumeAfterInterruption.setter : Swift.Bool in libRNTrackPlayer.a(AudioPlayer.o)
      @objc RNTrackPlayer.AudioPlayer.resumeAfterConnectionLoss.setter : Swift.Bool in libRNTrackPlayer.a(AudioPlayer.o)
      @objc RNTrackPlayer.AudioPlayer.pausedForInterruption.setter : Swift.Bool in libRNTrackPlayer.a(AudioPlayer.o)
      @objc RNTrackPlayer.AudioPlayer.qualityIsBeingChanged.setter : Swift.Bool in libRNTrackPlayer.a(AudioPlayer.o)
      @objc RNTrackPlayer.AudioPlayer.setAudioSession(active: Swift.Bool) -> () in libRNTrackPlayer.a(AudioPlayer.o)
      ...
  "Darwin._convertDarwinBooleanToBool(Darwin.DarwinBoolean) -> Swift.Bool", referenced from:
      RNTrackPlayer.Reachability.startNotifier() -> Swift.Bool in libRNTrackPlayer.a(Reachability.o)
      RNTrackPlayer.Reachability.stopNotifier() -> () in libRNTrackPlayer.a(Reachability.o)
      closure #1 (Swift.UnsafeMutablePointer<__C.SCNetworkReachabilityFlags>) -> Swift.Bool in RNTrackPlayer.Reachability.(isReachableWithTest in _ABA917A8CD08ECF4A7D4A1108D051B63)((__C.SCNetworkReachabilityFlags) -> Swift.Bool) -> Swift.Bool in libRNTrackPlayer.a(Reachability.o)
      closure #1 (Swift.UnsafeMutablePointer<__C.SCNetworkReachabilityFlags>) -> Swift.Bool in RNTrackPlayer.Reachability.(reachabilityFlags in _ABA917A8CD08ECF4A7D4A1108D051B63).getter : __C.SCNetworkReachabilityFlags in libRNTrackPlayer.a(Reachability.o)
  "value witness table for Builtin.UnknownObject", referenced from:
      full type metadata for RNTrackPlayer.BackgroundHandler in libRNTrackPlayer.a(BackgroundHandler.o)
      full type metadata for RNTrackPlayer.PlayerEventProducer in libRNTrackPlayer.a(PlayerEventProducer.o)
      full type metadata for RNTrackPlayer.TrackEventProducer in libRNTrackPlayer.a(TrackEventProducer.o)
      type metadata for __ObjC.SCNetworkReachability in libRNTrackPlayer.a(Reachability.o)
      full type metadata for RNTrackPlayer.Reachability in libRNTrackPlayer.a(Reachability.o)
      full type metadata for RNTrackPlayer.AudioPlayer in libRNTrackPlayer.a(AudioPlayer.o)
      full type metadata for RNTrackPlayer.NetworkEventProducer in libRNTrackPlayer.a(NetworkEventProducer.o)
      ...
  "value witness table for Builtin.NativeObject", referenced from:
      full type metadata for RNTrackPlayer.MediaWrapper in libRNTrackPlayer.a(MediaWrapper.o)
  "Swift.String.init(_builtinStringLiteral: Builtin.RawPointer, utf8CodeUnitCount: Builtin.Word, isASCII: Builtin.Int1) -> Swift.String", referenced from:
      static (extension in RNTrackPlayer):__ObjC.AVPlayer.(ap_KVOProperties in _2CAF76C44F1F4F8066958DB8186B649F).getter : [Swift.String] in libRNTrackPlayer.a(PlayerEventProducer.o)
      RNTrackPlayer.PlayerEventProducer.observeValue(forKeyPath: Swift.String?, of: Any?, change: [__C.NSKeyValueChangeKey : Any]?, context: Swift.UnsafeMutableRawPointer?) -> () in libRNTrackPlayer.a(PlayerEventProducer.o)
      static RNTrackPlayer.Track.(ap_KVOProperties in _D1DABDE7A18D3470C0209F7228F5C23A).getter : [Swift.String] in libRNTrackPlayer.a(TrackEventProducer.o)
      RNTrackPlayer.TrackEventProducer.TrackEvent.rawValue.getter : Swift.String in libRNTrackPlayer.a(TrackEventProducer.o)
      _globalinit_33_ABA917A8CD08ECF4A7D4A1108D051B63_func0 in libRNTrackPlayer.a(Reachability.o)
      RNTrackPlayer.Reachability.init(reachabilityRef: __ObjC.SCNetworkReachability?) -> RNTrackPlayer.Reachability in libRNTrackPlayer.a(Reachability.o)
      variable initialization expression of RNTrackPlayer.Reachability.(reachabilitySerialQueue in _ABA917A8CD08ECF4A7D4A1108D051B63) : __ObjC.DispatchQueue in libRNTrackPlayer.a(Reachability.o)
      ...
  "Swift.String.init<A where A: Swift.CustomStringConvertible>(stringInterpolationSegment: A) -> Swift.String", referenced from:
      RNTrackPlayer.RNTrackPlayer.seek(to: Swift.Double) -> () in libRNTrackPlayer.a(RNTrackPlayer.o)
      RNTrackPlayer.RNTrackPlayer.setVolume(level: Swift.Float) -> () in libRNTrackPlayer.a(RNTrackPlayer.o)
      RNTrackPlayer.RNTrackPlayer.setRate(rate: Swift.Float) -> () in libRNTrackPlayer.a(RNTrackPlayer.o)
  "generic specialization <Swift.String> of Swift.String.init<A where A: Swift.CustomStringConvertible, A: Swift.TextOutputStreamable>(stringInterpolationSegment: A) -> Swift.String", referenced from:
`
thank you !

**Comment by Guichaguri** [comment]
Please, read the [troubleshooting section](https://github.com/react-native-kit/react-native-track-player/wiki/Installation#ios-library-not-found-for--lswiftcoreaudio-for-architecture-x86_64).

**Comment by mydesweb** [comment]
@Guichaguri  my fault, I didn't see this section, now it's working, you all are doing a great work here
