### ISSUE TITLE
some issues I found during testings, hope will help

### ISSUE THREAD

**Issue by mydesweb** [react-native-kit/react-native-track-player#186]
Player.stop() will return STATE_STOPPED on iOS and 0 (STATE_NONE) - Android bug

event handler is returning "STATE_PLAYING" as string on iOS and 3 on Android (well known bug)

if you call Player.remove([]) - with an empty array - the whole queue is cleared - iOS bug

sometimes the Player continue to play even if I remove the app from background with stopWithApp: true, moreover if I use stopWithApp: true the Player is very unstable but if set to false everything is working perfect, I think  stopWithApp  should not be an option :)

some inconsistency after last track is played
Android
`Object {type: "playback-queue-ended", position: 200.525, track: "2"}`

iOS
```
{type: "playback-state", state: "STATE_PAUSED"}
{type: "playback-queue-ended", track: "2", position: 200.6204081632653}
```

**Comment by Guichaguri** [comment]
Yes, we're working on those inconsistencies
