### ISSUE TITLE
iOS Project has many linker errors when developing only in Objective C

### ISSUE THREAD

**Issue by csotiriou** [react-native-kit/react-native-track-player#187]
Seems that when installing the library in a pure Objective C project, many many linker errors are present. Probably due to the react-native-track-player having Swift files inside, so the Swift versions of the libraries should be linked.

I personally solved the problem by adding a single swift file (empty) in my project, and accepting Xcode to ad da bridging header for Objective C. That converted my project to Objective C / Swift, and I was able to compile in Xcode.

This should be mentioned in the documentation.

React Native 0.54 / Xcode 9.3

**Comment by Guichaguri** [comment]
It actually is mentioned in the documentation, in the [troubleshooting section](https://github.com/react-native-kit/react-native-track-player/wiki/Installation#ios-library-not-found-for--lswiftcoreaudio-for-architecture-x86_64).
