### ISSUE TITLE
TypeError: _reactNativeTrackPlayer2.default.getVolume is not a function

### ISSUE THREAD

**Issue by oddpanda** [react-native-kit/react-native-track-player#190]
As the title suggests. SetVolume works as expected but when this is called I log this error.

`TypeError: _reactNativeTrackPlayer2.default.getVolume is not a function
`

Currently calling it after setup with: 

```
  async toggleVolume(){
    try {
      let volume = await TrackPlayer.getVolume()
      console.log('Current volume is ' + volume);
      this.setState({volume : volume})
    } catch(e){
      console.log(e);
    }
  }
```

**Comment by dcvz** [comment]
This should not be an issue with v1.0.0
