### ISSUE TITLE
getCurrentTrack returns null

### ISSUE THREAD

**Issue by msabaeian** [react-native-kit/react-native-track-player#195]
i got null when calling getCurrentTrack (song is playing)
```
let state = await TrackPlayer.getState(); // return state
let trackId = await TrackPlayer.getCurrentTrack(); // return null

```
platform Android
react-native 0.49.3
react 16.0.0-beta.5

**Comment by hiteshi-infotech** [comment]
got the same issue.

**Comment by krishna1012** [comment]
i am getting same issue.am i handling promise in wrong way.

**Comment by Guichaguri** [comment]
Are you still facing this issue in 1.0.0?

**Comment by krishna1012** [comment]
@Guichaguri yeah i am still facing issue i am able to get play state and other progress variables but not able to get current track.plz guide me .i am working on android.

**Comment by kyungjoongo** [comment]
same issue

**Comment by Guichaguri** [comment]
I'll be closing this issue. Feel free to reopen it if you're still having problems.
