### ISSUE TITLE
Feature request: preload next track from the queue

### ISSUE THREAD

**Issue by aksyonov** [react-native-kit/react-native-track-player#196]
When using this library to play music from remote server I notice delays between tracks (1-3 seconds and even more on 3g connection). It would be nice if the library could (optionally) preload next track from the queue so that listening became more seamless.

**Comment by Guichaguri** [comment]
Which platform?

**Comment by aksyonov** [comment]
Android

**Comment by Guichaguri** [comment]
This is one of the things that will be brought in #165

**Comment by mydesweb** [comment]
@Guichaguri I know you have asked, I use this solution in production and I can confirm that it is a very cool feature that the music continue to play after you close/remove the app from background. Hope you will not remove this feature, just try to improve the code if it is possible.. I heard that API 27 introduces new limitations about background tasks

**Comment by Guichaguri** [comment]
This feature has been released in 1.0.0.

**Comment by JakeMotta** [comment]
@Guichaguri pre-loading (pre-buffering?) the next track done automatically, or is this something we need to specify in the code? I can't seem to find anything specific on this topic. My app utilizes the track queue, but when I skip songs, there's a definite ~1 second delay between. Trying to figure out what I can do to help reduce/minimize this delay. Currently using react-native-track-player v(^1.2.3). Was using v2, but media controls weren't working so I swapped. Same issue on both versions though for track delay.

**Comment by BR4VE** [comment]
@JakeMotta Hi, have you figured that out what we need to do in order to enable pre-loading/pre-buffering? I also need that feature for my application
