### ISSUE TITLE
Incompatable type '()-> [AnyHashable: Any]'

### ISSUE THREAD

**Issue by jariwalabhavesh** [react-native-kit/react-native-track-player#199]
Hello
I had follow installation instruction and also followed ios trubleshooting part as well (creating dummy.swift file) but i am facing two error

1. Method does not override any method from its superclass
2. Overriding method with selector 'constantsExport' has incompatible type '()->[AnyHashable: Any]'
![screen shot 2018-05-15 at 4 55 22 pm](https://user-images.githubusercontent.com/10993666/40054213-b559ec9c-5861-11e8-8227-a16020834051.png)

Project  Details
react-native: 0.47.0
react-native-track-player: 0.2.4
xcode version: 9.1
os: MacOs Higher sierra (10.13.2)

**Comment by Guichaguri** [comment]
This should not be a problem anymore with the latest react-native. Please, update your project.
