### ISSUE TITLE
Error: Could not invoke TrackPlayerModule.setupPlayer null (Android)

### ISSUE THREAD

**Issue by KalebPortillo** [react-native-kit/react-native-track-player#200]
Hello, I am having a issue when trying to run this lib on Android...
In IOS works fine, but when I try to run on andorid it give me this error on de React-Native Red Screen:

![screen shot 2018-05-18 at 09 48 42](https://user-images.githubusercontent.com/10066821/40235560-0c63cbb8-5a81-11e8-8a64-792bded7b7c5.png)

The Strange part of this issue is that the error only shows in the red screen, in the chrome console it not appears.
The other thing is that if I print the TrackPlayer it displays the TrackPlayer object correctly, so the linking is working fine, I dont know what is causing this issue.

Thanks in advance for any help.
Cheers

**Comment by Guichaguri** [comment]
You're probably using a newer version of the support library. This issue is being addressed in #165

**Comment by KalebPortillo** [comment]
Yes, I downgraded my android project to API 26 and it works now

**Comment by ParthNandaniya** [comment]
can anyone solve this issue??
changing API to 26 not solcing problem

**Comment by Guichaguri** [comment]
@ParthNandaniya Try using the latest version, and make sure you have linked the module properly.
