### ISSUE TITLE
What formats (codecs) support in Android and iOS

### ISSUE THREAD

**Issue by liberd** [react-native-kit/react-native-track-player#202]
Hi, I dont find this in the docs. What codecs can I play with the player and how I config this. Im planning use SILK codec but I dont kwnow If is supported.
Thanks.

**Comment by Guichaguri** [comment]
On Android, if you're using the default player, there's an official list of the codecs supported: https://developer.android.com/guide/topics/media/media-formats

In case you're using ExoPlayer on Android, here's the list: https://google.github.io/ExoPlayer/supported-formats.html

**Comment by liberd** [comment]
Thanks @Guichaguri!
On iOS the player is only the official? (and supose, the codecs too)
