### ISSUE TITLE
No sound on iOS

### ISSUE THREAD

**Issue by janlonden** [react-native-kit/react-native-track-player#208]
As there are no install instructions for iOS in the documentation I tried adding RNTrackplayer.xcodeproj to my Libraries and then linking libRNTrackPlayer.a, as you would do with many other packages. I can build my app without problems and I can use the controls but there's no sound and the progress bar isn't moving. Any idea why it isn't working? Have I missed some installation step?

**Comment by dcvz** [comment]
there's plenty of documentation. It sounds like you may not be adding tracks and playing the properly. Are you still facing this issue?

**Comment by janlonden** [comment]
> there's plenty of documentation. It sounds like you may not be adding tracks and playing the properly. Are you still facing this issue?

I solved the issue by copying the example project and modifying it.

Good job on the new release!
