### ISSUE TITLE
Load and Play Next Track in Background (iOS)

### ISSUE THREAD

**Issue by whobutsb** [react-native-kit/react-native-track-player#211]
Hello All!  Looking for suggestions or tips on how to load a track when the application is in the background. 

Right now my application will request a track url, download, and play it, when the song has finished the state `playback-queue-ended` will fire a function and request a new track url, download it and play it.  This all works fine if the application is open and running.  But if the app is in the background or if the phone is locked then the music will stop after the first song has finished playing.  My guess is that javascript does not keep running in the background.

Just seeing if anyone has encountered this issue or has figured out how to keep the javascript running in the background.  

Thank you in advance!

**Comment by moonstruck** [comment]
Enable Background Modes from Capabilities.

**Comment by whobutsb** [comment]
I do have it enabled.  I think the issue lies in the execution of background javascript.

```
	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>fetch</string>
	</array>
```

**Comment by violetforest** [comment]
@whobutsb did you figure this out?

**Comment by whobutsb** [comment]
@violetforest - I haven't.  Are you experiencing the same issue?

**Comment by violetforest** [comment]
@whobutsb this is my issue https://github.com/react-native-kit/react-native-track-player/issues/220

**Comment by violetforest** [comment]
@whobutsb My first track only starts if its in the foreground. it doesnt start playing if it is started while the app is in the background (im usig a set timeout). im guessing you are pressing play on your first track so its startig okay but the next track isnt starting.

**Comment by whobutsb** [comment]
Exactly.  I'm fetching a new track, which I suspect is working, but it is not playing.

**Comment by violetforest** [comment]
@whobutsb [here]( https://github.com/indiecastfm/react-native-audio-streamer/issues/1) is a discussion from a different streaming module where people are experiencing the same issue

**Comment by whobutsb** [comment]
@violetforest Thanks for sharing!  It looks like at the end of the thread they were able to get it to work.  I might take some time and try to build a sample app to see if it indeed works.  Let me know if your experiences too.

**Comment by whobutsb** [comment]
The one downside is the project doesn't look like its being maintained. Last update was April 2017.

**Comment by moonstruck** [comment]
So far this one is the most maintained audio player module for react native. Last commit https://github.com/react-native-kit/react-native-track-player/commit/a89f8ba97a2462c137ccd126af9ec40962a82bb5 6 days ago.

**Comment by whobutsb** [comment]
@moonstruck I was referring to this repo - https://github.com/indiecastfm/react-native-audio-streamer.  The React Native Track Player contributors are doing an excellent job maintaining the project.  I would like to continue using it, but I need to solve this problem of playback in the background first.

**Comment by jasongrishkoff** [comment]
@whobutsb are you adding songs to the queue? With my app I actually line up 100 songs in a row when the user initiates the first play, and the background playback has no issues transitioning to the next song.

**Comment by whobutsb** [comment]
@jasongrishkoff - I'am adding to the queue.  But I before I add the track url to the queue, I first need to hit an api service to figure out what the next song is going to be.  I don't have all the next songs available to add in the beginning.

**Comment by salisuabubakar** [comment]
Please can someone help me with example how to show buffering with toggle play and pause. Thanks

**Comment by mateomorris** [comment]
@salisuabubakar not sure what you mean but I'd start here https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#getbufferedposition

**Comment by dcvz** [comment]
You're running into an issue with iOS.. once playback stops you'll have a limited amount of time before the OS kills the app. Your fetch for a new track must not be working effectively and the OS is shutting down the app. possibly the RN thread is also sleeping on you.

**Comment by dineshucreate** [comment]
@dcvz Sorry but, I do not agree with you on this because the same functionality is already available with one more package **react-native-music-control**  So I think it should be fixed.
One more thing it's already working with the IOS simulator So in my opinion there should be a nice fix for this.
I need your help with this!
Opening new issue here: [911](https://github.com/react-native-kit/react-native-track-player/issues/911)
