### ISSUE TITLE
Error when playing audio on background in Android 8+

### ISSUE THREAD

**Issue by nasmuris** [react-native-kit/react-native-track-player#212]
Hi, I have encountered errors while playback starts/stops in background. 
`java.lang.RuntimeException: Unable to unbind to service guichaguri.trackplayer.logic.services.PlayerService@4524003 with Intent { act=trackplayer.connect cmp=com.my.app/guichaguri.trackplayer.logic.services.PlayerService }: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.my.app/guichaguri.trackplayer.logic.services.PlayerTask (has extras) }: app is in background uid UidRecord{7afbdac u0a80 SVC  bg:+1m27s426ms idle change:idle procs:1 seq(0,0,0)}`
Steps to reproduce -> Open app, start some audio, lock the phone, after playing the track, the app should stop with error
In my scenario, I'm also starting the audio from background on some conditions, the same error occurs.
Similar error [here](https://stackoverflow.com/a/46445436)

**Comment by bodrug98** [comment]
I have the same problem,
The error occurs after some time if the audio is paused

**Comment by bodrug98** [comment]
Has anyone found a solution?

**Comment by dcvz** [comment]
This should be solved as part of v1.0.0
