### ISSUE TITLE
Can't kill app anymore (Android)

### ISSUE THREAD

**Issue by clundberg1** [react-native-kit/react-native-track-player#213]
After following the docs, I'm able to get an audio to play, and the notification appears correctly and all, but upon killing the app and running it once again, the entire app state is still there; almost like if I had only sent the app to the background, although React's life cycle hooks are definitely running again.

**Comment by jimthedev** [comment]
Can I ask what phone / api level / android version you are on? We're getting some weirdness but only on a Galaxy S9+ on api 26 / android 8.0.0. Specifically I am getting MediaPlayer.MEDIA_ERROR_SERVER_DIED

**Comment by clundberg1** [comment]
@jimthedev I'm only running it on the emulator Nexus 5X API 25 Android 7.1.1. There's actually no error whatsoever. What happens is that I kill the app, but when I reopen it, my redux state is still there. I'm assuming the library is somehow keeping the app alive in the background.

**Comment by jimthedev** [comment]
Gotcha. Is this the example app that you are running?

**Comment by clundberg1** [comment]
No, it's my own, although I'm not doing anything fancy. Just testing it out first. I managed to narrow it down for you a bit. It apparently only happens to me when streaming audio over the network. If the `url` property is a file system path, everything seems to work correctly.

**Comment by clundberg1** [comment]
Actually the audio even starts playing once again as soon as I run the app again.

**Comment by Guichaguri** [comment]
Does it still happens on 1.0.0?

**Comment by Drazail** [comment]
@Guichaguri 

yes, in my case if i inject the store into the registerEventHandler, as long as the MusicService is alive when onDestroy is called, the redux store persists between sessions.

however I'm not sure if this is a flaw with this library or our redux implementation, the work around is to reset the store. 

@clundberg1 
something like this worked for us:
```JavaScript
componentWillUnmount() {
    TrackPlayer.reset().then(() => store.dispatch(resetStore()));
  }
```

**Comment by Guichaguri** [comment]
You don't need to use `registerEventHandler` anymore, there is a new event registration method which allows you to separate your store from the playback service. Read more about it [here](https://github.com/react-native-kit/react-native-track-player/wiki/API#receiving-events).

**Comment by mimamuh** [comment]
@Guichaguri: I actually have the same issue on Android through multiple versions on different Android Simulators and on a real device with test and production builds equally. I had it with version 1.1.4 and it still exists after upgrading to 1.1.6.

I tired to use `stopWithApp: true` - but it doesn't change anything. I'm really confused about the issue. It works fine on iOS, so I guess it is not about my implementation but an Android issue.
