### ISSUE TITLE
Does anyone have this working on a Samsung Galaxy S9+

### ISSUE THREAD

**Issue by jimthedev** [react-native-kit/react-native-track-player#216]
This worked wonderfully for ios and android. The exception to that is two different people who have Samsung Galaxy S9's. With them I get a MEDIA_ERROR_SERVER_DIED error. I have been unable to determine what might be causing this and was curious if anyone else is working with these devices using this project.

**Comment by Guichaguri** [comment]
You're probably using the Android's SDK player, which is kinda unstable. As its code is inside the OS, it really depends on the Android version and the OEM's OS fork.

I really recommend you to [enable ExoPlayer](https://github.com/react-native-kit/react-native-track-player/wiki/Build-Preferences#exoplayer-android-only), as it's way more stable than the default player. In fact, we'll be removing the default player in the future and making ExoPlayer the default one.

**Comment by Guichaguri** [comment]
As the Android's SDK player have been removed from this package. This shouldn't be an issue anymore.
Please, try the new 1.0.0 version, feel free to reopen this issue if it's still not working.
