### ISSUE TITLE
No task registered for key TrackPlayer

### ISSUE THREAD

**Issue by farman05** [react-native-kit/react-native-track-player#217]
Sound is playing in background but still getting this error everytime on app start

`
    async componentDidMount() {
     
         TrackPlayer.setupPlayer().then(() => {
            console.log('ready')
             TrackPlayer.add({
                id: '234',
                url: 'http://soundbible.com/mp3/Tyrannosaurus%20Rex%20Roar-SoundBible.com-807702404.mp3',
                title: 'Track Title',
                artist: 'Track Artist',
                artwork: 'http://example.com/avaritia.png'
            });
            console.log('paly')
            TrackPlayer.play()
            // The player is ready to be used
        });`

**Comment by Guichaguri** [comment]
Register an event listener and those errors will stop showing up.

**Comment by RavindraMaddukuri** [comment]
I am also facing the same issue 

` playing(){
    TrackPlayer.setupPlayer().then(async () => {
      await TrackPlayer.add(playlistData);
      {TrackPlayer.play() }
     this.setState({
      paused:true
     })
    });
  }
  stop(){
    TrackPlayer.pause();
    this.setState({paused:false})
  }
skipToNext(){
  TrackPlayer.skipToNext();
}
skipToPrevious(){
  TrackPlayer.skipToPrevious();
}`
as u said, "Register an event listener and those errors will stop showing up."
how can I add register event

**Comment by RavindraMaddukuri** [comment]
I have solved by doing changes in the index.js file
`import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);`
Thank you
