### ISSUE TITLE
TrackPlayer.seekTo(100) Doesn't Change Position When Outside TrackPlayer.getPosition()

### ISSUE THREAD

**Issue by AustinErck** [react-native-kit/react-native-track-player#218]
I've included two code snippets below and hopefully it is a user error I'm seeing. Essentially if I run `seekTo` then `play` it doesn't seek as expected. If I wrap it in a `getPosition` it seeks as expected. My first thought was maybe the TrackPlayer isn't started but realized this is run in a promise chain based off `setupPlayer`. Is there a reason this is happening?

Example 1 (Working) - Seeks correctly then begins to play:
```
TrackPlayer.setupPlayer().then(() => {

  TrackPlayer.updateOptions({
    capabilities: [
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE
    ]
  });

  return TrackPlayer.add(tracks);
}).then(success => {      

  console.warn('Seeking to 100');

  // Load last position
  TrackPlayer.getPosition().then(position => {
    console.warn('Before seek position: ' + position)

    TrackPlayer.seekTo(100);
  });

  console.warn('Post seek')

  // Begin playback if argument is true
  if(startPlayback === true) {
    dispatch(play());
  }
}
```

Example 2 (Not Working) - Fails to seek and begins from the beginning of the first track:
```
TrackPlayer.setupPlayer().then(() => {

  TrackPlayer.updateOptions({
    capabilities: [
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE
    ]
  });

  return TrackPlayer.add(tracks);
}).then(success => {      

  console.warn('Seeking to 100');

  // Load last position
  TrackPlayer.getPosition().then(position => {
    console.warn('Before seek position: ' + position)
  });

  TrackPlayer.seekTo(100);
  console.warn('Post seek')


  // Begin playback if argument is true
  if(startPlayback === true) {
    dispatch(play());
  }
}
```

UPDATE: After further testing I've found the two flows below show it must be playing in order to seek. However the documentation states that in order to seek the player must be loaded. But from what I can tell it is loaded. Is this intended behavior? Is is possible to seek before actually beginning playback?

This flow works.
`setupPlayer` -> `add` -> `play` -> `seekTo`

This flow doesn't .
`setupPlayer` -> `add` -> `seekTo` -> `play`

**Comment by Guichaguri** [comment]
Android, iOS or UWP?

**Comment by AustinErck** [comment]
iOS

**Comment by brenwell** [comment]
Yep I am seeing the same issue, additionally no events are triggered so `TrackPlayer.Component` doesn't update. Any Ideas out there to solve this one?

**Comment by dcvz** [comment]
This should be solved in v1.0.0. the calls are now async so please use `await` I believe you're just running these too fast sequentially.

**Comment by brenwell** [comment]
Yes I noticed that play was not returning a promise and thus not waiting

**Comment by praisedavid787** [comment]
Hmmm, just hitting this one. Anyone fixed this yet.
