### ISSUE TITLE
No audio on Android

### ISSUE THREAD

**Issue by maendamedia** [react-native-kit/react-native-track-player#219]
Tried to install everything and on iOS it works great. But on android I do not get sound at all.
I followed the steps for installation, tried to switch to Exoplayer, but still no luck.

This is what I see in log:

`06-18 22:04:26.874 506-506/com.gigantfm D/ViewRootImpl@dde0d9d[NavigationActivity]: ViewPostImeInputStage processPointer 0
06-18 22:04:26.981 506-506/com.gigantfm D/ViewRootImpl@dde0d9d[NavigationActivity]: ViewPostImeInputStage processPointer 1
06-18 22:04:27.026 506-506/com.gigantfm D/ReactNativeTrackPlayer: onPlaybackUpdate
06-18 22:05:40.086 506-511/com.gigantfm I/art: Do partial code cache collection, code=122KB, data=122KB
06-18 22:05:40.087 506-511/com.gigantfm I/art: After code cache collection, code=122KB, data=122KB
    Increasing code cache capacity to 512KB
06-18 22:06:19.734 506-506/com.gigantfm D/ViewRootImpl@dde0d9d[NavigationActivity]: MSG_WINDOW_FOCUS_CHANGED 0
06-18 22:06:19.744 506-506/com.gigantfm D/SensorManager: unregisterListener ::   
06-18 22:06:20.388 506-506/com.gigantfm D/InputTransport: Input channel destroyed: fd=87
06-18 22:10:30.497 506-506/com.gigantfm D/ViewRootImpl@dde0d9d[NavigationActivity]: MSG_WINDOW_FOCUS_CHANGED 1
06-18 22:10:30.498 506-506/com.gigantfm D/ViewRootImpl@dde0d9d[NavigationActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -786186240}
06-18 22:10:30.501 506-506/com.gigantfm V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@436a46d nm : com.gigantfm ic=null
06-18 22:10:30.501 506-506/com.gigantfm I/InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
06-18 22:10:30.508 506-506/com.gigantfm D/InputTransport: Input channel constructed: fd=53
06-18 22:10:30.600 506-506/com.gigantfm D/SensorManager: registerListener :: 0, MPU6500 Acceleration Sensor, 66667, 0,  
06-18 22:10:31.594 506-506/com.gigantfm D/ViewRootImpl@dde0d9d[NavigationActivity]: ViewPostImeInputStage processPointer 0
06-18 22:10:31.950 506-506/com.gigantfm D/ViewRootImpl@dde0d9d[NavigationActivity]: ViewPostImeInputStage processPointer 1
06-18 22:10:31.988 506-506/com.gigantfm D/ReactNativeTrackPlayer: onPlaybackUpdate
06-18 22:10:33.477 506-506/com.gigantfm D/ViewRootImpl@dde0d9d[NavigationActivity]: ViewPostImeInputStage processPointer 0
06-18 22:10:33.593 506-506/com.gigantfm D/ViewRootImpl@dde0d9d[NavigationActivity]: ViewPostImeInputStage processPointer 1
06-18 22:10:33.673 506-506/com.gigantfm D/ReactNativeTrackPlayer: onPlaybackUpdate`

I use an Shoutcast stream by the way. Any ideas?

**Comment by maendamedia** [comment]
Any idea?
Fresh install, even no luck :(

**Comment by maendamedia** [comment]
Looks like url issue. As I see for exoplayer now:
`06-22 15:45:54.962 24841-24841/com.audioplayer I/ExoPlayerImpl: Init ExoPlayerLib/2.4.3 [zerolte, SM-G925F, samsung, 24]
06-22 15:45:59.706 24841-25256/com.audioplayer E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:722)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:645)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
`

I cannot get it to work with this url:

`[
  {
    "id": "1111",
    "url": "http://link.to.stream/listen.pls?sid=1",
    "title": "Longing",
    "artist": "David Chavez",
    "artwork": "https://picsum.photos/200"
  }
]`

Please help!

**Comment by Guichaguri** [comment]
That's not an audio file, that's a playlist file. You can either use the direct URL to the stream or fetch the playlist file, parse it and add it to the queue.
