### ISSUE TITLE
Got 'React/RCTBridgeModule.h' file not found after ejected from expo

### ISSUE THREAD

**Issue by silkyland** [react-native-kit/react-native-track-player#221]
Got  'React/RCTBridgeModule.h' file not found after ejected from the expo on iOS, and how to solve this issue? Thank you.

**Comment by maendamedia** [comment]
create a dummy.swift file in your XCODE project en link the bridge when asked

**Comment by silkyland** [comment]
Thank you, If I install from react-native init and add dummy.swift I got no problem. But ejected from expo has a problem with error code above.

**Comment by maendamedia** [comment]
I think you need to link it again. Try removing it and re-create

**Comment by silkyland** [comment]
@maendamedia Thanks for your support but still don't solve the problem.

![React/RCTBridgeModule.h](https://i.imgur.com/nq85f6c.png)

**Comment by ManrickCapotolan** [comment]
@silkyland I followed the instructions found [here](https://forums.expo.io/t/how-do-i-manually-add-pods-headers-public-to-the-header-search-paths-configuration/2427/4). see modenero's comment.

the path i entered is `$(SRCROOT)/../../../ios/Pods/Headers/Public/**`

**Comment by Guichaguri** [comment]
Expo is not supported at the moment.
