### ISSUE TITLE
Pause the app on incoming calls

### ISSUE THREAD

**Issue by ovidiu-balau** [react-native-kit/react-native-track-player#223]
Hi,

Is there any way to pause the player whenever a call is incoming? Also, not just that but anything such as Youtube or any other app that would override the sound in order to stop it.

Thank you.

**Comment by Guichaguri** [comment]
Which platform? Android, iOS or UWP?

**Comment by Nitingadhiya** [comment]
We have facing issue in Android 8.0.

**Comment by hsparihar-systango** [comment]
@Guichaguri  I am listening to all events.


At the time of removing earphone jack not events fired while on plugin jack getting pause event fired  in IOS.

**Comment by hsparihar-systango** [comment]
@Guichaguri 
So basically there are 2 major issues with track-player version "0.2.5" which we want urgently either fix or any other way to handle these:
1. In android on receive call player pause but on call disconnect no events to resume audio play. Same thing working fine in IOS.

2. On IOS while eject earphone jack not getting any event to pause audio but OS pause audio but app state shows in play mode. Same thing working fine in Android on eject jack it fires remote-pause' event.
Please help in this

**Comment by Guichaguri** [comment]
This should be fixed in 1.0.1.
