### ISSUE TITLE
Android app crashes

### ISSUE THREAD

**Issue by khaisayhai** [react-native-kit/react-native-track-player#225]
I made this data in a separate javascript file. Then when I run my code, it instantly crash the app. It only works when I remove the part 'songlist' but I want to include it inside.
This is my data
`const TrackMusic = 
[
  { songlist:
    [
    {
      id: '1',
      url: 'http://tegos.kz/new/mp3_full/Luis_Fonsi_feat._Daddy_Yankee_-_Despacito.mp3',
      songtitle: 'Despacito',
      artist: 'Luis Fonsi',
    },
    {
      id: '2',
      url: 'http://tegos.kz/new/mp3_full/5_Seconds_Of_Summer_-_Youngblood.mp3',
      songtitle: 'YoungBlood',
      artist: '5SOS',
    },
   ]
  }
]
 module.exports = { TrackMusic:TrackMusic};`
When I run the play class the app crashes. It will only work if i remove songlist. How can I run this without removing the songlist part?
This is my Play class
`export default class Play extends Component{
    componentDidMount()
{
        TrackPlayer.setupPlayer().then(async () => {  
            await TrackPlayer.add(TrackMusic);
            TrackPlayer.play();  
        });
    }
      onPressPlay = () => { TrackPlayer.play(); };  
    onPressPause = () => { TrackPlayer.pause(); };
    render() {
      return (
        <View style={styles.container}>
            <View style= {{flexDirection :'column'}}>
          <TouchableOpacity style= {styles.play} onPress = {this.onPressPlay}>
              <Text style = {{fontWeight:'bold',textAlign:'center',color:'white'}}>Play</Text>
          </TouchableOpacity>
          <TouchableOpacity style= {styles.pause} onPress = {this.onPressPause}>
              <Text style = {{fontWeight:'bold',textAlign:'center',color:'white'}}>Pause</Text>
          </TouchableOpacity>          
            </View>
        </View>
      ); }  }`

**Comment by Guichaguri** [comment]
`TrackPlayer.add(TrackMusic[0].songlist)` should do the trick.

Please, use StackOverflow instead, it's designed for programming questions. Use this issue tracker only for issues coming directly from the TrackPlayer module.
