### ISSUE TITLE
Android ProgressComponent giving weird values

### ISSUE THREAD

**Issue by KalebPortillo** [react-native-kit/react-native-track-player#228]
Hello there,

While implementing the progress component, I'm extending the ProgressComponent like code below:

```
class ProgressBar extends ProgressComponent {
  render() {
    const position = Math.floor(this.state.position)
    const duration = Math.floor(this.state.duration)
    const progress = this.getProgress() * 100
    const buffered = this.getBufferedProgress() * 100

    console.log("Position:", position, "Duration:", duration, "Progress:", progress, "buffered:", buffered)
    return (
      <View style={styles.progress}>
        <View style={{ flex: this.getProgress(), backgroundColor: 'red' }} />
        <View style={{ flex: 1 - this.getProgress(), backgroundColor: 'grey' }} />
      </View>
    )
  }
}
```

Only in android, the above console log shows these output:

When i just add the track, without playing it:
![screen shot 2018-07-05 at 19 20 44](https://user-images.githubusercontent.com/10066821/42350943-0b552ebe-8089-11e8-89dc-bd0835b3f061.png)

And when I hit play:
![screen shot 2018-07-05 at 19 21 08](https://user-images.githubusercontent.com/10066821/42350960-1807b6ea-8089-11e8-86fe-7a19cc94c062.png)

In iOS is working fine, anyone has a clue of whats going on?
I'm using the latest release: 0.2.4

**Comment by Guichaguri** [comment]
Are you using the default player or ExoPlayer?

**Comment by KalebPortillo** [comment]
ExoPlayer

**Comment by Guichaguri** [comment]
What are you playing? Is it a local file? A remote one? MP3, AAC? Shoutcast stream?

**Comment by KalebPortillo** [comment]
A remote MP3 file
the exact link i'm using when adding the track is as follow:
https://drive.google.com/uc?export=download&id=1AjPwylDJgR8DOnmJWeRgZzjsohi-7ekj

**Comment by KalebPortillo** [comment]
```
await TrackPlayer.add({
        id: '1111',
        url: 'https://drive.google.com/uc?export=download&id=1AjPwylDJgR8DOnmJWeRgZzjsohi-7ekj',
        title: 'Longing',
        artist: 'David Chavez',
        artwork: 'https://picsum.photos/200'
      })
```

**Comment by mahmoudfelfel** [comment]
I have the same exact issue, the duration for remote streaming files e.g. continuous buffering like a radio or so without a full content length comes as `9223372036854776`.

**Comment by jurimato** [comment]
Had the same issue.
Fixed it by enabling ExoPlayer and some other features from https://github.com/react-native-kit/react-native-track-player/wiki/Build-Preferences
I enabled hls and smoothstreaming, and it worked for me.
Play around a little bit to see which option actually helps, or just set hls and smoothstreaming to true to try it out.

**Comment by Guichaguri** [comment]
Is this still happening in 1.0.0?

**Comment by CapitanRedBeard** [comment]
I'm seeing `this.getProgress` and `this.state.position` returning 0 once and not causing rerendering when a track is playing unlike iOS, will try and get clearer beahvior

**Comment by ishigamii** [comment]
@KalebPortillo do you still have the issue with new version ? if not can you close the issue ?

**Comment by jllodra** [comment]
> I'm seeing `this.getProgress` and `this.state.position` returning 0 once and not causing rerendering when a track is playing unlike iOS, will try and get clearer beahvior

This happed to me. Then I saw mp3 files were 22 kHz in samplerate. I just used lame to resample to 44.1 kHz. Then the progress was reported correctly on Android.

**Comment by Guichaguri** [comment]
For issues where you have bad media: unfortunately there's not much I can do to help.
For issues where the duration is being reported zero: you should be feeding the duration into the track object instead.

Please, let me know if there is a third issue that makes it not work.
