### ISSUE TITLE
TrackPlayer.getDuration() always give 0

### ISSUE THREAD

**Issue by imran1992** [react-native-kit/react-native-track-player#229]
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-track-player": "^0.2.4",
"Platform": "Android"
"OS":"7.0"
I think I am doing wrong. I am actually playing online audio by LINK.
In `componentWillMount` First I just add the track detail then set the remote capabilities and then I am trying to get the duration of audio which i just setup

```
componentWillMount() {
    TrackPlayer.setupPlayer().then(
      async () =>
        await TrackPlayer.add({
          id: "123",
          url: this.state.Url,
          title: "Track Title",
          artist: "Track Artist",
          artwork:
            "https://socialecologies.files.wordpress.com/2015/10/a_monk.jpg"
        }).then(() =>{
          TrackPlayer.updateOptions({
            capabilities: [
              TrackPlayer.CAPABILITY_PLAY,
              TrackPlayer.CAPABILITY_PAUSE,
              TrackPlayer.CAPABILITY_STOP
            ],
            compactCapabilities: [
              TrackPlayer.CAPABILITY_PLAY,
              TrackPlayer.CAPABILITY_PAUSE,
              TrackPlayer.CAPABILITY_STOP
            ]
          });
          this._GetTrackDuration()  //<-------Here I Called It
        }
        )
    )
  }
```
And Here is my getting duration of audio function:
```
_GetTrackDuration = async () => {
  let GetDuration = await TrackPlayer.getDuration();
   alert(GetDuration);
   this.setState({
   duration: GetDuration
   });
   };
```
**Update:** When I run it in `Debug Mode` It show the `Trackplayer.getDuration()` exactly what I expected but this time the Audio play 2 times. And without` Debug Mode` Audio play 1 time. My Code for Playing too:
```
componentDidMount() {
    this.play();
  }
```
My Play Function:
```
play = () => {
    this.setState({ playState: "playing" });
    TrackPlayer.play();
  };
```

**Comment by brenwell** [comment]
Duration is 0 until it plays. This maybe related to the issue where on track changed returns null for track on first play.

**Comment by dcvz** [comment]
Is this still an issue in v1.0.0?

**Comment by Guichaguri** [comment]
The duration will only be available after the module loads and analyses the track. It might be available before that if you feed it manually (the track object accepts a `duration` property). You also have to make sure you're only playing after the `setupPlayer`/`add` promises resolves.

**Comment by imran1992** [comment]
OK. Will test it in other future project. For Now I am closing it.
