### ISSUE TITLE
Chromecast on android.

### ISSUE THREAD

**Issue by MobiusHorizons** [react-native-kit/react-native-track-player#230]
First off, thanks for the great library. It is very useful!!
I have been trying to get to get the Chromecast support working, but I haven't been able to get it to do anything at all.

First, I added the `CastButton` to my application as it says in the documentation, but even though I have a chomecast at home, and other apps don't have any trouble finding it, I don't get any cast events, and the button does not show up. I have tried this with both native and expo player. 

I have also tried to directly query the cast state by calling 
```
	TrackPlayer.setupPlayer()
	.then(() => TrackPlayer.getCastState())
	.then(cast => {
		console.log('cast', cast);
	});
```

The console log never gets fired, so I don't know how to debug any further. Seems like I just haven't enabled the support, but I don't see anything in the documentation to point me in the right direction.

**Comment by MobiusHorizons** [comment]
Ok, thanks. It might be good to document that.

**Comment by Pushplaybang** [comment]
This is an awesome library, and Glad to see this will be a separate module.

**Comment by benkaiser** [comment]
@Guichaguri any updates on plans for bringing back cast support?

**Comment by jasongrishkoff** [comment]
Would definitely be cool to see this one flushed out in 2019 @guichaguri!

**Comment by jasongrishkoff** [comment]
@Guichaguri rad! Is it ready for testing?

**Comment by Guichaguri** [comment]
Not yet, but I have a question about its API design: How the transition from a local playback to a remote one should work?

#### Automatic
The transition between the local playback and the remote playback should be completely automatic, the app just receives a `cast-connected` event and can use that for UI updates. The whole queue will be transferred to the cast device.
* Pro: Easiest integration for an existing react-native-track-player app
* Con: No flexibility for customization

#### Manual
When the app receives the `cast-connected` event, you should execute `setupRemotePlayer(options)` and then add the tracks into the newly created player manually, with the option to pass custom options for a custom receiver. You should execute `setupPlayer(options)` again when you receive `cast-disconnected`.
* Pro: The queue, the tracks and the player can be fully customized
* Con: A bit of code needs to be added to integrate with the module

**Comment by MobiusHorizons** [comment]
Personally I think it would be nice to be able to update cast playlist
separately from the local one when the cast-connected event occurs. I think
this could be implemented so that the default state of the cast playlist
after a connection event is a duplicate the local playlist. Similarly, it
should update the local playlist by default on disconnect. That way it
behaves like the automatic solution unless someone needs a different
behavior.

**Comment by jasongrishkoff** [comment]
I'd look to Spotify for guidance here -- their app and Chromecast seem to always be synced, and I think it's expected user behavior that the two behave the same way. I've got a lot of Chromecast devices set up in my house, and use them every day, always controlled from my phone. So, that (to me) implies that "automatic" is the right way to go -- the mobile app should lead the way and control the cast device.

Automatic would also be useful when one considers that many times, I start playing music before I connect to my cast device, and I expect that the device will continue playing from the same spot once connected, rather than having to restart/reload everything.

**Comment by Guichaguri** [comment]
The automatic one could be implemented on top of the manual like this:
```js
CastPlayer.addEventListener('cast-connected', async (data) => {
    const queue = await TrackPlayer.getQueue();
    const currentTrack = await TrackPlayer.getCurrentTrack();
    const state = await TrackPlayer.getState();

    await CastPlayer.setupRemotePlayer(data.deviceId, {...});

    await TrackPlayer.add(queue);
    await TrackPlayer.skip(currentTrack);

    if(state == TrackPlayer.STATE_PLAYING || state == TrackPlayer.STATE_BUFFERING)
        await TrackPlayer.play();
});

CastPlayer.addEventListener('cast-disconnected', async () => {
    const queue = await TrackPlayer.getQueue();
    const currentTrack = await TrackPlayer.getCurrentTrack();

    await TrackPlayer.setupPlayer({...});

    await TrackPlayer.pause(); // Let's not surprise the user
    await TrackPlayer.add(queue);
    await TrackPlayer.skip(currentTrack);
});
```

It's mostly boilerplate code that most of apps wouldn't change. The main reason I'm asking about it is the queue, it's a waste of time sending the whole queue to the cast device to remove tracks from it right after it.

We can also implement both options together with an additional option, and it would look like this:
```js
CastPlayer.addEventListener('cast-connected', async (data) => {
    await CastPlayer.setupRemotePlayer(data.deviceId, {
        sync: true
    });
});

CastPlayer.addEventListener('cast-disconnected', async () => {
    await TrackPlayer.setupPlayer({
        sync: true
    });
});

// Or
TrackPlayer.setOptions({ sync: true });
```

I'd also love to hear @MobiusHorizons use-case.

**Comment by benkaiser** [comment]
I really like the options option:

```
TrackPlayer.setOptions({ sync: true });
```

That way a consumer of the library can get the functionality with very little ease. And then just allow overriding if sync is set to false.

**Comment by jasongrishkoff** [comment]
Hey @Guichaguri, have you had a chance to look at Chromecast recently?

**Comment by inctor** [comment]
Hey @Guichaguri , is there any news on casting? :)
