### ISSUE TITLE
seekTo(not buffered position) causes the player to skip to next track 

### ISSUE THREAD

**Issue by alikazemkhanloo** [react-native-kit/react-native-track-player#237]
Hi,
I created a player with a seek-bar, all tracks are going to be played from network.
When I put the seek bar at some point at the end ( for example 30 sec before end of  the track), the player skips to next track. But if I wait long enough for the track to fully buffer, I can seek to anywhere I want.

Expected behavior is to wait for the track to buffer and then continue playing.
Is this a known issue?

I am using react native's Slider as the seekbar.

EDIT: no problem using Exoplayer

**Comment by Guichaguri** [comment]
Android, iOS or UWP?

**Comment by alikazemkhanloo** [comment]
Android

**Comment by Guichaguri** [comment]
The default Android player has all kinds of weird issues on different devices and versions, because of that, we are going to remove it and keep ExoPlayer only. Please, use ExoPlayer instead.

**Comment by alikazemkhanloo** [comment]
thank you. I'm doin' so.

**Comment by Drazail** [comment]
@salisuabubakar 
https://github.com/react-native-kit/react-native-track-player/blob/e06f449905ae13f82497f99d426c3982cb8eebde/example/react/components/Player.js#L10-L19
