### ISSUE TITLE
Song ended callback - how to know song ended?

### ISSUE THREAD

**Issue by jdrorrer** [react-native-kit/react-native-track-player#239]
Is there a callback once the song ends? I didn't find anything like that currently, so I'm doing something like the following:

```js
const state = await TrackPlayer.getState();

if (state === "playing" || state === 3) {
  const position = await TrackPlayer.getPosition();
  const duration = await TrackPlayer.getDuration();

  if (position >= duration) {
    console.log("song ended!!!");
    // call custom next logic that handles stuff like shuffle, repeat-playlist, repeat-current, caching previous song
    await AudioService.playlistNext();
  }
}
```

I'm just not sure how reliable getPosition/getDuration is for determining that the song ended. My custom next logic works great when a user selects next and I can manually route them there, but a trusted method for determining the song ended on its own would be really nice.

**Comment by Guichaguri** [comment]
Use the `playback-track-changed` event for a transition between tracks and `playback-queue-ended` for the end of the playback.

**Comment by jdrorrer** [comment]
@Guichaguri the problem I'm having with `playback-track-changed` is it fires again when `.skip()` is called and it seems its default behavior is to call `.skipToNext()` -  this is creating an infinite loop for me since I'm using `.skip(someSpecificTrackId)` depending on shuffle/repeat/etc settings. To recreate the infinite loop, try something like the following:
```js
// index.js
TrackPlayer.registerEventHandler(async (data) => {
  if (data.type === "playback-track-changed") {
    if (data.nextTrack) {
      console.log("playback-track-changed");
      AudioService.next()
    }
  }
});

// audio-service.js
next() {
    // ... logic to determine nextSong based on shuffle/repeat/other criteria ...
    TrackPlayer.skip(nextSong.id);

    return { nextSong };
  }
}
```

And while `playback-queue-ended` is useful, it doesn't apply to this situation since I just want to know when a track officially ended.

The most reliable method I've found is checking if the current position >= duration, but that's not totally reliable either since I'm polling every second, in which case position may be less than duration when the song should have technically ended.

**Comment by jdrorrer** [comment]
@Guichaguri this can be closed. I was able to find a workaround doing something like this: https://github.com/react-native-kit/react-native-track-player/issues/122#issuecomment-394018444
