### ISSUE TITLE
Playback Track Changed Returning Null For Track and Next Track

### ISSUE THREAD

**Issue by thecodecafe** [react-native-kit/react-native-track-player#241]
Hi, so on the event listener I'm listening for the `playback-track-changed` event but every time that happens i.e I go next or start playing a track, it returns null for both track and next track.

Here's the payload I receive on the event.
```
{
    type: 'playback-track-changed',
    nextTrack: null,
    position: 0,
    track: null 
}
```

However, when I click on next some seconds into the current sone, I get the following payload.

```
{
    type: 'playback-track-changed',
    nextTrack: null,
    position: 5.3, // This depends on the number of seconds the song has played for.
    track: null 
}
```

Don't really know if I'm missing something here.

Will really appreciate the help, thanks.

**Comment by jdrorrer** [comment]
I've noticed this issue as well. On the first go-around, track and nextTrack are null. If the `playback-track-changed` event is fired again for any reason, then they will be populated. I've found this to be the case on an iOS simulator, but haven't tested it elsewhere yet.

**Comment by CapitanRedBeard** [comment]
I too am seeing this. The data always returns `position: null` unless `TrackPlayer.seetTo(someValue)` is set explicitly. After that it seems to work properly.

**Comment by dcvz** [comment]
is this still an issue in v1.0.0?

**Comment by curiousdustin** [comment]
https://github.com/react-native-kit/react-native-track-player/commit/fff44d90849e9f0bc53317b32b90c21c4d431551 should resolve this, if it is even still an issue.

**Comment by bahtiyarerden** [comment]
I am facing with this issue v1.2.3

``` 
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: playback-track-changed with body: {
nextTrack = "<null>";
position = "251.6255782312925";
track = 1000031847;
}. Bridge is not set. This is probably because you've explicitly synthesized the bridge in RNTrackPlayer, even though it's inherited from RCTEventEmitter.
```


```
Application Specific Backtrace 1:
0 CoreFoundation 0x0000000111174af6 __exceptionPreprocess + 242
1 libobjc.A.dylib 0x0000000110fc9e78 objc_exception_throw + 48
2 CoreFoundation 0x000000011117491f +[NSException raise:format:] + 0
3 Foundation 0x000000010f02d633 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
4 My Application Name 0x000000010bb92877 -[RCTEventEmitter sendEventWithName:body:] + 551
5 My Application Name 0x000000010bfe084e $s25react_native_track_player018RNTrackPlayerAudioF0C29AVWrapperItemDidPlayToEndTimeyyF + 1198
6 My Application Name 0x000000010bf965e1 $s25react_native_track_player11AudioPlayerCAA23AVPlayerWrapperDelegateA2aDP29AVWrapperItemDidPlayToEndTimeyyFTW + 17
7 My Application Name 0x000000010bfaa646 $s25react_native_track_player15AVPlayerWrapperC20itemDidPlayToEndTimeyyF + 150
8 My Application Name 0x000000010bfaa679 $s25react_native_track_player15AVPlayerWrapperCAA0E32ItemNotificationObserverDelegateA2aDP20itemDidPlayToEndTimeyyFTW + 9
9 My Application Name 0x000000010bf9a3f6 $s25react_native_track_player32AVPlayerItemNotificationObserverC20itemDidPlayToEndTime33_1C328B24BA45329C7453A200A972C026LLyyF + 150
10 My Application Name 0x000000010bf9a44a $s25react_native_track_player32AVPlayerItemNotificationObserverC20itemDidPlayToEndTime33_1C328B24BA45329C7453A200A972C026LLyyFTo + 42
11 CoreFoundation 0x00000001110b5f12 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
12 CoreFoundation 0x00000001110b5ee1 ___CFXRegistrationPost_block_invoke + 49
13 CoreFoundation 0x00000001110b55ff _CFXRegistrationPost + 454
14 CoreFoundation 0x00000001110b4f6d _CFXNotificationPost + 796
15 AVFCore 0x00000001262ff5fd __avplayeritem_fpItemNotificationCallback_block_invoke + 5686
16 libdispatch.dylib 0x000000011591132f _dispatch_call_block_and_release + 12
17 libdispatch.dylib 0x0000000115912508 _dispatch_client_callout + 8
18 libdispatch.dylib 0x000000011591eff7 _dispatch_main_queue_callback_4CF + 1045
19 CoreFoundation 0x00000001110e2dbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
20 CoreFoundation 0x00000001110dd63e __CFRunLoopRun + 2685
21 CoreFoundation 0x00000001110dc6d6 CFRunLoopRunSpecific + 567
22 GraphicsServices 0x0000000116f06db3 GSEventRunModal + 139
23 UIKitCore 0x000000011ce1be0b -[UIApplication _run] + 912
24 UIKitCore 0x000000011ce20cbc UIApplicationMain + 101
25 My Application Name 0x000000010b5788c0 main + 112
26 libdyld.dylib 0x000000011599b3e9 start + 1
27 ??? 0x0000000000000001 0x0 + 1
```

**Comment by quangtam** [comment]
> I am facing with this issue v1.2.3
> 
> ```
> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: playback-track-changed with body: {
> nextTrack = "<null>";
> position = "251.6255782312925";
> track = 1000031847;
> }. Bridge is not set. This is probably because you've explicitly synthesized the bridge in RNTrackPlayer, even though it's inherited from RCTEventEmitter.
> ```
> 
> ```
> Application Specific Backtrace 1:
> 0 CoreFoundation 0x0000000111174af6 __exceptionPreprocess + 242
> 1 libobjc.A.dylib 0x0000000110fc9e78 objc_exception_throw + 48
> 2 CoreFoundation 0x000000011117491f +[NSException raise:format:] + 0
> 3 Foundation 0x000000010f02d633 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
> 4 My Application Name 0x000000010bb92877 -[RCTEventEmitter sendEventWithName:body:] + 551
> 5 My Application Name 0x000000010bfe084e $s25react_native_track_player018RNTrackPlayerAudioF0C29AVWrapperItemDidPlayToEndTimeyyF + 1198
> 6 My Application Name 0x000000010bf965e1 $s25react_native_track_player11AudioPlayerCAA23AVPlayerWrapperDelegateA2aDP29AVWrapperItemDidPlayToEndTimeyyFTW + 17
> 7 My Application Name 0x000000010bfaa646 $s25react_native_track_player15AVPlayerWrapperC20itemDidPlayToEndTimeyyF + 150
> 8 My Application Name 0x000000010bfaa679 $s25react_native_track_player15AVPlayerWrapperCAA0E32ItemNotificationObserverDelegateA2aDP20itemDidPlayToEndTimeyyFTW + 9
> 9 My Application Name 0x000000010bf9a3f6 $s25react_native_track_player32AVPlayerItemNotificationObserverC20itemDidPlayToEndTime33_1C328B24BA45329C7453A200A972C026LLyyF + 150
> 10 My Application Name 0x000000010bf9a44a $s25react_native_track_player32AVPlayerItemNotificationObserverC20itemDidPlayToEndTime33_1C328B24BA45329C7453A200A972C026LLyyFTo + 42
> 11 CoreFoundation 0x00000001110b5f12 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
> 12 CoreFoundation 0x00000001110b5ee1 ___CFXRegistrationPost_block_invoke + 49
> 13 CoreFoundation 0x00000001110b55ff _CFXRegistrationPost + 454
> 14 CoreFoundation 0x00000001110b4f6d _CFXNotificationPost + 796
> 15 AVFCore 0x00000001262ff5fd __avplayeritem_fpItemNotificationCallback_block_invoke + 5686
> 16 libdispatch.dylib 0x000000011591132f _dispatch_call_block_and_release + 12
> 17 libdispatch.dylib 0x0000000115912508 _dispatch_client_callout + 8
> 18 libdispatch.dylib 0x000000011591eff7 _dispatch_main_queue_callback_4CF + 1045
> 19 CoreFoundation 0x00000001110e2dbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
> 20 CoreFoundation 0x00000001110dd63e __CFRunLoopRun + 2685
> 21 CoreFoundation 0x00000001110dc6d6 CFRunLoopRunSpecific + 567
> 22 GraphicsServices 0x0000000116f06db3 GSEventRunModal + 139
> 23 UIKitCore 0x000000011ce1be0b -[UIApplication _run] + 912
> 24 UIKitCore 0x000000011ce20cbc UIApplicationMain + 101
> 25 My Application Name 0x000000010b5788c0 main + 112
> 26 libdyld.dylib 0x000000011599b3e9 start + 1
> 27 ??? 0x0000000000000001 0x0 + 1
> ```

I've got the same issue

**Comment by pke** [comment]
Does this seem to be only simulator related? Have not experienced it on a real device so far.
