### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by khaisayhai** [react-native-kit/react-native-track-player#242]
Hi, I was wondering whether you have a sample for the Rating. I'm not sure how to implement the thumbs up and down rating feature

**Comment by ishigamii** [comment]
@khaisayhai did you find the way ?if you did can you post the answer and close the issue ?

**Comment by neoassyrian** [comment]
I don't think this is implemented. I would also like to know how to use this feature.

**Comment by Guichaguri** [comment]
It is implemented, but currently it only shows up in external Android devices (e.g. smartwatches, cars, etc). It doesn't add anything to the notification, but there is already a feature suggestion for that in #67

**Comment by neoassyrian** [comment]
So if you hit the thumbs up in the smart watch, how do you capture the event? Is there an event that fires?

**Comment by Guichaguri** [comment]
Yes.

First of all, you need to set the the `ratingType` option using [`updateOptions`](https://react-native-kit.github.io/react-native-track-player/documentation/#updateoptionsoptions). It must be a [Rating Constant](https://react-native-kit.github.io/react-native-track-player/documentation/#rating). This basically says which type of rating you want to use throughout the app.

The rating value changes depending on the rating type. For instance, a `RATING_THUMBS_UP_DOWN` is a `boolean`, being `true` (thumbs up), `false` (thumbs down) and `null`/`undefined` (unset rating)

You can set the defined rating value for each track through the `rating` property in the [Track Object](https://react-native-kit.github.io/react-native-track-player/documentation/#track-object). If you don't define a value, it will treat as "unset rating".

When the user updates the rating, you'll receive the [`remote-set-rating`](https://react-native-kit.github.io/react-native-track-player/documentation/#remote-set-rating) event with the value (that depends on the rating type).

Heres is a quick example:
```js
// Sets the rating type
TrackPlayer.setOptions({ratingType: TrackPlayer.RATING_5_STARS});

// Adds a track with the rating of 4 stars
TrackPlayer.add({
    // ...
    rating: 4
});

TrackPlayer.addEventListener('remote-set-rating', (data) => {
    console.log(data.rating); // A number from 0 to 5 stars
    // ...
});
```
