### ISSUE TITLE
How to pause and resume audio on incoming call

### ISSUE THREAD

**Issue by ashokkumar88** [react-native-kit/react-native-track-player#248]
Hi,

Is there any way to pause the audio on incoming call and resume after call disconnect?

**Comment by maendamedia** [comment]
If it is correct it will do it by itself. At least it works for me :)

**Comment by dcvz** [comment]
This should already be working to some extent. Have you tried in v1.0.0?

**Comment by hsparihar-systango** [comment]
not working for me with latest version.
With older version 
IOS was working fine but in android after call audios was not resume (play state)

After updating to new version:
Android : on call audios continue with ring tone getting logs  as : onDuck

**Comment by Guichaguri** [comment]
Yes, that's expected. You have to implement the [`remote-duck`](https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#remote-duck) event, which tells you another app or the system is trying to play something and needs your app to lower its volume.

**Comment by SteponasIvasovas** [comment]
Not working on IOS

**Comment by Dajust** [comment]
Was resuming track ever fixed for ios?

**Comment by nl-danish** [comment]
Any fixes for iOS? It does not seem to resume back on iOS Device nor with CarPlay.
