### ISSUE TITLE
Loaded track starts about a minute in

### ISSUE THREAD

**Issue by robbiemilejczak** [react-native-kit/react-native-track-player#256]
On Android, react-native@0.54.4 and react-native-trackplayer@0.24.4

It's not a massive issue but when I add a track, it's initial state isn't playing (which is expected) but as soon as I call the play method, if I call the getDuration method I get a reported time of 60 - 70 seconds. It's easy enough to work around (I just seekTo(0) after I add the track) but I figured I would report anyway.

Here's my event emitter:
```
AppRegistry.registerHeadlessTask('TrackPlayer', () => {
  return async (data) => {
    if (data.type == 'remote-play') {
      TrackPlayer.play()
    } else if (data.type == 'remote-pause') {
      TrackPlayer.pause()
    } else if (data.type == 'remote-seek') {
      TrackPlayer.seekTo(data.position)
    }
  }
})
```

Initializing the player:
```
    TrackPlayer.setupPlayer().then(async () => {
      const track = {
        id: this.props.ep.guid,
        url: this.props.ep.link,
        title: this.props.ep.title,
        artist: this.props.ep.author,
        artwork: this.state.img.source.uri
      }
      await TrackPlayer.add(track)
      TrackPlayer.seekTo(0)
    })
```

And here's where I am getting the time:
```
    this._progressInterval = setInterval( async () => {
      const state = await TrackPlayer.getState()
      const pos = await TrackPlayer.getPosition()
      if (state == TrackPlayer.STATE_PLAYING) {
        this.setState(prevState => {
          let time = Math.floor(Math.max(prevState.currentTime, pos))
          console.log(prevState.currentTime, pos, time)
          return { currentTime: time, seekValue: time }
        });
      }
    }, 100)
```

On an unrelated note, do you have any recommendations on how to best utilize this? I'm specifically wondering if I can store the TrackPlayer in redux somehow? It doesn't seem like initializing the TrackPlayer returns any object but it does seem like the TrackPlayer manages it's own state across my components? Hope that makes sense. Thanks

**Comment by dcvz** [comment]
Is this still happening in v1.0.0?

You can also take a look at the example for inspiration.
