### ISSUE TITLE
playback track just work for one time forward track why?

### ISSUE THREAD

**Issue by awaisAndr** [react-native-kit/react-native-track-player#259]
playback just forward the track one time and after that it is not working ,why?

**Comment by osiloke** [comment]
I've experienced something similar, it only occurs when you switch network

Steps to reproduce
===

- Add a list of tracks to the queue
- Play a track
- Pause a track
- Change network
- Play track
- Wait for track to end
- Track switches to next track item
x but does not play track

**Comment by awaisAndr** [comment]
no , it switch first time correctly as i want but second time it did not
switch

**Comment by dcvz** [comment]
I don't understand the question here. Could you explain what's happening?

**Comment by awaisAndr** [comment]
thanks for your concern i solved it
