### ISSUE TITLE
Why should `skip()` cause the player to `play()`?

### ISSUE THREAD

**Issue by Pczek** [react-native-kit/react-native-track-player#260]
I have a stopped player and want to skip ahead a few tracks. Using the `skip(trackId)` function causes the player to start playing. I suggest this should not be the case. Let me handle if I want to start the playback right away after a skip or not.

https://github.com/react-native-kit/react-native-track-player/blob/dev/ios/RNTrackPlayer/Logic/MediaWrapper.swift#L142

**Comment by dcvz** [comment]
This has been fixed in `v1.0.0` which was just published. You can see the changelog [here](
https://github.com/react-native-kit/react-native-track-player/releases/tag/v1.0.0).
