### ISSUE TITLE
Add a way to remove the event handler - 'removeEventHandler'

### ISSUE THREAD

**Issue by Pczek** [react-native-kit/react-native-track-player#261]
As recommended in the docs the EventHandler should be registered as soon as possible in the app. 
I currently have an issue with that and registering the EventHandler `componentDidMount` in my component which is using the TrackPlayer. However I have no way to remove the handler when the component is not used anymore `componentWillUnmount`, thereby reregistering yet another event handlers to the TrackPlayer when the component remounts.

Doesn't it make sense to have this functionality as well? Registering the handler and removing the handler programmatically whenever I want?

**Comment by Pczek** [comment]
I did a workaround by relaying the `react-native-track-player` events through a nodejs `EventEmitter` which I can add and remove listeners freely.

**Comment by dcvz** [comment]
You can take a look at the example for inspiration. the event handler wasn't meant to be created and destroyed continuously and used in individual components.

an approach more like the one @Pczek mentions is recommended.
