### ISSUE TITLE
Need help with playing music from local files instead of urls

### ISSUE THREAD

**Issue by himankpathak** [react-native-kit/react-native-track-player#264]
I wanted to know where should my file be located so I can play music by using

`url: require('./song2.mp3'),`

music is currently in project root directory but player is unable to play it.

**Comment by maendamedia** [comment]
Can you try: 

`url:  './song2.mp3'`

**Comment by himankpathak** [comment]
thanks for the reply
This actually is working

`url: require('./song2.mp3'),`

I was trying to load network files and local files together via JSON and only network files where being loaded even though local files were located in the directory.
