### ISSUE TITLE
Color & icons being set in updateOptions() not working

### ISSUE THREAD

**Issue by visagegod** [react-native-kit/react-native-track-player#268]
Just implemented react-native-track-player today, and first off let me say how great it is!

Currently have only tested on Android, however the icons that are being set are not being used (see screenshot below).

Also I read the docs on setting the color and how it should be ARGB Hexidecimal, but that means absolutley nothing to me... nor Google..

Could anyone shed some light on where I am going wrong AND/OR how to get a ARGB hexidemal color for '#FA3843'? 

Many thanks in advance!

```
TrackPlayer.setupPlayer().then(() => {
        TrackPlayer.updateOptions({
                maxArtworkSize: 1000,
                capabilities: [
                        TrackPlayer.CAPABILITY_PLAY,
                        TrackPlayer.CAPABILITY_PAUSE,
                        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS
                ],
                playIcon: play,
                pauseIcon: pause,
                previousIcon: previous,
                nextIcon: next,
                icon: require('../../img/48logo.png'),
                color: '#FA3843',
                stopWithApp: true
        });
        TrackPlayer.play();
        this.getTracksFromApi()
});
```

![41033362_1911231849181098_609592563816464384_n](https://user-images.githubusercontent.com/35296827/45127234-44e2ca80-b16f-11e8-8414-806aef2e0e9d.jpg)

**Comment by Nivekiba** [comment]
Hello @visagegod....
I have the same issue, but i read in another issue that you can see the icons of the notification only in the release version of the app... In debug it's not possible to see those icons...


For the color, by saying ARGB hexadecimal value they just mean replace your ```color: "#??????"``` by ```color: 0x??????```

**Comment by visagegod** [comment]
Thanks for the help @Nivekiba 

I've just tried using `color: 0xfa3843` but nothing has changed. To be honest with you I'm not actually sure what I'm expecting to happen, there are no screenshots that I've seen. The notification always takes colors from the media artwork that is provided.

As for the icons only not being available in debug, that's interesting. Do you have a link to the issue where this was raised (I can't find it).

Many thansk

**Comment by Nivekiba** [comment]
https://github.com/react-native-kit/react-native-track-player/issues/68#issuecomment-344236577

And for the color it works for me... After some refresh...

**Comment by dcvz** [comment]
Is this still an issue in v1.0.0?

**Comment by Guichaguri** [comment]
The color only works in older Android versions. In the most recent versions, it automatically picks a color based on the artwork.
