### ISSUE TITLE
Help playing local files that aren't statically included in project

### ISSUE THREAD

**Issue by jlangfor** [react-native-kit/react-native-track-player#271]
My project lets users download mp3 files from the web, I am using "rn-fetch-blob": "^0.10.13" to do this. There are no download issues but when I attempt to require the dynamic files I run into issues because this is a big no-no in JavaScript. So I wanted to see if there were any other ways I can work around this issue by passing in a dynamic path to the local files.

I am porting this app from a native iOS and I was using AVPlayer before and using it was fairly straightforward were I could pass in the dynamic path. But due to the limitations of dynamically sourcing in files this is becoming a major headache. 

Any help would be very much appreciated.

**Comment by iThinker** [comment]
Do you have a fork by any chance? I need to include media as an expansion file. And it looks painful. because on iOS I want to leverage existing setup with `require`, but for Android, I have to do some workarounds.

**Comment by jlangfor** [comment]
I didn't fork I just pulled the source from npm. I can fork and make the changes if you are interested. Or I can provide you the files on iOS and Android that were touched that made it work

**Comment by iThinker** [comment]
Fork would be the best. I would then fork it if any additional modifications are needed for my case. Thank you.

**Comment by alangumer** [comment]
One easy way to do it is just passing the URL in the format 'file://' + localPathToFile

**Comment by iThinker** [comment]
Yes, I figured it out. I have to use expansion file and content provider to access it.
