### ISSUE TITLE
undefined is not an object (evaluating 'TrackPlayer.STATE_NONE')

### ISSUE THREAD

**Issue by mckmarc** [react-native-kit/react-native-track-player#276]
Hello!

I can not make this library work in any way... I have observed this entry #102 and #96 , but I can not get it to work ... I have tried modifying the files ios/RNTrackPlayer/RNTrackPlayer.swift, I have tried installing "npm uninstall --save react-native-kit/react-native-track-player#dev ".

The error appears just by importing the library into any project screen

At the moment I've only tried on ios

![captura de pantalla 2018-09-10 a les 17 07 01](https://user-images.githubusercontent.com/12086564/45306061-fc832e00-b51b-11e8-80be-e5b9e3117175.png)

**react-native-cli:** 2.0.1
**react-native:** 0.56.0

**npm --v**
6.2.0

I'm desperate, thanks

**Comment by rkostrab** [comment]
I am facing the same issue. I downgraded to 0.2.4 to make it work...

**Comment by himankpathak** [comment]
getting the same error on android

react-native: 0.54
react-native-track-player: 0.2.4

**Comment by jitish1** [comment]
@mckmarc @himankpathak  Go to project navigator -> click right button on project name -> click New File -> than select Swift file -> give file name like dummy.swift -> Clean & Run

**Comment by Guichaguri** [comment]
Looks like a linking problem. Try removing the library, adding it again and linking it.
