### ISSUE TITLE
Add feature to change notification's font color

### ISSUE THREAD

**Issue by Pczek** [react-native-kit/react-native-track-player#278]
I just used the feature to change the overall color of a notification. However choosing quite a lite color will make the text unreadable.

![image 5](https://user-images.githubusercontent.com/839848/45438340-2b81d700-b6b7-11e8-9343-64263487b7ec.jpeg)

**Comment by Guichaguri** [comment]
It's the system UI job to choose a text color that works with the background. It should work automatically on the stock UI.

Changing the text color requires us to implement a custom notification view, which should break the "music" compatibility layer with the rest of the system. Sorry.
