### ISSUE TITLE
Android Artwork only works once

### ISSUE THREAD

**Issue by Pczek** [react-native-kit/react-native-track-player#279]
Hi,
I love this package and use it heavily lately. I'm currently building the background experience with the artwork shown in the Notification in Android and on the Lockscreen on iOS. On iOS everything works fine. On Android however, I encounter a problem, where the artwork is shown in the notification on the first track I play. Next time I start a track the Artwork is missing in the notification. Is definitely there and works on iOS.
Not sure if this is important but it's actually the same artwork for both tracks, same file.

**Comment by dcvz** [comment]
This issue is solved in v1.0.0
