### ISSUE TITLE
Document `jumpInterval` option

### ISSUE THREAD

**Issue by Pczek** [react-native-kit/react-native-track-player#284]
The documentation is missing the `jumpInterval` option which is present since v 2.3 .
https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#player-functions

`data.jumpInterval | number | Interval in seconds to skip or rewind` 

How about to implement two options for the interval in order to be able to have two different values? 
`jumpIntervalForward` & `jumpIntervalBackward`.
`skipInterval` & `rewindInterval`?

I've seen some podcasts app setting different intervals for skip and rewind. It can be quite useful.

**Comment by Guichaguri** [comment]
Documentation updated. Please, open another issue for suggesting a new feature.
