### ISSUE TITLE
App crashes on call to TrackPlayer.setupPlayer()

### ISSUE THREAD

**Issue by ajaykumar97** [react-native-kit/react-native-track-player#288]
The app crashes when I call `TrackPlayer.setupPlayer()` on Android. However, on iOS, the player works fine. If I comment the `TrackPlayer.setupPlayer()` statement, the app runs as normal.
I am initializing the player in root component like:
**App.js**

`class App extends Component {`
  `componentDidMount() {`
    `TrackPlayer.setupPlayer()`
    `.then(() => {`
    `console.log('player setup');`
  `})`
`.catch(error => console.log('error occured while setting up player: ', error));`
`}`
`render() {`
`const store = createStore(reducers, {}, applyMiddleware(ReduxThunk));`
		`TrackPlayer.registerEventHandler(createEventHandler(store));`
`return(`
`//other stuff`
`);`
`}}`

Also, I have updated build.gradle file inside the react-native-track-player's android folder like:
`compileSdkVersion 26`    <-- changed from 23 to 26
` buildToolsVersion "27.0.3"`   <--changed from 23.0.3 to 27.0.3
`implementation 'com.android.support:appcompat-v7:27.1.1'`  <--changed from 23.2.0 to 27.1.1
 `implementation "com.android.support:support-media-compat:26.+"`  <--added
  `implementation 'com.android.support:design:27.1.1'`   <--added

**Comment by dcvz** [comment]
React Native is 57 and Android sdk 27 wasn't supported until release `v1.0.0` which was just released. You can find the changelog [here](https://github.com/react-native-kit/react-native-track-player/releases/tag/v1.0.0).
