### ISSUE TITLE
Completley broken since RN 0.57 

### ISSUE THREAD

**Issue by visagegod** [react-native-kit/react-native-track-player#289]
I've spent hours going through issues and have read/tried every resolution for error messages throughout the Googlesphere. Anyone had any success with any hacks to get this project working on RN 0.57? Or how long until an update?

Thanks

**Comment by jasongrishkoff** [comment]
I see you closed this issue -- mind providing some context to how you solved it?  Quite a few other users are having issues getting it up and running.
