### ISSUE TITLE
NotificationService: No Channel found

### ISSUE THREAD

**Issue by jasongrishkoff** [react-native-kit/react-native-track-player#297]
Similar to issue #204, with the android-redesign package I run into this error:

```
NotificationService: No Channel found for pkg=com.xxx.xxx, channelId=trackplayer, id=1, tag=null, opPkg=com.xxx.xxx, callingUid=10089, userId=0, incomingUserId=0, notificationUid=10089, notification=Notification(channel=trackplayer pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 category=transport vis=PUBLIC)
```

![screenshot_1539193437](https://user-images.githubusercontent.com/375379/46755230-d9879d80-ccc4-11e8-92fd-b80f7014aba0.png)

**Comment by hqdai** [comment]
I got the same issue on Android 27, tried to change com.android.support:support-compat: 27.1.1 from root build.gradle but issue still happen.
Just so you know no issue with Android 28 but it seems player is not started.

**Comment by jasongrishkoff** [comment]
Fixed by @dcvz  in the android-redesign section
