### ISSUE TITLE
[Android] Cant register event handlers, expo detached

### ISSUE THREAD

**Issue by ManrickCapotolan** [react-native-kit/react-native-track-player#299]
I detached from expo. 

`TrackPlayer.registerEventHandler` doesnt seem to work. I keep on getting this error:

`Module AppRegistry is not a registered callable module (calling startHeadlessTask)`

I tried doing `AppRegistry.registerComponent('App', () => App)` right before `TrackPlayer.registerEventHandler` but no good. 

Also tried `Expo.registerRootComponent(App);` at the bottom of App.js but still no good. 

has anyone encountered this? and have a solution?

**Comment by Guichaguri** [comment]
Expo is not supported at the moment.
