### ISSUE TITLE
ID's MUST BE A STRING - (SOLVED) (PR NEEDED)

### ISSUE THREAD

**Issue by visagegod** [react-native-kit/react-native-track-player#303]
When adding a track make sure you make the id into a string, otherwise none of the event handlers will recognize anything in the track player queue (lost a good couple hours over this).

BAD
```
TrackPlayer.add([{
      id: track.id,
      url: track.url,
      artist: track.title,
      title: 'LoveLstn',
      artwork: track.image,
    }]);
```

GOOD
```
TrackPlayer.add([{
      id: track.id.toString(),
      url: track.url,
      artist: track.title,
      title: 'LoveLstn',
      artwork: track.image,
    }]);
```

**Comment by visagegod** [comment]
It currently just fails silently

**Comment by dcvz** [comment]
This is already part of the documentation and if you use the Typescript bindings you'll get this safety. However, I've still added another additional check in https://github.com/react-native-kit/react-native-track-player/commit/fe89ec5a784a9830974f68e000a4a1a1302a299d.

So it'll be resolved in the next version.
