### ISSUE TITLE
send headers for audio

### ISSUE THREAD

**Issue by hoseineghbal** [react-native-kit/react-native-track-player#304]
i wanna send header for Authorization of file is possible ??
like this ::

`await TrackPlayer.add({
        id: 'trackId',
        url:
                {
                    uri:'https://abc.com/download/67',
                    method: 'Get',
                    headers: {
                        'Authorization': 'Bearer ' + this.props.user.access_token,
                        'Content-Type': 'application/json',
                    }
                },
        title: 'Track Title',
        artist: 'Track Artist',
        artwork: require('track.png')
    });`

**Comment by Guichaguri** [comment]
@dcvz what do you think? I guess it would be useful not only for authorization, but also for analytics.

**Comment by Guichaguri** [comment]
As the player updates n

**Comment by Guichaguri** [comment]
Unless it's too complicated for the current implementation, I don't think we should support it for the whole player. Let's say your app plays shoutcast radios, one of them requires a Authorization header (it's a private/premium radio) but another of them doesn't, it's a big security flaw to share the same headers for everything.

**Comment by bodrug98** [comment]
Hello @Guichaguri, @dcvz , how long will this option be implemented?

**Comment by jasongrishkoff** [comment]
@bodrug98 this is an open source library that they work on in their free time, so no deadlines are imposed or committed to. You're welcome to submit a pull request though!

**Comment by bodrug98** [comment]
**jasongrishkoff** , I know and respect that, I just wanted to know if they have plans to make this option

**Comment by hoseineghbal** [comment]
@Guichaguri @dcvz @jasongrishkoff 
is there any resource to learn how change java file and objective-c file and then send change to github ?? i can implement this feature but how can i change java ???

**Comment by Guichaguri** [comment]
@hoseineghbal there are a [few](https://br.atlassian.com/git) [resources](https://try.github.io/) [to](http://gitready.com/) [learn](https://medium.com/quick-code/top-tutorials-to-learn-git-for-beginners-622289ffdfe5) [git](https://git-scm.com/book/en/v2/Getting-Started-Git-Basics) around the internet
