### ISSUE TITLE
iOS: Lock screen pause / play buttons flicker when toggling playback.

### ISSUE THREAD

**Issue by curiousdustin** [react-native-kit/react-native-track-player#309]
Is there a way to stop the flicker that happens on the iOS lock screen pause / play buttons when toggling playback?

I see this behavior both in my own app and in the example.

For instance, when a track is playing, go to the iOS lock screen and tap the pause button. Immediately after, I see the button flicker between the states a couple times rapidly: pause, play, pause, play, pause.

A similar thing happens when going from paused to playing.

I suspect this is related to the buttons sending events instead of affecting playback directly? ( #94 )

**Comment by curiousdustin** [comment]
To clarify, I am still seeing this after testing on v1.0.0.

**Comment by curiousdustin** [comment]
We are getting close to releasing our app, is there anything I can do about this?

**Comment by dcvz** [comment]
Is this still an issue @curiousdustin ?

**Comment by curiousdustin** [comment]
Which version would you like me to test?

**Comment by dcvz** [comment]
1.1.2 on npm @curiousdustin  💃

**Comment by curiousdustin** [comment]
So much better 👍 

Thank you all once again for all your work on this player! 🥇
