### ISSUE TITLE
Getting progress updates on Android

### ISSUE THREAD

**Issue by anderslemke** [react-native-kit/react-native-track-player#31]
It seems that we're not getting events for progress on Android.

Would that be possible?

If someone isn't working on this, I could.

**Comment by Guichaguri** [comment]
That is definitely possible, but not a plausible solution, as it would cause a lot of performance issues.

I've been working on a JS utility class that doesn't use events and provide progress updates to the UI, after it's done, we'll be removing the event from iOS

**Comment by Guichaguri** [comment]
We've implemented a component base that updates itself. See more about it [here](https://github.com/react-native-kit/react-native-track-player/wiki/API#progress).
