### ISSUE TITLE
CIRCULAR REFERENCE error after linking react-native-track-player

### ISSUE THREAD

**Issue by Maximuschka** [react-native-kit/react-native-track-player#311]
Hi,

My dependencies are:
```
"dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3",
    "react-native-track-player": "^1.0.0"
  },
```

I have followed your [installation directions](https://github.com/react-native-kit/react-native-track-player/wiki/Installation) on a fresh RN project (react-native init). After linking react-native-track-player (react-native link) I am building for Android and I am getting following error:

CIRCULAR REFERENCE:com.android.tools.r8.ApiLevelException: Default interface methods are only supported starting with Android N (--min-api 24): void com.google.android.exoplayer2.Player$EventListener.onLoadingChanged(boolean)

The issue is solved by adding the following to build.gradle in app module:

```
android {
...
  compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
...
}
```
I thought I am posting this here, in case somebody is facing the same issue.
Cheers

**Comment by Guichaguri** [comment]
This has been added to the troubleshooting section. Thanks
