### ISSUE TITLE
Android Lock Screen Player Controls

### ISSUE THREAD

**Issue by dileepbolisetti** [react-native-kit/react-native-track-player#319]
How To get Player Controls Like the one in image so that can use controls Directly.

![screenshot_20181028-024450](https://user-images.githubusercontent.com/8918698/47609418-b34f5500-da5b-11e8-980a-202bd4113159.png)

**Comment by Guichaguri** [comment]
Set the `compactCapabilities` in [`updateOptions`](https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#updateoptionsdata) and they'll appear in the compact mode.
