### ISSUE TITLE
Info about previous and current track on `playback-track-changed`

### ISSUE THREAD

**Issue by anderslemke** [react-native-kit/react-native-track-player#32]
Would it be possible to get the ids of finished track, and next track when the player changes track?

**Comment by Guichaguri** [comment]
The next track is already sent to the event, but the finished track can definitely be added as well.

**Comment by jasongrishkoff** [comment]
@Guichaguri I'm not sure that's the case on iOS. @dcvz said it returns nothing. Haven't tested on Android.

**Comment by dcvz** [comment]
iOS now returns the track id for both track changed and the new `track-ended` event 💃

**Comment by dcvz** [comment]
@Guichaguri what's the status of this on Android?

**Comment by Guichaguri** [comment]
@dcvz It currently sends the new track as the `track` property in the event object. How about `previous-track` and `next-track`?

Also, we should unify the event system in both platforms (#33)

**Comment by Guichaguri** [comment]
This has been added on all platforms. Check the [documentation](https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#playback-track-changed) for more information
