### ISSUE TITLE
IOS : Lock Screen Backward Forward Button not working

### ISSUE THREAD

**Issue by jitish1** [react-native-kit/react-native-track-player#322]
Right now my lock screen backwards/forward buttons are disabled.
How to enable them ??
Can anyone help me out?
Thanks. :)

**Comment by jitish1** [comment]
Hi, @ishigamii I have added already.

My code looks like this

  await TrackPlayer.setupPlayer({});
        TrackPlayer.updateOptions({
            //stopWithApp: true,
            capabilities: [
                TrackPlayer.CAPABILITY_PLAY,
                TrackPlayer.CAPABILITY_PAUSE,
                TrackPlayer.CAPABILITY_SEEK_TO,
                TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
                
            ],
            	
        });


On Android its working fine but not on IOS.

**Comment by ishigamii** [comment]
Not sure about this but I removed the seek_to on iso cause it seems to me that it is making it bug 
Try to remove : `TrackPlayer.CAPABILITY_SEEK_TO`
like in this example : https://github.com/react-native-kit/react-native-track-player/blob/dev/example/react/screens/PlaylistScreen.js

**Comment by jitish1** [comment]
Hi, @ishigamii  Thanks for responding to my query.
It was my mistake, I was using old version package. Issue is fixed after upgrading. :)

**Comment by ishigamii** [comment]
@jitish1 Perfect glad to hear that 👍 
Don't forget to close the issue ;)
