### ISSUE TITLE
Missing Typescript Definitions

### ISSUE THREAD

**Issue by rtmalone** [react-native-kit/react-native-track-player#325]
I added this package to a brand new project set up with Typescript today. We found that the Constants weren't in the declared `RNTrackPlayer` namespace. In addition, we discovered the Handler type needed to be exported

`export type Handler = (data: EventData) => void`

as well as the typed structure for EventData

```
 export type EventData = {
    type: EventType
    state: String
    error?: String
  }
```

Without the fixes tslinting was trying to find definitions for these items. We solved it by overriding the modules `index.d.ts` file with our own and pointing to it through our projects `tsconfig.json`. I'll can create a PR with these changes so you can review them.

**Comment by sirajulm** [comment]
Type definitions are missing for `registerPlaybackService` and `addEventListener`

**Comment by Guichaguri** [comment]
@sirajulm can you try 94d64db7904b1aae328351f9cab2e59067099599?

**Comment by sirajulm** [comment]
@Guichaguri Cool. That helps, thanks. 
And good work team behind track-player  👍

**Comment by dcvz** [comment]
Looks like this is resolved. I'll go ahead and close this now 😃

**Comment by dcvz** [comment]
The new definitions are out with v1.1.1 on npm 💃
