### ISSUE TITLE
Play again same track

### ISSUE THREAD

**Issue by oleksii-sauliak** [react-native-kit/react-native-track-player#326]
For some reason I can't play same track one more time.
I added track `TrackPlayer.add({id: trackId, url: audioFile, title, }).then(() => {});`.
Then started my track `TrackPlayer.play();`.
At the end I got event ` {position: 99.999, track: "some-track-id", type: "playback-queue-ended"} `.
And now I want play same track again with `TrackPlayer.play();` but nothing happens.

Can you please help me with this issue? How can I play same track one more time?

**Comment by dcvz** [comment]
When the player plays it doesn't reset to the beginning of the queue. Could you try using `skip('some-track-id')` and then using `play()` again?

**Comment by oleksii-sauliak** [comment]
@dcvz Thanks a lot!
