### ISSUE TITLE
When the app comes from the background  I can not play the music, the player does not work

### ISSUE THREAD

**Issue by bodrug98** [react-native-kit/react-native-track-player#328]
Hi
I have such a problem: I installed the player and everything is fine and the music is played, then I pause and send the application in the background
When the app comes from the background  I can not play the music, the player does not work
Does anyone know the cause and there is a way to solve it?

**Comment by Drazail** [comment]
Can you share the logs?

**Comment by jasongrishkoff** [comment]
In #307 @Guichaguri mentioned we might want to explore caching the last state of the player so that we can easily pick up where we left off.

**Comment by jasongrishkoff** [comment]
@Guichaguri any thoughts on this? Would be great if the module could resume its last state easily.

**Comment by Guichaguri** [comment]
We'll be keeping track of this issue in #307.
