### ISSUE TITLE
Clarification on Track Object Data

### ISSUE THREAD

**Issue by rtmalone** [react-native-kit/react-native-track-player#330]
I'm confused about the purpose of all the data on the Track object. How is the data accessible once the Track has been created? I've noted the methods related to retrieving Player information [here](https://github.com/react-native-kit/react-native-track-player/wiki/API#player-information). However, compared to all the data which can be set for a [Track](https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#track-structure), it seems that a lot of those options are encapsulated in a Track but not readable afterwards. In your own example `artist`, `title`, and `artwork` are tracked with Mobx.

I expected `TrackPlayer.getState()` to return the Track info as it was initialized or updated with `updateOptions()`. The fact that one can update options further confuses me, if i can't read that info from TrackPlayer anyway. So how/where is all that data used?

**Comment by rtmalone** [comment]
Should have looked at the docs one more time

https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#gettrackid

**Comment by rtmalone** [comment]
Actually could `getTrack()` be documented in the wiki on this [page](https://github.com/react-native-kit/react-native-track-player/wiki/API)? That may provide greater visibility. I'd provide a PR but I didn't realize project wikis don't work like that.

**Comment by Guichaguri** [comment]
The documentation is pretty outdated, mostly because we keep adding new features. We should update it as we go

**Comment by Guichaguri** [comment]
The documentation has been updated.
