### ISSUE TITLE
1.0.0 Android probably shouldn't be the recommended as the stable version?

### ISSUE THREAD

**Issue by visagegod** [react-native-kit/react-native-track-player#334]
`stopWithApp: true` just gets ignored

theres also issues with the notification not calling the event handler correctly.

im also sometimes getting stuck in 'playback-queue-ended' never ending loops

clicking notification will also open the app and overwrite the existing player

`this.state.position` not working in progress component

playback from remote sources appears buggy

im going to migrate back to 0.2.5 for a bit, appreciate all the work you're doing though guys!

**Comment by imran1992** [comment]
I don't have answer for your question But where should I use `stopWithApp: true`?

**Comment by alangumer** [comment]
Take a look to [#333](https://github.com/react-native-kit/react-native-track-player/issues/333?_pjax=%23js-repo-pjax-container#issuecomment-437928258)

**Comment by visagegod** [comment]
@alangumer event issues are only the beginning. 1.0.0 on android is still totally broken. im still advising to stick to 0.2.5

**Comment by Guichaguri** [comment]
We know 1.0.0 is kinda broken, it has been released earlier than I thought it would, but we are slowly but surely fixing all of those issues in the `dev` branch.

**Comment by visagegod** [comment]
@Guichaguri you're doing a fab job, much respect!
