### ISSUE TITLE
Play after first bit is downloaded- IOS

### ISSUE THREAD

**Issue by ntk860** [react-native-kit/react-native-track-player#341]
Hi All,

I am beta testing my app, and the main problem that I see is the loading time, I am downloading the files every time the listener want to listen to the song. The download is taking at most 3-6 seconds but the player is taking sometimes 10 to 20 seconds to start play the song. I am not using cacheing. what do you think I should do to make the song play after the first bit gets downloaded ?

**Comment by moonstruck** [comment]
@ntk860 Let's keep same issue in a single thread.
You may close any of these issue.
[Related issue.](https://github.com/react-native-kit/react-native-track-player/issues/342)

**Comment by ntk860** [comment]
ok thank you!
