### ISSUE TITLE
Unable To Play Local Files

### ISSUE THREAD

**Issue by dileepbolisetti** [react-native-kit/react-native-track-player#344]
hi I am trying Sample Example  In Android

With this  PlayList.json Its Working Good:

**[
  {
    "id": "4444",
    "url": "https://drive.google.com/uc?export=download&id=1V-c_WmanMA9i5BwfkmTs-605BQDsfyzC",
    "title": "Rhythm City (Demo)",
    "artist": "David Chavez",
    "artwork": "https://picsum.photos/200"
  }
]**

When I try To Add Some Local File Path in the json And try To play Its Not Working...

**[
  {
    "id": "2222",
    "url": "file:///storage/emulated/0/Download/Selena_Gomez_-_Naturally.mp3",
    "title": "Soul Searching (Demo)",
    "artist": "David Chavez",
    "artwork": "https://picsum.photos/200"
  },
  {
    "id": "4444",
    "url": "https://drive.google.com/uc?export=download&id=1V-c_WmanMA9i5BwfkmTs-605BQDsfyzC",
    "title": "Rhythm City (Demo)",
    "artist": "David Chavez",
    "artwork": "https://picsum.photos/200"
  }
]**

I Enabled  Permissions.

Thanks In Advance...

**Comment by Guichaguri** [comment]
Please, try the latest `dev` branch.

**Comment by dileepbolisetti** [comment]
**"react-native-track-player": "git+https://github.com/react-native-kit/react-native-track-player.git#dev"**
    
Tried With this one no luck.... @Guichaguri

**Comment by dileepbolisetti** [comment]
"react-native-track-player": "git://github.com/react-native-kit/react-native-track-player.git#dev"

**Comment by imran1992** [comment]
And want from app's files folder.
file:///storage/emulated/0/Android/data/com.myproject/files/audios/myaudio.mp3
How??
I am doing by
url:"file:///storage/emulated/0/Android/data/com.myproject/files/audios/myaudio.mp3".

**Comment by dileepbolisetti** [comment]
@imran1992  dev branch is  working try remove, node modules and android build folders from project and do npm i and build

and i guess  RNFB.fs.dirs.DocumentDir Will have '/' in its path give it a shot with 

url:"file://" + RNFB.fs.dirs.DocumentDir + "/myaudio.mp3"

**Comment by cinder92** [comment]
for me is not working, im using dev branch, and put `file://` before my song name

results into this. `file:///storage/emulated/0/DCIM/mysong.mp3`

in Android Studio results on this

```
11-22 19:13:15.234 30016-30150/com.fancyplayer E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:249)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```

it says that my file doesn't exist, but that URL its comming from a native module

**Comment by Daavidaviid** [comment]
Damn, I couldn't get it to work on the iPhone simulator today. I added the `file://` prefix. But nothing to do. I downloaded the file with `react-native-fs`, don't know if it's related.

The file is downloaded, so it's not coming from the fs library...

If any one has an idea, do not hesitate.
Thanks

**Comment by Guichaguri** [comment]
There was a really old issue about local files that the fix was to change from `file://` to `file:///` (three slashes instead of two), I don't know if that would work, but you should try that.

**Comment by Daavidaviid** [comment]
Hey ! Thanks for answering. I found out where it came from, what I did was
launch the app from xcode with the simulator so I could track the issue.
And I found it came from the MediaURL in Swift.

Basically what I had to do was use encodeURI on my localUrl. I had already
done that for the distantUrl before.

Didn't think about it...

But now it's working.

Le lun. 26 nov. 2018 01:37, Guilherme Chaguri <notifications@github.com> a
écrit :

**Comment by vicheanak** [comment]
I also tried on Emulator but it doesn't work, it seems to work on a real device only

**Comment by akashi7** [comment]
where to find the dev repo and how to put it in my project
thanks

**Comment by fivecar** [comment]
FWIW, I spent a long time debugging the same issue, and for me, it came down to the player **requiring a file extension**. If your local file doesn't have a file extension, the player won't play the audio (and will silently fail without `Event.PlaybackError`).
