### ISSUE TITLE
Custom Notification onClick event

### ISSUE THREAD

**Issue by pramishp** [react-native-kit/react-native-track-player#346]
We want to navigate to player screen on notification click. Is there any solution?

**Comment by imran1992** [comment]
solution should contain a Notification onPress event Callback.
In which this package sendback All CurrentLoaded Data in TrackPlayer as argument of function. And in this function whatever We Write To perform ...

**Comment by Guichaguri** [comment]
Can you specify an use-case for this feature? Thanks

**Comment by Guichaguri** [comment]
I've added the URI `trackplayer://notification.click`, it will be triggered when the notification is clicked. Read about how to handle it in [linking](https://facebook.github.io/react-native/docs/linking).

**Comment by Guichaguri** [comment]
There are two conditions you should know:
- The app is already open and the notification is clicked
```js
// This event will be fired
Linking.addEventListener('url', (data) => console.log(data.url));
```
- The app is closed (stopWithApp is set to false) and the notification is clicked
```js
// You have to retrieve the URL manually
Linking.getInitialURL().then(url => console.log(url));
```

---

Here's an example that handles both conditions:
```js
class App extends Component {
    componentDidMount() {
        Linking.getInitialURL().then(this.handleUrl);
        Linking.addEventListener('url', this.handleUrl);
    }

    componentWillUnmount() {
        Linking.removeEventListener('url', this.handleUrl);
    }

    handleUrl = (url) => {
        if (url === 'trackplayer://notification.click') {
            // Do something
        }
    };
}
```

**Comment by HessiPard** [comment]
Is it just for android? It doesn't work in IOS ..

**Comment by ovy9086** [comment]
yeah, looking at the sources it seems this is only implemented for Android.

**Comment by abhishek-capsitech** [comment]
It's not actually working.., i'm not getting any url when I tap on notification it only opens the app

**Comment by patlux** [comment]
Anyone an idea how to catch this with `expo-router` without getting `Unmatched route`?

**Comment by erimfranci** [comment]
@patlux I figured that you can handle the notification by adding the intent on app.json and create a `notification.click.tsx` file in your root. When the notification is tapped Expo will route you to that component. However in my case, I'd like Expo to do nothing. If I don't have this component, it'll take the user to 404, if I have the file it'll take the user to this component. There is no way of "ignoring" this route and resume the app at its previous state. Is this what you are trying to achieve as well?

**Comment by patlux** [comment]
@erimfranci Yes, exactly. I wanted to open a Modal when the user clicked on the notification. I solved it by patch-package the package in `node_modules` to change `notification.click` to something custom. In my case to `scheme://home?action=show-modal`. 

```diff
diff --git a/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt b/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt
index 9d6d869efcece065618d4f2cefdc8c54831af9ed..8c4dc20ec739312643cf7bf1df7646262e978042 100644
--- a/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt
+++ b/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt
@@ -226,7 +226,7 @@ class MusicService : HeadlessJsTaskService() {
         val openAppIntent = packageManager.getLaunchIntentForPackage(packageName)?.apply {
             flags = Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP
             // Add the Uri data so apps can identify that it was a notification click
-            data = Uri.parse("trackplayer://notification.click")
+            data = Uri.parse("scheme:///home?action=show-player")
             action = Intent.ACTION_VIEW
         }
 
```
