### ISSUE TITLE
Android seekTo restarts playback and lock screen controls don't work

### ISSUE THREAD

**Issue by marioot** [react-native-kit/react-native-track-player#348]
Hi, I started working with this library today, latest version 1.0.0

Running on react-native 0.57.5, Android 8.0

Play/Pause work without a problem.
SeekTo restarts the playback.

The lock screen controls don't appear to do anything.

This is the handler setup:
I was trying to get any reaction in the playback, thats why there is the pause invocation.

index:
`AppRegistry.registerHeadlessTask('TrackPlayer', () => require('./media-player-handler.js'));`
```
import TrackPlayer from 'react-native-track-player';

module.exports = async (data) => {
  console.log(data);
  if (data.type === 'playback-track-changed') {
  } else if (data.type === 'playback-state') {
    // Update the UI with the new state
    TrackPlayer.pause();
  } else if (data.type === 'remote-play') {
    // The play button was pressed, we can forward this command to the player using
    TrackPlayer.play();
  } else if (data.type === 'remote-stop') {
    // The stop button was pressed, we can stop the player
    TrackPlayer.stop();
  } else if (data.type === 'remote-pause') {
    // The play button was pressed, we can forward this command to the player using
    TrackPlayer.pause();
  } else if (data.type === 'remote-seek') {
    // The play button was pressed, we can forward this command to the player using
    TrackPlayer.seekTo(data.position);
  } else if (data.type === 'remote-jump-forward') {
    // The play button was pressed, we can forward this command to the player using
    TrackPlayer.seekTo(data.interval);
  } else if (data.type === 'remote-jump-backward') {
    // The play button was pressed, we can forward this command to the player using
    TrackPlayer.seekTo(data.interval);
  }
};
```

In the player componentWillMount:
```
const capabilities = [
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE,
      TrackPlayer.CAPABILITY_SEEK_TO,
      TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
      TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
      TrackPlayer.CAPABILITY_JUMP_FORWARD,
      TrackPlayer.CAPABILITY_JUMP_BACKWARD
    ];
    await TrackPlayer.setupPlayer({
      stopWithApp: true,
      jumpInterval: 15,
      capabilities,
      compactCapabilities: capabilities
    });

    await TrackPlayer.add(this.state.playlistData);
    await TrackPlayer.play();
```

**Comment by Guichaguri** [comment]
Please, don't use `AppRegistry.registerHeadlessTask` anymore. It will not receive the events properly. Instead, use `TrackPlayer.registerEventHandler(require('./media-player-handler.js'))` in your index.js file.

Alternatively, we are trying a new form of event listening as discussed in #332

**Comment by shiroze** [comment]
> Please, don't use `AppRegistry.registerHeadlessTask` anymore. It will not receive the events properly. Instead, use `TrackPlayer.registerEventHandler(require('./media-player-handler.js'))` in your index.js file.
> 
> Alternatively, we are trying a new form of event listening as discussed in #332

Where is this `media-player-handler.js` can found ? we create it ?

**Comment by mbhuiayan** [comment]
@Guichaguri - Is there any option on Android to add close button on lock screen that will make the app close? Thank you!

**Comment by Guichaguri** [comment]
You change the stop button icon, add the stop capability, add it to the compactCapabilities and listen to the `remote-stop` event, destroying the player.

Please, don't comment on old closed issues, open new ones for that. Mainly if the question you're asking is not related to the original issue.
