### ISSUE TITLE
[IOS] remote-duck

### ISSUE THREAD

**Issue by GH974** [react-native-kit/react-native-track-player#352]
hi, I found a bug in my app.

'remote-duck is not a supported event type for RNTrackPlayer? Supported events are: ....

**Comment by Guichaguri** [comment]
Fixed in 08e9b784759085553e63c7c608453b8b63b16ef8

**Comment by GH974** [comment]
Oh, thanks you.

**Comment by hoang-rio** [comment]
IOS does not support `remote-duck` so how to detect headset unplug? It pause media player but no event fire.

**Comment by maartenvandillen** [comment]
@Guichaguri looks like it's back again? yesterday everything was working fine on v 1.1.4, today I get "remote-duck is not a supported event type for RNTrackPlayer". Still on v 1.1.4.

**Comment by Guichaguri** [comment]
`remote-duck` has been added to iOS on 1.1.5, you can keep the subscription on both platforms now.

**Comment by maartenvandillen** [comment]
Thanks, it's working now. Not sure why it stopped working before though.
