### ISSUE TITLE
Is M3U file supported? Alternative?

### ISSUE THREAD

**Issue by newfylox** [react-native-kit/react-native-track-player#353]
I was wondering if `react-native-track-player` can play **M3U** files and if not, is there a way to do it? Do I need to import a M3U parser and do it by myself?

Thanks!

**Comment by Guichaguri** [comment]
No, you have to parse it yourself. Luckily for you, M3U files are pretty simple to parse, [here is one parser](https://github.com/nickdesaulniers/javascript-playlist-parser) that should work on react-native.

**Comment by newfylox** [comment]
Thank you!
