### ISSUE TITLE
Screenshots of an example

### ISSUE THREAD

**Issue by SamaneYaghoobi** [react-native-kit/react-native-track-player#354]
Can anybody upload screenshots of an app that using react-native-track-player?
I think it's necessary for any package to have demo screenshots. 
I like this package in theory but I can't decide to use it or not.

**Comment by SamaneYaghoobi** [comment]
Oh sorry, I didn't see the demo repository.
please close the issue and place the link of demo repo, in README file of the package.

Thanks in advance

**Comment by Guichaguri** [comment]
You're right, we need a few screenshots from [the new example app](https://github.com/react-native-kit/react-native-track-player/tree/dev/example), both for iOS and Android, with a few screenshots showing its native media buttons

**Comment by dcvz** [comment]
I've added the link to our README 👍

**Comment by SamaneYaghoobi** [comment]
@dcvz Thanks a lot,
But still, this issue should be open, because there isn't any screenshot of the example app in README.

**Comment by Guichaguri** [comment]
I've added three Android screenshots in 86672450fa9cd2677487415e8aaf0adb35714778. @dcvz can you add iOS ones?

**Comment by SamaneYaghoobi** [comment]
@Guichaguri That's great! Thank you :)
