### ISSUE TITLE
getState returns different results between platforms

### ISSUE THREAD

**Issue by brenwell** [react-native-kit/react-native-track-player#355]
Hey thanks for the lib!

It appears that with 1.0.0 on android getState returns an enum 0,1,2,3,etc representing STATE_PLAYING, etc but on ios it returns strings 'playing', 'paused'

Is that intentional? 

Forgive me if this is my mistake or I am simply being stupid

```
const state = await TrackPlayer.getState()
```

**Comment by brenwell** [comment]
Sorry been a long day. I see now on iOS you map strings to state and on Android its integers, but that actually represent the same things

**Comment by Guichaguri** [comment]
Duplicate of #250
