### ISSUE TITLE
Looking for the stable version

### ISSUE THREAD

**Issue by ntk860** [react-native-kit/react-native-track-player#356]
Hi guys, right now I am using version 1.0.0 but not from #dev branch. I see @Guichaguri saying in some other issues that v1.0.0 is a little bit broken (but some bugs have been fixed on #dev), which version should I consider stable for both platforms? Should I use #dev as stable version ? 

Features that are not working well on v1.0.0  and bugs that I see.

- playing from local url (IOS and Android)
- delay to start playing after play (IOS) - I want to make the song play as fast as it can after I call play
- Crashing on close (Android)

**Comment by Guichaguri** [comment]
We are working on it. There were big changes in 1.0.0 (both in Android and in iOS) which caused a number of problems, there is still some people using 0.2.5, which is the last version before 1.0.0, it's definitely more stable (although it has a few issues in Android 8+).

Please, keep each problem into its own single issue.
