### ISSUE TITLE
duration is always zero in iOS

### ISSUE THREAD

**Issue by alikazemkhanloo** [react-native-kit/react-native-track-player#359]
I'm streaming audio from direct links. for the progress bar, I use ProgressComponent. In iOS I get duration = 0, while it's working fine in android.
RNTP version 1.0.0
RN version 0.57.4

**Comment by gazedash** [comment]
For me it is reverse: it is 0 on android, but works on iOS.

I have provided the duration for the track, I have awaited for player setup and add, and only then play.

**Comment by dcvz** [comment]
@alikazemkhanloo could you try with this commit? 4c0483332779995e98e5f9164ad3c7d548f46615

**Comment by ishigamii** [comment]
@alikazemkhanloo  can you try using the new version and close this issue if everything is good now ?

**Comment by alikazemkhanloo** [comment]
Ok I will check it out ASAP.  But it may take couple of days.

**Comment by ishigamii** [comment]
No problem ;) should work now take your time and close the issue if done ;)

**Comment by ishigamii** [comment]
@alikazemkhanloo did you have time to check it out ? otherwise can you close it and open a new issue when you get to check it with latest ? 👍

**Comment by alikazemkhanloo** [comment]
OK, I'll close it.
Sorry, I'm too busy to update my old project.
