### ISSUE TITLE
[iOS] playback-error near end of track only after previously seeking

### ISSUE THREAD

**Issue by curiousdustin** [react-native-kit/react-native-track-player#361]
I'm getting a playback-error event 1-2 seconds before the end of a track only after seeking to near the end and then letting it play to the end.

What might cause this?

It doesn't happen every time. 

The file is streaming from a server.

**Comment by ishigamii** [comment]
@curiousdustin do you still have the issue with new version ? if not can you close the issue ?

**Comment by curiousdustin** [comment]
I haven't noticed this in a while, but it was kind of hard to replicate in the first place. 

Closing for now.
