### ISSUE TITLE
playback-error codes are not descriptive

### ISSUE THREAD

**Issue by roman-gula** [react-native-kit/react-native-track-player#362]
Can you pass some descriptive error codes for playback-error instead of "exoplayer"?
https://github.com/react-native-kit/react-native-track-player/blob/54904d21a3461166c7fa8d7974a515b071af5d85/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java#L348

We should be able to differ exсeptions by their codes.

**Comment by Guichaguri** [comment]
Here are the new error codes:
* `playback-source` - Error related to retrieving the media source, the file or stream which you are playing. (e.g. the player can't reach the server)
* `playback-renderer` - Error related to converting and playing the media source (e.g. the format is not supported)
* `playback` - Any other unexpected error related to the playback
