### ISSUE TITLE
Player does not respond after playback error (Android)

### ISSUE THREAD

**Issue by roman-gula** [react-native-kit/react-native-track-player#364]
I am trying to play track from network. If no connection, after error ({type: "playback-error", code: "playback-source"}) player does not respond, even if connection is resumed. Nothing happens when I try to play tracks, there is no events, only can skip to other track.
I expect:

1. if no connection, every time I press play button (or similar action that requests track) it should trigger an error;
2. when connection is resumed the player should be able to play tracks;

I tried `destroy` or / and `setupPlayer` but it did not help.

How should player behave in these situations or what should I do to make it work? Thanks!

**Comment by roman-gula** [comment]
This problem is not only with files from network, but local too. I deleted playing file and scroll progress out of buffer. After error appeared I could not play any other tracks unless restart app.

**Comment by Guichaguri** [comment]
Let me know if 05b8725e7a82ccbfe5d8b92e33db9281d0ff7d73 solves the problem for you.

**Comment by roman-gula** [comment]
Thanks! Currently my laptop in a service center. I will try it as soon as possible.

**Comment by ishigamii** [comment]
@roman-gula do you still have the issue with new version ? if not can you close the issue ?

**Comment by roman-gula** [comment]
No more issues with it. Thanks!
