### ISSUE TITLE
[iOS] No controls on lock screen and sound is stuck after app is in background

### ISSUE THREAD

**Issue by mpaxglobal** [react-native-kit/react-native-track-player#365]
Hey all,

So I updated to latest 1.0.0 version but and it works all perfect on Android while on iOS I'm having some troubles (0.2.5 also had same issues). I tested on multiple simulators: iPhone 6, iPhone 8 and iPhone X but they all have same issue.

First one is that if I pull notification/lock screen I don't see player controls even if it's playing.

Second one is if I press home screen and app goes in background, sound from player is stuck, like last 1 second is in loop. I tried several ways of initialising player but issue persist. 

Here is simplified code from my project:
RootComponent.tsx
```
async initializePlayer() {
    await TrackPlayer.setupPlayer();
        
    TrackPlayer.updateOptions({
        capabilities: [CAPABILITY_PLAY, CAPABILITY_PAUSE, CAPABILITY_STOP],
        compactCapabilities: [CAPABILITY_PLAY, CAPABILITY_PAUSE, CAPABILITY_STOP],
        stopWithApp: true,
    });
}
```

PlayerComponent.tsx
```
TrackPlayer.add({
    id: 'trackId',
    url: config.streamUrl,
    title: config.title,
    artist: config.artist,
    artwork: config.artwork,
});
TrackPlayer.play()
```

React native version: 0.55.4

Thanks.

**Comment by AChevallier** [comment]
We have the same problem ! 😢 
Any solution ?! ❤️

**Comment by deepaksingh16** [comment]
For Controls on iOS, test on real device. I guess it won't show in simulator.

**Comment by mpaxglobal** [comment]
@deepaksingh16 Thanks, will try it out.
@AChevallier I fixed that stuck sound by enabling Background Mode for Audio.

**Comment by mpaxglobal** [comment]
Yep, Simulator doesn't show controls, real device does.

**Comment by wsrast** [comment]
Same issue here. iOS emulator shows no controls on the lock screen, while a real device does.

**Comment by curiousdustin** [comment]
Recent versions of the iOS simulators do not support showing lock screen controls. You must test this on real devices.
