### ISSUE TITLE
Long time buffering local file (android)

### ISSUE THREAD

**Issue by roman-gula** [react-native-kit/react-native-track-player#366]
I am playing local file with url like `/data/user/0/... `, not with require(). File is playing but buffering takes about 13 seconds. It happens also when skip to track.
Such files should play immediately. Thanks!

**Comment by ntk860** [comment]
I think you need to add file:/// at the beginning and its going to look like this file:///data/user/0/.... I do not know how its even playing without file:/// at the beginning of the url. Also you need to install this version github:react-native-kit/react-native-track-player#dev

I am playing songs from local files and its working just fine

**Comment by roman-gula** [comment]
I am using dev version. 
Player works equally with and without `file:///`. That is why I just removed it. Also it does not depend on how much slashes, but shoud be minimum 3. `file:////////////` also works fine for me :).
@ntk860 did you try to remove `file:///`?

**Comment by roman-gula** [comment]
After writing last line in my previous comment, I finaly understand that  the reason was convertion settings of mp3 file. I tried play with mp4 and it works fine. Then I reconverted mp3 and it also works fine!

@ntk860 thanks for help ;)

**Comment by ataravati** [comment]
@roman-gula how did you resolve this issue?
