### ISSUE TITLE
example background mode issue

### ISSUE THREAD

**Issue by pkhodaveissi** [react-native-kit/react-native-track-player#367]
been playing around with example app, 
If the app is in background, it can play the current track to the end, but after that it stops and won't play next one, is this ok if I have the player setup as:
```
TrackPlayer.updateOptions({
      stopWithApp: false,
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
      ]
    });
```
also I have xCode background capabilities for audio and fetch enabled, 
what is it I'm doing wrong?
one other question, does caching work in ios?

**Comment by pkhodaveissi** [comment]
I should say the problem with the next thing was with #dev branch

now the second question matters:
s it possible to cache some bit of next track beforehand?
and please close the issue if you see fit, the main issue is out of picture

**Comment by pkhodaveissi** [comment]
The main issue concerning app stops playing was in #dev branch and I use v1 and it's fine but let me know about controlling the cache?

**Comment by ishigamii** [comment]
@pkhodaveissi do you still have the issue with new version ? if not can you close the issue ?

**Comment by pkhodaveissi** [comment]
Haven’t checked in a while but sure, I’ll close for now

**Comment by ishigamii** [comment]
@pkhodaveissi Thanks ;)
