### ISSUE TITLE
Event Registration [Android]

### ISSUE THREAD

**Issue by ntk860** [react-native-kit/react-native-track-player#370]
Hello, I am using 1.0.0 #dev version and I am getting this error on android 

undefined is not an object (evaluating 'taskProvider()(data).then') 

I think it has to do with event registering because when I do not setup the player the bug goes away. 
Is the new event registering working now ? the one described on #332

**Comment by tuantai0625** [comment]
If you use old method registerEventHandler then open file index.js in lib folder and change line 109 from
`return function() {`
to
`return async function() {`

**Comment by ntk860** [comment]
@tuantai0625 it worked, thank you!

**Comment by jenipharachel** [comment]
@tailt94 @vbspace I'm using the new method according to the example app. Any idea on how to fix this issue?

> TypeError: undefined is not an object (evaluating 'taskProvider()(data).then')
