### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by rgagnon** [react-native-kit/react-native-track-player#372]
Since I upgraded to 1.0.1 I'm getting this issue.  

The stack trace is not very helpful 

Any idea?  

![screenshot_20181227-100522](https://user-images.githubusercontent.com/27264/50484576-22dfb300-09bf-11e9-9986-08b9998dd46c.png)

**Comment by jpolo** [comment]
https://github.com/react-native-kit/react-native-track-player/blob/cb4aa8977b48cd8a898cc2c99838cbcedb6b1b4e/lib/index.js#L109

Shouldn't be an async method ?

**Comment by rgagnon** [comment]
I tried on my side and it worked.  

Thank you

**Comment by jpolo** [comment]
@rgagnon My project is also impacted : the registerEventHandler is broken.
I tried to hotfix it to create an async method and it works. This error could have been caught with unit tests or flow/typescript...

**Comment by rzakirov** [comment]
I confirm works after added `async`

**Comment by Guichaguri** [comment]
I'll release a new version tomorrow with the fix. We should definitely automate tests at some point.

**Comment by Guichaguri** [comment]
Released 1.0.2
