### ISSUE TITLE
[iOS] Support for skipping 15 seconds forward and backwards on lock screen

### ISSUE THREAD

**Issue by anderslemke** [react-native-kit/react-native-track-player#38]
This is possible when using `react-native-music-control`.

Also, from `react-native-music-control` I got the impression that there is a `playPauseToggle` that is invoked when pressing the button on a headset.

**Comment by dcvz** [comment]
in progress here: https://github.com/react-native-kit/react-native-track-player/pull/82

**Comment by Guichaguri** [comment]
It has been merged: b6d1272118712b2d0928055d7a20dccdb20bef23

**Comment by Pczek** [comment]
@Guichaguri is there a way to change the previous and next icons on iOS? I've seen the options in the documentation, however, they don't seem to work on iOS nor Android. I want to be able to change the icon to rewind less seconds than 15 and skip more than 15 like in several podcast apps.

https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#updateoptionsdata

![simulator screen shot - iphone 6 - 2018-09-17 at 09 56 10](https://user-images.githubusercontent.com/839848/45611532-fb905600-ba5f-11e8-9dc8-608df8e42492.png)
