### ISSUE TITLE
Converting project from swift 3 to swift 4 

### ISSUE THREAD

**Issue by ithustle** [react-native-kit/react-native-track-player#383]
I think this is an awesome lib but I'm suffering to put it on working. 
Can you, please, update the code to swift 4 for correctly use... I'm spending more than 4 hours trying to build on xcode to implement on my project.

**Comment by maendamedia** [comment]
Xcode is indeed “complaining” about swift 3

**Comment by dcvz** [comment]
I just published version 1.1.0 which is running on Swift 4, can you try now?

**Comment by ithustle** [comment]
I'll check and comeback if any issue occurs

**Comment by gazedash** [comment]
Doesn't work with Swift 4.1

**Comment by dcvz** [comment]
The project has been updated to Swift 4.2. Please set your Xcode project to use that ☀️
