### ISSUE TITLE
1.0.2 - Android Notification & Rating Bugs

### ISSUE THREAD

**Issue by visagegod** [react-native-kit/react-native-track-player#386]
*claps* @Guichaguri, can I just say you are doing a FANTASTIC job maintaining this module! *claps*

Notification buttons events only fire the first time I open the app from a 'Settings -> App List -> App -> FORCE STOP'. If the app is normally closed and reopened the new notification is totally unresponsive and does not even bring the app to the foreground when clicked. (and sometimes displays the wrong track)

The `TrackPlayer.CAPABILITY_SET_RATING` with `ratingType: 'RATING_HEART'` just doesn't appear to work, nor could I see any assets that would prove it ever did work?

Other mention - I think the java socket timeout is too short (new issue here #389).

**Comment by Guichaguri** [comment]
At the moment the rating is only visible through external devices, such as a smartwatch. There is already a suggestion for that in #67. I never gave it attention due to it being a really old issue and people not having interest on it.

I'll look into the notification problem tomorrow.

**Comment by Guichaguri** [comment]
Tell me a bit more about the notification problem: What options are you using? Do you have debug logs at the time the issue happens?

**Comment by visagegod** [comment]
I believe this is only happening when I totally lag out my application, will do some more experimenting and get back to you! Any news on #389 this is becoming the most frustrating but to deal with right now?

**Comment by visagegod** [comment]
Ok so I've been experiencing more of this today, and I think I've figured it out. The problem is that `stopWithApp: true` is not actually correctly destroying the service (or at-least as I would expect it to). The fix: 

1. Remove all notification button event listeners in unmount (duhh why was I not doing this before *facepalm*)

2. You MUST call `TrackPlayer.destroy()` in `componentWillUnmount()` (This may only be required for me as I am using `android:launchMode="singleTop"` but maybe should be put in the docs nevertheless)

Can close this issue :+1:

**Comment by Guichaguri** [comment]
I get it now, you're handling the music control events inside a React component, which makes them stop working after the activity is closed. The proper way (if anybody reads this in the future) is to put all logic-handling events inside the **playback service** and only use events inside React components that are used purely to update the UI state.

I don't think `singleTop` is the culprit here, I'll have to investigate it further.

**Comment by skizzo** [comment]
@visagegod how exactly do you "remove all notification button event listeners"? I wouldn't know how to do that with v1.2.0.. Thanks for any hints
