### ISSUE TITLE
TrackPlayer.reset() doesn't set the track to null

### ISSUE THREAD

**Issue by AChevallier** [react-native-kit/react-native-track-player#390]
Hello 

I have a small bug which it not blocking but it looks like a bug.

When I call TrackPlayer.reset(), it should stop and remove the track.
When I call TrackPlayer.stop(), it should stop the track.

But actually reset() doesn't remove the track, so i have to set the track to null by myself.

Is it a bug ?

**Comment by Guichaguri** [comment]
Which platform? iOS, Android or Windows?

**Comment by AChevallier** [comment]
I can reproduce this on Android. iOS is fine. I didn't try on Windows.

**Comment by Guichaguri** [comment]
What do you mean by "set the track to null"?

Is it `getCurrentTrack()` that doesn't return null?
Is it the `playback-track-changed` that doesn't get fired?

**Comment by AChevallier** [comment]
- What do you mean by "set the track to null"?
Sorry I got lost in my redux abrastraction :)

- Is it getCurrentTrack() that doesn't return null?
This function return null actually

- Is it the `playback-track-changed` that doesn't get fired?
 Indeed this event is not fired. And it's where I change my track in my redux.

So `reset()` set the track at null but doesn't fired `playback-track-changed`

**Comment by jpolo** [comment]
As the `reset()` method actually set the track to null. It should trigger the playback-track-changed event to be consistent.

**Comment by Guichaguri** [comment]
Let me know if 333ce49 fixes it for you.

**Comment by AChevallier** [comment]
@Guichaguri 

It works!  Good job  ! 
Thank you
