### ISSUE TITLE
Playing SpotifyURI

### ISSUE THREAD

**Issue by JakeMotta** [react-native-kit/react-native-track-player#396]
Hello All, 

Does anyone know of any way to play a SpotifyURI using 'react-native-track-player'? I was able to get everything setup and working properly while using the Spotify Preview URL, but I'm not sure how to get the full track to play for an authenticated Spotify Premium user.

Side Note: I am able to play the full track using 'rn-spotify-sdk' library, but then I run into the issue of being unable to play music in the background (when app is minimized or in lock-screen). 

Any advice is appreciated!

**Comment by vjhameed** [comment]
Would you please let us know how can we use just the notification from your player  ? so that we can use spotify sdk to play tracks and notification from your player to display controls

**Comment by kuabhish** [comment]
Hey @JakeMotta 
Were you successful? If yes. Can you please tell me how?

**Comment by rein96** [comment]
Hi @JakeMotta 

How's the progress? I also want to play the preview_url from Spotify data

From what I see, it's not possible with this library (please CMIIW)

I also will try the `react-native-spotify-remote` library
