### ISSUE TITLE
TrackPlayer is stuck loading on iOS (works on android)

### ISSUE THREAD

**Issue by jonaird** [react-native-kit/react-native-track-player#399]
I have a very simple demo app. It works in android but the TrackPlayer state is stuck on 'loading' forever on iOS (emulator).

`TrackPlayer.setupPlayer().then(async () => {
  
      // Adds a track to the queue
      await TrackPlayer.add({
          id: 'trackId',
          url: require('./sample.mp3'),
          title: 'Track Title',
          artist: 'Track Artist',
         artwork: require('./picture.png')
      });
      TrackPlayer.updateOptions({
        jumpInterval: 60,
        capabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_SEEK_TO,
          TrackPlayer.CAPABILITY_JUMP_FORWARD,
          TrackPlayer.CAPABILITY_JUMP_BACKWARD,
        ],
      });
      // Starts playing it
      TrackPlayer.play();`

**Comment by dcvz** [comment]
Thank you for reporting this @jonaird. I've fixed this now in a9768b38f5a5189d79b967f88823813f1eea1df6 and will deploy v1.1.1 shortly 💃

**Comment by rephidimC** [comment]
@dcvz I am experiencing the same issue ATM

**Comment by dcvz** [comment]
@rephidimC does this happen with the example app?
