### ISSUE TITLE
iOS Notification doesn't show the current title

### ISSUE THREAD

**Issue by dnish** [react-native-kit/react-native-track-player#401]
Hey,
just created a new empty RN project with the lastest version of react-native-track-player. If I start playing a song, the control notification stays empty. It doesn't show any information about the current track. Also I'm not able to control any buttons there. Did I forget something within the configurations?

Device: iPhone 6s - iOS 12 (real device)

**Comment by minhtc** [comment]
this commit will fix your issue: https://github.com/HomieTech/react-native-track-player/commit/2c1b3d679e438b7a45a28e4687ce90b03e84980e

**Comment by dcvz** [comment]
This has been fixed in v1.1.2

**Comment by dnish** [comment]
@dcvz Yes, it works on 1.1.2. But if I use the latest version on GitHub (due to issue #422) it stops working, still an empty notification widget.
