### ISSUE TITLE
Version 1.1.0 Not Showing player on locked screen

### ISSUE THREAD

**Issue by ntk860** [react-native-kit/react-native-track-player#402]
@dcvz I am testing version 1.1.0 and its not showing the functionalities of the player on locked screen, any suggestion ?

**Comment by ntk860** [comment]
IOS

**Comment by ntk860** [comment]
I haven't tried on Android yet

**Comment by moonstruck** [comment]
@ntk860 Real device?

**Comment by ntk860** [comment]
@moonstruck Yes, real device

**Comment by GH974** [comment]
Hi, have you add this ?
`await TrackPlayer.updateOptions({
				stopWithApp: true,
				capabilities: [
					TrackPlayer.CAPABILITY_PLAY,
					TrackPlayer.CAPABILITY_PAUSE,
					TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
					TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
				]
			});`

**Comment by ntk860** [comment]
@GH974 thats what I am doing!

**Comment by minhtc** [comment]
The newest version remove all the commands after song loaded, that's why the notification control doesn't showing up.
apply this commit will fix the issue: https://github.com/HomieTech/react-native-track-player/commit/2c1b3d679e438b7a45a28e4687ce90b03e84980e

**Comment by dcvz** [comment]
This has been fixed in 30bf388e05a1b1ca8d3b43f2f7e988b306de6439 (#dev) and it will go out in a new npm version later today.

Thank you for reporting the issue ya'll ☀️

**Comment by ntk860** [comment]
@dcvz I will thank you!

**Comment by ishigamii** [comment]
@ntk860 can you close this issue if everything is good now ?
