### ISSUE TITLE
ios Error symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by shiroze** [react-native-kit/react-native-track-player#403]
How to solve this problem ? I use this on new project to test run my default program and it show error

Here is my PodFile to resolve symbol not found problem

![image](https://user-images.githubusercontent.com/6022114/51456205-6986ba00-1d7f-11e9-8a78-9c4a490405e6.png)

after 'Pod Install'

Here is the error.

![image](https://user-images.githubusercontent.com/6022114/51456257-9aff8580-1d7f-11e9-973d-791bea377ede.png)

is there a way to install this RNTrackPlayer ?

Step I try 
1. Create New project
2. yarn add react-native-track-player
3. open ios project and show : Symbol(s) not found for architecture x86_64 (Solved when install pod)

Stuck in this problem

**Comment by rtman** [comment]
@shiroze how did you fix this? Please don't just close an issue without posting the solution...

**Comment by shiroze** [comment]
> @shiroze how did you fix this? Please don't just close an issue without posting the solution...

Create .swift File

you can check the [Here](https://react-native-kit.github.io/react-native-track-player/install/#troubleshooting)

**Comment by rtman** [comment]
@shiroze appreciate it! that worked.

**Comment by shiroze** [comment]
> @shiroze appreciate it! that worked.

your welcome, dont forget give response so other can solve it.

Happy to help.
