### ISSUE TITLE
Error when playing in the background

### ISSUE THREAD

**Issue by ataravati** [react-native-kit/react-native-track-player#405]
I get the following error when playing in the background. (Platform iOS, I haven't tried it in Android). 

> Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8083/callbacks_poll'.

**Comment by curiousdustin** [comment]
@ataravati , this sounds like you’re trying to make a request while in the background that is not related to audio, but not the actual loading of the track url. 

If so, this is out of scope for this module. 

Closing this. Please let us know if this error is indeed coming directly from the TracPlayer.
