### ISSUE TITLE
[ios] 1.1.x duration changes as track loads.

### ISSUE THREAD

**Issue by curiousdustin** [react-native-kit/react-native-track-player#407]
In version 1.1.x on iOS, the full duration is no longer reported from the start of playing. Instead the duration changes as the track loads.

How can we display the full duration in our UI ?

**Comment by curiousdustin** [comment]
I'm using code based on the ProgressComponent example.

I call `play()` in an unrelated script, and then I see the duration slowly growing in my ProgressComponent.

**Comment by ntk860** [comment]
on your ProgressComponent you can do something like this (on render method), it will calculate the position and duration as it buffers the song

```const position = formatTime(Math.floor(this.state.position));```
```const duration = formatTime(Math.floor(this.state.duration));```

where 
````
function formatTime(seconds) {
    const ss = Math.floor(seconds) % 60;
    const mm = Math.floor(seconds / 60) % 60;
    const hh = Math.floor(seconds / 3600);

    if(hh > 0) {
        return hh + ':' + formatTwoDigits(mm) + ':' + formatTwoDigits(ss);
    } else {
        return mm + ':' + formatTwoDigits(ss);
    }
}

**Comment by minhtc** [comment]
I have just made a pull request to fix this issue.
https://github.com/HomieTech/react-native-track-player/commit/ef1050ad9cc48f3a037f2859eef2de9e97771828
