### ISSUE TITLE
java.lang.NullPointerException in Android studio

### ISSUE THREAD

**Issue by maendamedia** [react-native-kit/react-native-track-player#409]
Today in installed version 1.1.1.
I'm not able to run this version on Android as it states:

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-track-player'.
> java.lang.NullPointerException (no error message)`

Android studio states:

`Unsupported Modules Detected: Compilation is not supported for following modules: android. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

21:29	Gradle sync started

21:30	Project setup started

21:30	Gradle sync failed: java.lang.NullPointerException (34s 62ms)
`

Any idea how to fix?

**Comment by Guichaguri** [comment]
[This stackoverflow thread](https://stackoverflow.com/questions/28668252/android-studio-error-unsupported-modules-detected-compilation-is-not-supported) might help you
