### ISSUE TITLE
It is unclear how to use Casting

### ISSUE THREAD

**Issue by gazedash** [react-native-kit/react-native-track-player#410]
It is claimed that this library supports casting and in the readme casting refers to a WIP repository
https://github.com/react-native-kit/react-native-track-casting

Documentation in wiki (https://github.com/react-native-kit/react-native-track-player/wiki/Cast-Integration) doens't have any mentions about this repository.

So how do I add cast support in my React-Native application?

If the cast doesn't work with this library, it should be indicated in README, because it is very misleading

**Comment by neoassyrian** [comment]
I totally agree with gazedash. I thought this would work with Google Cast

**Comment by marcinkieruzel** [comment]
@curiousdustin Do you have any plan for finishing casting feature?

**Comment by curiousdustin** [comment]
Sorry, no. I have assigned this to myself to make sure our docs are accurate regarding this topic.

**Comment by lukepighetti** [comment]
The front page still says this has casting support, but I cannot figure out how to make it work. Did it ever get implemented?
