### ISSUE TITLE
Add to the documentation that this library needs Swift 4.2 in order to work on iOS

### ISSUE THREAD

**Issue by gazedash** [react-native-kit/react-native-track-player#411]
https://github.com/react-native-kit/react-native-track-player/issues/400

This library doesn't work with Swift 4.1

**Comment by ntk860** [comment]
you need 4.2

**Comment by ntk860** [comment]
its not the entire library, its only version 1.1.0, if you use version 1.0.0 you can use any previous swift version.

**Comment by dcvz** [comment]
Sorry for the problems @gazedash. It's now part of the setup section in the wiki :)
