### ISSUE TITLE
[iOS] Crash on ios 9

### ISSUE THREAD

**Issue by hoang-rio** [react-native-kit/react-native-track-player#413]
Crash on iOS in first run with version 1.1.0 and 1.1.1 but 1.0.2 work

## Crash Log
```
dyld: Symbol not found: _MPNowPlayingInfoCollectionIdentifier
  Referenced from: /Users/[hidden]/Library/Developer/CoreSimulator/Devices/DB4355DD-07B2-40D0-9140-5C79CE94AE39/data/Containers/Bundle/Application/9A81486F-D6DF-4FCB-98C8-215F7C87D12E/[hidden]/[hidden]

  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/MediaPlayer.framework/MediaPlayer

 in /Users/[hidden]/Library/Developer/CoreSimulator/Devices/DB4355DD-07B2-40D0-9140-5C79CE94AE39/data/Containers/Bundle/Application/9A81486F-D6DF-4FCB-98C8-215F7C87D12E/[hidden]/[hidden]
```

**Comment by ntk860** [comment]
the latest version of Xcode comes with swift 4.2, try to setup your project to use swift 4.2

**Comment by hoang-rio** [comment]
I saw swift 4.2 in my Xcode build setting. And i don't think this is problem of swift version. Because build successfull and all another iOS version work except iOS 9. I run my app in iOS 9.3 Simulator and it crashed

**Comment by timmywil** [comment]
You were able to compile properly, but RNTP is using APIs that aren't available in iOS 9. This became blatantly apparent when I tried to link with pods and it set the platform to iOS 9: https://github.com/react-native-kit/react-native-track-player/pull/486

Unfortunately for some, the likely solution is to not support iOS 9.

**Comment by hoang-rio** [comment]
> You were able to compile properly, but RNTP is using APIs that aren't available in iOS 9. This became blatantly apparent when I tried to link with pods and it set the platform to iOS 9: #486
> 
> Unfortunately for some, the likely solution is to not support iOS 9, but it'll be 2 years in August since the last patch Apple made to iOS 9 so maybe it's time.

I know it can compile. It only crash when run in ios 9 device. React native support ios 9 over higher so if RNTP support ios 9 will bettter

**Comment by timmywil** [comment]
I'm not sure you understood what I meant. RNTP is using native APIs that are not available in iOS 9, so it will not work in iOS 9.

**Comment by hoang-rio** [comment]
> I'm not sure you understood what I meant. RNTP is using native APIs that are not available in iOS 9, so it will not work in iOS 9.

I understood watch you mean. But i realy want RNTP support iOS 9 like v1.0.2 and previous

**Comment by andtos90** [comment]
I had the same problem, I think that the minimum supported version should be stated on the docs. @gazedash it's ok for you if I open a new PR?

**Comment by gazedash** [comment]
> I had the same problem, I think that the minimum supported version should be stated on the docs. @gazedash it's ok for you if I open a new PR?

@andtos90 I think you mentioned the wrong guy :) 
I think it should be @Guichaguri

**Comment by andtos90** [comment]
> > I had the same problem, I think that the minimum supported version should be stated on the docs. @gazedash it's ok for you if I open a new PR?
> 
> @andtos90 I think you mentioned the wrong guy :)
> I think it should be @Guichaguri

Yep sorry, wrong autocomplete!

**Comment by curiousdustin** [comment]
The underlying SwiftAudio library that is used for iOS requires iOS 10 or higher. 

https://github.com/jorgenhenrichsen/SwiftAudio#requirements

Therefore, react-native-tracker-player will not work on iOS 9.
