### ISSUE TITLE
[Feature] Missing progress event when track is playing

### ISSUE THREAD

**Issue by kesha-antonov** [react-native-kit/react-native-track-player#415]
Hey! Can you add this please?

Same as here https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#player

We need ```playback-progress```

**Comment by nishanBende** [comment]
@Guichaguri ProgressComponent works but wouldn't it be better to have that timer event on the native side just to reduce the overhead on JS side?

**Comment by Guichaguri** [comment]
That would actually create even more overhead. Just the process of sending events to the JS engine is way slower than a simple timer. It would be a timer in both cases anyway.
And also, a component for doing it actually stops the timer when it's not being rendered anymore, reducing unnecessary overhead.
