### ISSUE TITLE
Samsung devices show skip buttons instead of jump buttons on lock screen.

### ISSUE THREAD

**Issue by curiousdustin** [react-native-kit/react-native-track-player#417]
On several Samsung devices I have tried, the lock screen shows skip buttons instead of jump buttons.

The Notification (swiping from top) shows the correct jump buttons, but the lock screen does not.

I have capabilities set like this: 
```
export const trackPlayerOptions = {
  stopWithApp: true,
  capabilities: [
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
    TrackPlayer.CAPABILITY_SEEK_TO,
    TrackPlayer.CAPABILITY_JUMP_FORWARD,
    TrackPlayer.CAPABILITY_JUMP_BACKWARD
  ],
  compactCapabilities: [
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
    TrackPlayer.CAPABILITY_SEEK_TO,
    TrackPlayer.CAPABILITY_JUMP_FORWARD,
    TrackPlayer.CAPABILITY_JUMP_BACKWARD
  ],
  notificationCapabilities: [
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
    TrackPlayer.CAPABILITY_SEEK_TO,
    TrackPlayer.CAPABILITY_JUMP_FORWARD,
    TrackPlayer.CAPABILITY_JUMP_BACKWARD
  ]
};
```

**Comment by curiousdustin** [comment]
I decided to try just letting the lock screen have skip buttons, but make them look like jump buttons.

No luck. Setting the various icon assets has no effect on either the lock screen or notification.

**Comment by curiousdustin** [comment]
I'm also willing to just let the lock screen have these skip buttons, but code them to react like jump buttons. But, I'm not getting the skip events from these buttons either, they are just uselessly there...

**Comment by curiousdustin** [comment]
I determined, I can get the events to fire if I enable the capabilities like this:

```
capabilities: [
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
    TrackPlayer.CAPABILITY_SEEK_TO,
    TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
    TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
    TrackPlayer.CAPABILITY_JUMP_FORWARD,
    TrackPlayer.CAPABILITY_JUMP_BACKWARD
  ],
```

But, I really don't WANT those capabilities, just trying to get these Samsung devices to work. If I add these capabilities, but leave them out of the compact and notification capabilities, what exactly will this effect? Will the JUMP capabilities override the SEEK capabilities if possible?

**Comment by Guichaguri** [comment]
It's really strange, we are providing the correct capabilities to the OS, but I think it's ignoring them.

The capabilities array tells the OS what your app is capable of, so a smartwatch can show a seek bar if you add the `CAPABILITY_SEEK_TO`. Notification and compact capabilities are only used by the notification itself.

This is not the first issue we have with Samsung devices, they seem to be pretty buggy with music metadata.

**Comment by Guichaguri** [comment]
You can see it, that's just a hint for the OS that your app supports media and supports skipping. The OS might use that hint for anything it wants, such as showing custom media buttons. The hint may also be used by other devices, such as smartwatches or cars

**Comment by redbluenat** [comment]
Hi, I am facing this issue with Samsung Galaxy S20 ULTRA. Is there any workaround to have jump buttons visible?

Samsung:

<img width="236" alt="Zrzut ekranu 2020-07-7 o 09 51 35" src="https://user-images.githubusercontent.com/15861135/86741222-81b3cd00-c037-11ea-80d9-a7211f43cd17.png">

On other devices I have:

<img width="382" alt="Zrzut ekranu 2020-07-7 o 10 00 03" src="https://user-images.githubusercontent.com/15861135/86742776-a8263800-c038-11ea-8f86-c0ad33b50471.png">
