### ISSUE TITLE
seekTo android restarts the track

### ISSUE THREAD

**Issue by gazedash** [react-native-kit/react-native-track-player#418]
Possibly related to https://github.com/react-native-kit/react-native-track-player/issues/348

The bug is reproduced on Nexus 5X API 28 x86 android virtual device emulator.
Possibly reproducible on real device(?)

Works on iOS fine though.

**Comment by Guichaguri** [comment]
What track are you playing? Are you receiving `playback-error` events?

**Comment by gazedash** [comment]
@Guichaguri 
I receive two playback-state events:
{state: 6}
{state: 3}

I am not an android expert but is this related to PlaybackStateCompat https://developer.android.com/reference/android/support/v4/media/session/PlaybackStateCompat ?
As I can see, there is multiple events tied to same int values. E.g. 3 is REPEAT_MODE_GROUP, STATE_PLAYING and ERROR_CODE_AUTHENTICATION_EXPIRED

**Comment by Guichaguri** [comment]
It is, but you should be checking using our constants (e.g. `event.state === TrackPlayer.STATE_PLAYING`) instead, as the values will change depending on the version and the platform.

**Comment by gazedash** [comment]
@Guichaguri I am able to reproduce this error on real device Android 4.4.2

**Comment by gazedash** [comment]
Maybe it is related to a bug where duration is 0?

**Comment by gazedash** [comment]
It does reproduce even with example tracks:
https://github.com/react-native-kit/react-native-track-player/blob/dev/example/react/data/playlist.json

**Comment by Guichaguri** [comment]
That seems to be it. I'll take a look later today
