### ISSUE TITLE
Disable autoplay when adding new songs

### ISSUE THREAD

**Issue by dnish** [react-native-kit/react-native-track-player#422]
Hey,
just having a new issue when I try to load a new playlist. I'm adding tracks of a playlist like this:

```
  await TrackPlayer.add(tracks);
  await TrackPlayer.skip(this.playlist.currentIndex.toString()); // Selected song from the playlist
```

The problem is that I always here a short part of the first song before the player skips to the requested one. It seems that <code>TrackPlayer.add</code> automatically starts playback, and so the player begins with the first song. Any idea how I can disable this autoplay behavior?

**Comment by Guichaguri** [comment]
Duplicate of #404
