### ISSUE TITLE
Destroying player doesn't destroy events

### ISSUE THREAD

**Issue by dnish** [react-native-kit/react-native-track-player#423]
If I destroy and re-create the player two or several times, the events fire twice or more. So for example, I'm using this event handler:

```
    TrackPlayer.addEventListener('remote-next', () => alert('Test'));
```

If I click on "next" on the notification widget, the event is fired several times. I'm using the <code>.destroy()</code> method to destroy the player. It doesn't happen on first initialization. 

Tested on iOS 12 and iPhone XS.

**Comment by dnish** [comment]
Mhh possible that's an issue how we handle the creation of the player. We did it before like this:

```
   async initPlayerInstance(autoPlay = true) {

   await TrackPlayer.reset();
   await TrackPlayer.setupPlayer();

   await TrackPlayer.updateOptions({

                capabilities: [
                    TrackPlayer.CAPABILITY_PLAY,
                    TrackPlayer.CAPABILITY_PAUSE,
                    TrackPlayer.CAPABILITY_STOP,
                    TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                    TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
                    TrackPlayer.CAPABILITY_SEEK_TO
                ],

                compactCapabilities: [
                    TrackPlayer.CAPABILITY_PLAY,
                    TrackPlayer.CAPABILITY_PAUSE,
                    TrackPlayer.CAPABILITY_STOP,
                    TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                    TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
                    TrackPlayer.CAPABILITY_SEEK_TO
                ]
            });

     ...adding tracks
   }
```
It seems that <code>updateOptions</code> creates multiple events. If we change the code like this, the events are only fired once:

```
  if(!this.playerReady) {
            await TrackPlayer.setupPlayer();

            await TrackPlayer.updateOptions({

                capabilities: [
                    TrackPlayer.CAPABILITY_PLAY,
                    TrackPlayer.CAPABILITY_PAUSE,
                    TrackPlayer.CAPABILITY_STOP,
                    TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                    TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
                    TrackPlayer.CAPABILITY_SEEK_TO
                ],

                compactCapabilities: [
                    TrackPlayer.CAPABILITY_PLAY,
                    TrackPlayer.CAPABILITY_PAUSE,
                    TrackPlayer.CAPABILITY_STOP,
                    TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                    TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
                    TrackPlayer.CAPABILITY_SEEK_TO
                ]
            });


            this.playerReady = true;
        }

  await TrackPlayer.reset();
```

So <code>setupPlayer</code> and <code>updateOptions</code> are only called once during runtime. If I got it right, <code>updateOptions</code> could be called several times (to update the notication widgets), so I guess the multiple events are a bug.

**Comment by Guichaguri** [comment]
How are you registering the events? Can you show the code of that part?

**Comment by dnish** [comment]
Hey,
yeah, we register the events once within the <code>player_service.js</code>

```
module.exports = async function() {

    TrackPlayer.addEventListener('remote-play', () => PlayerStore.play());

    TrackPlayer.addEventListener('remote-pause', () => PlayerStore.pause());

    TrackPlayer.addEventListener('remote-stop', () => TrackPlayer.destroy());

    TrackPlayer.addEventListener('remote-next', () => PlayerStore.next());

    TrackPlayer.addEventListener('remote-previous', () => PlayerStore.prev());

    TrackPlayer.addEventListener('remote-seek', ({position}) => PlayerStore.seek(position));

    TrackPlayer.addEventListener('playback-state', ({state}) => {
        PlayerStore.isPlaying = (state === "playing");
    });
};
```

**Comment by Guichaguri** [comment]
That seems to be the same issue as #424.

**Comment by dnish** [comment]
@Guichaguri Adding  <code> player.remoteCommands.removeAll();</code> solves the issue. 
<img width="1452" alt="bildschirmfoto 2019-02-12 um 19 48 12" src="https://user-images.githubusercontent.com/7636313/52660184-753d4a80-2eff-11e9-8422-fea8bb02e418.png">

**Comment by HessiPard** [comment]
Problem is fixed in IOS but exists in Android.
track-player `1.1.8`

**Comment by HessiPard** [comment]
Packages like [react-native-exit-app](https://github.com/wumke/react-native-exit-app) will destroy everyThings for you

**Comment by farshed** [comment]
A temporary workaround for android:

Use a global flag to decide whether an event handler should run or not.

`let flag = false;`

Inside event handlers,

```
function someEventHandler() {
  if (flag) return;
  flag = true;
  setTimeout(() => (flag = false), 250);
}
```

If multiple handlers are registered for the same event, only one of them will execute and the rest will simply return. Hacky I know, but it works.
