### ISSUE TITLE
[Question] Streams with 'chunked' transfer encoding cannot be played

### ISSUE THREAD

**Issue by timmywil** [react-native-kit/react-native-track-player#434]
The exact same stream transferred with the chunked [Transfer Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding) does not play/is silent, but if sent over unchunked and with a content-length header, it plays.

I'm not necessarily suggesting that react-native-track-player support this. I'd just like to hear your thoughts on how difficult it might be to support. My use is case is that we're working on text-to-speech generation in elixir/phoenix and my team tells me there isn't a way to send an unchunked response, at least with their current architecture. HLS seems like it may be an option tho, so they are working on implementing that. However, I'm curious if it *could* be possible to play the chunked response with react-native-track-player. I think the only practical difference is the lack of content-length.

**Comment by Guichaguri** [comment]
Which platform have you tested this?

**Comment by timmywil** [comment]
We've just rolled an update to a lib and it started working. I have no idea what was going on.
