### ISSUE TITLE
iOS local files are not working

### ISSUE THREAD

**Issue by nezaidu** [react-native-kit/react-native-track-player#435]
My fix (AudioPlayer.swift)
![image](https://user-images.githubusercontent.com/3225817/52415990-379c8400-2af1-11e9-9db4-b1222b628b68.png)

```

**Comment by rzakirov** [comment]
There is problem when local file has no extension. Its ok for Android but iOS cannt play. After download and save file with extension (.mp3) it is playing well

**Comment by curiousdustin** [comment]
@nezaidu, Local files are working for me in `v1.2.3`.

Closing this for now.

Can you provide more specifics about your issue? Can you provide the differences between the original and your fix shown above?
