### ISSUE TITLE
Installation impossible Android

### ISSUE THREAD

**Issue by Aornn** [react-native-kit/react-native-track-player#438]
Hi ! i try to implement this module to my android app (create with CRNA) but i have an error 

`Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.`
`> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/ronan/Documents/perso/APP/android/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/88`

I follow the both installation guide but it doesn't work do you have some ideas ?
Thanks :)

**Comment by ishigamii** [comment]
can you give more informations, like what react native version you are using and what version of this lib  you are trying to use ?
