### ISSUE TITLE
URL-encoding inconsistencies

### ISSUE THREAD

**Issue by anderslemke** [react-native-kit/react-native-track-player#44]
On iOS, I have to decode the URL for the player:

    url: "https://example.com/æ.mp3"

On Android, I have to encode it:

    url: "https://example.com/%C3%A6.mp3"

**Comment by Guichaguri** [comment]
The right solution would be to support both of them on both platforms, right?

**Comment by dcvz** [comment]
I think we should expect the user to use non-encode URL's. It should not be the client's job to encode.

**Comment by Guichaguri** [comment]
We also should expect encoded URLs. The URL can be received encoded from a server or even hardcoded.

**Comment by Guichaguri** [comment]
For now on, you'll have to encode the URL to use on both platforms (See #71)
