### ISSUE TITLE
[WIKI] Update the wiki pages 

### ISSUE THREAD

**Issue by ishigamii** [react-native-kit/react-native-track-player#445]
Hi, I am currently trying the new version and so far I am happy to see that Android is working nicely now, though I am having some trouble with iOS now (that was okay before 👍 ) 

I am writing this cause I saw some improvement that could be done on the wiki page and I can't make a PR for that so here they are : 

in the Page : 
https://github.com/react-native-kit/react-native-track-player/wiki/API
```
TrackPlayer.registerPlaybackService(() => require('service.js')); 
```
Should be 
```
TrackPlayer.registerPlaybackService(() => require('./service.js')); 
```

```
// service.js
module.exports = async function() {
    // ...
}
```
Should be more detailed (had to go see the example to see what was supposed to be here) 
```
// service.js
module.exports = async function() {
    // For example this three events will allow to pause, play and stop from notification.
   // You can find all the possible events in https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#events

  TrackPlayer.addEventListener('remote-play', () => {
    TrackPlayer.play();
  });

  TrackPlayer.addEventListener('remote-pause', () => {
    TrackPlayer.pause();
  });

  TrackPlayer.addEventListener('remote-stop', () => {
    TrackPlayer.destroy();
  });
}
```

You actually explain it again in https://github.com/react-native-kit/react-native-track-player/wiki/API#playback-service maybe make a link to it directly would be a good idea 

Thanks a lot for you library

**Comment by Guichaguri** [comment]
The reason why I create an empty playback service is that the module won't run until you register one. In case someone is starting now step by step, it won't crash on Android.

**Comment by ishigamii** [comment]
@Guichaguri sorry about that then. Thanks for the details 👍

**Comment by Guichaguri** [comment]
No, you're right. I should at least write "we'll see use this later" or something like that.

**Comment by ishigamii** [comment]
@Guichaguri Should I close this or leave it open  ?
