### ISSUE TITLE
[Android] Seeking while paused causes playback-state NONE

### ISSUE THREAD

**Issue by curiousdustin** [react-native-kit/react-native-track-player#451]
When a track is paused, seeking in time, causes 2 `playback-state` events to happen.

First it goes to NONE for some reason, and then back to PAUSED.

This makes it hard to know how to render the UI, because NONE usually means that there is no current track and such.

**Comment by Guichaguri** [comment]
That's expected, but now that I look at it, it's indeed weird.

`BUFFERING` looks like the proper state to use instead of `NONE`, but I wanted it to indicate the player was playing but paused to buffer (and will resume playing after buffering is done)

* Keeping it as `PAUSED` will not trigger `playback-state`, but you won't be able to know whether the player is buffering while paused.
* Changing it to `BUFFERING` won't allow you to discriminate between paused and playing. That shouldn't be a problem for most apps.
* We can also add a new state for this specific case.

**Comment by curiousdustin** [comment]
Ah I see, so what I think you're saying is:

**Seeking while playing is meant to go through these states:**
PLAYING > BUFFERING > PLAYING

**Seeking while paused is meant to go through these states:**
PAUSED > NONE > PAUSED

This is intentional, in order to discriminate between playing vs paused while seeking.

I like your option B, change to buffering while seeking, whether paused or playing. Maybe the data passed for the `playback-state` event could include the intended next state? Something like: `{state: BUFFERING, nextState: PAUSED}`

I'd like to look into this further, but I am having a hard time finding the native Java code that actually causes these state changes. Can you point me in the right direction?

**Comment by Guichaguri** [comment]
You can change this specific line: https://github.com/react-native-kit/react-native-track-player/blob/dev/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java#L180

**Comment by curiousdustin** [comment]
I ended up working around this with other logic in my app. Feel free to close the issue if you do not intend to update the behavior.

**Comment by Guichaguri** [comment]
I've decided to change it to STATE_PAUSED, so it won't trigger unnecessary events. If someone ever needs to know whether the track is buffering while paused, we should probably implement a `isPlaying` property to the event.

**Comment by mimamuh** [comment]
I would need the case to distinguish between playing vs paused while seeking. 

Case: 
For a button I ...
... show a pause-icon when the show is playing or loading.
... and I show the play-icon when the show is stopped or paused.

But after changing the behaviour with `1.1.4` it flickers the icon when the user is seeking on a paused show as I don't know if `BUFFERING` is caused while the show was `PAUSED` before or was `PLAYING`.

**Comment by Guichaguri** [comment]
@dcvz What do you think about adding a `PREPARING` state?

**Comment by Guichaguri** [comment]
It should return the `CONNECTING` state in newer versions.
