### ISSUE TITLE
[Android] Notification remove the link onClick

### ISSUE THREAD

**Issue by ishigamii** [react-native-kit/react-native-track-player#453]
Hi, I am currently using the version `1.1.2` of the library and once again that's an amazing job you are doing there. Here are some strange things I am experimenting with this version : 

# Configuration
package.json
```
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-track-player": "^1.1.2",
    "react-native-swift": "^1.2.2",
```

react-native info
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.2
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

# Question 

I am wondering if it is possible de remove the notification `onclick` action on Android. For the moment I have no use of it and more than this it is opening the app again and so creating some problems for me so far. I read some post about it saying that I should add the `SingleTop` (didn't try it yet) and that the current link is  `trackplayer://notification.click`.  (https://github.com/react-native-kit/react-native-track-player/issues/346).

Thanks for help 👍

**Comment by Guichaguri** [comment]
That actually shouldn't affect anything, it's just an additional feature in case you want to customize the behavior.

**Comment by ishigamii** [comment]
Solved this with removing my `SingleTop` and adding `android:launchMode="singleTask"` to AndroidManifest.xml under the activity `android:name=".MainActivity"`.
