### ISSUE TITLE
Do options need to be provided separately to setupPlayer() and updateOptions()?

### ISSUE THREAD

**Issue by curiousdustin** [react-native-kit/react-native-track-player#460]
In the docs there are 2 sets of configuration option objects documented.

There is set of options that is documented under setupPlayer().
https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#setupplayeroptions

And there is another set that is documented under updateOptions().
https://github.com/react-native-kit/react-native-track-player/wiki/Documentation#updateoptionsdata

**Do these options objects need to be applied separately like this, or can one settings object with ALL these settings be safely passed to setupPlayer(), and never use updateOptions()?**

Looking at the native code makes me think that these do indeed need to be called separately with separate sets of options. Also, looking at the code makes me think that the options documented under setupPlayer(), are not actually used at all on iOS, which probably should be clarified in the docs, unless I am just overlooking that.

**Comment by Guichaguri** [comment]
They are completely different options, one is related to the behavior of the player, and the other one related to the behavior of the metadata and media buttons.

At the moment, iOS doesn't support any of those options, so they're basically ignored. We should at some point add to the documentation which platforms each option/function is available.

`updateOptions()` can be called multiple times, even during playback, while `setupPlayer()` will work once until you run `destroy()`.

**Comment by curiousdustin** [comment]
I would gladly submit a proposed update to the docs, but as far as I can tell, there isn't a way to do this similar to normal PRs, correct?

**Comment by Guichaguri** [comment]
There isn't, unfortunately, but I've enabled public editing. Feel free to update it.

@dcvz we should probably move the wiki to the main repo, [creating a docs site](https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/). What do you think?

**Comment by curiousdustin** [comment]
I made some edits. Please double check my assessment of which options/parameters are used on each platform. This was another point of confusion for me when starting out with this plugin.

I am also willing to attempt moving the docs into the main repo as described in your link above, but I don't want to duplicate work you might already be doing. Let me know, public editing is obviously not necessarily ideal.

**Comment by dcvz** [comment]
@Guichaguri that would probably be for the best, that would allow easy contribution and review from our side. Let's do it!

**Comment by Guichaguri** [comment]
[Done](https://react-native-kit.github.io/react-native-track-player/). I feel like the CSS can be improved a lot, but everything else is in place.

@curiousdustin thanks for the contribution :)
