### ISSUE TITLE
stopWithApp doesn't work

### ISSUE THREAD

**Issue by Aornn** [react-native-kit/react-native-track-player#463]
```
    async componentDidMount() {
        await TrackPlayer.setupPlayer()
        TrackPlayer.updateOptions({
            stopWithApp: true
        });
}
```

Hi i have this code but when i kill my app while a song is running it doesn't stop the song, i have no error or whatever ...
Do you know why ? Thanks !

**Comment by Guichaguri** [comment]
Which platform?

**Comment by Aornn** [comment]
Android, last version of this player

**Comment by Aornn** [comment]
so you don't know ?

**Comment by ishigamii** [comment]
@Aornn what is the version you are using ? `1.1.2` or `1.1.3`?

**Comment by mkdotcom** [comment]
I don't have this issue anymore with 1.1.3
thanks

**Comment by ishigamii** [comment]
@mkdotcom cool 
@Aornn do you still have this issue in `1.1.3` ? if not can you close the issue ?

**Comment by Aornn** [comment]
OK it's fixed for me too :D
