### ISSUE TITLE
[iOS] add Category option to allow custom AVAudioSession category

### ISSUE THREAD

**Issue by timmywil** [react-native-kit/react-native-track-player#469]
Category is set here: https://github.com/react-native-kit/react-native-track-player/blob/686e7a4d9fe6607d58347c573ba83ed6010d7ee5/ios/RNTrackPlayer/RNTrackPlayer.swift#L134

I'm using another plugin that uses the microphone and because AVAudioSession is shared, it needs to set `playAndRecord` as the category. Obviously, it doesn't seem appropriate to just set that here. It would be ideal if this was configurable somehow in react-native-track-player.

Here's a good explanation of the issue: https://github.com/wenkesj/react-native-voice/issues/50#issuecomment-347066628

react-native-sound `setCategory` method: https://github.com/zmxv/react-native-sound/blob/master/RNSound/RNSound.m#L110

I envision an option passed to `setupPlayer` rather than a method like the above. Maybe not `updateOptions` as it seems to be more work to change the category after the audio session becomes active.

**Comment by curiousdustin** [comment]
This was addressed in #484.
