### ISSUE TITLE
Large artwork issues (Android)

### ISSUE THREAD

**Issue by mdekrey** [react-native-kit/react-native-track-player#471]
When using large images for the `artwork` url on Android, on some devices one of the following happens:

* Notification bar controls and lock-screen controls do not appear. (Noted in emulator of Lollipop android, 2GB of RAM, xhdpi resolution. More stats available on request.)

    I couldn't find a corresponding message in the logs.

* Emulator crashes (Noted in emulator of Lollipop android, 2GB of RAM, xxhdpi resolution. More stats available on request.)

    Exception shows in log as follows:

        03-02 15:50:33.774 E/AndroidRuntime( 1960): *** FATAL EXCEPTION IN SYSTEM PROCESS: main
        03-02 15:50:33.774 E/AndroidRuntime( 1960): java.lang.OutOfMemoryError: Failed to allocate a 36000012 byte allocation with 4194208 free bytes and 8MB until OOM
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.graphics.Bitmap.nativeCreate(Native Method)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.graphics.Bitmap.createBitmap(Bitmap.java:714)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.graphics.Bitmap.createBitmap(Bitmap.java:639)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.graphics.Bitmap.createBitmap(Bitmap.java:619)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.app.Notification.cloneInto(Notification.java:1366)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.app.Notification.clone(Notification.java:1337)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.service.notification.StatusBarNotification.clone(StatusBarNotification.java:157)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at com.android.server.notification.NotificationManagerService$NotificationListeners.notifyPostedLocked(NotificationManagerService.java:2848)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at com.android.server.notification.NotificationManagerService$7.run(NotificationManagerService.java:1812)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.os.Handler.handleCallback(Handler.java:739)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.os.Handler.dispatchMessage(Handler.java:95)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at android.os.Looper.loop(Looper.java:135)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at com.android.server.SystemServer.run(SystemServer.java:269)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at com.android.server.SystemServer.main(SystemServer.java:170)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at java.lang.reflect.Method.invoke(Native Method)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at java.lang.reflect.Method.invoke(Method.java:372)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        03-02 15:50:33.774 E/AndroidRuntime( 1960):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

I'm on version 1.1.3.

Example image: [Gimlet Media's 3000x3000 podcast album image](https://static.megaphone.fm/podcasts/05f71746-a825-11e5-aeb5-a7a572df575e/image/uploads_2F1516902193862-jqkml22bswo-cee641b4533ddb31a5a7ab656fe45116_2FCURRENT_Reply%2BAll%2BLogo.png).

**Comment by Guichaguri** [comment]
That's expected. the module used to resize artworks after downloading them, but since I realized you shouldn't be using large images as resizing also needs to allocate it to the memory anyway and may take time to finish resizing.

Please, use lower resolution artworks, they'll load faster and they won't cause memory issues.

**Comment by mdekrey** [comment]
Unfortunately, higher dpi devices are actually driving the artwork providers towards higher resolution artworks.

So I'm understanding correctly, the recommended solution is to resize the image (on the device or otherwise) prior to passing the artwork url in order to guard against URLs that have image sizes such as the example? I understand that this is a track-player library, not an image-resize library 😄 

I am concerned about a too-large-image crashing the phone if it can crash the emulator, though.

**Comment by Guichaguri** [comment]
The phone can run out of memory the same way an emulator does. I know we're driving to higher resolution images, but you don't have to go overkill. Soundcloud, for instance, only stores up to 500x500 artworks on their servers, and they look completely fine.

Artworks have to be downloaded in full resolution and then allocated to the memory in full resolution. Just that can make the device crash if the artwork is too big.
Resizing it just makes it consume less memory after at the cost of a bit of processing time, which you can skip if you start using lower resolution artworks in the first place.

**Comment by mdekrey** [comment]
As I mentioned before, this isn't my artwork; it's from Gimlet Media, recently acquired by Spotify. It's the link available in the RSS feed for the podcast "Reply All".

But I'll see what I can do to downsize the artwork. Thanks!
