### ISSUE TITLE
[Android] Custom notification icon does not appear in debug builds. (Works in release builds)

### ISSUE THREAD

**Issue by ithustle** [react-native-kit/react-native-track-player#475]
I'm using this code to show icon on notification but it does not show up.

```
TrackPlayer.setupPlayer();
		TrackPlayer.updateOptions({
			stopWithApp: true,
			capabilities: [
			  TrackPlayer.CAPABILITY_PLAY,
			  TrackPlayer.CAPABILITY_PAUSE,
			  TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
			  TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
			  TrackPlayer.CAPABILITY_STOP
			],
			compactCapabilities: [
			  TrackPlayer.CAPABILITY_PLAY,
			  TrackPlayer.CAPABILITY_PAUSE
            ],
            
            icon: require('./../imgs/ic_logo_notification.png'),
		});```

Am I doing something wrong?

**Comment by ManeeshAkurathi** [comment]
If you want to show icon in notification. You need to add that as follows

`TrackPlayer.add({
        // Other params comes here as usual like url, title etc
        artwork:require('./../imgs/ic_logo_notification.png')  //this is your notification icon
      });`

**Comment by ithustle** [comment]
@ManeeshAkurathi are you sure about this? 

AFAIK  `artwork: require('...')` show audio cover ...

**Comment by Guichaguri** [comment]
Can you send a screenshot showing the how the notification looks to you? Can you also send the icon image?

**Comment by ithustle** [comment]
@Guichaguri , please FIA.

Now I figure it out that happens on device with differents sizes ... 
My icon has 33 x 33 px

![ic_logo_notification](https://user-images.githubusercontent.com/5114680/53877045-721e1180-4008-11e9-8c52-a40c6230dc5a.png)

![screenshot_20190306-120139](https://user-images.githubusercontent.com/5114680/53876938-2f5c3980-4008-11e9-9862-8e0e7a4f6178.png)

**Comment by ManeeshAkurathi** [comment]
@ithustle  It worked for me.

**Comment by ithustle** [comment]
@ManeeshAkurathi it works on different screens sizes?

**Comment by ithustle** [comment]
Ahh... Never mind... I missed this https://facebook.github.io/react-native/docs/images.html

**Comment by ithustle** [comment]
I reopened this discussion because this issue still ...

**Comment by YajanaRao** [comment]
@ithustle any update on the issue?

**Comment by YajanaRao** [comment]
Hi,
It resolve this issue by added one more icon to drawable of android name icon and passed it as a default value  to the method in MetadataManager.java file.

`builder.setSmallIcon(getIcon(options, "icon", R.drawable.icon));`

**Comment by Guichaguri** [comment]
@ishigamii do you have the icon image in different scales (the filename ending with @2x, @3x, etc)?

**Comment by ishigamii** [comment]
@Guichaguri I think you mistook me with the tag ;)

**Comment by Guichaguri** [comment]
Sorry for that. That was meant for @ithustle

**Comment by ithustle** [comment]
@Guichaguri, yep

**Comment by mojtaba-hajishah** [comment]
Icon does not work for me either.
react-native-track-player: 1.1.4
react-native: 0.55.3

```
TrackPlayer.updateOptions({
      stopWithApp: true,
      alwaysPauseOnInterruption: true,
      icon: require('../assets/img/logo.png'),
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
        TrackPlayer.CAPABILITY_STOP,
      ],
      compactCapabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
      ],
```

**Comment by Guichaguri** [comment]
@ithustle It doesn't make sense to have `ic_logo_notification.png` and `ic_logo_notification@1.0.png` at the same time.

To follow Android specification more strictly, try this:
* `ic_logo_notification.png` - 24x24 px (mdpi)
* `ic_logo_notification@1.5x.png` - 36x36 px (hdpi)
* `ic_logo_notification@2x.png` - 48x48 px (xhdpi)
* `ic_logo_notification@3x.png` - 72x72 px (xxhdpi)
* `ic_logo_notification@4x.png` - 96x96 px (xxxhdpi)

**Comment by ithustle** [comment]
Thanks, @Guichaguri . That it is I had asking before. :)
I'll try do this.

**Comment by ithustle** [comment]
@Guichaguri... well,  this is awkward but still no working :(

**Comment by jonnyberanek** [comment]
I was facing the same problem. It seems that while developing it will only display the default play icon, but with the release build installed, it gave me my desired notification icon.

(I'm on RN 0.60.5 and version 1.1.8 of this package)

**Comment by curiousdustin** [comment]
Related: https://github.com/react-native-kit/react-native-track-player/issues/901#issuecomment-617242014

**Comment by curiousdustin** [comment]
@ithustle Are you still facing this issue?

Any chance it was only failing on debug builds?

**Comment by ithustle** [comment]
@curiousdustin , for now I'm not worried about it. Maybe in next days I'll keep my eyes on it. But yeah, I still facing this issue.

**Comment by curiousdustin** [comment]
Please let us know if it is happening on debug and/or release builds.

**Comment by lylest** [comment]
some body please give some solutions i can't see a notification icon only art work

**Comment by ainar** [comment]
I confirm that the notification icon is working in release build but it is not working in debug build.

**Comment by ithustle** [comment]
Me too

**Comment by lylest** [comment]
Why did you removed it the thing is still unsolved

**Comment by curiousdustin** [comment]
I removed the question label because I consider this a confirmed bug at this point. Custom icon does not appear in debug builds.

**Comment by lylest** [comment]
Ohh okay nice

**Comment by Guichaguri** [comment]
In short, it's not fixable. Android requires bundled assets for notification icons, and since the icons in debug mode are not bundled but retrieved from a local server, it won't work.

**Comment by dimbslmh** [comment]
> In short, it's not fixable. Android requires bundled assets for notification icons, and since the icons in debug mode are not bundled but retrieved from a local server, it won't work.

It is required to set bundleInDebug to true as it's by default set to false. 
```
project.ext.react = [
    bundleInDebug: true,
]
```
Reference: https://github.com/facebook/react-native/blob/88f2356eedf71183d02cde0826c8a0c6910f83dd/template/android/app/build.gradle#L26-L27


```
const options = {
  icon: { uri: 'app_icon' }
}
TrackPlayer.updateOptions(options)
```
Reference: https://reactnative.dev/docs/images#images-from-hybrid-apps-resources
