### ISSUE TITLE
New version ExoPlayer r2.9.6

### ISSUE THREAD

**Issue by ithustle** [react-native-kit/react-native-track-player#477]
Any plans to update ExoPlayer r2.9.6 version?

**Comment by Guichaguri** [comment]
Is there a specific reason for the update? I mean, it's always good to update, but the version we're using is working pretty well.

**Comment by ithustle** [comment]
Maybe... 

As I reffered in #476 , I'm wondering maybe I can see my problem solved.
I'm doing a few tests and for now, it seems maybe solved ... I'm not so sure ... 

If it does, can you accept my PR?

**Comment by Guichaguri** [comment]
Absolutely!

**Comment by Guichaguri** [comment]
ExoPlayer has been updated in the dev branch.
