### ISSUE TITLE
Repeat track on queue

### ISSUE THREAD

**Issue by ithustle** [react-native-kit/react-native-track-player#481]
Is there a way to repeat one track on queue of at least 4 tracks? 

If no, have you guys a plan to implement it?

**Comment by Guichaguri** [comment]
Duplicate of #122

**Comment by ithustle** [comment]
Unfortunetly it doesn't help me...

**Comment by Guichaguri** [comment]
I'm unifying each suggestion in a single issue, it's supposed to help the project stay organized. If you want this feature, you should 👍 that issue instead.
