### ISSUE TITLE
Start a specific track from a playlist

### ISSUE THREAD

**Issue by ithustle** [react-native-kit/react-native-track-player#483]
I have the following track:

```
const tracks = [
    {
        id: "166898571529",
        ...
    },
    {
        id: "166898571539",
        ...
    },
    {
        id: "166898571549", // <--- I need to start song play from here
        ...
    },
    {
        id: "166898571559",
        ...
    },
]
```

My users start playing songs when they tap a song. On a playlist they can tap any song whatever they want and any position. So, is there a way (from this lib) to start a song as I described above in comment and when the current song ends the track list continue playing next track `166898571559` ?

PS: I tried `insertBeforeId` but as I referred in https://github.com/react-native-kit/react-native-track-player/issues/170#issuecomment-470998449 it doesn't work.

**Comment by zedissime** [comment]
I guess I would try to split the logic of the playlist. 
Maybe 2 playlist would do the trick. One playlist in the state in order to be shown to your users, and the second one built in RNTP.
When your user tap on a song, I would [`removeUpcomingTracks()`](https://react-native-kit.github.io/react-native-track-player/documentation/#removeupcomingtracks) on the player, then add the song.

**Comment by ithustle** [comment]
Yep, that’s the trick. I did something like that.

**Comment by patrickbattisti** [comment]
it solve my problem

```
 const addRadioToTrackPlayer = useCallback(
    async (radios: Radios, radioIndex: number) => {
      const radio = radios[radioIndex];

      const currentTrack = {
        id: radio.title_song,
        url: radio.radio_stream,
        title: radio.radio_name,
        artist: radio.title_song,
        artwork: `https://www.radioair.info/images_radios/${radio.radio_logo}`,
      };

      const playlists = radios.reduce(
        (acc: { before: any; after: any }, radio, index) => {
          const track = {
            id: radio.title_song,
            url: radio.radio_stream,
            title: radio.radio_name,
            artist: radio.title_song,
            artwork: `https://www.radioair.info/images_radios/${radio.radio_logo}`,
          };

          return {
            before:
              index < radioIndex ? [...(acc.before || []), track] : acc.before,
            after:
              index > radioIndex ? [...(acc.after || []), track] : acc.after,
          };
        },
        { before: [], after: [] },
      );

      await TrackPlayer.reset();

      await TrackPlayer.add(currentTrack);
      await TrackPlayer.play();
      await TrackPlayer.add(playlists.before, currentTrack.id);
      await TrackPlayer.add(playlists.after);
      const queue = await TrackPlayer.getQueue();

      console.log(queue);
    },
    [],
  );
```

**Comment by zcsEason** [comment]
const playAudio=async (item:AudioItem)=>{
  //check if the Track was added
  var list= await TrackPlayer.getQueue()
  let selectedIndex=0
  let selectedTrack=list.find((track,index) => {
    if(track.id==item.id)
    {
      selectedIndex=index
      return true
    }
  });
  if(selectedTrack == undefined)//not added then add to the queue
  {
    await TrackPlayer.add({
      id: item.id,
      url:encodeURI(item.fileName),
      title: item.displayName,
      artist: 'Track Artist',
      artwork: require('~/assets/play.png')
     });
     list= await TrackPlayer.getQueue()
     selectedIndex=list.length-1;
  }
  // skip to selected index then play
  TrackPlayer.skip(selectedIndex)
  await TrackPlayer.play();
}

**Comment by ser-emejia** [comment]
> Yep, that’s the trick. I did something like that.

Could you share you solution?
