### ISSUE TITLE
Events are not triggered

### ISSUE THREAD

**Issue by matinzd** [react-native-kit/react-native-track-player#491]
Hi,
My events are not triggered in service.
Here is my code
And does anyone have any ideas about getting tracks duration in queue?!

```
tracks.push({
          url: BASE_URL + value.path96.replace(/\\/g, "/"),
          id: index
});

 TrackPlayer.updateOptions({
        stopWithApp: true,
        compactCapabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE
        ],    
        capabilities: [
          TrackPlayer.CAPABILITY_PLAY_FROM_ID
        ],
        playIcon: require('../../assets/images/player_play.png'),
        pauseIcon: require('../../assets/images/player_pause.png'),
      })
  TrackPlayer.setupPlayer().then(async () => {
        await TrackPlayer.add(tracks);
        TrackPlayer.play()
        this.setState({
          paused: false
        })
      })
    })
```

And my TrackPlayerService.js

```
import TrackPlayer from 'react-native-track-player'

const TrackPlayerService = async () => {
    console.log('adding event listeners')
    TrackPlayer.addEventListener('remote-play', () => {
        console.log('remote-play');
        TrackPlayer.play();
        TrackPlayer.getDuration().then((duration) => {
            setStore({
                sliderDuration: duration
            })
        })
    });

    TrackPlayer.addEventListener('remote-pause', () => {
        console.log('remote-pause');
        TrackPlayer.pause();
    });

    TrackPlayer.addEventListener('remote-next', () => {
        console.log('remote-next');
        TrackPlayer.skipToNext();
    });

    TrackPlayer.addEventListener('remote-previous', () => {
        console.log('remote-previous');
        TrackPlayer.skipToPrevious();
    });

    TrackPlayer.addEventListener('remote-stop', () => {
        console.log('remote-stop');
        TrackPlayer.destroy();
    });
};

export default TrackPlayerService;

```

RN: v0.58.4
OS: Android 9.0 Pie
TrackPlayer: 1.1.3

**Comment by Guichaguri** [comment]
1. You should be setting up the player before updating the options.
2. You shouldn't be updating your store inside the service, that shouldn't cause issues in your case, but it might.
3. `remote-` based events are only trigger when the user presses a button in the notification or in another device. As you aren't specifying the proper capabilities in the options, I think they're not triggering because the buttons don't show up.
4. You can feed the duration manually and then retrieve it using `getQueue()`. The player won't calculate the duration (which you can retrieve using `getDuration()`) until you start the track.

**Comment by matinzd77** [comment]
Thanks for your response.
How can I remove notitication?

**Comment by Guichaguri** [comment]
You can't. Android requires a notification up in order to start a foreground service

**Comment by matinzd77** [comment]
So I selected icon for pause and play but nothing happens

**Comment by Guichaguri** [comment]
Can you share the code of your app, so we can take a look at it?

**Comment by matinzd77** [comment]
Here is my code, I have removed icon options.

**Comment by weslley39** [comment]
I'm with the same issue

While `remote-jump-forward` works fine on iOS, Android for some strange reason is not firing this event.

**Comment by Guichaguri** [comment]
@weslley39 Make sure you have the `CAPABILITY_JUMP_FORWARD` added to the options, if it's still not working, please, open a new issue.
