### ISSUE TITLE
null is not an object (evaluating 'TrackPlayer.STATE_NONE')

### ISSUE THREAD

**Issue by eff-society** [react-native-kit/react-native-track-player#495]
I get this error whenever I import TrackPlayer in a file. I've gone through the similar issues on this repo and tried everything, including reinstalling and relinking the lib (manually too) but nothing works.
I'm building for android btw.

![Screenshot_2019-03-18-11-53-16-08](https://user-images.githubusercontent.com/23633421/54512080-d0d27c00-4974-11e9-9860-8a9f2e956b6e.png)

**UPDATE:** Upon further testng, the module seems to work fine on the emulator. The error is produced only on my phone. The only difference I can think of is that my phone runs Marshmallow 6.0 while emulator is running Oreo 8.1.

Any thoughts?

**Comment by Guichaguri** [comment]
Are there any other crashes in the logs?

**Comment by eff-society** [comment]
@Guichaguri My bad. I reinstalled the app on the phone and the error's gone. It was probably a cache problem. Feel free to close the issue :p

**Comment by eff-society** [comment]
Closing this issue now

**Comment by Sanan4li** [comment]
Just Reinstalled the app and everything is working fine.

**Comment by piyush1302000** [comment]
> Just Reinstalled the app and everything is working fine.

Expo client app in mobile?

**Comment by farshed** [comment]
@piyush1302000 It's a native module, it doesn't work with Expo

**Comment by piyush1302000** [comment]
> @piyush1302000 It's a native module, it doesn't work with Expo

I am using expo client and getting same error, can you tell me what I can do to fix this error?

**Comment by farshed** [comment]
I just told you that it doesn't work with Expo. It's a NATIVE MODULE. Expo doesn't support native modules. If you want to use it, you have to create a vanilla RN project

**Comment by WolfMAN-DEV** [comment]
https://github.com/piyush1302000 also you can use expo bare workflow instead of managed workflow

**Comment by sho19** [comment]
i tried the above mentioned methods by i still am getting the same error
