### ISSUE TITLE
Update Current Track

### ISSUE THREAD

**Issue by shiroze** [react-native-kit/react-native-track-player#507]
![image](https://user-images.githubusercontent.com/6022114/54808209-1fa04e80-4cb2-11e9-80cc-2f9726e8b96f.png)

is there a way to Update current track Title, Artist, and Image ?

**Comment by Guichaguri** [comment]
Duplicate of #93. This is already being worked on #465

**Comment by shiroze** [comment]
Thanks @Guichaguri , the pull Request work for Android. but how about ios ?

**Comment by Guichaguri** [comment]
The PR is still in the works, it won't be merged until we have iOS support fully working too.
