### ISSUE TITLE
Player disappear on lock screen and buttons randomly get disabled

### ISSUE THREAD

**Issue by diego3g** [react-native-kit/react-native-track-player#508]
Hello,

I'm having two problems in iOS:

1. Sometimes in the lock screen when i press next/prev buttons the player fades away and i need to unlock the phone and lock again to see it. See (https://i.imgur.com/Zv4XvoX.mp4)

2. When i press prev/next buttons on Control Center sometimes these buttons get disabled and i can't press it anymore, even when they're not the first or last items on the list. Also, the previous button remains active when it's the first song and the next button when it's the last song. (See https://imgur.com/a/h6cMiKm)

Is there any way to control when the buttons are active within my application?

**Comment by curiousdustin** [comment]
I think these issues have been resolved in v1.2.3. 

Please let us know if this is not resolved.
