### ISSUE TITLE
RNTrackPlayer/RNTrackPlayer.swift:139:34: Use of unresolved identifier 'SessionCategory'; did you mean 'sessionCategory'?

### ISSUE THREAD

**Issue by kkkkkt** [react-native-kit/react-native-track-player#510]
Got error, maybe related to this chage ( https://github.com/react-native-kit/react-native-track-player/commit/f4afe2304de95af3a692510266abae4f6cf2f77e#diff-44c74236a1adc81d43903a61beab25ea )

Previous Version ( https://github.com/react-native-kit/react-native-track-player/commit/686e7a4d9fe6607d58347c573ba83ed6010d7ee5#diff-44c74236a1adc81d43903a61beab25ea ) worked well.

- History
  - https://github.com/react-native-kit/react-native-track-player/commits/f4afe2304de95af3a692510266abae4f6cf2f77e/ios/RNTrackPlayer/RNTrackPlayer.swift

**Comment by ishigamii** [comment]
You just have to add it to the ios Project it's missing in the project ;)

**Comment by shiroze** [comment]
@ishigamii already add the ios Project to my project but, xcode still say same.

**Comment by ishigamii** [comment]
I meant add the file to the project ;) cause it was missing for me 
https://github.com/react-native-kit/react-native-track-player/issues/502

**Comment by Guichaguri** [comment]
https://github.com/react-native-kit/react-native-track-player/pull/500/commits/ee9e2a4e65d5c4510012fbab1f580963f80c0c07 seems to fix it, can you try it?

**Comment by shiroze** [comment]
the File that must add to RNTrackPlayer project Folder Models is 

> SessionsCategories.swift

Problem solved
