### ISSUE TITLE
Multiple instances of the different audio files are playing

### ISSUE THREAD

**Issue by Kendysond** [react-native-kit/react-native-track-player#518]
Hi, 

Experiencing an odd issue, when I call the play method on subsequent audio files, it doesn't stop the previously playing file, rather it plays while the former is playing and you can hear multiple audio outputs. 

Any help on what i'm doing wrong would be really appreciated. 

Also, even when the app is refreshed(not close per se), the audio continues playing. I'd have imagined it would be stopped.

**Comment by moonstruck** [comment]
@Kendysond Are you getting this on real device or emulator? Sometimes emulator behaves weird . . .

**Comment by Kendysond** [comment]
@moonstruck Interesting.. I'm testing on my emulator currently, but I'll try it on a real device and share the feedback. Thanks!

**Comment by Myerden** [comment]
AFAIK you are responsible to manage this situation.
Same problem occurs in my project. I solved this problem by adding these lines to my project. You can add this code to home screen or anywhere you want. By this way, when you navigate to home screen, you will check if the Track Player is running or not. If running, stop it.
(I assume that you are using **React Navigation**)

    componentWillMount(){
        const { navigation } = this.props;
        this.focusListener = navigation.addListener("didFocus", async () => {
          // The screen is focused
            let statePlaying = TrackPlayer.STATE_PLAYING
            let isPlaying = await TrackPlayer.getState() == statePlaying
            if(isPlaying){
                await TrackPlayer.stop()
            }
        });
    }

    componentWillUnmount() {
        // Remove the event listener
        this.focusListener.remove();
    }

**Comment by Guichaguri** [comment]
Is it happening on Android or iOS?

**Comment by ishigamii** [comment]
Already got this on iOS but just have the kill the app completely and it stop all. 
I think it's cause of the debug mode

**Comment by dcvz** [comment]
There was a bug that if you reloaded ReactNative -- it would keep then old instance and it'd continue playing. This has been fixed in the #dev branch.

Could this have been the problem?

**Comment by curiousdustin** [comment]
This is fairly old. Closing for now. 

If anyone is still experiencing this, please comment with OS, RNTP version, and whether it happens in debug and/or release builds.
