### ISSUE TITLE
Support for controlling playback speed

### ISSUE THREAD

**Issue by anderslemke** [react-native-kit/react-native-track-player#52]
It would be nice to be able to control playback speed, so users could choose to playback at eg. 1.5 times.

**Comment by Guichaguri** [comment]
How about `setSpeed`/`getSpeed`? The speed would be represented as a double, `1` being the original speed.

Also, why not also implement `setPitch`/`getPitch`?

**Comment by gregoiredumas** [comment]
That would be a great addition. `react-native-sound` doesn't work for long file but is the only on that lets you change the speed.

**Comment by Guichaguri** [comment]
Added in 75e1c5626006e6ae021e558938d4673b287f7327 (v0.2.3)

**Comment by alikazemkhanloo** [comment]
This feature is not in the Wiki. please update it.
Thanks.

**Comment by zach-luman** [comment]
Are those APIs for playback speed control not supported yet?

**Comment by Guichaguri** [comment]
They are. The wiki is not updated yet.

**Comment by obsd** [comment]
Can I help with the wiki update? @Guichaguri

**Comment by Guichaguri** [comment]
They are already there (see `setRate` and `getRate`). But if you want to help with the documentation, you can open a pull request editing the files inside the `docs` directory.

**Comment by pawanv048** [comment]
The speed can be control according to the rate.

const [playbackRate, setPlaybackRate] = useState(1.0);

// Default playback rate
const handleDefaultPlaybackRate = async () => {
  await TrackPlayer.setRate(1.0);
  setPlaybackRate(1.0);
}

// Change playback rate
const handleChangePlaybackRate = async (rate) => {
  await TrackPlayer.setRate(rate);
  setPlaybackRate(rate);
}

{playbackData.map((item, index) => {
  return (
    <TouchableOpacity
      key={index}
      onPress={() => handleChangePlaybackRate(item.rate)}
      style={{
        marginHorizontal: 40,
        marginVertical: 10,
        backgroundColor: item.rate === playbackRate ? 'green' : 'white'
      }}
    >
      <Text>{item.label}</Text>
    </TouchableOpacity>
  )
})}

// Call the default playback rate function on component mount
useEffect(() => {
  handleDefaultPlaybackRate();
}, []);
