### ISSUE TITLE
[iOS] TrackPlayer.setRate() plays the loaded track

### ISSUE THREAD

**Issue by CapitanRedBeard** [react-native-kit/react-native-track-player#520]
When preparing an audio I have to call setRate anytime the audio changes because it resets the rate back to 1.0. This is fine because I can just keep a local value of what the playbackSpeed should be and then set this rate whenever a new track gets loaded via `handlePlaybackTrackChanged` event. 

However the problem is when I call `TrackPlayer.setRate(rate)` the audio will begin playing whatever is loaded which is not ideal. 

It would be ideal if I could just `TrackPlayer.setRate(rate)` and have it continue whatever playback state was happening before.
Right now the only way I can think of fixing this is to check if the state is playing, if it's not call `TrackPlayer.setRate(rate)` and then call `TrackPlayer.pause()` right after which messes up my playback execution and is unreliable since checking the state is asynchronous. 

@dcvz Do you know what is causing this? Is is similar to the issue we had earlier about adding tracks will play them automatically?

**Comment by brenwell** [comment]
This is likely because setting is rate is how you start and stop AVPlayer under the hood. If I remember correctly. 

E.g avplayer.setRate(0) is how you pause

Bee a while though. So I might be wrog

**Comment by computerjazz** [comment]
@brenwell  Your solution works for setting rate to 0, but not if I want to set the rate to anything else without audio starting.
