### ISSUE TITLE
removeUpcomingTracks() is not removing all tracks from the Queue [Android]

### ISSUE THREAD

**Issue by ntk860** [react-native-kit/react-native-track-player#523]
I am trying to remove all songs from the queue without firing any event. removeUpcomingTracks() does it, but is leaving the first song added. Is there any way that I can remove all songs from the queue with removeUpcomingTracks() ?

**Comment by Guichaguri** [comment]
`removeUpcomingTracks()`, as the name says, removes all tracks that are after the position of the current one.

If you want to remove all tracks, why not just `reset()` it?

**Comment by ntk860** [comment]
#519 asks that question as well.

Because reset() fires **playback-queue-ended** and **playback-track-changed** it gonna create an infinite loop because I keep track of my queue in **playback-queue-ended**

**Comment by ntk860** [comment]
Even by using `getQueue()` and looping the queue array then removing individually, its not working because remove() for some reason is not removing the items.

I am using version 1.1.3

**Comment by Guichaguri** [comment]
I'll be closing this one and keeping #519 instead, as `removeUpcomingTracks()` is working as expected.

**Comment by marister** [comment]
I temporarily solved my issue by listening to the event which has the param `position` and it is equal to `0`
