### ISSUE TITLE
Track Player can crash iOS app if empty array is supplied

### ISSUE THREAD

**Issue by hbarylskyi** [react-native-kit/react-native-track-player#526]
Hi. I experienced a bug today. This is strange, but it happens only in production mode for us (probably not related to the library). 

App crashes on iOS when empty array of tracks is supplied to `TrackPlayer.add()`. Here's a bigger snippet where it happened: 

 ```
 if (resetPlaylist) TrackPlayer.reset();
  return TrackPlayer.getQueue()
    .then(() =>
      TrackPlayer.add([]), // empty array for simplicity
    )
```

From what I found, it happens on line 93 of QueuedAudioPlayer.swift:
`try self.load(item: currentItem!, playWhenReady: playWhenReady)`. At the time of debugging this line in XCode I saw that currentItem was nil and playWhenReady was false.

**Comment by dcvz** [comment]
Fixed in commit: a99597c51c33b9118df6c432602c58300500c2c4
