### ISSUE TITLE
iOS updateMetadataForTrack error and how to fix

### ISSUE THREAD

**Issue by holospeed** [react-native-kit/react-native-track-player#538]
![IMG_2008](https://user-images.githubusercontent.com/3962013/56145803-45fd9500-5fa5-11e9-8f2c-11bcce8596c3.PNG)

The error:
The error caused by a wrong ObjC method name in the  RNTrackPlayerBridge.m file.

The fix:
At the line: 99 in  RNTrackPlayerBridge.m file change "withProperties" method name to "properties" method name.  

After the fix it is working as expected!

**Comment by ishigamii** [comment]
What was the version of the lib you were using ?

**Comment by holospeed** [comment]
1.1.4

**Comment by Guichaguri** [comment]
@holospeed can you open a pull request fixing the bug?
