### ISSUE TITLE
'AudioPlayerDelegate' is deprecated

### ISSUE THREAD

**Issue by appinteractive** [react-native-kit/react-native-track-player#539]
'AudioPlayerDelegate' is deprecated: Delegates will be removed in future versions of SwiftAudio. Use event handlers instead.

Using Target 10.0 for iOS

<img width="1251" alt="grafik" src="https://user-images.githubusercontent.com/432828/56140501-54df4a00-5f9b-11e9-8c78-932d668b6996.png">

**Comment by curiousdustin** [comment]
As of `v1.2.3` SwiftAudio is up to date. (`v0.11.2`)

This line no longer exists.
