### ISSUE TITLE
[Android] Error - No task registered for key TrackPlayer

### ISSUE THREAD

**Issue by jonanderdev** [react-native-kit/react-native-track-player#54]
I've started testing this library on Android and so far it works great.

I'm just having an issue that maybe is related to missing configuration on my part. 
But I've reading the documentation and followed all the steps indicated. Maybe you guys could point me in the right direction.

This error appears every time an action (play, pause, add tracks, ...) on the player is run.
Do you know what could be the reason?

`ExceptionsManager.js:65 No task registered for key TrackPlayer`

![error](https://user-images.githubusercontent.com/9866591/31388065-17b8150c-adcd-11e7-8ce0-afa333c38329.jpg)

Thanks in advance,
Jon.

**Comment by dcvz** [comment]
Do you have an event handler registered?

https://github.com/react-native-kit/react-native-track-player/wiki/API

**Comment by jonanderdev** [comment]
Thanks for the quick response @dcvz 
Yes I have it. But not sure if is in the correct place & the correct way.

Here i what I got:
```
AppRegistry.registerComponent('appname', () => App);

TrackPlayer.setupPlayer({}).then(() => {
  TrackPlayer.updateOptions({
    capabilities: [
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE
    ],
  });

  TrackPlayer.registerEventHandler(() => {
    return async (data) => {
      if (data.type == 'playback-state') {
        // Update the UI with the new state
      } else if (data.type == 'remote-play') {
        // The play button was pressed, we can forward this command to the player using
        TrackPlayer.play();
      } else if (data.type == 'remote-stop') {
        // The stop button was pressed, we can stop the player
        TrackPlayer.stop();
      } else if (data.type == 'remote-pause') {
        // The play button was pressed, we can forward this command to the player using
        TrackPlayer.pause();
      }
    };
  });
});
```

**Comment by Guichaguri** [comment]
You have to register the event handler right after registering the component with `registerComponent`
It would look like this:

```js
AppRegistry.registerComponent('appname', () => App);
TrackPlayer.registerEventHandler(() => {...});
```

Also, you're using the `dev` branch, right? We didn't pushed the new event handler to master/npm yet

**Comment by jonanderdev** [comment]
Yes I'm registering the event in the line below of `AppRegistry.registerComponent`. 
But you're right, I was using the master/npm branch not the `dev` one. That must be the reason why the event handler doesn't work.

But the issue is still there if I don't declare the handler. 
Is there a different way to declare the event handler for the current master version?

Thanks again for the response and the support. 
I'm really enjoying using this library. Great work guys!

**Comment by Guichaguri** [comment]
There is, you can use [registerHeadlessTask](https://facebook.github.io/react-native/docs/headless-js-android.html#the-js-api) on Android, something like this:

```js
AppRegistry.registerHeadlessTask('TrackPlayer', () => require('./player-handler.js'));
```

For iOS and Windows, you should use the `EventEmitter` from `TrackPlayer.eventEmitter.addListener('event-name', callback);`

**Comment by brenwell** [comment]
Hey guys, I need some help with this issue. I am using with the track player with redux so its not really practical to register the event handler before I have setup the store. But I think more importantly I don't really understand what is causing the error. Even if I don't register the event handler a all I still get this on any reload
