### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-999 "cancelled"

### ISSUE THREAD

**Issue by fcaride** [react-native-kit/react-native-track-player#541]
I have a url that returns a code 301 (redirect) with the url of the song. Using that link im not able to play the song. If the url is direct to the song it works fine. Im using a network inspector an the second url is never called.

this is my link:       "https://v23.musuy.com/servlet/com.musuy.musweb.agetstream?/jHtnqj4WR2b7xcC5jE4gwGJsPt5jCZAoxctYaMI0CBBIk55Lg/T9BwZeACkwvsgaTqDBURqSrmIhwN3Jrc5QP06/zdovRcOeP68eWFFoE3hJd8%2BjkvAw3Sr%2B7YPfwl/";

If i use this link in the AVPlayer of AVFoundation in IOS it works perfectly.
I saw the other issue with the code 302 but it was with an http request not https, i allowed arbitrary loads anyways but it didnt change nothing.

Do i have to do something in special?

**Comment by bishnudev** [comment]
the second url itself doesn't serve any media file

**Comment by fcaride** [comment]
Yes it does, the generated url (the second one) can only be used one time. If you try that url in the browser it wont work because it make the request 2 times. If you try it out in any player it works.

**Comment by fcaride** [comment]
To add more info im getting this in the console:

player[37893:3340017] Task <3DD9395D-9C9F-475F-B0C9-1AF454EC8E4B>.<1> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://v20.musuy.com/servlet/com.musuy.musweb.agetstream?Cs9PuwKuD8aMbQ67Hg9UZ1Z+sWbQ3xVr+hZSffqhG8kEzXhTRx1kZ7n81pjp+apGZB4BPWEoe8Y4RuabK8P/ydCJMi0Uh13KBjJGOuEDOds91jvScIsWG3LhWwVDF11o, NSErrorFailingURLKey=https://v20.musuy.com/servlet/com.musuy.musweb.agetstream?Cs9PuwKuD8aMbQ67Hg9UZ1Z+sWbQ3xVr+hZSffqhG8kEzXhTRx1kZ7n81pjp+apGZB4BPWEoe8Y4RuabK8P/ydCJMi0Uh13KBjJGOuEDOds91jvScIsWG3LhWwVDF11o, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <3DD9395D-9C9F-475F-B0C9-1AF454EC8E4B>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3DD9395D-9C9F-475F-B0C9-1AF454EC8E4B>.<1>, NSLocalizedDescription=cancelled} [-999]

**Comment by fcaride** [comment]
Im trying with a direct url of 7Digital that works in the browser and im getting the same error and no audio

**Comment by fcaride** [comment]
I've tried in Android and it works perfectly with that link. And added an AVPlayer implementation into this project and it works well too (So there is no problem with the plist configuration).  
Sorry for spamming i just want to help adding information because i really want to use this library in my project. :)

**Comment by fcaride** [comment]
It was a problem with encoding the url if you look is different the url i provided with the url of the log output. I created another issue related to this. Thanks  #564

**Comment by mrigo** [comment]
Hi,
I have the same error with a supernormal URL:
https://www.myserver.com/audio/7
this URL is a PHP page that checks the auth token and then respond with the file or with an error.
Calling the URL with Postman or with Axios inside the app, all works fine, but with this library I've -999 code error...
I've added all headers required but the request doesn't even reach the server, it's cancelled before doing the request.
Any advise?

**Comment by fcaride** [comment]
That url says me this: 
This site can’t be reachedwww.myserver.com’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by mrigo** [comment]
Yes, the host is obviously a fake URL to not show you my real server address :) but the /audio/7 is correct.
It's my client's site so I can't write it in clear right now.

**Comment by fcaride** [comment]
In my case all the %2  were encoded by the lib so it was reaching a diferent url. I dont know your url though
