### ISSUE TITLE
[iOS] url decoding issue

### ISSUE THREAD

**Issue by kevex91** [react-native-kit/react-native-track-player#543]
Issue: When I load urls containing '%2F'. This gets converted to '/' when the track is loaded.

This is an example url: https://firebasestorage.googleapis.com${ourEndpoint}o/tracks%2F6bd9a8b7-4998-49c6-a86f-f747dd8fad9.mp3?alt=media&token=78a05743-862-4ddb-bce-d9797eb91bb

Firebase storage uses '%2F' 🤷‍♂️ to define a path into a folder. Seems related to #40 and #44 .

This is what the track player attempts to play:
https://firebasestorage.googleapis.com${ourEndpoint}o/tracks/6bd9a8b7-4998-49c6-a86f-f747dd8fad9.mp3?alt=media&token=78a05743-862-4ddb-bce-d9797eb91bb

This results in: load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled"

**Comment by AylanBoscarino** [comment]
I'm having the same issue. Is there a solution?

**Comment by rkbhochalya** [comment]
I'm having this issue as well.

**Comment by kevex91** [comment]
temporary fix, replace code in this file:

<img width="1512" alt="Screenshot 2019-06-04 at 9 30 48 AM" src="https://user-images.githubusercontent.com/20353382/59817836-140b0500-933f-11e9-9b6a-ed5788d47023.png">


```
//
//  MediaURL.swift
//  RNTrackPlayer
//
//  Created by David Chavez on 12.08.17.
//  Copyright © 2017 David Chavez. All rights reserved.
//

import Foundation

struct MediaURL {
    let value: URL
    let isLocal: Bool
    private let originalObject: Any
    
    init?(object: Any?) {
        guard let object = object else { return nil }
        originalObject = object
        
        if let localObject = object as? [String: Any] {
            let uri = localObject["uri"] as! String
            isLocal = uri.contains("http") ? false : true
            let encodedURI = uri.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!
            value = URL(string: encodedURI.replacingOccurrences(of: "file://", with: ""))!
        } else {
            let url = object as! String
            isLocal = url.lowercased().hasPrefix("file://")
            value = URL(string: url.replacingOccurrences(of: "file://", with: ""))!
        }
    }
}

```

**Comment by kevex91** [comment]
I see that this "fix" was done a few years ago and then reverted.

I would suggest allowing to disable it with a parameter in config. @dcvz

**Comment by kevex91** [comment]
Hey @Guichaguri , could we test and merge this: https://github.com/react-native-kit/react-native-track-player/pull/631
