### ISSUE TITLE
`http` request not allowed?

### ISSUE THREAD

**Issue by sideokyou** [react-native-kit/react-native-track-player#551]
Hi,

I am currently building an app for streaming audio. 
It works both iOS and Android. but Only Samsung Galaxy S10 is not working. 

The streaming URL starts with `http://example.com/mp3`, not `https://example.com/mp3` 
I also found that even images from server provide HTTP URL, this device didn't render it.

So, is there any method or props that enabling HTTP request? (not https).

Here is the log 

```
04-19 17:53:34.782  8066 12067 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-19 17:53:34.793  8066 12007 E ExoPlayerImplInternal: Source error.
04-19 17:53:34.793  8066 12007 E ExoPlayerImplInternal: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://my-streaming-url.com
```

**Comment by Guichaguri** [comment]
Can you send us which URL are you trying to play? Which Android version is not working? Which version is your app targeting?

**Comment by puckey** [comment]
This is most probably caused by https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by Guichaguri** [comment]
Unfortunately, Android 8+ only allows secure requests by default. Either use the workaround from @puckey link or start using SSL in your backend.

SSL these days are not hard to get at all, [CloudFlare](https://www.cloudflare.com/) is pretty easy to plug in, or you can use a non-proprietary solution such as [Let's Encrypt](https://letsencrypt.org/)
