### ISSUE TITLE
Could not find support-media-compat.jar (com.android.support:support-media-compat:28.0.0)

### ISSUE THREAD

**Issue by ilkhanihosein** [react-native-kit/react-native-track-player#554]
hello my friends , please help me , i has this error 
Could not find support-media-compat.jar (com.android.support:support-media-compat:28.0.0).
  Searched in the following locations:
      https://dl.google.com/dl/android/maven2/com/android/support/support-media-compat/28.0.0/support-media-compat-28.0.0.jar
but not found this file

**Comment by Guichaguri** [comment]
This happens because Google discontinued the support lib from API level 28. We'll have to update it to the new `androidx` libraries.

For now you can target API 27, using an older React Native version.

**Comment by Guichaguri** [comment]
Should be fixed in 6471be68dfc772bc3f94ad74d74455902651a7c8

**Comment by sootood** [comment]
hi RN: 0.59.8 
has this issue

**Comment by Guichaguri** [comment]
Update the module to the latest dev branch.
