### ISSUE TITLE
Adding interval functionality

### ISSUE THREAD

**Issue by NagashreeMeda** [react-native-kit/react-native-track-player#556]
Is there any way for us to have 2 instances of trackplayer? I'm working on adding interval functionality where I play bell sound or some alert track at some intervals.

Any help??

**Comment by Guichaguri** [comment]
No, since this is a music/podcast dedicated module, this won't be a good solution if you want to play sound effects, the module won't allow you to play more than one track at the same time. I suggest you use `react-native-sound` for this kind of functionality.

**Comment by NagashreeMeda** [comment]
Got it!! Thanks @Guichaguri
