### ISSUE TITLE
SeekTo restarts track

### ISSUE THREAD

**Issue by galizhan** [react-native-kit/react-native-track-player#558]
So seekTo is restarting my audio to 0. When I am calling current position it is also 0. However ProgressComponents position is not 0.

**Comment by Guichaguri** [comment]
Which platform?

**Comment by galizhan** [comment]
Android natively running @Guichaguri

**Comment by galizhan** [comment]
I want add that when I am using async/await syntax position is ok, however in terms of Promise by then and catch it is 0. Also my duration is 0, despite of I added it by my self at trackinfo. Could it be because of duration is 0?

**Comment by Guichaguri** [comment]
Tell me more about the track. It is from the network? If it is, does the server accepts range requests?

**Comment by galizhan** [comment]
@Guichaguri ok, so it is on my laptop, and I just requiring it in url as in example at Getting started.

**Comment by Guichaguri** [comment]
Can you upload the file somewhere so I can take a look?

**Comment by galizhan** [comment]
https://drive.google.com/file/d/1QuXDQMAuEYwJjqGJzXl5i481_X2uIGGs/view?usp=sharing @Guichaguri

**Comment by galizhan** [comment]
@Guichaguri Have you opened and tested?

**Comment by mcgomez** [comment]
@Guichaguri Have you had a chance to look into this issue? I'm also experiencing this. The tracks we use are from a server, however seeking on iOS works fine.

**Comment by raaannzzz** [comment]
seekTo does not work in android, i use the track from the example folder

https://drive.google.com/uc?export=download&id=1AjPwylDJgR8DOnmJWeRgZzjsohi-7ekj

**Comment by edem98** [comment]
I am facing the same for one week now. I am playing the track from the bundle. TrackPlayer.getPosistion() return 0 after a call to seekTo.
Does anyone find a solution to this problem ?

**Comment by felix-voicehub** [comment]
What we have figured out is that seeking, at least right after calling `.play()` needs to be different for each platform.

On Android you can just call them after each other:
```
await TrackPlayer.play();
await TrackPlayer.seekTo(whatever);
```

On iOS however, this won't work, it will always play from the start, so use an Event Listener:

```
	TrackPlayer.addEventListener('playback-state', async (stateObject) => {
		if (stateObject.state === TrackPlayer.STATE_PLAYING ) {
			await TrackPlayer.seekTo(snippet.start);
		}
	});
	await TrackPlayer.play();
```

**Comment by edem98** [comment]
Thanks

**Comment by Guichaguri** [comment]
The original issue seems to be related to [unseekable tracks](https://exoplayer.dev/troubleshooting.html#why-are-some-media-files-not-seekable).

The latter one will be fixed by #713

**Comment by gbalduzzi** [comment]
Hi everyone, 

unfortunately the solution provided by @fritzfr does not work for me, because I experience the problem on android and not on iOS.

I am trying to implement the jump backward/jump forward functionality. In my service I registered:

```
TrackPlayer.addEventListener('remote-jump-backward', (data) => {
    let seconds = data.interval ? data.interval : data // on Ios I get the seconds, while on android i get an object with the interval property
    console.log('backward', seconds)
    TrackPlayer.getPosition().then((current) => {
      console.log('current position', current)
      console.log('seeking to', Math.round(current) - seconds)
      TrackPlayer.seekTo(Math.round(current) - seconds)
        .then(() => console.log('seeked properly'))
        .catch((err) => console.warn('error seeking', err))
    })
  })
```

When I press the jump backward button on Android, the logs are correct:

```
LOG backward 10
LOG current position 16.118
LOG seeking to 6
LOG seeked properly
```

But the track starts again from 0, instead of the selected seconds (6 in the example). The same track and the same method on iOS works perfectly

**Comment by t-tornado** [comment]
Is there a work around for this problem? The developers should come up with something for us cause seeking is an important feature in a player.

**Comment by Strate** [comment]
I'm facing exactly same issue. However, using react-native-video component for playing audio tracks works fine on android, but react-native-track-player restarts from 0.

**Comment by Strate** [comment]
Seems like I found a way to fix it. Check out the patch

```
diff --git a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/models/Track.java b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/models/Track.java
index 543f6bc..dc74d43 100644
--- a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/models/Track.java
+++ b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/models/Track.java
@@ -8,6 +8,7 @@ import android.support.v4.media.MediaMetadataCompat;
 import android.support.v4.media.RatingCompat;
 import android.support.v4.media.session.MediaSessionCompat.QueueItem;
 import com.google.android.exoplayer2.extractor.DefaultExtractorsFactory;
+import com.google.android.exoplayer2.extractor.mp3.Mp3Extractor;
 import com.google.android.exoplayer2.source.MediaSource;
 import com.google.android.exoplayer2.source.ProgressiveMediaSource;
 import com.google.android.exoplayer2.source.dash.DashMediaSource;
@@ -179,7 +180,8 @@ public class Track extends TrackMetadata {
                 return createSsSource(ds);
             default:
                 return new ProgressiveMediaSource.Factory(ds, new DefaultExtractorsFactory()
-                        .setConstantBitrateSeekingEnabled(true))
+                        .setConstantBitrateSeekingEnabled(true)
+                        .setMp3ExtractorFlags(Mp3Extractor.FLAG_ENABLE_CONSTANT_BITRATE_SEEKING & Mp3Extractor.FLAG_ENABLE_INDEX_SEEKING))
                         .createMediaSource(uri);
         }
     }
```

**Comment by AjayParambath** [comment]
I'm still facing this issue.
Not only does seekTo(position) does not work(it starts from 0 like others have already mentioned), but getDuration method also gives 0. 
I tried using the useProgress hook and I can get position finely with getPosition/ useProgress.position. 
but useProgress duration returns 0.

please do something about duration and seekTo

**Comment by RohitDhingra0786** [comment]
@jspizziri Any update on this
