### ISSUE TITLE
getVolume always returns 1

### ISSUE THREAD

**Issue by NagashreeMeda** [react-native-kit/react-native-track-player#559]
TrackPlayer.getVolume() always returns 1, even if i mute and then play.

**Comment by Guichaguri** [comment]
`getVolume` returns the volume of the player, not the OS volume, so it will always be 1 unless you update it with `setVolume`.

**Comment by NagashreeMeda** [comment]
Okay, is there anyway for us to get access to OS volume?

**Comment by Guichaguri** [comment]
Not with react-native-track-player. But you can use [react-native-system-setting](https://github.com/c19354837/react-native-system-setting) for that.
