### ISSUE TITLE
URL encoding problem

### ISSUE THREAD

**Issue by fcaride** [react-native-kit/react-native-track-player#564]
# Configuration

 React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 477.41 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
# Issue

Before all thanks for this library its really good :)
I have a url with percentages and the library is changing it. This only happens in IOS. In Android works fine.
I have figured out its the MediaURL class that is encoding the url removing the percentages. If it is important to encode it maybe add an option to not encode or something? Ill be happy to do the changes if you want

Thanks!

**Comment by sideokyou** [comment]
Check your URL or any files from a server. If it contains letters other than English, it might cause an issue. 

For me, my URL contained other language letters. after changing all to English, it works fine.

**Comment by fcaride** [comment]
My url comes with '%' caracters from a external server and if i encode the url it doesnt get processed by the server. I need the librery to not encode the url in order to work :(
