### ISSUE TITLE
File system playing

### ISSUE THREAD

**Issue by msabaeian** [react-native-kit/react-native-track-player#57]
hi
i placed an mp3 file in music directory `storage/emulated/0/Music/music.mp3` and use `file://` prefix for load this but it doesn't work (shows in notificationbar but not playing)
code:
```
await TrackPlayer.add({
      id: 'track',
      url: 'file://storage/emulated/0/Music/music.mp3',
      title: 'Despacito gg',
      artist: 'Luis Fonsi Feat. Daddy Yankee',
      artwork: 'http://images-eu.ssl-images-amazon.com/images/I/61JH2ggghmL._AC_US160_.jpg'
});
TrackPlayer.play();
```

whats wrong?

**Comment by Guichaguri** [comment]
You're on Android, right?

**Comment by msabaeian** [comment]
@Guichaguri yes

**Comment by Guichaguri** [comment]
@msabaeian Just tested here, and it works for me.
Try which three slashes, like so: `file:///storage/emulated/0/Music/music.mp3`

**Comment by ShumGG** [comment]
@Guichaguri im trying with three slashes and it doesnt work:

```
`await TrackPlayer.add([{
            id: "1",
            url: "file:///storage/emulated/0/Downloads/music/Yummy.mp3",
            title: "Yummy",
            artist: "Justin Bieber"
        }]);
        
        TrackPlayer.play();`
```

**Comment by ajoykarmakar** [comment]
Yes local mp3 not playing with /// or with this //. Did anyone found solution?

**Comment by ShumGG** [comment]
@ajoykarmakar yes, if you are using it in Android X, allow permissions first, read external and edit external storage then add in AndroidManifest in application this: `android:requestLegacyExternalStorage="true"`

**Comment by musabgulfam** [comment]
Not working for me either.

**Comment by musabgulfam** [comment]
await TrackPlayer.add({
        id: 'trackId',
        url: "https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_2MG.mp3",
        title: 'Track Title',
        artist: 'Track Artist',
    });

    // Start playing it
  await TrackPlayer.play()

**Comment by musabgulfam** [comment]
```
await TrackPlayer.add({
        id: 'trackId',
        url: "https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_2MG.mp3",
        title: 'Track Title',
        artist: 'Track Artist',
    });

    // Start playing it
  await TrackPlayer.play()
```

**Comment by musabgulfam** [comment]
```
await TrackPlayer.add({
        id: 'trackId',
        url: "file:///data/user/0/com.riderguide/files/1.mp3",
        title: 'Track Title',
        artist: 'Track Artist',
    });

    // Start playing it
  await TrackPlayer.play()
```
