### ISSUE TITLE
Livestream doesn't work

### ISSUE THREAD

**Issue by SergiOnGit** [react-native-kit/react-native-track-player#578]
### Configuration

Run react-native info in your project and share the content.

```
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 8.27 GB / 15.89 GB
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501
```

What react-native-track-player version are you using?
1.1.4

"react": "16.8.3",
"react-native": "0.59.5"

Platform: android

### Issue

Hi everyone,

I am building livestream app and trying this module. It plays well when stream has fixed time for example this url: https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8 but when it is livestream with no time it doesn't work. I tried lots of configurations but none worked. Can anyone help? It doesn't play this url: https://tv.cdn.xsg.ge/cld9-0386/fortuna/index.m3u8

error message

```
code: "playback-source"
message: "Unable to connect to https://tv.cdn.xsg.ge/cld9-0386/fortuna/index.m3u8"
```

### Code

```
TrackPlayer.setupPlayer().then(async () => {

            // Adds a track to the queue
            await TrackPlayer.add({
                id: '1',
                url: 'https://tv.cdn.xsg.ge/cld9-0386/fortuna/index.m3u8',
                type: 'hls',
                contentType: 'application/vnd.apple.mpegurl',
                title: 'Title',
                artist: 'Artist',
                artwork: 'https://www.howtogeek.com/wp-content/uploads/2018/09/xvac_lede.png.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.e3upAKG0Zg.jpg'
            });
        
            // Starts playing it
            TrackPlayer.play();
        
        });
```

**Comment by Guichaguri** [comment]
We don't have a <Video> component. Is that from `react-native-video` or a custom built component? If it is a custom one, can you send the code from that so we can look what is not working?

**Comment by SergiOnGit** [comment]
> We don't have a `<Video>` component. Is that from `react-native-video` or a custom built component? If it is a custom one, can you send the code from that so we can look what is not working?

Sorry, somehow i pasted incorrect code. Now it's fixed.

**Comment by SergiOnGit** [comment]
@Guichaguri I changed https to http and now it works. Is this normal? Also one problem i noticed is that sometimes default background controls doesn't work. Then i close app open again and it works. Can this happen in production app too?
