### ISSUE TITLE
How to  realize the Player mode (Repeat, Repeat all, Shuffle)

### ISSUE THREAD

**Issue by Goodem** [react-native-kit/react-native-track-player#585]
# Configuration

The latest version of `react-native-track-player` 

# Issue
How to  realize the Player mode (Repeat, Repeat all, Shuffle)

**Comment by LiWeiQiangAndroid** [comment]
android see: https://medium.com/google-exoplayer/repeat-modes-in-exoplayer-19dd85f036d3

setRepeatMode
and
setShuffleModeEnabled

**Comment by Guichaguri** [comment]
It's not implemented at the moment. We do plan to add it in the near future.

Duplicate of #122

**Comment by LiWeiQiangAndroid** [comment]
I've implemented it, but there seems to be a bug

**Comment by Mangirish-Bhagat** [comment]
@LiWeiQiangAndroid  can you share the implimented code? or share the logic here of how you've implimented it ?
