### ISSUE TITLE
Ready Constant has value undefined [ANDROID]

### ISSUE THREAD

**Issue by ntk860** [react-native-kit/react-native-track-player#587]
@Guichaguri constant STATE_READY has the value undefined instead of a number.

**Comment by Guichaguri** [comment]
Fixed in 2b4dfa4a20943e5ac619dcf9d4bab346a8931ed0

**Comment by mitchdowney** [comment]
@Guichaguri I just wanted to confirm, so Android does not have a true READY state, but iOS does? I notice in your commit that READY and PAUSE are both equal to 2.

**Comment by HessiPard** [comment]
> @Guichaguri I just wanted to confirm, so Android does not have a true READY state, but iOS does? I notice in your commit that READY and PAUSE are both equal.
> 
> Also, I see a value of `state === 8` in the playback-state event on Android, but there does not seem to be a TrackPlayer.STATE_ value that corresponds with 8. What does 8 represent?

Its [STATE_CONNECTING](https://developer.android.com/reference/android/support/v4/media/session/PlaybackStateCompat.html#STATE_CONNECTING)
