### ISSUE TITLE
iOS background mode issue on 11

### ISSUE THREAD

**Issue by reactbreainbuddy** [react-native-kit/react-native-track-player#59]
I am not able to play audio in background mode though I have enabled background Modes . Here is my code: 
    constructor (props){
        super(props)
        this.state = {
            duration1:0,
            currentTime1:0
        }
    }

    async setPlayer(){

        debugger
        var track = {
            id: '01',

            url: 'file:///Users/itilak/Documents/myMusic/goriRadha.mp3', // Load media from the network
            // url: require('./avaritia.mp4'), // Load media from the app bundle

            title: 'Avaritia',
            artist: 'deadmau5',
            album: 'while(1<2)',
            genre: 'Progressive House, Electro House',
            date: '2014-05-20T07:00:00+00:00', // RFC 3339

            artwork: 'https://is5-ssl.mzstatic.com/image/thumb/Music/v4/57/0e/87/570e87b0-d994-97f9-e5bd-8428d8753be3/886444175029.jpg/1200x630bb.jpg', // Load artwork from the network
            // artwork: require('./avaritia.jpg'), // Load artwork from the app bundle
        };
        await TrackPlayer.add(track);

        // Starts playing it
        TrackPlayer.play();
        this.setTimer()
    }
    async setNewPlayer(){
        TrackPlayer.setupPlayer({}).then(() => {

            let p = this.setPlayer()
            TrackPlayer.updateOptions({
                capabilities: [
                    TrackPlayer.CAPABILITY_PLAY,
                    TrackPlayer.CAPABILITY_PAUSE
                ],
            });
        })
    }
    getCurrentTime = () => {
        console.log("aasdasdasd")
        let audioDuration = 0;
        TrackPlayer.getDuration().then((duration) => {
            if (duration) {
                audioDuration = duration;
            }
        });
        TrackPlayer.getPosition().then((currentTime) => {
            if (currentTime) {
                this.setState({currentTime1: currentTime, duration1: audioDuration});
                console.log("Current: ",currentTime)
                console.log("Duration: ",audioDuration)
            }
        });
    };

    setTimer() {
        let interval1Id =  setInterval(() => {
            this.getCurrentTime()
        }, 1000);
        this.setState({
            interval1Id: interval1Id,
        });
    }
    clearTimer() {
        if(this.state.interval1Id != null) {
            clearInterval(this.state.intervalId);
        }
    }
    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.welcome} onPress={() => {
                    let playing=this.setNewPlayer()
                }}>
                    set Player!
                </Text>
                <Text style={styles.instructions} onPress={() => {
                    Alert.alert("set timer")
                    TrackPlayer.play()
                    this.setTimer()
                }}>
                    Play Audio
                </Text>
                <Text style={styles.instructions} onPress={() => {

                    TrackPlayer.pause()
                }}>
                    Pause Audio
                </Text>
                <Text style={styles.instructions} onPress={() => {

                    TrackPlayer.reset()
                }}>
                    Reset Audio
                </Text>
                <Text style={styles.instructions}>
                    {"Current:"+this.state.currentTime1}
                </Text>
                <Text style={styles.instructions}>
                    {"Duration:"+this.state.duration1}
                </Text>
            </View>
        );
    }
}

**Comment by jasongrishkoff** [comment]
So it plays fine when the app is focused, but as soon as you background it the music stops playing?

**Comment by reactbreainbuddy** [comment]
yes

**Comment by reactbreainbuddy** [comment]
I have enable background mode for iOS too

**Comment by anitalanet** [comment]
Yes @jasongrishkoff , I have also enabled background mode for ios.
![screen shot 2017-10-12 at 11 20 54 am](https://user-images.githubusercontent.com/9551704/31481248-0615058e-af40-11e7-8268-0ff2f8c24ce5.png)

**Comment by jasongrishkoff** [comment]
Is this on Simulator or on a device?  Have you tried with a remote URL for the song?  Same result?

**Comment by anitalanet** [comment]
simulator, I have also tried with remote url

**Comment by anitalanet** [comment]
@jasongrishkoff, Is your audio is playing on background on iOS?

**Comment by jasongrishkoff** [comment]
Yes, I'm using remote URLs and it works fine on both simulator and device.  Are you working from the dev branch or the master branch?

**Comment by anitalanet** [comment]
dev branch, can you please help me with the small demo for iOS?

**Comment by dcvz** [comment]
Does the file play in foreground?
You're setting up the player in your `render()` I don't think that's very wise as you'll be setting it up every single time you call render (change state). It could be that's your problem.

**Comment by anitalanet** [comment]
Yes my player is playing perfectly in foreground, just stops when it comes to background and I am setting up the player onPress of the text. It is just random code so it is messy.sorry on that!

**Comment by dcvz** [comment]
do you have this on a Github repository? Want to share it?

**Comment by anitalanet** [comment]
yes sure you can check demo: https://github.com/anitalanet/trackPlayer.git

Please,
It will be grateful if you can help me with this.

**Comment by anitalanet** [comment]
Hi Guys, any luck on this? I really need help with this

**Comment by anny1895** [comment]
I am also getting the same issue on iOS 11..my code was working file with another library for music controls...as I updated my OS and xcode it doesn't supporting audio in background now.. seems to have problem with iOS11.
@dcvz and @jasongrishkoff , Have you people done anything else escape enable background mode???

**Comment by peterlazar1993** [comment]
@reactbreainbuddy @anny1895 @dcvz @jasongrishkoff This is probably related to https://stackoverflow.com/questions/46601068/backgound-audio-not-working-in-ios10-ios11-on-simulator

**Comment by dcvz** [comment]
It seems to work on devices, and given the thread linked by @peterlazar1993 it should be fixed in the 11.2. I will now close this issue.
