### ISSUE TITLE
Error: Given track ID was not found in queue

### ISSUE THREAD

**Issue by ithustle** [react-native-kit/react-native-track-player#591]
# Configuration

React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
      Memory: 814.81 MB / 11.60 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.8 => 0.59.8 

# Issue

Maybe I missed undestood about this functions `add(tracks, insertBeforeId)`, but its supposed the second song of my array object start to play in first place or am I wrong? 

# Code

```
const tracks = [
{
    id: "1002",
    url: "https://url_song",
    title: "Awesome music",
    artist: "Artist name",
    album: "Best album",
    artwork: "https://cover_url"
},
{
    id: "1003",
    url: "https://url_song",
    title: "Awesome music",
    artist: "Artist name",
    album: "Best album",
    artwork: "https://cover_url"
},
];

TrackPlayer.add(tracks, tracks[1].id);
```

**Comment by brenwell** [comment]
If I understand your question correctly then yes you have misunderstood. 

Firstly add doesn’t play. 
Secondly insertById doesn’t skip, skip does

What you want is: 

Trackplayer.add(tracks)
Trackplayer.skip(tracks[1].id)
Trackplayer.play()

The second param of add indicates where to add the new tracks in the existing queue

**Comment by ithustle** [comment]
@brenwell, you rock.

**Comment by Sandeep155Vibhuti** [comment]
![Screenshot 2020-12-12 at 11 54 14 PM](https://user-images.githubusercontent.com/75908175/101991862-64b1b300-3cd5-11eb-97ca-c8c41d537abb.png)
I also get this Issue than I want to Play the PlayList of the Local Files in IOS.
