### ISSUE TITLE
android -  should only request audio focus when actually playing sound

### ISSUE THREAD

**Issue by gaodeng** [react-native-kit/react-native-track-player#593]
currently, even adds a track to queue,TrackPlayer will request audio focus which makes other audio app stops playing.

**Comment by Guichaguri** [comment]
Can you send your JS code that is causing the problem?

The module only [requests focus when it starts playing](https://github.com/react-native-kit/react-native-track-player/blob/dev/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java#L141).

**Comment by gaodeng** [comment]
@Guichaguri  await TrackPlayer.add(tracks)
![屏幕快照 2019-05-20 上午7 34 36](https://user-images.githubusercontent.com/1118249/57989728-c7c76d80-7ad1-11e9-8c49-7419cd906ba5.png)

**Comment by Guichaguri** [comment]
That doesn't really help, I need the full code to investigate what is going wrong.
If you don't want to share your app's code, at least create a reproducible copy so we can test it out.

**Comment by gaodeng** [comment]
@Guichaguri  I will create a repositionry to reproduc it later.
This problem is obvious . 
add a breakpoint here.
 https://github.com/react-native-kit/react-native-track-player/blob/0f411baf0c8b21184d4585c9515d805798b0a244/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java#L141

```
TrackPlayer.add(tracks) 
```
 will trigger the breakpoint

**Comment by gaodeng** [comment]
@Guichaguri  here is the  repositionry
https://github.com/gaodeng/RNTrackPlayerBug

**Comment by ntk860** [comment]
This is also happening to me. Song stops for no reason or without any prior action.

**Comment by ntk860** [comment]
This is related to #374. Its happening exactly the same way.

**Comment by Guichaguri** [comment]
Ok, figured it out. This issue was caused by #499 and should be fixed by 4cd43f20bbbf772248280d046832a49f9e021ebd

**Comment by gaodeng** [comment]
it's not fixed,please reopen this.
