### ISSUE TITLE
Casting on iOS and Windows

### ISSUE THREAD

**Issue by Guichaguri** [react-native-kit/react-native-track-player#60]
Currently, casting is only supported through Android with Google Cast devices

* The official [Cast SDK](https://developers.google.com/cast/docs/ios_sender_integrate) can be integrated on iOS for Google Cast support.
* [AirPlay](https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/AirPlayGuide/Introduction/Introduction.html) can also be integrated on iOS.
* The official [Casting Namespace](https://docs.microsoft.com/en-us/uwp/api/windows.media.casting) can be integrated on Windows for Miracast, DLNA, and Bluetooth support.
* [SharpCaster](https://github.com/Tapanila/SharpCaster) can be integrated on Windows for Google Cast support.

It might be a better idea to move the cast integration to another module (an "addon module") for various reasons, what do you think?

**Comment by peterlazar1993** [comment]
IMO casting should be an add-on module.

**Comment by Guichaguri** [comment]
Yes, we've already discussed about splitting features like this into an add-on module, and we will.

**Comment by Guichaguri** [comment]
This issue don't belongs to this project anymore. The cast integration is being moved to [react-native-track-casting](https://github.com/react-native-kit/react-native-track-casting)
