### ISSUE TITLE
iOS: Build failed

### ISSUE THREAD

**Issue by marksturm** [react-native-kit/react-native-track-player#61]
I tried to us this but i cant build a app cause of this:

  override func constantsToExport() -> [String: Any] { !! Overriding method with selector 'constantsToExport' has incompatible type '() -> [String : Any]'

in

https://github.com/react-native-kit/react-native-track-player/blob/dev/ios/RNTrackPlayer/RNTrackPlayer.swift

using: xcode Version 9.0 (9A235)

**Comment by pmagnussen** [comment]
+1

**Comment by Guichaguri** [comment]
Can you try the solution from #27?

**Comment by moduval** [comment]
I got the same error on xcode version 9.0

**Comment by Guichaguri** [comment]
cc @dcvz

**Comment by olivierlesnicki** [comment]
+1

**Comment by jpgarcia** [comment]
Hi guys, I'm using the latest version `0.2.0` and it still doesn't work. I'm using xCode 9 and I'm getting the following error:

`library not found for -lswiftCoreAudio for architecture x86_64`

any clue?

**Comment by moduval** [comment]
Hi,

You need to use the solution from #27. This solution should definetly be documented in readme.

**Comment by jpgarcia** [comment]
I was just about to write the same! fixed it with the `dummy.swift` solution!

thank you!
