### ISSUE TITLE
usePlaybackState is not function

### ISSUE THREAD

**Issue by briansamuel** [react-native-kit/react-native-track-player#622]
I have problem when get playbackState.
This is my code 

`import TrackPlayer, { usePlaybackState } from 'react-native-track-player';

  const playbackState = usePlaybackState();`

**Comment by Guichaguri** [comment]
`usePlaybackState` is a recent feature which has not been released yet. You'll not be able to use it just yet unless you're in the [latest dev branch](https://react-native-kit.github.io/react-native-track-player/install/#unstable).

**Comment by jandog8990** [comment]
May I ask why you have it in the example/ in the master branch if it uses dev modules and functions? @Guichaguri

**Comment by Guichaguri** [comment]
This issue is quite old, and it has been released in 1.1.6 and newer.

**Comment by jandog8990** [comment]
@Guichaguri I'm using 1.1.8 and I'm still getting this error, can you explain? Thank you.

**Comment by emrepirnaz** [comment]
@jandog8990 +1

**Comment by mmrk09** [comment]
@jandog8990 +1

**Comment by mortezacruise** [comment]
100% guaranteed  way to solve this issue is  :
use like this "TrackPlayer.usePlaybackState() " instead of  "import Trackplater ,{usePlaybackState}"
it is all.

**Comment by CHALLARAKESHREDDY** [comment]
ERROR  TypeError: _reactNativeTrackPlayer.default.usePlaybackState is not a function (it is undefined)
