### ISSUE TITLE
Submodule use breaks npm dependency use from github

### ISSUE THREAD

**Issue by mhabegger** [react-native-kit/react-native-track-player#624]
When linking the react-native-track-player as github npm (`github:react-native-kit/react-native-track-player#dev`) as described in the documentation, the recent change to submodule use for ios Vendor. See: https://react-native-kit.github.io/react-native-track-player/install/#unstable

Breaking Commit: https://github.com/react-native-kit/react-native-track-player/commit/da407573456c71338b8e11c132844e4ac9b1cc0f

# Configuration

Add dependency `npm install --save "react-native-kit/react-native-track-player#dev"` to the project
Run build `react-native run-ios` and wait for failure

# Issue

When used as github dependency the directory `node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer` stays empty and build fails with:

```
error: Build input files cannot be found: '/Users/[...]/node_modules/react-native-track-
player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/AVPlayerWrapper/
AVPlayerWrapperDelegate.swift', '/Users/[...]/node_modules/react-native-track-
player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/QueueManager.swift', 
'/Users/[...]/node_modules/react-native-track-
player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/TimeEventFrequency.swift',
```

**Comment by mhabegger** [comment]
It seems that it works with
```
npm install
```
rather than
```
yarn install
```

Anyone familiar with submodule checkout on npm vs. yarn ?

**Comment by biomancer** [comment]
This is ongoing issue in yarn https://github.com/yarnpkg/yarn/issues/1488
