### ISSUE TITLE
[Android]Change icon play, pause in Player when click play, pause in notification miniPlayer

### ISSUE THREAD

**Issue by briansamuel** [react-native-kit/react-native-track-player#627]
`this.state = {
      status: 'play',
      duration: 0,
      position: 0,
      seek: 0,
      isSeeking: false,
      Detail: [],
    };`

This is my state;
How to i can change status to play or pause, when i click play or pause in notification miniPlayer.
`componentWillMount() {
    
    TrackPlayer.updateOptions({
       stopWithApp: true,
       capabilities: [
         TrackPlayer.CAPABILITY_PLAY,
         TrackPlayer.CAPABILITY_PAUSE,
         TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
         TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
       ],
       compactCapabilities: [
         TrackPlayer.CAPABILITY_PLAY,
         TrackPlayer.CAPABILITY_PAUSE
       ]
     });
   const { Detail } = this.props.navigation.state.params;
   this.setState({ Detail: Detail });

   TrackPlayer.setupPlayer({}).then(async () => {
     await TrackPlayer.add({
       id: Detail.SongID,
       url: Detail.SongStreamLink,
       title: Detail.SongName,
       artist: Detail.SongSinger,
       artwork: Detail.SongThumbnail,
     });
     TrackPlayer.play();
     this.setState({ status: 'pause' });
   });
    console.log('WilMount');

  }`
I was try with that code
`TrackPlayer.addEventListener('playback-state', async (data) => {
      console.log(data);
    });`
But i use it, event click play and pause in notification miniPlayer not work ?!

**Comment by Guichaguri** [comment]
The events starting with `remote-` are triggered by the user from out-of-app sources. So all media buttons have their own `remote-` event. The ones you're looking for are `remote-play` and `remote-pause`.

**Comment by vijaysoul** [comment]
I Have same issue?

**Comment by Guichaguri** [comment]
This issue is quite old, please, open a new one with details from the problem you're facing
