### ISSUE TITLE
dev branch raises swift version compatibility error on new xCode.

### ISSUE THREAD

**Issue by shuvo0074** [react-native-kit/react-native-track-player#628]
# Configuration
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

    `react-native-track-player` version : react-native-track-player#dev

# Issue
I upgraded xcode to 10.2.1 and xcode gives me this error when I try to run my project through xcode "The target “RNTrackPlayer” contains source code developed with Swift 3.x. "

# Steps to reproduce:
1. react-native init testApp
2. yarn add react-native-kit/react-native-track-player#dev **or** yarn add react-native-track-player@next (1.1.5-rc9)
3. yarn start
4. open ios/testApp.xcodeproj
5. run

**Comment by moonstruck** [comment]
Let's close this issue as build problem is gone.
