### ISSUE TITLE
The duration and position returned are inconsistent.

### ISSUE THREAD

**Issue by manzoorwanijk** [react-native-kit/react-native-track-player#629]
# Configuration
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 2.80 GB / 15.86 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.1-next.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
```

What `react-native-track-player` version are you using?
**1.1.4**

# Issue.
In `ProgressComponent` the position and duration are inconsistent. Most of the time, I see the position at the end of the video is few seconds more than the total duration which makes `mm:ss` times illogical. I use SoundCloud audios.

# Code
I tried this code in my `Player` component.
```JS
await TrackPlayer.getPosition().then((time) => {
  console.log('Position: ',time);
  //dispatch(updateAudioPlayTime(time));
});
await TrackPlayer.getDuration().then(duration => {
  console.log('Duration: ',duration);
});
```
Here is the result on console when the audio finishes playing:

![image](https://user-images.githubusercontent.com/18226415/59685130-16fbdd80-91f9-11e9-8fcc-26b7ebe17453.png)

You can see that the current `Position` is more than total `Duration`.

**Comment by Guichaguri** [comment]
That's expected. `react-native-track-player` is a streaming library, which means it slowly downloads and plays audio.

Duration becomes a problem when it's not predetermined in most audio tracks, the player uses a few tricks to calculate the duration, but it might be a little off, or might not be able to calculate at all.

The solution is the same for any streaming app: don't rely on the player to calculate the duration, instead, store that on a database or something. In your case, you should be able to retrieve the real duration from SoundCloud's API.

You should be feeding the real duration into the `duration` parameter in the Track Object to avoid any problems.

**Comment by manzoorwanijk** [comment]
Yee, I do feed the duration from SoundCloud but it's still the same.

**Comment by Guichaguri** [comment]
Which version are you using?

**Comment by manzoorwanijk** [comment]
> Which version are you using?

**1.1.4**

This is my redux action

```JS
export const playCurrentAudio = () => {
  return async (dispatch, getState) => {
    const { audios: { collection, currentlyPlaying: { id, index } } } = getState();

    // Make sure the audio exists in our collection
    if (!id || index < 0 || !collection.hasOwnProperty(index)) {
      return;
    }

    // get the audio object from SoundCloud collection
    const audio = collection[index];

    const currentTrack = await TrackPlayer.getCurrentTrack().then(track => track);

    // if the track has already been added/played
    if (currentTrack === null || id.toString() !== currentTrack ) {

      await TrackPlayer.reset();

      const id = audio.id.toString(),
        url = getAudioStreamUrl(audio),
        title = audio.title,
        duration = audio.duration/1000,
        artist = 'XYZ',
        artwork = audio.artwork_url;

      await TrackPlayer.add({
        id,
        url,
        title,
        duration,
        artist,
        artwork,
      });
    }

    dispatch(setAudioEnded(false));
    dispatch(setAudioPaused(false));

    await TrackPlayer.play();
  }
};
```

**Comment by Guichaguri** [comment]
Fixed in the `dev` branch.

**Comment by manzoorwanijk** [comment]
@Guichaguri  thanks :)

**Comment by ZsofiaMajoros** [comment]
Is this already merged in v1.1.8?

**Comment by ZsofiaMajoros** [comment]
@Guichaguri doesn't work in `dev` branch on my end
Reproduction steps:
add to package.json: `"react-native-track-player": "react-native-kit/react-native-track-player#dev",`
`yarn`
and run `yarn android`

**Comment by Guichaguri** [comment]
Are you feeding the `duration` property?

**Comment by lylest** [comment]
any body fixed it???

**Comment by curiousdustin** [comment]
@lylest , are you including a `duration` in the track object you pass to `TrackPlayer.add()`?
