### ISSUE TITLE
How to use with react component

### ISSUE THREAD

**Issue by moduval** [react-native-kit/react-native-track-player#63]
Hi,

Before checking this component, I used react-native-video to play my stream file.

My component looks like this: 
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import Video from 'react-native-video';

function AudioPlayer(props) {

  if (props.paused) {
    return null;
  }

  const { source, paused, onLoad, onError } = props;

  return (
    <Video
      source={{ uri: source }}
      volume={1.0}
      muted={false}
      onLoad={onLoad}
      paused={paused}
      onError={onError}
      playInBackground
      playWhenInactive
    />
  );
}

AudioPlayer.propTypes = {
  source: PropTypes.string.isRequired,
  paused: PropTypes.bool.isRequired,
  onLoad: PropTypes.func.isRequired,
  onError: PropTypes.func.isRequired
};

export default AudioPlayer;
```

Since react-native-video is not working great on android while playing in background, i was looking for this component but I do now understand how I am supposed to use redux to dispatch action to the player.

In my app, my ui component dispatch redux actions like Play, Pause, etc. I have a component over  my audioplayer bind to redux that pass props to my AudioPlayer to update it depending on user action. 

My question: How can I accomplish similar lifecycle using this component ? All the events are in the headless task and I do not understant how am i supposed to update the props of my components using this.

I want to keep a similar API for my component as I am going to use react-native-track-player only on android.

Thank you.

**Comment by Guichaguri** [comment]
As you have mentioned, `react-native-video` works as a UI component. But due to the fact that we need audio to work in background (with lockscreen controls), `react-native-track-player` works as an API.



You can update your redux store with new information from through the headless task

**Comment by moduval** [comment]
How to access store in the headless task ?

**Comment by jasongrishkoff** [comment]
You should just be able to import it?  I use Mobx, so I just `import store from '../store/PlayerStore'`

**Comment by Guichaguri** [comment]
You also can just pass it to the function like so:

```js
// index
const store = ...
....registerHeadlessTask('TrackPlayer', () => require('event-handler.js').bind(null, store));
```

```js
// event-handler.js
module.exports = async (store, data) {
    if(event.type == '...') {
        store.dispatch(...);
    }
};
```

**Comment by moduval** [comment]
Thanks for the help, it works

**Comment by rahulbhankar786** [comment]
Thanks for help @Guichaguri 
Its working

**Comment by jeosebastian555** [comment]
Thanks for the help. It works
