### ISSUE TITLE
Update metadata shoutcast streams (iOS and Android)

### ISSUE THREAD

**Issue by maendamedia** [react-native-kit/react-native-track-player#636]
Using version 1.1.4 of the module.

I'm already asked this but it is not really clear how we need to use the update for artist and player information using a shoutcast stream.

We can do it two ways:

1) extract it from the stream (so everything gets updated in the app)
2) using a text file which contains the information and extract changes from there using the track-player module. 

But neither i'm sure how this works as the title and artist are set once and never gets updated in the module. 

I created a timing script to extract it from the text file but i do not manage to update the information inside the module.

Any help is welcome

**Comment by Guichaguri** [comment]
You can update the track metadata through `updateMetadataForTrack`:
```js
const trackId = await TrackPlayer.getCurrentTrack();
TrackPlayer.updateMetadataForTrack(trackId, {
    title: ...,
    artist: ...
});
```

The function accepts any type of metadata from the track object (like `artist`, `title`, `genre`, `album`, `artwork`, etc).

Extracting from stream only works on Android, you have to listen to the `playback-metadata-received` event:
```js
TrackPlayer.addEventHandler('playback-metadata-received', async e => {

    const currentTrack = await TrackPlayer.getCurrentTrack();
    TrackPlayer.updateMetadataForTrack(currentTrack, {
        title: e.title,
        artist: e.artist
    });

});
```

Hopefully this clarifies a bit.

**Comment by maendamedia** [comment]
Hi, thanks. Yes that clears it up a bit.
Do you have ideas on howto do this for iOS? As that is a problem when it does not work :(

**Comment by Guichaguri** [comment]
You'll have to implement some other way around not having the `playback-metadata-received` event, like fetching from a server from time to time.

**Comment by maendamedia** [comment]
Sure but how do i get that updated in the module? The first time iT works but after update i’m not sure how to push iT to ios

**Comment by Guichaguri** [comment]
You can setup an interval inside the player service, something like this:

```js
module.exports = async () => {

    if (Platform.OS === 'android') {
        TrackPlayer.addEventListener('playback-metadata-received', async (e) => {
            const currentTrack = await TrackPlayer.getCurrentTrack();
            TrackPlayer.updateMetadataForTrack(currentTrack, { title: e.title, artist: e.artist });
        });
    } else {
        setInterval(() => {
            fetch(....).then(r => r.json()).then(data => {
                const currentTrack = await TrackPlayer.getCurrentTrack();
                TrackPlayer.updateMetadataForTrack(currentTrack, { title: data.title, artist: data.artist });
            });
        }, 1000 * 60); // Repeat every minute
    }

};
```

**Comment by maendamedia** [comment]
Tried this, but the error i receive is an immutable issue.

You attempted to set the key '_65'with the value '1' on an object that is meant to be immutable and has been frozen.

Seems i cannot update the state this way.

`async function togglePlayback() {
    const currentTrack = await TrackPlayer.getCurrentTrack();
    if (currentTrack == null) {
      await TrackPlayer.reset();
      await TrackPlayer.add({
        id: 'HeteHits',
          url: playerSetting.playerUrl,
          title: '',
          artist: '',
        artwork: "https://picsum.photos/200"
      });
      await TrackPlayer.play();

     if (Platform.OS === 'android') {
        TrackPlayer.addEventListener('playback-metadata-received', async (e) => {
            const currentTrack = await TrackPlayer.getCurrentTrack();
            TrackPlayer.updateMetadataForTrack(currentTrack, { title: e.title, artist: e.artist });
        });
    } else {
        setInterval( () => {
        
            fetch('https://www.hetehits.nu/json.php?type=gespeeld&limiet=1')
                .then(r => r.json())
                .then(data => {
                const currentTrack = TrackPlayer.getCurrentTrack();
                TrackPlayer.updateMetadataForTrack(currentTrack, 
                    { 
                        title: data.nowplaying[0].artist, 
                        artist: data.nowplaying[0].artist });
            });
        }, 1000 * 5); // Repeat every minute
    }

    } else {
      if (playbackState === TrackPlayer.STATE_PAUSED) {
        await TrackPlayer.play();
      } else {
        await TrackPlayer.pause();
      }
    }
  }
`

**Comment by Guichaguri** [comment]
Inside the fetch, you have:
`const currentTrack = TrackPlayer.getCurrentTrack();`, which won't return the current track, it returns a promise instead.

You'll have to make the function handling the promise `async`, and then run `const currentTrack = await TrackPlayer.getCurrentTrack();`.

**Comment by maendamedia** [comment]
That is it indeed. Overlooked that one *sigh*
changed it to:

```
if (Platform.OS === 'android') {
        TrackPlayer.addEventListener('playback-metadata-received', async (e) => {
            const currentTrack = await TrackPlayer.getCurrentTrack();
            TrackPlayer.updateMetadataForTrack(currentTrack, { title: e.title, artist: e.artist });
        });
    } else {
        setInterval( () => {
            fetch('urltojson')
                .then(r => r.json())
                .then(async (data) => {
                const currentTrack = await TrackPlayer.getCurrentTrack();
                TrackPlayer.updateMetadataForTrack(currentTrack, 
                    { 
                        title: data.nowplaying[0].title, 
                        artist: data.nowplaying[0].artist });
            });
        }, 1000 * 5); 
```

and that works. Although for iOS it does. Android should be tested :)

Thanks man!

**Comment by maendamedia** [comment]
Update: Android works fine too (y)

**Comment by Guichaguri** [comment]
Nice!

**Comment by maendamedia** [comment]
One little question. Can i get the track and artist also back from the TrackPlayer?
I mean, when it is set, how can i read it so i can update a text field? Or do i need to parse it twice from the web? One for TrackPlayer and one for the text field (or maybe using state?)

**Comment by Guichaguri** [comment]
You can use `await TrackPlayer.getTrack(await TrackPlayer.getCurrentTrack())`, which will give you back the track object.

**Comment by Tucker2015** [comment]
Trying to display Metadata for my stream.  I have used the following code but nothing is received.  How can I make this work ?

`async function togglePlayback() {
    const currentTrack = await TrackPlayer.getCurrentTrack();
    if (currentTrack == null) {
      await TrackPlayer.reset();
      await TrackPlayer.add({
        id: '1111',
        url: 'http://149.56.185.59:8022',
        title: '',
        artist: '',
        artwork: require('../assets/main_logo.png'),
        duration: 0,
      });
      await TrackPlayer.play();
      if (Platform.OS === 'android') {
        TrackPlayer.addEventListener('playback-metadata-received', async (e) => {
            const currentTrack = await TrackPlayer.getCurrentTrack();
            TrackPlayer.updateMetadataForTrack(currentTrack, { title: e.title, artist: e.artist });
        });
    } else {
        setInterval( () => {
            fetch('urltojson')
                .then(r => r.json())
                .then(async (data) => {
                console.log(data)
                const currentTrack = await TrackPlayer.getCurrentTrack();
                TrackPlayer.updateMetadataForTrack(currentTrack, 
                    { 
                        title: data.nowplaying[0].title, 
                        artist: data.nowplaying[0].artist });
            });
        }, 1000 * 5); 
      }
    } else {
      if (playbackState === TrackPlayer.STATE_PAUSED) {
        await TrackPlayer.play();
      } else {
        await TrackPlayer.pause();
      }
    }
  }`

Thanks for any help.  Very new to React-Native :)

This is the last thing I need to do for my App.

**Comment by BryonConley** [comment]
Hi,  I cane across this as I wanted to extract shoutcast metadata.  Your suggested code to do this includes this line from above:
TrackPlayer.addEventHandler('playback-metadata-received', async e => {

It is apprent there is no 'addEventHandler' function and my react-native-track-player is fairly fresh, ony a couple weeks old install with npm install as well as the master compressed folder from your GitHub page.  Is there by any chance you mean 'addEventListener' instead of 'addEventHandler' when coding for Android?   Thanks for developing such a high quality project!
