### ISSUE TITLE
Why no HLS support on IOS

### ISSUE THREAD

**Issue by moduval** [react-native-kit/react-native-track-player#64]
Reading the doc about platform support, it says that the IOS version doesn't support HLS or DASH. How can we play this type of streaming on IOS using this player ?

Thanks

**Comment by SatoshiInoue** [comment]
@moduval I can play an HLS stream on iOS with TrackPlayer. I can also play IceCast 2.4 streams.

**Comment by amed** [comment]
@SatoshiInoue Can you please provide an example?

**Comment by SatoshiInoue** [comment]
@amed You can simply use your HLS/IceCast stream URL as 'url' when you call TrackPlayer.add().

**Comment by smkhalsa** [comment]
@moduval were you able to get HLS running on iOS?

If it does indeed work, the documentation should be updated within the project README as well as [here](https://github.com/react-native-kit/react-native-track-player/wiki/Platform-Support).
