### ISSUE TITLE
Need add arm64-v8a support. Google play requires 64-bit support

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [react-native-kit/react-native-track-player#643]
https://developer.android.com/distribute/best-practices/develop/64-bit?hl=zh-cn

**Comment by Guichaguri** [comment]
That shouldn't be a problem because the module doesn't use native code, but I'll removing the native code filters just to make sure it doesn't cause any problems.

**Comment by LiWeiQiangAndroid** [comment]
thanks
