### ISSUE TITLE
[Android] App crashes when I set type: 'hls'

### ISSUE THREAD

**Issue by tk3cforever** [react-native-kit/react-native-track-player#649]
# Configuration

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
      Memory: 19.11 GB / 31.95 GB
    Binaries:
      Node: 10.15.3 - C:\NodeJs\node.EXE
      npm: 6.4.1 - C:\NodeJs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

1.1.0 and 1.2.0

# Issue
TrackPlayer works otherwise, but whenever I set type: anything other than 'default', because I want to play .m3u8 stream, the app crashes

# Code

	async componentDidMount() {
		await TrackPlayer.setupPlayer();
		this.play();
	}

	async play() {
		await TrackPlayer.add({
			id: '1',
			type: 'hls',
			url: this.props.currentRadio.acf.soundFile,
			title: this.props.currentRadio.title
		});
		TrackPlayer.play();
	}

**Comment by Guichaguri** [comment]
Did you [enabled `hls` in the build preferences](https://react-native-kit.github.io/react-native-track-player/build-preferences/#hls-android-only) file?

**Comment by tk3cforever** [comment]
That was it! Thank you so much!

**Comment by GeekChao** [comment]
> Did you [enabled `hls` in the build preferences](https://react-native-kit.github.io/react-native-track-player/build-preferences/#hls-android-only) file?

I enable 'hls' in the build preference. But the app can not play music track due to "playback-error {"code": "playback-source", "message": "Input does not start with the #EXTM3U header."}"

I am using v1.2.2. Thank you

**Comment by Guichaguri** [comment]
Please, open a new issue for that
