### ISSUE TITLE
Crash when removing tracks while playing the last track in queue

### ISSUE THREAD

**Issue by wkmcyz** [react-native-kit/react-native-track-player#661]
# Configuration

Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?
`v1.1.6`
# Issue

On Android, when calling `remove()` to remove tracks in the queue while the currently playing music is the last one in the queue, it will generate a `array index out of bounds` crash.
```

    @Override
    public void onPositionDiscontinuity(int reason) {
        Log.d(Utils.LOG, "onPositionDiscontinuity: " + reason);

        if(lastKnownWindow != player.getCurrentWindowIndex()) {
            Track previous = lastKnownWindow == C.INDEX_UNSET ? null : queue.get(lastKnownWindow);   // <------- This is the line crash happens.
            Track next = getCurrentTrack(); 
//....
```
it is because the `remove` did removed the track from `queue` and cause the return value of `player.getCurrentWindowIndex()` changed. However the  `lastKnownWindow` is not changed appropriately. In the situation where the currently playing music is the last one, the `lastKnownWindow` will be greater than `queue.size()` ,which makes the crash.

# Code

Show us the code you are using

**Comment by Fghurayri** [comment]
I have the same issue :(

**Comment by Fghurayri** [comment]
My workaround is to call clear() to clear the queue then add tracks again.
