### ISSUE TITLE
Can this cast video? (I know it’s an audio player)

### ISSUE THREAD

**Issue by flexgrip** [react-native-kit/react-native-track-player#669]
Hello,

First... I know this is an audio player. However, I’m wondering if this can be hijacked to cast video on Android. Let me explain why.

The react-native-google-cast repo provides chromecasting on iOS and Android. However, it’s currently broken in Android on RN 0.60.

In my app, the chromecast button is not linked to the video player at all. They are instantiated separately.

I’m wondering, as a temporary workaround, what happens if I stuff an m3u8 manifest in your player that is filled with HLS video, and only exposed the chromecast button, if it would cast the video.

I had a short time earlier where I started to try it, but now I’m traveling and won’t be able to play with it for another day or two. Wondering if anyone has attempted this.

**Comment by curiousdustin** [comment]
At this time casting is no longer provided by this library. @Guichaguri please correct me if I am mistaken.
