### ISSUE TITLE
Able to add duplicate songs to queue. 

### ISSUE THREAD

**Issue by YajanaRao** [react-native-kit/react-native-track-player#672]
Able to add duplicate songs to queue. When a track is already in the queue, Is there a possibility to not to add again ?.

**Comment by Guichaguri** [comment]
That seems like a bug, but we plan to remove the `id` parameter from the track, so everything uses the track index instead, which means you'll have to be checking for duplicates by yourself anyway.

**Comment by Guichaguri** [comment]
It has been removed in v2.
