### ISSUE TITLE
the player cannot play streaming audio (radio)

### ISSUE THREAD

**Issue by RayhanYulanda** [react-native-kit/react-native-track-player#676]
# Configuration

Run `react-native info` in your project and share the content.
System:
OS: Windows 10
CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
Memory: 2.39 GB / 7.90 GB

Binaries:
Node: 12.2.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.15.2 - C:\Users\ASUS\AppData\Roaming\npm\yarn.CMD
npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

`react-native-track-player@2.0.0-rc13` version
   
# Issue
I just follow the instructions and take some reference from issue to play radio streaming but it doesn't work. player in notification bar appear and the just in 1 second disappear

# Code

`import React, { Component } from 'react';

import {Image, StyleSheet, Text, View} from 'react-native';
import Header from './template/Header';
import {Button} from 'react-native-elements';
import TrackPlayer from 'react-native-track-player';

class Radio extends Component {

    componentWillMount () {
        // Creates the player
        TrackPlayer.setupPlayer().then(async () => {

            // Adds a track to the queue
            await TrackPlayer.add({
                id: 'trackId',
                url: 'http://mobil.metal-only.de:8000',
                title: 'Radio',
                artist: 'the name artist',
                artwork: require('./_resources/smalllogo.png'),
                type: 'hls',
            });

        });
    }

    _onPlay = async () => {
        await TrackPlayer.play();
    };

    _onStop = async () => {
        await TrackPlayer.stop();
    };

    render() {
        return (
            <View style={{flex:1}}>
                <Header title='Radio' />
                <View style={styles.con}>
                    <View style={styles.row}>
                        <View>
                            <Button type={'outline'}
                                    buttonStyle={styles.tombol}
                                    onPress={()=>this._onPlay()}
                                    icon={
                                        <View style={styles.conButton}>
                                            <Image style={styles.ic} source={require('./_resources/radio-play.png')}/>
                                            <Text style={styles.textButton}>Play Radio</Text>
                                        </View>
                                    }
                            />
                        </View>
                        <View>
                            <Button type={'outline'}
                                    buttonStyle={styles.tombol}
                                    onPress={()=>this._onStop()}
                                    icon={
                                        <View style={styles.conButton}>
                                            <Image style={styles.ic} source={require('./_resources/radio-stop.png')}/>
                                            <Text style={styles.textButton}>Stop Radio</Text>
                                        </View>
                                    }
                            />
                        </View>
                    </View>
                    <View style={styles.row}>
                        <View>
                            <Button type={'outline'}
                                    buttonStyle={styles.tombol}
                                    onPress={()=>'test'}
                                    icon={
                                        <View style={styles.conButton}>
                                            <Image style={styles.ic} source={require('./_resources/radio-record.png')}/>
                                            <Text style={styles.textButton}>Radio Record</Text>
                                        </View>
                                    }
                            />
                        </View>
                        <View>
                            <Button type={'outline'}
                                    buttonStyle={styles.tombol}
                                    onPress={()=>'test'}
                                    icon={
                                        <View style={styles.conButton}>
                                            <Image style={styles.ic} source={require('./_resources/radio-stoprecord.png')}/>
                                            <Text style={styles.textButton}>Stop Record</Text>
                                        </View>
                                    }
                            />
                        </View>
                    </View>
                </View>
            </View>
        );
    }
}`

**Comment by Guichaguri** [comment]
The url isn't a HLS manifest, it's a shoutcast stream. You should remove the `type: 'hls'` from the track object.

**Comment by RayhanYulanda** [comment]
okee thank you. my bad. it's work when i delete track-player.json

**Comment by RayhanYulanda** [comment]
it doesnt work. when i tried click the button play, nothing happen. just one time i tried it with this link works : http://pvstreaming.rri.co.id:9214/rribandaacehpro1.mp3

and the when i try it again, nothing happens
