### ISSUE TITLE
Data.icon not working on Android

### ISSUE THREAD

**Issue by moduval** [react-native-kit/react-native-track-player#68]
When i used the method updateOptions with and image. The image is not display in the statusBar

**Comment by Guichaguri** [comment]
Can you send the image and the code used?

**Comment by moduval** [comment]
Here is the icon i used:
![notificon](https://user-images.githubusercontent.com/6440586/32147170-50e1c95e-bcb9-11e7-9a07-803f7cf0d1ae.png)

Here is the code used: 
```javascript
    TrackPlayer.updateOptions({
      icon: require('./notifIcon.png'),
      ratingType: RATING_HEART,
      capabilities: [CAPABILITY_PLAY, CAPABILITY_PAUSE, CAPABILITY_STOP],
      compactCapabilities: [CAPABILITY_PLAY, CAPABILITY_PAUSE, CAPABILITY_STOP],
      stopWithApp: true
    });
```

**Comment by moduval** [comment]
When I put logging in the package, my image has an URL like this: `http://10.0.2.2:8081/assets/src/main/assets/myIcon.png?platform=android&hash=4facae8d580b80cd94e5d4c0b19f0bc5` but the ResourceDrawableIdHelper return 0.

I don't know why the ResourceDrawableIdHelper return 0 and there is no doc for this class in react-native.

**Comment by Guichaguri** [comment]
This is a issue that only happens in the development mode. Instead of React Native bundling your icon into your app, it downloads directly from the packager.
Unfortunately, there is no easy way to fix it, so you'll have to test it in release mode,

**Comment by davidcort** [comment]
In Android works in release mode :)
