### ISSUE TITLE
hls in android seem not work

### ISSUE THREAD

**Issue by Gate26** [react-native-kit/react-native-track-player#684]
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
      Memory: 18.04 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 21, 23, 26, 28, 29
        Build Tools: 28.0.2, 28.0.3, 29.0.0
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-video: 5.0.0Run `react-native info` in your project and share the content.

react-native-track-player version  1.1.8

It seem that android cant play m3u8 stream. I set up a node server to stream m3u8 and it works great with IOS and Safari. When I try with Android, only the m3u8 file is sent and nothing after like stream0.ts, stream1.ts .....
I set up a track-player.json in root dir with hls: true

I use the really basic code:

async componentDidMount() {

    // Creates the player
  TrackPlayer.setupPlayer().then(async () => {
 
    // Adds a track to the queue
    await TrackPlayer.add({
      id: '1',
      url: "http://10.10.10.32:8001/out.m3u8",
      title: 'title',
      artist: 'title',
    });

    // Starts playing it
    TrackPlayer.play();

  });

I dont know if its a bug or Am I missing something

thanks

**Comment by Guichaguri** [comment]
You're missing the track `type` parameter. You also have to enable the HLS integration in the [build preferences file](https://react-native-kit.github.io/react-native-track-player/build-preferences/)

**Comment by maxckelly** [comment]
Did you solve this? I’m facing the same issue. When I press play it seems to play but there is no sound. I’m stream the audio from our node server using Regis.

**Comment by surhidamatya** [comment]
Did anyone solve this issue? Facing the same issue in Android devices. The url runs smoothly in emulator but it does not load in android device

**Comment by charneykaye** [comment]
> Did you solve this? I’m facing the same issue. When I press play it seems to play but there is no sound. I’m stream the audio from our node server using Regis.

I'm also seeing zero errors, everything appears to be correct, including the state change to Playing. However, in emulator on both iOS and Android, zero sound is audible.
