### ISSUE TITLE
App stucks on Launch screen on IOS after linking 

### ISSUE THREAD

**Issue by appify-waheed** [react-native-kit/react-native-track-player#700]
i am have tried react-native-track-player version 1.1.8 and version 1.1.6 and same issue on both xcode was creating an exception in automatic linking with react-native link react-native-track-player and in manual linking and starts but always stuck on the splash screen on ios any solution please, i have also manually select the swift version 4.2 in xcode.
But it behaviour is inconsistent some times it gets stuck and sometimes i got a an exception in xcode like this
<img width="758" alt="Screenshot 2019-08-11 at 10 01 44 PM" src="https://user-images.githubusercontent.com/45425486/62837021-a5359280-bc83-11e9-9f6e-1aaf7a183bd9.png">

**Comment by curiousdustin** [comment]
Can you try version 1.2.3?

**Comment by appify-waheed** [comment]
Yeah, it was gets fixed in 1.1.8.
Maybe I was doing something wrong or dummy.swift file was making some problem.
