### ISSUE TITLE
[iOS] Git submodule points to missing commit

### ISSUE THREAD

**Issue by biomancer** [react-native-kit/react-native-track-player#703]
In current dev branch ios/RNTrackPlayer/Vendor/AudioPlayer points to https://github.com/dcvz/SwiftAudio/commits/81ca1ae6413c1c301dfedc590a8a70ca2997c129 and while this commit exists on github, it seems to be removed from all branches and it's not available when you clone the repo locally.
Here is what happens when I try to fetch submodules locally:
```
git submodule update --init --recursive

Submodule 'ios/RNTrackPlayer/Vendor/AudioPlayer' (https://github.com/dcvz/SwiftAudio.git) registered for path 'ios/RNTrackPlayer/Vendor/AudioPlayer'
Cloning into '/Volumes/HDD/Projects/github/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer'...
error: no such remote ref 81ca1ae6413c1c301dfedc590a8a70ca2997c129
Fetched in submodule path 'ios/RNTrackPlayer/Vendor/AudioPlayer', but it did not contain 81ca1ae6413c1c301dfedc590a8a70ca2997c129. Direct fetching of that commit failed.
```

Also trying to clone SwiftAudio repo directly and to check out 81ca1ae6413c1 commit directly fails.

@dcvz could you please take a look and update submodule to existing commit, or push a branch to SwiftAudio repo with that commit so it would be available?

**Comment by biomancer** [comment]
I guess it's better to push a branch with commit, so that this submodule would work as expected historically

**Comment by curiousdustin** [comment]
Yes, please fix this. Is 1.1.x version actually working right now? It seems like this issue is breaking these versions.

I have tried using different commits in `dcvz/SwiftAudio`, but nothing seems to match up. Each combination breaks in a different way.

Where is this missing branch/commit?

**Comment by biomancer** [comment]
@curiousdustin well, I think you can download source as zip https://github.com/dcvz/SwiftAudio/archive/81ca1ae6413c1c301dfedc590a8a70ca2997c129.zip and place it locally in ios/RNTrackPlayer/Vendor/AudioPlayer.
As of myself - I am currently in process of upgrading the RN to 0.60 and of all player versions only v2 would build without additional actions https://github.com/react-native-kit/react-native-track-player/tree/v2.0.0-rc13, and it seems to have links to existing commits in dcvz/SwiftAudio. But I am not sure that this is good reason to switch to v2 as it's work in progress, so I'm planning to try once more with v1 branch, but seeing your comments on strange ios behaviour in 1.1.4+ I think I'll stick for now with 1.1.3 for now and will try to update in fork to keep it working in RN 0.60.
1.1.3 also had issue with ios being unable to recover after failure, but I think that is exactly what you have found here https://github.com/jorgenhenrichsen/SwiftAudio/issues/56 and it seems to be fixed, so I'll try to use 1.1.3 with version of SwiftAudio that includes that fix, but still does not have those async changes.

**Comment by biomancer** [comment]
@curiousdustin Thanks, but as far as I understood all these async assets / etc. changes were actually implemented to fix this issue https://github.com/react-native-kit/react-native-track-player/issues/548 in 1.1.4 which seems quite nasty too, so 1.1.3 seems to be more stable in that regard. We currently have 1.1.3 in production for few months (https://github.com/perushevandkhmelev-agency/react-native-track-player/commits/edge version to be exact, but these changes are mostly for android), and I have seen no major issues on ios with it other than that inability to recover from failure. So I'll try to keep it conservative as I'm not and ios developer and I actually do not understand most of late changes enough to be able to fix these async issues somehow.

**Comment by biomancer** [comment]
@curiousdustin Wow, that's interesting, if that issue was caused by build problems, not the code itself, I guess I'll try latest 1.1.x version first then before falling back to 1.1.3! That would make possible contribution and overall effort sync much easier, thank you!

**Comment by thorbenprimke** [comment]
I ran into the same issue. :) 

I added a [comment on the PR](https://github.com/react-native-kit/react-native-track-player/commit/418934123a721f25cee9d2d829907d202d9057e6#commitcomment-34813106) that adds headers which uses a commit that is not in SwiftAudio's Master. 

Perhaps I should put that change up as a PR on SwiftAudio and then we can point SwiftAudio back to Master instead of the fork. 

@dcvz - do you have time to put up the PR (for headers)? If not, I'm happy to do it as it should make dev easier for everyone.

**Comment by thorbenprimke** [comment]
My working [fork is here](https://github.com/repodio/SwiftAudio). It has the headers commit. I'm only working off `dev` though. 

I found that the headers PR didn't get merged - https://github.com/jorgenhenrichsen/SwiftAudio/pull/64

**Comment by curiousdustin** [comment]
@Guichaguri, It would be nice if we could get this submodule commit thing sorted. 

Also, it seems @dcvz has not been active on this project for awhile. Is there any info you can share with us about if he is expected to return, or if there is anyone else that may be taking over heading up the iOS effort?

**Comment by gaodeng** [comment]
It seems that no one is currently maintaining this project. I plan to start writing a RN Audio Player based on this project this month.

**Comment by curiousdustin** [comment]
@Guichaguri this broken submodule thing continues to be a PITA, especially when trying to submit improvement or bugfix PRs. Every time we have to figure out how to deal with submodule missing commit. It is making contributing back to the community a real pain.

What should we do about it?

Do you have contact with @dcvz outside of this project?

**Comment by Guichaguri** [comment]
No, unfortunately. We can try hitting @dcvz an email though.

David has been kinda active lately (or at least trying to), the last commit to the [SwiftAudio fork is from November 22](https://github.com/dcvz/SwiftAudio/commit/7e8607bbcb73af59014dfc871f393d5b085a08ce), not too long ago.

There's two open PRs (#819 and #802) with the "pods fix", adding the official SwiftAudio as a dependency, but I'm pretty sure they will break the custom headers feature. For the time-being we can try updating his fork in the react-native-kit org.

I'd also love to get more maintainers on the project, at least to help out organizing the issues. The project clearly needs more attention than it gets.

**Comment by Guichaguri** [comment]
The big think about the two PRs is that they ditched @dcvz fork, but they didn't notice that the ["headers" argument added in the fork](https://github.com/dcvz/SwiftAudio/commit/3a0e934fa169c12787fac42d6ed49da189b2aedc#diff-8c8e8654093dd12f3092f334ea58b2c4R171) was replaced by an ["options" argument with the same type](https://github.com/jorgenhenrichsen/SwiftAudio/blob/master/SwiftAudio/Classes/AVPlayerWrapper/AVPlayerWrapper.swift#L173), which didn't caused any compile issues.

**Comment by Guichaguri** [comment]
Digging up a bit, it looks like @dcvz got a [follow up](https://github.com/jorgenhenrichsen/SwiftAudio/pull/71) to the headers PR merged and fixed it in the [v2](https://github.com/react-native-kit/react-native-track-player/commit/99f85241a46e2e24064439e1cb862bde7cb63790) branch.
This last commit exists in both the official SwiftAudio repo and the master branch from the fork, which means we can probably just update the commit reference and voila!

**Comment by Guichaguri** [comment]
https://github.com/react-native-kit/react-native-track-player/commit/170c14a58d185b046b5d095cecfad43a08553f33 should fix the v2 branch, I'll cherrypick those into the dev branch too

**Comment by benjipott** [comment]
https://github.com/react-native-kit/react-native-track-player/pull/828 fix export interface mistake

imho use a podspec is better than git submodules

**Comment by curiousdustin** [comment]
> I'd also love to get more maintainers on the project, at least to help out organizing the issues. The project clearly needs more attention than it gets.

@Guichaguri I'm happy to try to help out more. Where/how should we discuss what that looks like?

**Comment by Guichaguri** [comment]
@curiousdustin Either on [Discord](https://discordapp.com/invite/ya2XDCR) (Guichaguri#5794) or through [email](mailto:guichaguri@gmail.com)

**Comment by curiousdustin** [comment]
https://github.com/react-native-kit/react-native-track-player/pull/904 resolves this.
