### ISSUE TITLE
On Android app crashed after installing

### ISSUE THREAD

**Issue by appify-waheed** [react-native-kit/react-native-track-player#706]
# Configuration

info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
      Memory: 613.13 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 25.0.3, 26.0.2, 27.0.3, 28.0.3
        System Images: android-18 | Google APIs ARM EABI v7a, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.59.3 => 0.59.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

# Issue
i Just installed the the version 1.1.8 from yarn linked on android and ios it runs fine on IOS but when run on the app got crashed.

**Comment by maendamedia** [comment]
Same issue here.

**Comment by rennanribeiro** [comment]
Same here.

`
AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
AndroidRuntime: 	at com.guichaguri.trackplayer.service.metadata.MetadataManager.updateOptions(MetadataManager.java:112)
AndroidRuntime: 	at com.guichaguri.trackplayer.service.MusicBinder.updateOptions(MusicBinder.java:45)
AndroidRuntime: 	at com.guichaguri.trackplayer.module.MusicModule.onServiceConnected(MusicModule.java:74)
AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1652)
AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1681)
AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6543)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
`

**Comment by psegalen** [comment]
Hi! I had the same issue but @dcvz's comment (https://github.com/react-native-kit/react-native-track-player/issues/668#issuecomment-511806298) pointed me in the right direction:

Was importing constants like this:
```
import TrackPlayer, {
  CAPABILITY_PLAY,
  CAPABILITY_PAUSE
} from "react-native-track-player";
```
Before using in `TrackPlayer.updateOptions()`
Had to replace it by:
```
import TrackPlayer, { Capability } from "react-native-track-player";
```
This fixed the crash!

**Comment by Guichaguri** [comment]
This issue happens when you pass a `null`/`undefined` value to the `capabilities` option. Figure out what is `null`/`undefined`, remove it and it should stop crashing.

**Comment by nathanguigui** [comment]
Hello I was facing the same issue with the latest version of `react-native-track-player` 

I think that is beacuase of the enum `Capability`.

![Sun Feb 27 07:01:51 PM CET 2022](https://user-images.githubusercontent.com/39025228/155894101-4e60203d-d18e-4d28-bd32-a0918cc58ec2.png)

As you can see on the screenshot the value of `Play` capability is `0`.

So I figured out by changing removing the `Capability.Play` from capabilities:
```javascript
await TrackPlayer.updateOptions({
  stopWithApp: false,
  capabilities: [Capability.Pause, Capability.Play, Capability.Stop],
  compactCapabilities: [Capability.Pause, Capability.Play, Capability.Stop],
});
```

to: 
```javascript
await TrackPlayer.updateOptions({
  stopWithApp: false,
  capabilities: [Capability.Pause, Capability.Stop],
  compactCapabilities: [Capability.Pause, Capability.Stop],
});
```

Note that the problem was only seen on android bundle build.

Here is my `package.json`

```json
{
  "name": "PackageName",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest"
  },
  "rnpm": {
    "assets": [
      "./src/assets/fonts"
    ]
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.5",
    "@react-native-community/picker": "^1.6.5",
    "@react-native-community/voice": "^1.1.9",
    "@react-navigation/drawer": "5.12.9",
    "@react-navigation/material-top-tabs": "^5.x",
    "@react-navigation/native": "5.9.8",
    "@react-navigation/native-stack": "5.0.5",
    "@react-navigation/stack": "^5.6.2",
    "@sentry/react-native": "2.6.2",
    "axios": "^0.19.2",
    "i18n-js": "^3.7.1",
    "i18next": "^19.7.0",
    "immutability-helper": "^3.1.1",
    "jetifier": "^1.6.6",
    "lodash": "^4.17.19",
    "react": "16.13.1",
    "react-i18next": "^11.7.2",
    "react-native": "0.63.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-iap": "^7.5.1",
    "react-native-screens": "3.5.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-track-player": "2.1.2",
    "react-native-vector-icons": "^7.0.0",
    "react-navigation-drawer": "^2.5.0",
    "react-navigation-stack": "^2.8.2",
    "request": "^2.88.2",
    "ts-jest": "^26.3.0"
  }
}

```
