### ISSUE TITLE
Get the streamed data

### ISSUE THREAD

**Issue by ITU-14** [react-native-kit/react-native-track-player#708]
Hello,

I want to broadcast the current audio stream. So, is there any way to get the current audio stream of the TrackPlayer please?

Thanks

**Comment by mhabegger** [comment]
What type of stream are you using ? Icecast with ICY-Metadata ?

**Comment by Guichaguri** [comment]
What do you exactly need? Is it metadata or the raw audio input?

**Comment by ITU-14** [comment]
Hello,

Thanks you very much. I already solve the issue. :)

Yours truly,
NIIRIJAONA Lala Ricoeur Khino

**Comment by nishanBende** [comment]
@ITU-14 can you explain how you solved the issue? 
Thanks

**Comment by ITU-14** [comment]
Hi,

I developed a native library with android studio and did implement it on my
react native project.

Kind regards,
NIRIJAONA Lala Ricoeur Khino
