### ISSUE TITLE
Crashing on Android (NoClassDefFoundError)

### ISSUE THREAD

**Issue by casesandberg** [react-native-kit/react-native-track-player#710]
# Issue
I am getting this error when trying to use the package on android:
`
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/source/hls/HlsMediaSource$Factory;
`

# Code
```
TrackPlayer.setupPlayer()
```

# Configuration

RN Info:
```
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
      Memory: 26.20 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.6.0 - ~/.nvm/versions/node/v8.6.0/bin/node
      npm: 6.10.1 - ~/.nvm/versions/node/v8.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 10, 15, 17, 23, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0
        System Images: android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Using `react-native-track-player@1.1.8`

Android configs:
```
buildToolsVersion = "28.0.3"
minSdkVersion = 18
compileSdkVersion = 28
targetSdkVersion = 28
supportLibVersion = "28.0.0"
```

**Comment by appify-waheed** [comment]
I am having same issue i tried 1.1.6 version, 1.1.8 version and also dev branch
"react-native-kit/react-native-track-player#dev"
when i try to install the app into the device it crashes every time

**Comment by maendamedia** [comment]
Same here. iOS is ok

**Comment by vibdheeraj** [comment]
any progress, I am facing the same issue.

**Comment by Guichaguri** [comment]
Are you facing this issue while building it or in runtime?

**Comment by casesandberg** [comment]
Runtime

**Comment by vibdheeraj** [comment]
At runtime

**Comment by Guichaguri** [comment]
Can you test 97692c6894c5ffaae9ad5772c4db0e24c420ac0d to see whether the error is fixed?

**Comment by luandro** [comment]
@Guichaguri seems that commit solved the problem. Should publish to npm :)

**Comment by ashishfeels** [comment]
Anybody Still facing this ? im not able to move to dev version `
npm ERR! code 1
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! warning: templates not found in /tmp/pacote-git-template-tmp/git-clone-ed05f9f8
npm ERR! error: Server does not allow request for unadvertised object 81ca1ae6413c1c301dfedc590a8a70ca2997c129
npm ERR! Fetched in submodule path 'ios/RNTrackPlayer/Vendor/AudioPlayer', but it did not contain 81ca1ae6413c1c301dfedc590a8a70ca2997c129. Direct fetching of that commit failed.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ashish/.npm/_logs/2019-12-20T17_18_20_328Z-debug.log

`

i get the following error
