### ISSUE TITLE
Exo-player conflicts

### ISSUE THREAD

**Issue by ntk860** [react-native-kit/react-native-track-player#715]
Hi @Guichaguri, I am trying to use the exo-player version of react-native-video, but the app is crashing because of the conflict caused by the exo-player used on this library. Is there any suggestions or anything I can do to avoid this problem ?

**Comment by florianalbrecht** [comment]
Hey, I had the same problem and created a PR to update exoplayer in react-native-video: https://github.com/react-native-community/react-native-video/pull/1722. You can use my branch for now to solve the issue.

**Comment by Guichaguri** [comment]
Looks like this has been fixed in react-native-video side. I'll be closing this, feel free to reopen if it's still causing problems.

**Comment by appify-waheed** [comment]
@Guichaguri i am having the same issue and i am using the latest version of react-native-video-player and its not been fixed in react-native side.

**Comment by appify-waheed** [comment]
@florianalbrecht i have tried with your branch and its also not working.

**Comment by infinitbility** [comment]
Hope it Helpful For you

https://infinitbility.com/app-crashed-immediately-after-install-react-native-video-or-track-player

**Comment by sadikyalcin** [comment]
> Hope it Helpful For you
> 
> https://infinitbility.com/app-crashed-immediately-after-install-react-native-video-or-track-player

Downgrading is not a fix.

**Comment by Robiullah2244** [comment]
I also facing the same issue with the `react-native-triton-player`
