### ISSUE TITLE
v2.0.0-rc13 - Android - Cannot read property 'RATING_HEART' of  null 

### ISSUE THREAD

**Issue by dmathewwws** [react-native-kit/react-native-track-player#719]
# Configuration
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 369.79 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.2 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.2, 27.0.3, 28.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: ^0.60.5 => 0.60.5 
  npmGlobalPackages:
    create-react-native-app: 1.0.0

react-native-track-player: 2.0.0rc-13

# Issue

Getting the Error: Cannot read property 'RATING_HEART' of  null, js engine Hermes

![Screenshot_1567455287](https://user-images.githubusercontent.com/2018931/64132318-d89ba680-cd83-11e9-8305-ab431c9c9a4d.png)

Thanks!

**Comment by dmathewwws** [comment]
oh, I see RatingCompat is in in the android.support library. 

Will see if I can fix and submit a PR.

**Comment by dmathewwws** [comment]
Was thinking import android.support.v4.media was not part of androidx but seems like it is (and that would be a big refactor!)

Not sure what the issue is, seems like TrackPlayer returns null via

```var TrackPlayer = react_native_1.NativeModules.TrackPlayerModule;```

**Comment by Guichaguri** [comment]
That is usually caused by a linking issue. Please, try unlinking the module and linking again manually.

**Comment by dmathewwws** [comment]
Yes, Thanks :) It was not properly linked.

I did fix the issue. For anyone else with a similar issue, I had to manually link react-native-track-player for android. which required using a react-native.config.js file and this to my settings.gradle file.

```
include ':react-native-track-player'
project(':react-native-track-player').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-track-player/android')
```

https://github.com/react-native-community/cli/blob/master/docs/autolinking.md was a good resource.

**Comment by saadnaveed94** [comment]
Still getting this in expo project. Any help will be appreciated
![Screenshot_1695064440](https://github.com/doublesymmetry/react-native-track-player/assets/43129124/1bc96b4f-0caa-4cc5-803a-e8d1503f88e6)
. Thanks

**Comment by CHANDRAMOHANnegi** [comment]
I am also seeing this issue in expo

**Comment by rickyanwar** [comment]
i also have same issue on expo go

**Comment by Iranzithierry** [comment]
> Still getting this in expo project. Any help will be appreciated ![Screenshot_1695064440](https://user-images.githubusercontent.com/43129124/268750283-1bc96b4f-0caa-4cc5-803a-e8d1503f88e6.png) . Thanks

did you found out solution
