### ISSUE TITLE
Empty constants on iOS

### ISSUE THREAD

**Issue by jpgarcia** [react-native-kit/react-native-track-player#72]
This is the output of a `console.log(TrackPlayer)` on both platforms:

### Android
![screen shot 2017-11-03 at 10 29 34 am](https://user-images.githubusercontent.com/95109/32376097-87dd0906-c082-11e7-9aa4-25db74bb83d6.png)

### iOS

![screen shot 2017-11-03 at 10 32 48 am](https://user-images.githubusercontent.com/95109/32376107-8b227448-c082-11e7-9762-115e043e5f05.png)

Then when calling the `TrackPlayer.getState()` method on **Android** it returns a number (which apparently match with the constants) but on **iOS** it returns a string like `STATE_PLAYING`

**Comment by Guichaguri** [comment]
I wonder if #70 caused this

**Comment by Guichaguri** [comment]
@jpgarcia does aa8302756baa732a21878cf100a3541a530535b7 fixes the issue?

**Comment by berkcoker** [comment]
@Guichaguri it didn't fix the issue for me

**Comment by chrissbendel** [comment]
@Guichaguri @dcvz could this be related to RN version > .49?

Getting a warning saying ```Module RNTrackPlayer requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.```

Not sure if this might be messing with the constants that are getting exported or not

**Comment by chrissbendel** [comment]
#98 Fixed this - submitted a pull request for this. The AudioPlayerState's may also need some sort of value attached to them as they are still null, however I am not sure if those get set once the player is playing audio.

**Comment by dcvz** [comment]
Fixed in: 5e2ce7db043a16fe26af6f3237b7488c57541024 and 5e2ce7db043a16fe26af6f3237b7488c57541024
