### ISSUE TITLE
onClick Event on Background Mode

### ISSUE THREAD

**Issue by matheus-erthal** [react-native-kit/react-native-track-player#720]
# Issue

I searched the docs in order to listen to the click event on background player and redirect the user in my app to a specific screen when the player is running on background but I was unable to find a way to do this. This event type exists or it is possible to implement a new functionality? If it has to be implemented yet, is there any way I can help to accomplish it? Thanks in advance

**Comment by HessiPard** [comment]
> # Issue
> I searched the docs in order to listen to the click event on background player and redirect the user in my app to a specific screen when the player is running on background but I was unable to find a way to do this. This event type exists or it is possible to implement a new functionality? If it has to be implemented yet, is there any way I can help to accomplish it? Thanks in advance

Its documented [here](https://react-native-kit.github.io/react-native-track-player/background/#notification).
But it just supports android
