### ISSUE TITLE
Android Q Media Notification + Seek

### ISSUE THREAD

**Issue by thorbenprimke** [react-native-kit/react-native-track-player#721]
Now that Android Q / 10 is rolling out, we should add support for the new media notification. Espeically having the seeker feature in the notification is pretty slick. 

More details here: 
https://developer.android.com/preview/features#media

Just wanted to put this up in case anyone else is working on this.

**Comment by Guichaguri** [comment]
That's really cool, I don't know how I missed that 😃

This should work right out of the bat as long as your app has `CAPABILITY_SEEK_TO` enabled, the `remote-seek` event is properly implemented and you define a `duration` in the track object greater than 0.

**Comment by curiousdustin** [comment]
@thorbenprimke, did this end up working for you?

**Comment by sriteja777** [comment]
@Guichaguri , you said to define duration in the track, but how can define duration for a network file?

**Comment by nriccar** [comment]
Solved adding duration on the add method, but Im facing the same thing as @sriteja777, what to do if the content is a network file? the useProgress method updates after the track is added
