### ISSUE TITLE
[iOS] NSURLErrorDomain Code=-999 "cancelled"

### ISSUE THREAD

**Issue by mrigo** [react-native-kit/react-native-track-player#728]
# Configuration

System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 99.09 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 19, 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.3
      System Images: android-19 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5

"react-native-track-player": "1.1.8",

# Issue

I've already checked other issues, but none of the method proposed worked for me.
I have this error

```
Adding tracks: [<react_native_track_player.Track: 0x7fdcaf792030>, <react_native_track_player.Track: 0x7fdcaf7481e0>]
2019-09-09 19:29:46.282978+0200 MyApp[36438:3165905] Task <28F1D414-9019-49D7-8A15-504383B49A36>.<1> load failed with error Error Domain=NSURLErrorDomain Code=-999 "annullato" UserInfo={NSErrorFailingURLStringKey=https://www.myserver.com/audio/7, NSErrorFailingURLKey=https://www.myserver.com/audio/7, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <28F1D414-9019-49D7-8A15-504383B49A36>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <28F1D414-9019-49D7-8A15-504383B49A36>.<1>, NSLocalizedDescription=annullato} [-999]
```

with an URL like this:
https://www.myserver.com/audio/7

this route uses a Laravel Controller that checks the auth token and then responds with the file or with an error.
Calling the URL with Postman or with Axios inside the app, all works fine, but with this library I've -999 code error...
I've added all headers required but the request doesn't even reach the server, it's canceled before doing the request.
Any advice?

# Code

The page on the server is:
```php
class AudioController extends AuthController
{
    public function getFile(Request $request, Chapter $chapter) {

        try {
            if (!$this->authUser) {
                return \ResponseHelper::formatErrorApiResponse("No auth user");
            } else {
                $pathToFile = \Storage::disk('audio')->url($chapter->audio_file);
                return response()->file($pathToFile);
            }

        } catch (\Throwable $th) {
            \Log::debug($th->getMessage());
            return \ResponseHelper::formatErrorApiResponse("Error chapter file");
        }

    }
}
```

and in React Native:

```javascript
setupPlayer = (chapters, callback) => {
        try {
            TrackPlayer.destroy(); // to clear the queue
            TrackPlayer.setupPlayer().then(() => {
            TrackPlayer.registerPlaybackService(() => require('./playback-service.js'));
            TrackPlayer.updateOptions({
                stopWithApp: true,
                capabilities: [
                    TrackPlayer.CAPABILITY_PLAY,
                    TrackPlayer.CAPABILITY_PAUSE,
                    TrackPlayer.CAPABILITY_STOP,
                    TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                    TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS
                ],
                });
                if (callback) {
                    callback(chapters);    
                }
            });
        } catch (error) {
            console.log("error audio service");
            console.log(error);
        }
        
    }

    setupTracks = async (chapters) => {

        var token = await retrieveToken();
        var auth = await getCheckHeaderValue();
        
        this.setupPlayer(chapters, (chapters) => {
            var tracks = chapters.map( chapter => {
                var url = encodeURI(chapter.audioUrl);
                var track = {
                    id: `id_${chapter.id}`,
                    url: `${url}`,
                    title: `${chapter.title}`,
                    artist: `${chapter.character}`,

                    album: `${chapter.collection}`,
                    artwork: `${chapter.image}`,

                    headers: {
                        "X-Auth": auth,
                        "Authorization": `Bearer ${token}`,
                        "Accept-Encoding": "gzip, deflate",
                    }
                };
                console.log(track);
                return track;
            })
    
            TrackPlayer.add(tracks).then( async () => {
                console.log("tracks added");
                var state = await this.playerState();
                console.log("STATE: "+state);
            }).catch( error => {
                console.log(error);
            });
        });
     
    }
```

The state is always IDLE and the error is "impossible to find the request URL on this server".

Thanks for your help, I've been stuck with this for too long :(
\m

**Comment by brunoserra** [comment]
@mrigo how did you solve this? I'm facing the same issue

**Comment by mrigo** [comment]
@brunoserra yes I solved! The url was incorrect and the server response was a right 404 ... check the url or the connectivity!
