### ISSUE TITLE
Save streamed file

### ISSUE THREAD

**Issue by dannydolph** [react-native-kit/react-native-track-player#73]
Hi,
Is there anyway to save streamed file on SD card? any suggestion how to do this?

**Comment by Guichaguri** [comment]
Yes, you can enable cache, it will store the track in the SD card and keep it based on size or time limits, but for now, only Android allows it.

**Comment by dannydolph** [comment]
How we can access to cache and save the track permanently?

**Comment by Guichaguri** [comment]
For now you can set `maxCacheSize` to a big number.

But I'll consider this issue as a suggestion, and implement in the future a proper way to store and access the track.

**Comment by Guichaguri** [comment]
This has been inactive for almost an year. This feature will be a bit tricky to implement, and there is not enough support to implement it, sorry.

**Comment by pkhodaveissi** [comment]
@Guichaguri but this is useful and if you give me directions, I'll be glad to help implementing it
