### ISSUE TITLE
Not working in iOS

### ISSUE THREAD

**Issue by akashmi** [react-native-kit/react-native-track-player#738]
This lib is not working for me in the below case:

I have one audio URL like https://firebasestorage.googleapis.com/..../......./Sounds%2F01.%20Aye%20Khuda.mp3

When I'm trying to play above URL using player it is automatically converting URL Path as below.

https://firebasestorage.googleapis.com/..../......./Sounds/01.%20Aye%20Khuda.mp3
and modified URL is not working in safari browser and the original one is working fine at all except this lib.

Here is is converting '%2F' with '/'. and it creating an issue in iOS app and browser.

**Comment by mhabegger** [comment]
According to this: https://tools.ietf.org/html/rfc3986#section-2.4
it should not do that. You say it does the same in iOS Safari Browser and decodes you %2F prior fetching the URL ?

**Comment by akashmi** [comment]
@mhabegger I have upgraded lib version to 1.1.8 from 1.1.4. and now it is working.
