### ISSUE TITLE
Android Status.paused is equal to Status.ready

### ISSUE THREAD

**Issue by fcaride** [react-native-kit/react-native-track-player#741]
Im using the r13 version, and i see that the constants Status.paused and Status.ready are both equal to 2. Is it on purpose? How do i distinguish between the two states?

Thanks!

**Comment by curiousdustin** [comment]
I think this is a case of Android not matching one-to-one with iOS. On android when the player is paused it is the same as ready. 

@Guichaguri can you canfirm?

**Comment by Guichaguri** [comment]
Yes, `READY` is unused on Android. See #942
