### ISSUE TITLE
Android not playing after upgrade

### ISSUE THREAD

**Issue by rsokz** [react-native-kit/react-native-track-player#744]
# Configuration

<details>
<summary>react-native info</summary>
<pre>
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 20.92 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 28.0.3
      System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5
</pre>
</details>

<details>
<summary>package.json</summary>
<pre>
{
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "postinstall": "npx jetify",
    "test": "jest",
    "lint": "eslint .",
    "eslint": "eslint ./src",
    "fixeslint": "eslint --fix ./src",
    "bundlea": "curl 'http://localhost:8081/index.android.bundle?platform=android' -o 'android/app/src/main/assets/index.android.bundle'",
    "r": "adb shell input text \"RR\"",
    "m": "adb shell input keyevent KEYCODE_MENU",
    "a": "react-native run-android",
    "i": "react-native run-ios"
  },
  "dependencies": {
    "@segment/analytics-react-native": "^1.1.0-beta.1",
    "axios": "0.18.0",
    "hermesvm": "^0.1.1",
    "jsc-android": "^241213.1.0",
    "lodash": "4.17.11",
    "moment": "2.23.0",
    "prop-types": "15.7.2",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-animatable": "1.3.2",
    "react-native-background-timer": "2.1.1",
    "react-native-branch": "4.1.0",
    "react-native-deep-linking": "2.2.0",
    "react-native-default-preference": "1.3.2",
    "react-native-fast-image": "7.0.2",
    "react-native-fbsdk": "1.0.4",
    "react-native-firebase": "5.5.6",
    "react-native-keyboard-aware-scroll-view": "0.9.1",
    "react-native-linear-gradient": "2.5.6",
    "react-native-loading-spinner-overlay": "1.0.1",
    "react-native-localization": "2.1.0",
    "react-native-permissions": "1.1.1",
    "react-native-router-flux": "4.0.5",
    "react-native-share": "https://github.com/react-native-community/react-native-share.git#479789966ae2ea9c77b9b25026f4a62cee745132",
    "react-native-simple-twitter": "2.3.0",
    "react-native-snap-carousel": "3.7.5",
    "react-native-splash-screen": "^3.2.0",
    "react-native-swift": "^1.2.2",
    "react-native-swipe-list-view": "2.0.1",
    "react-native-system-setting": "1.7.2",
    "react-native-track-player": "git+https://github.com/alexkendall/react-native-track-player#master",
    "react-native-twitter-signin": "git+https://github.com/GoldenOwlAsia/react-native-twitter-signin#master",
    "react-native-uuid-generator": "5.0.0",
    "react-native-vector-icons": "6.0.2",
    "react-native-voice": "^0.3.0",
    "react-native-wowza-gocoder": "git+https://github.com/findnedl/react-native-wowza-gocoder.git",
    "react-redux": "5.0.7",
    "redux": "4.0.1",
    "redux-logger": "3.0.6",
    "redux-persist": "5.10.0",
    "redux-thunk": "2.3.0",
    "tipsi-stripe": "6.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-eslint": "10.0.1",
    "babel-jest": "^24.8.0",
    "babel-preset-react-native": "5",
    "eslint": "^6.1.0",
    "eslint-config-airbnb": "17.1.0",
    "eslint-config-prettier": "3.0.1",
    "eslint-config-rallycoding": "3.2.0",
    "eslint-plugin-import": "2.16.0",
    "eslint-plugin-jsx-a11y": "6.2.1",
    "eslint-plugin-prettier": "3.0.0",
    "eslint-plugin-react": "7.11.1",
    "eslint-plugin-react-native": "3.3.0",
    "jest": "^24.8.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "^0.56.0",
    "prettier": "1.15.2",
    "react-native-clean-project": "^3.2.4",
    "react-test-renderer": "16.8.6",
    "schedule": "0.4.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "assets"
    ]
  }
}

</pre>
</details>

Using a forked version: https://github.com/alexkendall/react-native-track-player
because of this issue: https://github.com/react-native-kit/react-native-track-player/issues/737

# Issue
After upgrading to RN 0.60.5 and upgrading react-native-track-player, our remote urls aren't playing anymore. This is an Android only app.

The first `console.log` goes through but the second doesn't? Not sure if it's getting held up during `TrackPlayer.add`.

Here is an example remote url: http://listen.radioking.com/radio/5040/stream/13349

# Code
```
export const play = ({ url, title, artist }) => async (dispatch, getState) =>
  await TrackPlayer.setupPlayer().then(async () => {
    const track = {
      id: url,
      url,
      title,
      artist,
      type: 'default',
    };

    console.log('before add');
    await TrackPlayer.add([track]);
    console.log('after add');
    if (url && url.length !== 0) {
      await TrackPlayer.play();

      dispatch({
        type: 'IS_MUTED',
        payload: false,
      });
    }
  });
```

**Comment by mbhuiayan** [comment]
@rsokz - how did you get around the issue? We are facing the same issue after upgrade to RN 59.9 and suing react-native-track-player 1.1.8. Thank you!

**Comment by Guichaguri** [comment]
It's an issue with Android API 28, it doesn't allow **http** anymore. You have to use **https**. If you still want to use http, you'll have to enable [clear text traffic](https://developer.android.com/training/articles/security-config.html#CleartextTrafficPermitted).
