### ISSUE TITLE
Foward of Media Controls on IOS only work twice

### ISSUE THREAD

**Issue by fcaride** [react-native-kit/react-native-track-player#746]
Hi there,

Im using the r13 version and this config: 
TrackPlayer.updateOptions({
      stopWithApp: true,
      capabilities: [
        Capability.Play,
        Capability.Pause,
        Capability.Stop,
        Capability.SkipToNext,
        Capability.SkipToPrevious
      ],
      compactCapabilities: [Capability.Play, Capability.Pause]
    });
  }, []);

In Android works alright but in IOS the foward of Media Controls only works once, after that the play button and the next button keep disabled.

Thanks!

**Comment by fcaride** [comment]
Any idea what it can be? It only allows me to skip the song 2 times, then the button stays gray.

Thanks!

**Comment by curiousdustin** [comment]
https://github.com/react-native-kit/react-native-track-player/commit/d3400a475d8be146aa25696b5f014dd538e2dd86 should resolve this.
