### ISSUE TITLE
how to use react-native-track-player?

### ISSUE THREAD

**Issue by waterflower124** [react-native-kit/react-native-track-player#754]
# Configuration

System:
    OS: macOS Mojave 10.14.5
    CPU: (16) x64 Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
    Memory: 8.13 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 15, 17, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 21.1.2, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.0, 29.0.0, 29.0.0, 29.0.0, 29.0.2
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-P | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
waterdeiMac:Waves wflower$ 

# Issue

I am going to use react-native-track-player.
I was going to install component following comment.

npm install react-native-track-player
npm install --save react-native-swift

And then tried to install cocoapod. cd ios/ & pod install.
Then I can get following message:
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "react-native-track-player":
  In Podfile:
    react-native-track-player (from `../node_modules/react-native-track-player`)

Specs satisfying the `react-native-track-player (from `../node_modules/react-native-track-player`)` dependency were found, but they required a higher minimum deployment target.

How can I use this component in my project?

# Code

**Comment by abdulwahabcs** [comment]
@waterflower124 #664 please got through it.
