### ISSUE TITLE
git submodule update --init --recursive      no such remote ref 81ca1ae6413c1c301dfedc590a8a70ca2997c129

### ISSUE THREAD

**Issue by gaodeng** [react-native-kit/react-native-track-player#758]
# Issue
error: no such remote ref 81ca1ae6413c1c301dfedc590a8a70ca2997c129
Fetched in submodule path 'ios/RNTrackPlayer/Vendor/AudioPlayer', but it did not contain 81ca1ae6413c1c301dfedc590a8a70ca2997c129. Direct fetching of that commit failed.

# Code

npm run prepublishOnly

**Comment by curiousdustin** [comment]
Related to #703

**Comment by curiousdustin** [comment]
`v1.2.3` no longer uses git submodule.
