### ISSUE TITLE
Issue with constantsToExport

### ISSUE THREAD

**Issue by jasongrishkoff** [react-native-kit/react-native-track-player#76]
```
react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift:48:19: Overriding method with selector 'constantsToExport' has incompatible type '() -> [String : Any]'
```

And yep, I have dummy.swift. This is with RNTrackPlayer 0.2.1 + XCode 9.0 + RN 0.50.3.

**Comment by Guichaguri** [comment]
`constantsToExport` is really a mystery, if you [search it on GitHub](https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=constantsToExport&type=), you'll see that each project uses a different type :/

If you want, you can test each of them in your app to find which one works

**Comment by anderslemke** [comment]
It looks like @olivierlesnicki already fixed this: https://github.com/olivierlesnicki/react-native-track-player/commit/b4a3b0fc4932c97b7466618416dd7d3dcd20d71f

**Comment by Guichaguri** [comment]
@anderslemke but that's actually the same as the dev branch: https://github.com/react-native-kit/react-native-track-player/blob/dev/ios/RNTrackPlayer/RNTrackPlayer.swift#L48

**Comment by anderslemke** [comment]
Good. So this fix will be out in the next release, right?

**Comment by dcvz** [comment]
It changed recently in a new RN version.. we'll need to fix it to where it works no matter the version of RN you're using. I hope to fix this later today

**Comment by anderslemke** [comment]
Yes. OK. I was confused. The change @olivierlesnicki introduced actually broke it on newest RN.

**Comment by dcvz** [comment]
This has been fixed in `develop` and it should work for all versions of RN 0.49+ if you're using an older version please use an older version of the lib.

**Comment by RassaLibre** [comment]
Had the same problem and since I am using RN 0.48.4, I had to switch to 0.2.1. Once I have done that, the app wound finally build :-)
