### ISSUE TITLE
Rate doesn't persist across tracks on iOS, and when trying to update with the `playback-track-changed` listener, it doesn't update the rate of the new track.

### ISSUE THREAD

**Issue by octodhruv** [react-native-kit/react-native-track-player#766]
# Configuration

Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?

System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 65.38 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.6 => 0.60.6
  npmGlobalPackages:
    react-native-cli: 2.0.1

version: "^1.1.8"

# Issue

When transitioning between tracks with the player, the rate set for the previous track (eg 1.5) doesn't persist across to the new track. Using the `playback-track-changed` listener doesn't update the rate across to the newly playing track, either. This may be to do with the listener being unreliable, as outlined in other issues.

# Code

Show us the code you are using

**Comment by Guichaguri** [comment]
Which platform are you seeing this issue?

**Comment by dhruv-finimize** [comment]
Hi, I'm seeing this on iOS - we're running both iOS and android, I will
check now if it's also occurring on android.

Thanks!

**Comment by HessiPard** [comment]
Have this issue too on IOS

**Comment by Johkade** [comment]
this issue still exists in 1.2.7 on iOS only. I temporarily fixed it by doing something like this in trach-changed-handler aswell as after each seek() call: 

setTimeout( ( ) => setRate(storedRate), 200);
setTimeout( ( ) => setRate(storedRate), 500);
setTimeout( ( ) => setRate(storedRate), 800);

since it doesn't always take effect after 200/500 ms I call it three times with a delay. it seems to work for now.
