### ISSUE TITLE
Unable to install unstable dev version

### ISSUE THREAD

**Issue by sebastianwd** [react-native-kit/react-native-track-player#770]
# Configuration
System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 1.07 GB / 7.94 GB
  Binaries:
    Node: 10.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 21, 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 25.0.2, 25.0.3, 26.0.1, 27.0.3, 28.0.3
      System Images: android-19 | Intel x86 Atom, android-21 | ARM EABI v7a, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-Q | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2

What `react-native-track-player` version are you using?

  "react-native-track-player": "^1.1.8",

# Issue

I run the following command as shown in the docs: npm install --save react-native-kit/react-native-track-player#dev

And I get these errors: 
`npm ERR! code 1
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! warning: templates not found in C:\Users\PCL\AppData\Local\Temp\pacote-git-template-tmp\git-clone-3ed6d18b.`
`npm ERR! error: Server does not allow request for unadvertised object 81ca1ae6413c1c301dfedc590a8a70ca2997c129.`
`npm ERR! Fetched in submodule path 'ios/RNTrackPlayer/Vendor/AudioPlayer', but it did not contain 81ca1ae6413c1c301dfedc590a8a70ca2997c129. Direct fetching of that commit failed.`

I tried to use hooks by importing them directly from node_modules directories with no success:

`import TrackPlayer, {
  useProgress,
  useTrackPlayerEvents,
} from 'react-native-track-player/lib/index';`

And then :
`const Player = props => {
  const progress = useProgress(1000); 
...`

Got the following error:
`TypeError: (0,_index.useProgress) is not a function. (In '(0, _index.useProgress)(1000)',
'(0,_index.useProgress)' is undefined)`

This library has been working perfectly for my app but without this feature I'm unable to build an usable player since using a Class component doesn't work neither, progress never updates

# Code
Full component

```import React, {useEffect} from 'react';
import PropTypes from 'prop-types';
import TrackPlayer, {
  useProgress,
  useTrackPlayerEvents,
} from 'react-native-track-player/lib/index';
import {
  Image,
  StyleSheet,
  TouchableOpacity,
  View,
  ViewPropTypes,
} from 'react-native';
import {Text} from 'react-native-paper';

const Player = props => {
  const progress = useProgress(1000);
  useEffect(() => {
    setupPlayer();
  }, []);

  const setupPlayer = async () => {
    await TrackPlayer.setupPlayer();
    TrackPlayer.updateOptions({
      stopWithApp: false,
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
        TrackPlayer.CAPABILITY_STOP,
      ],
      compactCapabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
      ],
    });
  };
  return (
    <View style={props.style}>
      <Text>player</Text>
    </View>
  );
};

export default Player;

**Comment by sebastianwd** [comment]
Nevermind, I switched to yarn and I could install the branch, after that the hooks worked

**Comment by curiousdustin** [comment]
#703
