### ISSUE TITLE
How to stop the player when other audio or music player play?

### ISSUE THREAD

**Issue by itokun99** [react-native-kit/react-native-track-player#782]
Hi, i using the library for my app and the functionality is Great! thanks for  dev team.
I have some issue and one of that is the Audio cannot stop if i play other player app like music app. Or if incomming call same that.
How should i do for this issue?

**Comment by octodhruv** [comment]
Hi, you can look into using the `remote-duck` event, listed here: https://react-native-kit.github.io/react-native-track-player/documentation/#remote-duck

You may also want to look at the `alwaysPauseOnInterruption` option: https://react-native-kit.github.io/react-native-track-player/documentation/#updateoptionsoptions

Hope that helps.

**Comment by PeterHassaballah** [comment]
Can this be re-opened or edited please the documentation links are expired
