### ISSUE TITLE
My notifications buttons don't work

### ISSUE THREAD

**Issue by fabiocosta88** [react-native-kit/react-native-track-player#786]
# Configuration

react-native: 0.61.4
What `react-native-track-player` version are you using? Last

# Issue

# Code
index.js

AppRegistry.registerComponent(appName, () => App);
TrackPlayer.registerPlaybackService(() => require('./tracker-service'));
TrackPlayer.setupPlayer().then(() => {});

TrackPlayer.updateOptions({  
  stopWithApp: true,

  capabilities: [
      TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE,
      TrackPlayer.CAPABILITY_STOP,
      TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
      TrackPlayer.CAPABILITY_SEEK_TO,
  ],
  compactCapabilities: [
    TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
    TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
  ]
});

tracker-service.js

import TrackPlayer from 'react-native-track-player';

module.exports = async function () {
    TrackPlayer.addEventListener('remote-play', () => TrackPlayer.play());

    TrackPlayer.addEventListener('remote-pause', () => TrackPlayer.pause());

    TrackPlayer.addEventListener('remote-stop', () => TrackPlayer.destroy());
}

**Comment by Guichaguri** [comment]
Please, can you describe what is not working? Does the notification doesn't show up? Are the buttons not visible? Are the buttons not being triggered when pressed?

**Comment by fabiocosta88** [comment]
@Guichaguri The buttons are appearing normally, but it's as if the notification buttons don't trigger the events.

**Comment by fabiocosta88** [comment]
Just restarting the project that went back to work, forgive my slowness: c
