### ISSUE TITLE
Override silent switch

### ISSUE THREAD

**Issue by taylorpringle** [react-native-kit/react-native-track-player#787]
Is there a way to override the silent switch on iOS and Android so that the sound plays anyway?

**Comment by Guichaguri** [comment]
There probably is some hacky way of doing it, but that doesn't fit the project scope. Sorry.

**Comment by mchandleraz** [comment]
@taylorpringle did you ever find a way to override the silent switch?

@Guichaguri Many apps have this behavior, so I'm curious why you say this is out of scope for this project?
