### ISSUE TITLE
Android API 28 doesn't play stream music

### ISSUE THREAD

**Issue by Maxtro** [react-native-kit/react-native-track-player#797]
Hi.
I made my first RN app for online radio.
Debug apk unsigned version worked good. I tested release apk signed version for Google Play and it is working well on emulator Android API 24, 26, 27, but doesn't work on emulator Android API 28.  I have a real device on Android 9 and my app doesn't play stream music, notification opens and instantly closes. I tried testing on another phone with Android 6 and music played.
I don't know what the problem is. I need help, please.
Is there a workaround for this problem?

 OS: macOS Sierra 10.12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
    Memory: 582.45 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

react-native-track-player version 1.1.6

**Comment by Maxtro** [comment]
I founded when this problem. 
Android API 28 banned **http** url. You mast using **https** url.

**Comment by moonstruck** [comment]
@Maxtro you may consider closing the issue. :)

**Comment by Guichaguri** [comment]
We should add this to the documentation at some point
