### ISSUE TITLE
[android] No task registered for key TrackPlayer, stack: startHeadlessTask

### ISSUE THREAD

**Issue by Saehanseul** [react-native-kit/react-native-track-player#803]
# Configuration

Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?

# Issue
Production app tracking crashes like this, but I can't simulation. because It's occurs somethimes at some users. 

My firebase crash like this for 5% of my user.

![스크린샷 2019-12-06 오후 2 24 15](https://user-images.githubusercontent.com/25199891/70298621-9e83ea00-1835-11ea-87a5-a755fb9b85be.png)

# Code

Show us the code you are using

**Comment by danielle-Cman** [comment]
My solution is add service in `index.js` file
```
import { AppRegistry } from 'react-native';
import TrackPlayer from 'react-native-track-player';

import App from './App';
AppRegistry.registerComponent('example', () => App);
TrackPlayer.registerPlaybackService(() => require('./service'));
```
and file `service` you could find in example project

**Comment by Guichaguri** [comment]
@Saehanseul can you send the part of the code where you register the service?

**Comment by Saehanseul** [comment]
@Guichaguri I'm using mobx and made trackplayerStore. So using Trackplayer.registerPlaybackService in constructor of trackplayerStore.

like this.

`  async initTrackPlayer() {
    await this.final()
    try {
      TrackPlayer.registerPlaybackService(() => async () => {
        trackPlayerListener['remote-play'] = TrackPlayer.addEventListener('remote-play', async (params) => {
          IS_DEV && console.log(`[${moment().format('YYYY.MM.DD h:mm:ss')}]` + `[DEV][LOG][C/urrentPlaySongStore][TrackPlayerEvent][remote-play] params=${params && JSON.stringify(params)}`)
          // TrackPlayer.play()
          if (stores.mixtapeStore.currentPlayingMixtape) {
            if (stores.mixtapeStore.currentPlayingMixtape && stores.mixtapeStore.currentUsersPlayMixtapes && stores.mixtapeStore.currentPlayingMixtape['id'] === stores.mixtapeStore.currentUsersPlayMixtapes['mixtapeId']) {
              stores.mixtapeStore.currentUsersPlayMixtapesTmpTime = new Date()
            }
            // await stores.currentPlaySongStore.playMusic(stores.currentPlaySongStore.currentSongIndex, stores.currentPlaySongStore.playTime)
            await stores.mixtapeStore.playMixtape(stores.mixtapeStore.currentPlayingMixtape)
          } 
        // other codes
  }`

**Comment by Guichaguri** [comment]
You have to make sure you're registering it in the initialization file, you can't depend on any component to be mounted. We highly recommend registering it right after registering the main component for your app, so no component has to be loaded in order to register the playback service.

**Comment by Saehanseul** [comment]
Thanks. I'll try it and check the firebase user bug after that:)

**Comment by mschouhan123** [comment]
> My solution is add service in `index.js` file
> 
> ```
> import { AppRegistry } from 'react-native';
> import TrackPlayer from 'react-native-track-player';
> 
> import App from './App';
> AppRegistry.registerComponent('example', () => App);
> TrackPlayer.registerPlaybackService(() => require('./service'));
> ```
> 
> and file `service` you could find in example project

Here in The root folder you can add the File called service.js and 

and Under Service.js you can write the below code. 

"" Start ""
import TrackPlayer from 'react-native-track-player';


module.exports = async function () {

  try {
    TrackPlayer.addEventListener('remote-play', () => {
      TrackPlayer.play()
    })

    TrackPlayer.addEventListener('remote-pause', () => {
      TrackPlayer.pause()
    });

    TrackPlayer.addEventListener('remote-next', () => {
      TrackPlayer.skipToNext()
    });

    TrackPlayer.addEventListener('remote-previous', () => {
      TrackPlayer.skipToPrevious()
    });

    TrackPlayer.addEventListener('remote-stop', () => {
      TrackPlayer.destroy()
    });
  } catch (error) { }

};
"" End ""
