### ISSUE TITLE
Cannot read property STATE_NONE of undefined

### ISSUE THREAD

**Issue by devWaleed** [react-native-kit/react-native-track-player#804]
# Configuration

Run `react-native info` in your project and share the content.

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 3.55 GB / 11.92 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

What `react-native-track-player` version are you using?

1.1.8

# Issue

I have tried to link automatically and I have tried to link manually as well but in both cases i get "Cannot read property STATE_NONE of undefined".

Using:

"react": "16.8.6",
"react-native": "0.60.5",

**Comment by c0bra** [comment]
This is the first issue I came across when searching for this exact error. It would be good to add a solution here for others who come along.

**Comment by musangowope** [comment]
@c0bra did you ever find a solution for the issue?

**Comment by c0bra** [comment]
Pretty sure i gave up and started using nativescript.
