### ISSUE TITLE
[Android] Is there a way to get session id?

### ISSUE THREAD

**Issue by Tiamatmate** [react-native-kit/react-native-track-player#808]
I need a session id to use it for Equalizer initialization.

**Comment by Guichaguri** [comment]
Can you describe what are you trying to achieve and what do you exactly need?

**Comment by Tiamatmate** [comment]
I am trying to get `audioSessionId` from `ExoPlayer`. It's needed for the `Equalizer` intialization. I have managed to do it by changing some code in the library, but I'd rather not make PR since code is neither optimized or elegant.

If anyone wants to though:

Basically in `ExoPlayback.java` I extend `SimpleExoPlayer` instead of Player and add 
```
        player.addAnalyticsListener(new AnalyticsListener() {
            /**
             * Called when the audio session id is set.
             *
             * @param eventTime      The event time.
             * @param audioSessionId The audio session id.
             */
            @Override
            public void onAudioSessionId(EventTime eventTime, int audioSessionId) {
                // do something with audioSessionId
            }
        });
```
Create a get method for the id, export it and the use it as needed.
The problem I have is knowing when I actually got the id (or waiting for the listener before returning value).

**Comment by Guichaguri** [comment]
Since you have to play around with native code to take advantage of that function, I don't think we should be adding this to the module, but I highly encourage you to fork it and make your own modifications. Sorry
