### ISSUE TITLE
How to play Opus encoded files on iOS?

### ISSUE THREAD

**Issue by felix-voicehub** [react-native-kit/react-native-track-player#809]
Hey,

I'm struggling with trying to play opus encoded files using this player on iOS via a URL. I have tried `.webm`, `.opus` and `.ogg` containers and it does not seem to want to play, it just keeps loading forever.

I have also tried various `Content-Type` headers for each of the mentioned containers, such as `audio/ogg; codecs=opus`, `audio/ogg`, `audio/webm`.

Any ideas? Judging by AVFoundations docs it should be possible.

**Comment by felix-voicehub** [comment]
Never mind, I found the solution: Use the `.caf` container. I can't link to any specific apple docs page because I could not find any, but there were many hints that this container should work and indeed it does.

**Comment by DavideValdo** [comment]
Just tried converting a 6.1MB .webm audio file to .caf through convertio.com...
Result: 77.5MB

Are you kidding me?

**Comment by felix-voicehub** [comment]
@DavideValdo No, I am not “kidding you”.

First of all, I don’t know what convertico is doing with your file. You should check if it’s actually using opus. Don’t confuse containers with codecs, you should use an opus encoded file in a caf container. I am using ffmpeg and get pretty much the same file size for the same opus encoded file in different containers.
