### ISSUE TITLE
very strange !!

### ISSUE THREAD

**Issue by tarahiw** [react-native-kit/react-native-track-player#815]
# Your documentation is very strange

I've been writing javaScript code for years, at least in several projects directly, which means I have come across many libraries and packages and have understood them all, or have some example of something like YouTube that made me understand him. your Library but tried to install your package for 11 days and it is over 15 days to try to use your help with the package but i can't
The result: Either I'm too slow-minded or stupid or you have a lot of bad documentation

**Comment by moonstruck** [comment]
@tarahiw From my experience the documentation is fine, maybe got a little bit outdated in last release. There is no step by step tutorial though.
You may start with example app in that case.
Another good way is to check how other people are using. [Github repos](https://github.com/react-native-kit/react-native-track-player/network/dependents?package_id=UGFja2FnZS0xNDc4NjE3Nw%3D%3D)
Also there's a discord channel to talk to other fellows.

**Comment by zacharywenner** [comment]
@moonstruck That helped me a lot thanks. For anyone that might be having a hard time, looking at some github repos is helpful.

This one was super helpful:
https://github.com/avorg/audioverse-mobile
They are using v2.0.0-rc13 and it seems they might be using this in production on the app stores even though it's not the stable release? Either way it shows the code and config with v2.0

**Comment by Guichaguri** [comment]
Yes, the documentation is not the best, but there are a few other resources you can use like @moonstruck and @zacharywenner already pointed out. We are accepting contributions to the documentation though.
