### ISSUE TITLE
Remote-* event called multiple times on Android

### ISSUE THREAD

**Issue by nastarfan** [react-native-kit/react-native-track-player#827]
# Configuration
  SDKs:
    Android SDK:
      API Levels: 23, 26, 28
      Build Tools: 28.0.3, 29.0.0, 29.0.2
      System Images: android-Q | Google APIs Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

"react-native-track-player": "^1.1.8",

# Issue

Hi, first of all, thank you for this awesome library. 

Currently, I am having a problem with `remote-*` events on Android, i.e. controlling the playback from the notification button (haven't tested it on iOS). 
I don't know if I setup the player correctly, so whenever I want to play some audio files I invoke `setupPlayer()` on `componentDidMount()` of my component and call `destroy()` when stopping the playback.
Everything works as expected except that apparently `remote-*` event within my playback service is executed multiple times, like when I press next button in the notification the player will skip multiple tracks (instead of only skip one track).
I see a pattern though, the number of times the `remote-*` event is executed is equal to the number of times my component that contains code for player setup (`setupPlayer()`) get mounted and unmounted. It is as if there are multiple listeners for `remote-*` event are registered, even tho I ensure the `destroy()` function is executed when stopping and unmounting that component.

# Code
*service.js*
```
import TrackPlayer from 'react-native-track-player';

module.exports = async function() {
  TrackPlayer.addEventListener('remote-play', () => {
    TrackPlayer.play();
  });

  TrackPlayer.addEventListener('remote-pause', () => {
    TrackPlayer.pause();
  });

  TrackPlayer.addEventListener('remote-next', () => {
    TrackPlayer.skipToNext();
  });

  TrackPlayer.addEventListener('remote-previous', () => {
    TrackPlayer.skipToPrevious();
  });

  TrackPlayer.addEventListener('remote-stop', () => {
    TrackPlayer.destroy();
  });
};
```

*Player component*
```
async componentDidMount(){
    await TrackPlayer.setupPlayer();
    TrackPlayer.updateOptions({
      stopWithApp: true,
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
        TrackPlayer.CAPABILITY_STOP,
      ],
      compactCapabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_STOP,
      ],
      alwaysPauseOnInterruption: false,
    });
    await TrackPlayer.reset();
    await TrackPlayer.add(tracks);
    await TrackPlayer.play();
}

handleStopPlayback = async () => {
    const playerState = await TrackPlayer.getState();
    if (
      playerState === TrackPlayer.STATE_PLAYING ||
      playerState === TrackPlayer.STATE_PAUSED
    ) {
      console.log('destroying..');
      await TrackPlayer.stop();
      await TrackPlayer.destroy();
    }
  };
```

Also, I make sure audio service is executed only once when the app starts

**Comment by curiousdustin** [comment]
The discussion in #433 may help you.

**Comment by curiousdustin** [comment]
Basically you need to make sure you are removing listeners, or only add them once, even if you setup multiple times.

**Comment by nastarfan** [comment]
@curiousdustin thank you for your direction, didn't find the discussion before submitting this issue. Will try to work on it and report back

**Comment by nastarfan** [comment]
Just re-debug my code, the service indeed is executed multiple times. For now using your 'hack' does the trick, thank you

**Comment by mahmed0715** [comment]
+1 i am also having this issue.. Thanks folks
