### ISSUE TITLE
Can't update stop icon

### ISSUE THREAD

**Issue by sjsakib** [react-native-kit/react-native-track-player#833]
# Configuration

Run `react-native info` in your project and share the content.
```
System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 133.40 MB / 7.69 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.14.1 - /tmp/yarn--1579197020776-0.5122757383191685/node
    Yarn: 1.21.1 - /tmp/yarn--1579197020776-0.5122757383191685/yarn
    npm: 6.13.4 - /usr/bin/npm
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4
```
What `react-native-track-player` version are you using? `1.2.0`

# Issue
Cannot update icons in the notification. In the code below can confirm `Icon.getImageSource` returns a `Resource Object` that works perfectly with an `Image` component.

# Code
```js
const CloseIcon = await Icon.getImageSource('close');
const FastForwardIcon = await Icon.getImageSource('fast-forward');
const FastRewindIcon = await Icon.getImageSource('fast-rewind');

TrackPlayer.updateOptions({
  capabilities: [
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
    TrackPlayer.CAPABILITY_JUMP_FORWARD,
    TrackPlayer.CAPABILITY_JUMP_BACKWARD,
    TrackPlayer.CAPABILITY_STOP,
  ],
  stopWithApp: true,
  stopIcon: CloseIcon,
  forwardIcon: FastForwardIcon,
  rewindIcon: FastRewindIcon,
});
```

**Comment by shani-maini** [comment]
Same Here on ios only

**Comment by curiousdustin** [comment]
@sjsakib what platform are you having trouble with?

**Comment by sjsakib** [comment]
@curiousdustin I tried android

**Comment by curiousdustin** [comment]
On android, I think the custom icons will only work in release builds. Are you testing debug or release builds?

**Comment by sjsakib** [comment]
I tested release build

**Comment by curiousdustin** [comment]
The icons are not customizable on iOS.

https://react-native-kit.github.io/react-native-track-player/documentation/#updateoptionsoptions

**Comment by curiousdustin** [comment]
On Android, I can also confirm that custom icons will not appear when using debug builds connected to the metro server.

Custom icons for the media controls DO work for me on android release builds.

@sjsakib What version are you using for react-native and react-native-track-player?

**Comment by sjsakib** [comment]
@curiousdustin 
```
"react-native": "0.61.4",
"react-native-track-player": "1.2.0"
```

**Comment by curiousdustin** [comment]
Are you able to share the image(s) you are trying to use?

**Comment by sjsakib** [comment]
I was trying to use icons from [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) with `Icon.getImageSource`

**Comment by Guichaguri** [comment]
Android only accepts static image assets bundled in the apk, that's why it only works in a release build. 
The vector icons module builds the icon assets dynamically, which will not work.

Only icons bundled in the apk, loaded with `require(...)`/`import ...` will work.
