### ISSUE TITLE
Updating Queue through React Navigation

### ISSUE THREAD

**Issue by Tanvirazad3449** [react-native-kit/react-native-track-player#842]
# Configuration

System:
    OS: Windows 10 10.0.18362
    CPU: (16) x64 Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
    Memory: 3.94 GB / 15.92 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
`react-native-track-player` version: 1.1.8

# Issue

For a Spotify Clone, my file structure is as shown:

RootStack
      |
BottomTabNavigator
      |
Home, Search, Library, TabBarComponent(to implement the mini music player of spotify).

My query is, how can i update the queue in the track player from, say, Home Screen or Library Screen?

**Comment by felix-voicehub** [comment]
You import TrackPlayer and call the relevant methods (`.getQueue()`, `.remove()`, `.add()`, `.getCurrentTrack()`), which can be found in the docs. With these 4 you can manage every aspect of the queue.
