### ISSUE TITLE
iOS player widget not working with version 1.2.2 

### ISSUE THREAD

**Issue by Sathyanarayan09** [react-native-kit/react-native-track-player#845]
After upgrading from 1.1.8 to 1.2.2 version, iOS notification widgets are not calling remote events.

**Comment by DNA-h** [comment]
confirmed. Same code and same semantic did not work on 1.2.2 but with JUST reverting to 1.1.8 it worked. I must mention i dabbled a lot on making 1.2.2 working and ventured a lot on swift code but with no avail. whatever it is that makes 1.2.2. broken I am happy to find out and help but have no major clue.

**Comment by nesinervink** [comment]
I have encountered same issue after upgrading 1.1.8 to 1.2.2, yet this did help me solve the issue: https://github.com/react-native-kit/react-native-track-player/issues/831

**Comment by curiousdustin** [comment]
https://github.com/react-native-kit/react-native-track-player/commit/d3400a475d8be146aa25696b5f014dd538e2dd86 should resolve this.

**Comment by DNA-h** [comment]
good. will try it.
