### ISSUE TITLE
Android CAPABILITY_SEEK_TO not shows Seek bar in notification.

### ISSUE THREAD

**Issue by hussnainghani** [react-native-kit/react-native-track-player#855]
# Configuration

Run `react-native info` in your project and share the content.
`System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 116.76 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1`
What `react-native-track-player` version are you using?
`react-native-track-player: ^1.1.8`

# Issue
i add CAPABILITY_SEEK_TO in capabilities but seek bar not showing in notification. i also added other capabilities like
`TrackPlayer.CAPABILITY_PLAY,
TrackPlayer.CAPABILITY_PAUSE,
TrackPlayer.CAPABILITY_STOP,
TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
TrackPlayer.CAPABILITY_SEEK_TO,`
all of these are working perfect except `CAPABILITY_SEEK_TO`

# Code
`TrackPlayer.setupPlayer();
TrackPlayer.updateOptions({
  RATING_5_STARS, RATING_PERCENTAGE
  ratingType: TrackPlayer.RATING_5_STARS,
  stopWithApp: true,
  capabilities: [
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
    TrackPlayer.CAPABILITY_STOP,
    TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
    TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
    TrackPlayer.CAPABILITY_SEEK_TO,
  ],
  compactCapabilities: [
    TrackPlayer.CAPABILITY_PLAY,
    TrackPlayer.CAPABILITY_PAUSE,
  ],
});`

and here is event listener for `remote seek`
`TrackPlayer.addEventListener('remote-seek', async (position) => {
      await TrackPlayer.seekTo(position)
    });`

**Comment by lnickdnguyen** [comment]
@hussnainghani How did you fix this? I am running into the same issue, but have included TrackPlayer.CAPABILITY_SEEK_TO in my notificationCapabilities: [] as well.

**Comment by curiousdustin** [comment]
see #865 and #721
