### ISSUE TITLE
Ensure one event listener is registered in service.js

### ISSUE THREAD

**Issue by neoassyrian** [react-native-kit/react-native-track-player#856]
It's a question more than an issue, but how do I prevent the app from registering the remote events multiple times in the service.js file? 

Keep in mind we don't have any react states at the point because the UI might not be mounted.

**Comment by mrTuomoK** [comment]
I set a variable that keeps track if they are added or not... if not --> add & set the variable to true. A bit dirty but works

**Comment by neoassyrian** [comment]
> bit

Do you set the variable in the service itself? Can you send me an example code please. 

Thanks

**Comment by mrTuomoK** [comment]
Just a dumb variable before registering the eventlisteners (global) like this:

let didAddListeners = false;

module.exports = async function addService() {
  if (!didAddListeners) {
    didAddListeners = true;

    TrackPlayer.addEventListener('remote-play', () => {
      TrackPlayer.play();
    });
.........

Add service is the thing called from the registering of the service in the app

**Comment by neoassyrian** [comment]
Great thanks.
