### ISSUE TITLE
Depracation warning on rnpm when running "react-native link" 

### ISSUE THREAD

**Issue by obsd** [react-native-kit/react-native-track-player#858]
# Configuration

run react-native link on the getting started documentation

# Issue
`warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-swift: https://github.com/rhdeck/react-native-swift#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.`

**Comment by curiousdustin** [comment]
Looks like this has been resolved in react-native-swift. https://github.com/rhdeck/react-native-swift/pull/2
