### ISSUE TITLE
dev, v2 branch working?

### ISSUE THREAD

**Issue by Saehanseul** [react-native-kit/react-native-track-player#861]
I wanna test of dev and v2 latest branch.
but latest v2 branch can't install and dev branch not build.

`<unknown>:0: note: filenames are used to distinguish private declarations with the same name
<unknown>:0: error: filename "DSL.swift" used twice: '/Users/saehanseul/naivy/bitbucket/mixtape/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/Example/Pods/Quick/Sources/Quick/DSL/DSL.swift' and '/Users/saehanseul/naivy/bitbucket/mixtape/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/Example/Pods/Quick/Sources/Quick/DSL/DSL.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
<unknown>:0: error: filename "NowPlayingInfoCenter.swift" used twice: '/Users/saehanseul/naivy/bitbucket/mixtape/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/NowPlayingInfoController/NowPlayingInfoCenter.swift' and '/Users/saehanseul/naivy/bitbucket/mixtape/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/NowPlayingInfoController/NowPlayingInfoCenter.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
<unknown>:0: error: filename "NowPlayingInfoController.swift" used twice: '/Users/saehanseul/naivy/bitbucket/mixtape/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/NowPlayingInfoController/NowPlayingInfoController.swift' and '/Users/saehanseul/naivy/bitbucket/mixtape/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/NowPlayingInfoController/NowPlayingInfoController.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1`

How can I use it?

**Comment by stokesbga** [comment]
Remove the example folder from the target from node modules manually, with a patch-package, or fork.

**Comment by curiousdustin** [comment]
This should be resolved on `dev` and `v2` branches.
