### ISSUE TITLE
How do i prevent autoplay in que?

### ISSUE THREAD

**Issue by Acetyld** [react-native-kit/react-native-track-player#862]
Hello!

We use it for our soundboard. We add all downloaded sounds from our api to the track list, and play the corresponding one on the click of a button, but how do we prevent it from autoplaying. I tried using a listener on track change, but i cant manage to stop it.

**Comment by curiousdustin** [comment]
Duplicate. See https://github.com/react-native-kit/react-native-track-player/issues/869
