### ISSUE TITLE
Disable/Hide Audio Events/Media Controls from Notification and Lock Screen

### ISSUE THREAD

**Issue by creativeedge** [react-native-kit/react-native-track-player#868]
Is there a way to not hide/disable media controls and app status from notification/lock screen, not just media controls?

We are electing to use a dedicated media control library so that we can incorporate Spotify and other services as well into one player.

React Native Track Player currently does now support Spotify SDK.

**Comment by moonstruck** [comment]
In that case `react-native-sound` or` react-native-audio-toolkit` is better choice I guess if you manage player queue and notification service outside this library.

**Comment by creativeedge** [comment]
> In that case `react-native-sound` or` react-native-audio-toolkit` is better choice I guess if you manage player queue and notification service outside this library.

Awesome.  Thanks for quick response.  Unfortunately, each one of those libraries only work with either iOS or Android.  React Native Track Player is perfect, but we want to use https://github.com/tanguyantoine/react-native-music-control for controlling all audio including Spotify.  We have successfully got Spotify working, but in Android,  now 2 separate instances appear in notification area for same app when we switch between Spotify and non Spotify tracks.

We just want to kill the notification for React Native track player all together.

**Comment by creativeedge** [comment]
Is there a way to get the "notification" id of the widget in Android then use something like this to kill it?
https://stackoverflow.com/questions/42703830/delete-previous-notifications-using-react-native-push-notification

**Comment by Guichaguri** [comment]
No, that's not possible due to the nature of the module. In order to have a more robust player and play smoothly in background, the module is built around an Android service, which requires a notification to be up in order to allow allocating more resources.
Those other modules play music in the app's main thread/process.
