### ISSUE TITLE
Avoid autoplay next song when current finish

### ISSUE THREAD

**Issue by BRKsReginaldo** [react-native-kit/react-native-track-player#869]
# Configuration

System:
    OS: Linux 4.15 Linux Mint 19.2 (Tina)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 648.68 MB / 15.39 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    Yarn: 1.19.2 - /usr/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

What `react-native-track-player` version are you using? **^1.2.2**

# Issue
Hey guys, there is any way I can avoid the player from playing the next song, when the current finishes ? I have a streaming radios app, and i don't want the player to jump to the next radio if the streaming of the current  one sudenly stops (its rare but sometimes happen).

**Comment by curiousdustin** [comment]
One way to do this currently, is to manage the queue on your side. Only add a single track to the TrackPlayer at a time.

**Comment by curiousdustin** [comment]
@Guichaguri do you think a way to disable auto advancing the queue would be a good addition to the other queue improvements in v2?

**Comment by curiousdustin** [comment]
Another request: https://github.com/react-native-kit/react-native-track-player/issues/862

**Comment by Guichaguri** [comment]
Another one: #918
