### ISSUE TITLE
react-native-track-player": "^0.2.1 build failed in Android.

### ISSUE THREAD

**Issue by arunkrishna39** [react-native-kit/react-native-track-player#87]
"react": "16.0.0-alpha.12",
    "react-native": "0.46.4",
    "react-native-track-player": "^0.2.1"
NPM Version:3.10.10
Node Version:v6.11.1
Android TrackModule.java Throwing Error.
final ArrayList trackList = Arguments.toList(tracks);
toList Method not there in Arguments Class.
Error:(174, 46) error: cannot find symbol method toList(ReadableArray)

**Comment by Guichaguri** [comment]
Can you please add any information to the issue? Such as the React Native version, the build error, whether you're using other packages, etc

**Comment by Guichaguri** [comment]
You have to update React Native. This module only supports React Native 0.49 or greater.
