### ISSUE TITLE
notification showing after twice setup react native track player ios

### ISSUE THREAD

**Issue by shani-maini** [react-native-kit/react-native-track-player#871]
await TrackPlayer.setupPlayer().then(async () => {
        await TrackPlayer.reset();
        await TrackPlayer.updateOptions({
        stopWithApp: true,
        capabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
          TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
          TrackPlayer.CAPABILITY_SEEK_TO
        ]
      });

**Comment by curiousdustin** [comment]
@shani-maini can you explain you issue a bit more?

**Comment by curiousdustin** [comment]
Closing. Please let us know if you have more details.
