### ISSUE TITLE
Can`t stream https

### ISSUE THREAD

**Issue by markom983** [react-native-kit/react-native-track-player#872]
# Configuration
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3 CPU       M 350  @ 2.27GHz
    Memory: 128.01 MB / 3.65 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    npm: 6.10.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2

What `react-native-track-player` version are you using?
    "react-native-track-player": "^1.2.2",

# Issue

I have a problem to stream https url`s,  http is working fine. What can be the problem?

# Code

index.js

AppRegistry.registerComponent(appName, () => Main)
TrackPlayer.registerPlaybackService(() => require('./service.js'));

service.js

import TrackPlayer from 'react-native-track-player';

module.exports = async function() {

  TrackPlayer.addEventListener('remote-play', () => {
    TrackPlayer.play()
  })

  TrackPlayer.addEventListener('remote-pause', () => {
    TrackPlayer.pause()
  });

  TrackPlayer.addEventListener('remote-next', () => {
    TrackPlayer.skipToNext()
  });

  TrackPlayer.addEventListener('remote-previous', () => {
    TrackPlayer.skipToPrevious()
  });

  TrackPlayer.addEventListener('remote-stop', () => {
    TrackPlayer.destroy()
  });

};

home.js

class Home extends Component {

componentDidMount() {
    this.props.getDatabase();
    TrackPlayer.setupPlayer().then(async () => {
      TrackPlayer.updateOptions({
        stopWithApp: true,
        capabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_STOP
        ],
        compactCapabilities: [
          TrackPlayer.CAPABILITY_PLAY,
        ]
      });
  }).catch(error => {
    console.log('SETUP PLAYERRR', error)
  })
  }

    play = (item) =>	{
      return new Promise((resolve) => {
         this.setState({play: true, id: item.id})
         TrackPlayer.add({
             id: "1", //id ={item.id}
             url: item.url,
             title: "Track Title",
             artist: "Track Artist",
         }).then(res => {
            TrackPlayer.play();
            resolve()
         }).catch(error => {
           console.error('ERROR', error)
        })
     })
    }

}

**Comment by jcurlier** [comment]
Some of our users are experiencing `An SSL error has occurred and a secure connection to the server cannot be made.` - are you experiencing the same error?  Maybe only on some `OS 13.x` devices, not sure yet.

**Comment by markom983** [comment]
I dont get any error thats a problem 

if i put something like this

    TrackPlayer.setupPlayer().then(async () => {
      TrackPlayer.add({
          id: "1",
          url: "https://www.soundeffectsplus.com/uploads/prod_audio/40052174_money-coins-in-hand-03.mp3",
          title: "Track Title",
          artist: "Track Artist",
        })
      TrackPlayer.updateOptions({
        stopWithApp: true,
        capabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_STOP
        ],
        compactCapabilities: [
          TrackPlayer.CAPABILITY_PLAY,
        ]
      });
      TrackPlayer.play();
  }).catch(error => {
    console.log('SETUP PLAYERRR', error)
  })


then https url will play but if i put https url of radio for example this one https://streaming.tdiradio.com/top40.mp3
then it wont play, notification appear in status bar and after one second dissapear

**Comment by markom983** [comment]
This is the error im getting

java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

is there any fix for react native?

**Comment by markom983** [comment]
Add this to MainApplication.java

//Create a trust manager that does not validate certificate chains
TrustManager[] trustAllCerts = new TrustManager[] {new X509TrustManager() {
        public java.security.cert.X509Certificate[] getAcceptedIssuers()
        {
            return null;
        }
        public void checkClientTrusted(X509Certificate[] certs, String authType)
        {
            //
        }
        public void checkServerTrusted(X509Certificate[] certs, String authType)
        {
            //
        }
    }

//Install the all-trusting trust manager
try {
        SSLContext sc = SSLContext.getInstance("TLS");
        sc.init(null, trustAllCerts, new java.security.SecureRandom());
        HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());
    } catch (KeyManagementException|NoSuchAlgorithmException e) {
        e.printStackTrace();
}

**Comment by curiousdustin** [comment]
@markom983 did your last comment resolve this issue for you?

**Comment by markom983** [comment]
yes, this fix work for me
