### ISSUE TITLE
react-native-track-player 

### ISSUE THREAD

**Issue by vinylmix** [react-native-kit/react-native-track-player#875]
As i am new to this react native track player, i have a few questions, 

Does this player allow me to download or cache live shoutcast streams onto my android phone? instead of listening to a full hour mix on a shoutcast stream, am i able to rather quickly download each track of the mix one by one as this would save me time, in other words extract and break down the metadata of each song in the mix and choose which songs of the mix i want to keep on my phone and cache for offline listening, i don't wish to listen for long periods to a shoutcast stream, in other words i just want to tune in for a minimal amount of time and download as much as possible to build a offline listening app for myself, can this react native player guarantee me this to make it worth my while.

I also hope this player detects now playing info of a shoutcast stream even if the now playing info of the stream is not available, is this player able to show the last played history of a stream to possibly download or cache those tracks also, appreciate some answers, thanks.

**Comment by curiousdustin** [comment]
No. Downloading and storing audio files is not a feature of this library. 

I believe the answer to your second question is also no, but I am not positive.

**Comment by mvhk** [comment]
Closes react-native-kit/react-native-track-player#875

**Comment by Guichaguri** [comment]
For the second question, it dispatches events with shoutcast metadata (if they are available) on Android and hopefully in iOS in the near future (#937), but it doesn't keep a history or retrieves one, this is out of the scope of the project and can be done with pure JS.

**Comment by vinylmix** [comment]
I have just read about internet radio broadcasters having serious issues with listeners using react native track player 3.03, these are abusive listeners with blacklisted IP addresses according to radio broadcasters to the extent that listeners using react native track player get banned on radio platforms, this is where it gets interesting, after they have been banned, 80% of these banned listeners duplicate random IP addresses to urgently have another go to tune into the same radio platform using react native track player under a different IP address, most of these abusive listeners recreate up to 20 different IP addresses and keep slamming radio stations with this forceful behavior using react track native player, this seems very dodgy and in fact radio stations are classing these listeners as brief stream rippers with a listening length of 15 minutes a time (enough to download a full currently playing 1 hour mix).

Well, this is what i have read according to radio broadcasters, much to my surprise, i guess radio broadcasters see listener activity that none of us can see, one tends to actually believe them.

Thought i would share this with you.
