### ISSUE TITLE
a sample code for adding header to stream file

### ISSUE THREAD

**Issue by hoseineghbal** [react-native-kit/react-native-track-player#876]
`react-native-track-player` : > 2

hi is possible to tell me how i can play an stream by authorization (BEARER) header token ...?

**Comment by nesinervink** [comment]
At the bottom of Track Object [params list](https://react-native-kit.github.io/react-native-track-player/documentation/#track-object) you will find a _headers_ param.

**Comment by hoseineghbal** [comment]
find document
