### ISSUE TITLE
[bug/ios] background controls not show on IOS

### ISSUE THREAD

**Issue by fernando-pascoal** [react-native-kit/react-native-track-player#878]
# Configuration

react-native-cli: 2.0.1
react-native: 0.61.5
react-native-track-player: ^2.0.0-rc13
xcode: version 11.3.1 (11C504)

# Issue
Problems only at ios, when in background not show the action buttons and the quality of audio is decreased with hls type.

# Code
###service.js
> import TrackPlayer, {Event} from 'react-native-track-player';
> module.exports = async function() {
> TrackPlayer.addEventListener(Event.RemotePlay, () => TrackPlayer.play());
> TrackPlayer.addEventListener(Event.RemotePause, () => TrackPlayer.pause());
> };

### init
import {put, call, select, all, takeLatest, take} from 'redux-saga/effects';
import {eventChannel} from 'redux-saga';
import * as PlayerActions from './actions';
import TrackPlayer, {Capability, Event, State} from 'react-native-track-player';

export function* setupTrackPlayer() {
  console.log('setup TrackPlayer');
  yield call(TrackPlayer.setupPlayer);
  // yield call(TrackPlayer.reset);
  TrackPlayer.updateOptions({
    waitForBuffer: true,
    stopWithApp: false,
    capabilities: [Capability.Play, Capability.Pause, Capability.Stop],
    // compactCapabilities: [Capability.Play, Capability.Pause, Capability.Stop],
    // notificationCapabilities: [
    //   Capability.Play,
    //   Capability.Pause,
    //   Capability.Stop,
    // ],
  });
  yield call(statusChanged);
  yield call(trackChanged);
}

function* statusChanged() {
  const channel = eventChannel(emitter => {
    const onStatusChanged = TrackPlayer.addEventListener(
      Event.PlaybackState,
      emitter,
    );
    return () => onStatusChanged.remove();
  });
  try {
    while (true) {
      const {state} = yield take(channel);
      yield put(PlayerActions.setState({state}));
      if (state === State.Ready) {
        yield put(PlayerActions.play());
      }
    }
  } finally {
    channel.close();
  }
}

function* trackChanged() {
  const channel = eventChannel(emitter => {
    const onTrackChange = TrackPlayer.addEventListener(
      Event.PlaybackTrackChanged,
      emitter,
    );
    return () => onTrackChange.remove();
  });
  try {
    while (true) {
      const res = yield take(channel);
      console.tron.log(res);
    }
  } finally {
    channel.close();
  }
}

export function* setPodcast({podcast, episodeId}) {}

export function* setPlaylist(action) {
  try {
    const {playlist, header} = action.payload;
    yield call(TrackPlayer.stop);
    yield call(TrackPlayer.reset);
    const array = [...playlist];
    yield call(TrackPlayer.add, array);
    // yield call(TrackPlayer.play);
  } catch (error) {
    console.log(error);
  }
}

function* play() {
  TrackPlayer.play();
}

function* pause() {
  TrackPlayer.pause();
}

export function* prev() {}

export function* next() {}

export default all([
  takeLatest('@player/setup', setupTrackPlayer),
  takeLatest('@player/play', play),
  takeLatest('@player/pause', pause),
  takeLatest('@player/setPlaylist', setPlaylist),
]);

**Comment by fernando-pascoal** [comment]
someone can help me?

**Comment by rochapablo** [comment]
Did you figure it out?
