### ISSUE TITLE
Invariant violation Native module cannot be null

### ISSUE THREAD

**Issue by sreelash** [react-native-kit/react-native-track-player#880]
# Configuration

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 28.60 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

"react-native-track-player": "^1.2.2"

# Issue

NPM Installed
POD Installed

Installed the packages based on the following link:
https://react-native-kit.github.io/react-native-track-player/install/

When I build the Xcode project on simulator, I get the error **Invariant violation Native module cannot be null**

# Code

import React, {Component} from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
} from 'react-native';
import TrackPlayer from 'react-native-track-player'

class App extends Component {

  componentDidMount() {
    var track = {
        id: 'unique track id',
        url: 'http://example.com/avaritia.mp3',
        title: 'Avaritia',
        artist: 'deadmau5',
        album: 'while(1<2)',
        genre: 'Progressive House, Electro House',
        date: '2014-05-20T07:00:00+00:00',

        artwork: 'http://example.com/avaritia.png',
    };

    var track2 = {
        id: 'unique track id',
        url: 'http://example.com/avaritia.mp3',
        title: 'Avaritia',
        artist: 'deadmau5',
        album: 'while(1<2)',
        genre: 'Progressive House, Electro House',
        date: '2014-05-20T07:00:00+00:00',

        artwork: 'http://example.com/avaritia.png',
    };

    TrackPlayer.setupPlayer().then(async () => {
      TrackPlayer.add([track, track2]).then(function() {

      });
     TrackPlayer.play();
    });
  }

  render() {
    return(
      <View>
      </View>
    )
  }
}

export default App;
![Screenshot 2020-03-17 at 8 50 33 PM](https://user-images.githubusercontent.com/1913797/76871807-88081880-6891-11ea-8796-c2a15d87750b.png)

**Comment by fernando-pascoal** [comment]
try link manualy, this error is because not linked something

**Comment by curiousdustin** [comment]
@sreelash did you get this resolved? 

https://github.com/react-native-kit/react-native-track-player/issues/503#issuecomment-513427501 may help.

**Comment by curiousdustin** [comment]
Duplicate. See https://github.com/react-native-kit/react-native-track-player/issues/866
