### ISSUE TITLE
ProgressComponent in react-native-track-player: Super expression must either be null or a function

### ISSUE THREAD

**Issue by sreelash** [react-native-kit/react-native-track-player#882]
# Configuration

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 25.49 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

"react-native-track-player": "^2.0.0-rc10"

# Issue
My target is to trace the audio playing position and buffer position from react-native-track-player. I had spend a whole day with various options and finally I am posting here. Hope someone can help with this. Also I am a newbie in react-native. I hope that well explained below about the issue, if not please let me know.

I have a problem in ProgressComponent of react-native-track-player. The basic code starts working to play a remote audio file, but the problem happens on using the ProgressComponent to get the position, duration and bufferedPosition of playing audio.

Following error is throwing when I extend {ProgressComponent} in my custom component name ProgressBar.js.

Super expression must either be null or a function

Observation: If I change the extension of ProgressComponent to simple {Component} from react, everything starts working. Basically this seems as export issue, but I have already exported the module from ProgressBar.js. From a post I have seen that circular dependencies can also throw a similar error.

https://medium.com/@anuhosad/react-errors-super-expression-must-either-be-null-or-a-function-4aac6e5173ad

# Code

App.js

```
import React, {Component} from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
} from 'react-native';
import TrackPlayer from 'react-native-track-player'
import ProgressBar from './src/ProgressBar.js'
import MyComponent from './MyComponent'

export default class App extends Component {

  componentDidMount() {
    var track = {
        id: 'unique track id',
        url: 'https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.mp3',
        title: 'Avaritia',
        artist: 'deadmau5',
        album: 'while(1<2)',
        genre: 'Progressive House, Electro House',
        date: '2014-05-20T07:00:00+00:00',

        artwork: 'http://example.com/avaritia.png',
    };

    var track2 = {
        id: 'unique track id',
        url: 'https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.mp3',
        title: 'Avaritia',
        artist: 'deadmau5',
        album: 'while(1<2)',
        genre: 'Progressive House, Electro House',
        date: '2014-05-20T07:00:00+00:00',

        artwork: 'http://example.com/avaritia.png',
    };

    TrackPlayer.setupPlayer().then(async () => {
      TrackPlayer.add([track]).then(function() {

      });

      TrackPlayer.play();
    });
  }

  render() {
    return(
      <SafeAreaView>
        <Text>Begin +{}+ Ensd</Text>
        <ProgressBar />
      </SafeAreaView>
    )
  }
}
```

ProgressBar.js

```
import React from 'react';
import { View, Text, StyleSheet, TouchableWithoutFeedback } from 'react-native';
import TrackPlayer, {ProgressComponent} from 'react-native-track-player';

class ProgressBar extends ProgressComponent {
  render() {
    // const position = formatTime(Math.floor(this.state.position));
    // const duration = formatTime(Math.floor(this.state.duration));
![IMG_7519](https://user-images.githubusercontent.com/1913797/77069052-b6126780-6a0d-11ea-9467-23d39bcd715f.png)
![IMG_7519](https://user-images.githubusercontent.com/1913797/77069086-c7f40a80-6a0d-11ea-91d2-daedcb33613c.png)


    // const info = position + ' / ' + duration;
    //
    // let progress = this.getProgress() * 100;
    // let buffered = this.getBufferedProgress() * 100;
    //
    // console.log('Progress - '+progress)
    // console.log('Buffered - '+buffered)

    return(
      <View style={styles.container}>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    width: 300,
    height: 30,
    backgroundColor: 'red'
  }
})

module.exports = ProgressBar;
```

**Comment by sreelash** [comment]
![IMG_7519](https://user-images.githubusercontent.com/1913797/77069150-e78b3300-6a0d-11ea-9b0f-76316a49bed9.png)

This is the screenshot of error.

**Comment by oscarchs** [comment]
same issue

**Comment by ramazanarslan** [comment]
same issue any solution @sreelash  @oscarchs

**Comment by ramazanarslan** [comment]
okey, i found , we need to convert our class component to Hook.  https://github.com/react-native-kit/react-native-track-player/issues/662

**Comment by curiousdustin** [comment]
Correct. If you want to use v2, you need to convert to using hooks.
