### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by B1Z1** [react-native-kit/react-native-track-player#887]
When I add react-native-track-player and react-native-swfit and after linking. 
I have an error:
"Native module cannot be null"

When I do manually in ios, pod install. I get an error like 
"[!] Unable to add a source with url `https://cdn.cocoapods.org/` named `trunk`.
You can try adding it manually in `C:/Users/Ilushka/.cocoapods/repos` or via `pod repo add`."

Can you help me with this problem? 

react-native latest version

**Comment by sinafbd** [comment]
same here +1

**Comment by homanp** [comment]
@B1Z1 see this answer https://github.com/react-native-kit/react-native-track-player/issues/503#issuecomment-513427501

**Comment by curiousdustin** [comment]
@B1Z1 did this resolve your issue?

**Comment by B1Z1** [comment]
I change library to expo av. Maybe in future I will check this!
