### ISSUE TITLE
install latest version, the app cannot open on Android device.

### ISSUE THREAD

**Issue by catmans1** [react-native-kit/react-native-track-player#890]
# Configuration

Run `react-native info` in your project and share the content.
What `react-native-track-player` version are you using?
```
"react-native-track-player":  "^1.2.2",
 "react-native": "0.61.5",
```
# Issue
install latest version, the app cannot open on Android device.
on iOS work well

# Code
I just install in react native project

Any solution for this?

**Comment by girish54321** [comment]
Same issue app crashes after adding this package.

**Comment by homanp** [comment]
Same here. Can't run after installing this thing.

**Comment by strawberry-code** [comment]
Which error do you get? Any log?

**Comment by sgerendasy** [comment]
It's also crashing on load for me, right after I adding via 'npm install react-native-track-player'.
I tried manually linking as well without luck. I'm using react-native 61.5. gradle syncs without issues. There really isn't much in the stacktrace since it fails so early.

```
[12:20:43] D | ReactNative ▶︎ ReactInstanceManager.ctor()
[12:20:43] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.recreateReactContextInBackgroundInner()
[12:20:43] D | ReactNative ▶︎ ReactInstanceManager.onJSBundleLoadedFromServer()
[12:20:43] D | ReactNative ▶︎ ReactInstanceManager.recreateReactContextInBackground()
                           └ ReactInstanceManager.runCreateReactContextOnNewThread()
[12:20:43] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()
[12:20:43] D | ReactNative ▶︎ Initializing React Xplat Bridge.
[12:20:43] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge
[12:20:43] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge
                           └ CatalystInstanceImpl.runJSBundle()
[12:20:43] D | ReactNative ▶︎ ReactInstanceManager.setupReactContext()
                           └ CatalystInstanceImpl.initialize()
[12:20:43] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()
```

**Comment by homanp** [comment]
Solved by enabling headers for the React package in the Podfile.

**Comment by homanp** [comment]
I also downgraded to the package to an older version 1.8

**Comment by sgerendasy** [comment]
@homanp This solved it for Android?

**Comment by homanp** [comment]
@sgerendasy no iOS.

**Comment by sgerendasy** [comment]
@homanp Oh gotcha. I think this issue is for issues loading on Android.

**Comment by sgerendasy** [comment]
I was able to get react-native-track-player running by uninstalling react-native-video@5.0.2. That package was using a different version of exoplayer.

**Comment by girish54321** [comment]
> I was able to get react-native-track-player running by uninstalling react-native-video@5.0.2. That package was using a different version of exoplayer.

@sgerendasy oh i will try that. i all so have react-native-video install in my project

**Comment by curiousdustin** [comment]
@girish54321 did this end up working for you?

@catmans1 do you also happen to have another media related module that may contain exoplayer?

**Comment by catmans1** [comment]
@curiousdustin I also have `react-native-video` in project, my project is using exoplayer.

**Comment by curiousdustin** [comment]
@catmans1 Are you able to identify if it is using a conflicting version of exoplayer?

**Comment by catmans1** [comment]
@curiousdustin 
I'm using (with `"react-native-video": "^4.4.4",`)
```
implementation('com.google.android.exoplayer:exoplayer:2.9.3') {
        exclude group: 'com.android.support'
    }
```
and the version `react-native-track-player` is using (in `react-native-track-player/android/build.gradle`)
```
 def exoPlayerVersion = safeExtGet("exoPlayerVersion", '2.10.1')
```
If i identify incorrect, please correct me.

**Comment by alex521** [comment]
same to me ,after remove react-native-video , it's working

**Comment by alex521** [comment]
java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.ExoPlayer$EventListener"

**Comment by curiousdustin** [comment]
@catmans1 Are you able to use a more recent version of `react-native-video`? Looks like they are using exoplayer `2.10.5` now which may be compatible with this `react-native-track-player`.

**Comment by catmans1** [comment]
@curiousdustin 
Thank you for your contribution!
Now, I am not working with that. I will upgrade latest version of `react-native-video` and will let you know later.
And which version is stable on Android and iOS?

**Comment by alex521** [comment]
react native video 5.1.0-alpha6  is working

**Comment by girish54321** [comment]
@curiousdustin i had react native video all ready install but im not using this package 
im using old version now  https://github.com/tanguyantoine/react-native-music-control  
with react native video to play audio files (network files 'url') and react-native-music-control for notification control

**Comment by Guichaguri** [comment]
Different ExoPlayer versions will crash no matter what. Now that react-native-video started using ExoPlayer too, we should add to the documentation explaining that you should either pick matching ExoPlayer versions or use their default Android player version in order for it to work.

I'll be closing this for now, feel free to reopen if the issue was not related to different ExoPlayer versions.

**Comment by janlonden** [comment]
I'm getting the same problem. I've searched `node_modules` and there are no other packages that use exoplayer. I'm using rn 0.61.5 and track-player 1.2.3.

The app is built successfully but the metro server terminal closes in just a couple of seconds after it starts. I've tried without linking and with manual linking.
