### ISSUE TITLE
Player fails to resume in the background after fetching next track in the background lock mode (iOS)

### ISSUE THREAD

**Issue by Sathyanarayan09** [react-native-kit/react-native-track-player#891]
React-native version: 0.60.4
React-native-track-player: 1.2.0 
  
Issue related to: https://github.com/react-native-kit/react-native-track-player/issues/709

Failure to start playing when switching tracks from background. In this case, the lock screen controls change to a very generic setup showing the Apple music logo and other items that seem like defaults. 

The above mention issue still persists, please confirm if this issue has a solution or still work under progress? we are facing this issue on production app.

**Comment by parthkanani93** [comment]
Have you fix this issue?
