### ISSUE TITLE
usePlaybackState is not a fucntion

### ISSUE THREAD

**Issue by EhteshamAnwar** [react-native-kit/react-native-track-player#894]
# Configuration

I am using 
"react-native-track-player": "^2.0.0-rc10", with 
react-native 0.62.x
Build target: iOS

I am getting this error, I have tried importing it directly from the hook, without it. no luck. 

![error](https://user-images.githubusercontent.com/16754151/79128525-18684900-7dbd-11ea-871d-bc56159af362.jpeg)

# Issue

# Code

Show us the code you are using

**Comment by Xammie** [comment]
Looks like you are using the default export. This import should work.

    import TrackPlayer, {usePlaybackState} from "react-native-track-player";

**Comment by EhteshamAnwar** [comment]
@Xammie  I have the same import in my code.
import TrackPlayer, { usePlaybackState } from "react-native-track-player";

and this is how I am using usePlaybackStater. 

const playbackState = TrackPlayer.usePlaybackState();

this works on Android, but this is not working on ios.  Please tell me if I am doing something wrong.

**Comment by Xammie** [comment]
@EhteshamAnwar You are using the default export named `TrackPlayer`. You should use the hook like this. Hope this helps.

    import TrackPlayer, { usePlaybackState } from "react-native-track-player";

    function MyComponent() {
        const state = usePlaybackState();

        return (
            ...
        )
    }
