### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by ds8k** [react-native-kit/react-native-track-player#896]
I'm getting a hard crash on iOS with the following error after adding tracks to the trackplayer:

```
Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```

It points to this code in `NowPlayingInfoCenter.swift`:
```
public func set(keyValue: NowPlayingInfoKeyValue) {
        _info[keyValue.getKey()] = keyValue.getValue()
        self._infoCenter.nowPlayingInfo = _info
    }
```

How can I guard against this happening? I can't tell what key value it's trying to get that'd cause this crash

**Comment by taylorpringle** [comment]
Hi @ds8k,

I am also having this issue, did you fix the error?

Thanks

**Comment by JonahElbaz** [comment]
Why was this closed? It still seems to be persistent.

**Comment by marcinkieruzel** [comment]
Hi, here the same - I play hls streams
