### ISSUE TITLE
Got ld: library not found for -lswiftCoreAudio for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation) error when I build on xcode

### ISSUE THREAD

**Issue by kgom1028** [react-native-kit/react-native-track-player#90]

**Comment by kgom1028** [comment]
Hello, I tried to create a new project 
react-native init XXX
npm install react-native-track-player --save
react-native link
then run on xcode 9.2
react-native version: 0.51.0
I got link error when I build 

library not found for -lswiftCoreAudio for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation) error
Any body have experience on this?

**Comment by Guichaguri** [comment]
Please, read the troubleshooting section in the wiki: https://github.com/react-native-kit/react-native-track-player/wiki/Installation#ios-library-not-found-for--lswiftcoreaudio-for-architecture-x86_64

**Comment by phil-andrews** [comment]
In case anyone else comes here looking, the above solution also solves the standard Xcode `Mach-0 Linker Error`.
