### ISSUE TITLE
Notification Icon

### ISSUE THREAD

**Issue by lnickdnguyen** [react-native-kit/react-native-track-player#901]
# Configuration
```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.28 GB / 7.73 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_171 - C:\Program Files\Java\jdk1.8.0_171\bin\javac.EXE
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.1 => 0.62.1
```

What `react-native-track-player` version are you using?
1.2.2

# Issue
Can't reconfigure notification icon.

# Code
```
await TrackPlayer.setupPlayer().then(() => { 
                    TrackPlayer.updateOptions({                        
                        stopWithApp: false,
                        capabilities: [
                            TrackPlayer.CAPABILITY_PLAY,
                            TrackPlayer.CAPABILITY_PLAY_FROM_ID,
                            TrackPlayer.CAPABILITY_PAUSE,
                            TrackPlayer.CAPABILITY_STOP,
                            TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                            TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
                            TrackPlayer.CAPABILITY_JUMP_FORWARD,
                            TrackPlayer.CAPABILITY_JUMP_BACKWARD,
                            TrackPlayer.CAPABILITY_SEEK_TO
                        ],
                        notificationCapabilities: [
                            TrackPlayer.CAPABILITY_PLAY,
                            TrackPlayer.CAPABILITY_PAUSE,
                            TrackPlayer.CAPABILITY_STOP,
                            TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
                            TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
                            TrackPlayer.CAPABILITY_SEEK_TO
                        ],
                        jumpInterval: 10,            
                        icon: require('./assets/AppLogo.png')
                    });
});
```

**Comment by Guichaguri** [comment]
Whats the resolution of AppLogo.png? Does is have an alpha channel? Is it square? Can you send the icon file so we can take a look?

**Comment by lnickdnguyen** [comment]
> Whats the resolution of AppLogo.png? Does is have an alpha channel? Is it square? Can you send the icon file so we can take a look?

The dimensions are 487x464, so nearly square. Not sure what an alpha channel is, nor how to check for it. Here's the image:
![icon](https://user-images.githubusercontent.com/31356448/79643100-e5c8a280-8166-11ea-8124-c948076eff5b.png)

**Comment by Guichaguri** [comment]
It needs to be an exact square, and the shadows might also be an issue, it needs all colors to be either fully transparent or fully opaque. Also, that's a pretty big icon, you should provide a smaller (up to 92x92).

Finally, Android also recommends a solid white icon over a transparent background.

**Comment by lnickdnguyen** [comment]
> It needs to be an exact square, and the shadows might also be an issue, it needs all colors to be either fully transparent or fully opaque. Also, that's a pretty big icon, you should provide a smaller (up to 92x92).
> 
> Finally, Android also recommends a solid white icon over a transparent background.
> 
> Edit: [This online tool](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html) may help you convert the icon to fit the requirements

@Guichaguri I tried using the online tool and it still did not work. I've tried pasting my own logo without shadows, as well as using the Clipart and Text generating templates there with no luck. Do you have any other tips as to what might be causing the issue?

**Comment by curiousdustin** [comment]
@Guichaguri , does work in debug mode? 

It's not working for me either. I can see that the code makes it to `getIcon`, but defaults to the default icon because it doesn't pass this part:

**Comment by curiousdustin** [comment]
It does work in release builds.

@lnickdnguyen have you tested a release build?

**Comment by lnickdnguyen** [comment]
> It does work in release builds.
> 
> @lnickdnguyen have you tested a release build?

Yes, I just tried it today and it works! Thank you so much for you help!

**Comment by maartenvandillen** [comment]
A small transparent icon works indeed. I had mistaken the artwork graphic, which is much bigger (like the size of the launcher app icon) for the notification icon.
