### ISSUE TITLE
Slow performance on android

### ISSUE THREAD

**Issue by ariona** [react-native-kit/react-native-track-player#91]
Hi, I got slow performance on android even on release build. The UI become slow when playing the media.

I am using react native navigation and mobx as state management. For full code you can access it in [my repo](https://gitlab.com/ariona/asaticloud.git)

**Comment by Guichaguri** [comment]
What do you mean by "slow UI"? Does the whole device slow down or just the app's framerate drop?

**Comment by ariona** [comment]
Restarting the dev machine and it's gone, don't know what causes it (emulator bug maybe?)
