### ISSUE TITLE
Player Controls (previous, play, next) are disabled on lock screen in iPad.

### ISSUE THREAD

**Issue by kgom1028** [react-native-kit/react-native-track-player#92]
Here is my code to setup the player.
Player Controls on lock screen is disabled.
			TrackPlayer.updateOptions({
				// One of RATING_HEART, RATING_THUMBS_UP_DOWN, RATING_3_STARS, RATING_4_STARS, RATING_5_STARS, RATING_PERCENTAGE
			    ratingType: TrackPlayer.RATING_5_STARS,
			    // The maximum height or width that the artwork can have. It will be resized when necessary. The lower the number is, the lower is the memory used
				maxArtworkSize: 800,
		        // An array of media controls capabilities
			    // Can contain CAPABILITY_PLAY, CAPABILITY_PAUSE, CAPABILITY_STOP, CAPABILITY_SEEK_TO,
			    // CAPABILITY_SKIP_TO_NEXT, CAPABILITY_SKIP_TO_PREVIOUS, CAPABILITY_SET_RATING
			    capabilities: [
			        TrackPlayer.CAPABILITY_PLAY,
			        TrackPlayer.CAPABILITY_PAUSE,
			        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
			        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
			        TrackPlayer.CAPABILITY_SEEK_TO
			    ],
			    // Notification Color (Must be an ARGB Hexadecimal number)
			    color: 0x2ecc71
			});
			TrackPlayer.setupPlayer().then(() => {
				var index = 0;
				this.state.songs.map(song => {
					index ++;
					TrackPlayer.add({
				        id: 'track'+index,
				        url: song.url,
				        title: song.title,
				        artist: song.artist,
				        artwork: song.songImage
				    });
				});
	 
			    // Starts playing it
			    TrackPlayer.play();
			 
			});

**Comment by dcvz** [comment]
Hello, this issue was previously reported and addressed here: https://github.com/react-native-kit/react-native-track-player/issues/77
