### ISSUE TITLE
Crash when in the url there is no streaming content

### ISSUE THREAD

**Issue by fcaride** [react-native-kit/react-native-track-player#924]
**Describe the bug**
The app crashes when i put an url that has no streaming content (like www.google.com) in IOS on release. If i use an invalid url like "hello" it doesnt happen
**To Reproduce**
Use the code and run the app on release mode on IOS

**Environment (please complete the following information):**

> System:
>     OS: macOS 10.15.3
>     CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
>     Memory: 786.83 MB / 16.00 GB
>     Shell: 5.7.1 - /bin/zsh
>   Binaries:
>     Node: 13.10.1 - ~/.nvm/versions/node/v13.10.1/bin/node
>     Yarn: 1.22.1 - ~/.nvm/versions/node/v13.10.1/bin/yarn
>     npm: 6.13.7 - ~/.nvm/versions/node/v13.10.1/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.9.1 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
>     Android SDK:
>       Android NDK: 21.1.6352462
>   IDEs:
>     Android Studio: 3.6 AI-192.7142.36.36.6392135
>     Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
>   Languages:
>     Java: javac 12 - /usr/bin/javac
>     Python: 2.7.16 - /usr/bin/python
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 16.11.0 => 16.11.0
>     react-native: 0.62.2 => 0.62.2
>   npmGlobalPackages:
>     *react-native*: Not Found

What `react-native-track-player` version are you using?
Im using the 1.2.3 version
Are you testing on a real device or in the simulator? Which OS version are you running?
It happens on real device and in the simulator

**Code**
```
const prueba = {
      id: 1,
      artwork: 'https://softfabrics.com.mx/images/galleria/factura/01.jpg',
      title: 'prueba',
      artist: 'artist',
      url: 'www.google.com'
    };
    await TrackPlayer.add(prueba);
    await TrackPlayer.play();
```

**Comment by curiousdustin** [comment]
@fcaride , can you test the same on Android?

You really shouldn't be providing URL's that are not audio content, but it would be nice to protect the app from crashing in this case.

**Comment by fcaride** [comment]
In android it doesnt crashes

**Comment by curiousdustin** [comment]
ok, nice. Good to know. Thanks.

**Comment by fcaride** [comment]
My bad its happening in Android release also

**Comment by fcaride** [comment]
Looking at crashalytics im getting this error message.
Fatal Exception: com.facebook.react.common.d
ReferenceError: Property 'Event' doesn't exist, js engine: hermes, stack: anonymous@1:962306 anonymous@1:511350 value@1:62459 value@1:57754 anonymous@1:56286 value@1:57352 value@1:56244

**Comment by fcaride** [comment]
In the previous version it didnt happen (1.2.2)

**Comment by puckey** [comment]
Can you post the playback-error callback you are using?

**Comment by fcaride** [comment]
I found what was happening!. I was using the class Event of the v2.0 and for one reason it only was crashing on release. Thank you so much. Sorry for your trouble!!
