### ISSUE TITLE
metadata QUESTION

### ISSUE THREAD

**Issue by holospeed** [react-native-kit/react-native-track-player#93]
Hi!

I am wondering, is it possible to change (update) the artwork, artist and title during the track is playing ? 
I love to play internet radio stream on my app and change the artist data (title, artist, artwork) when a new song starts.

**Comment by Guichaguri** [comment]
Not yet, but I'll consider it as a suggestion :)

**Comment by puckey** [comment]
For mp3 streams, we could use something like this – but it does involve changes to the internals of the ExoPlayer library.: https://github.com/google/ExoPlayer/issues/466#issuecomment-290358993

**Comment by adidoes** [comment]
Any updates on this?

**Comment by questionablequestion** [comment]
Bump. Any update?

**Comment by cgomezmendez** [comment]
No need for internal modifications of exoplayer anymore it seems...

**Comment by Grandmac** [comment]
It would be a great feature ! any update ?
