### ISSUE TITLE
Module isn't working property

### ISSUE THREAD

**Issue by ithustle** [react-native-kit/react-native-track-player#931]
**Describe the bug**
I think `.setupPlayer()` it doesn't init the module.

**Code**
`await TrackPlayer.setupPlayer({})`

**Comment by curiousdustin** [comment]
Can you please provide more details? What version are you using?

**Comment by ithustle** [comment]
I was using 2.0.0-rc13 version and for nothing it stop working... I removed cache, remove the module and reinstall and not success. So, I tried use 1.2.3 version and same.

**Comment by curiousdustin** [comment]
Can you try the example app in 1.2.3?

**Comment by ithustle** [comment]
I'm building now an example app for test. If it fail, I try the example app

**Comment by ithustle** [comment]
In brand new project is working fine. I can't figure it out why it stops working on my project.

**Comment by mcdit** [comment]
I just had the same issue on android. In my case it was the
`TrackPlayer.TrackPlayerEvents.PLAYBACK_STATE` event in the `useTrackPlayerEvents`

`useTrackPlayerEvents([TrackPlayer.TrackPlayerEvents.PLAYBACK_STATE], async ()=>{});`
prevented await TrackPlayer.setupPlayer({});

I'll try to use the hook now

**Comment by Guichaguri** [comment]
As you didn't provided steps to reproduce the issue and it seems you're not facing it anymore, I'll be closing it.
