### ISSUE TITLE
multiple player same time

### ISSUE THREAD

**Issue by mtalhagaoglu** [react-native-kit/react-native-track-player#934]
hi. I have a app that use react native youtube iframe and react native track player. i need to use both them at the same time but on ios they can't work together, one of them have to stop. android works perfectly but ios gives me problem. is there anyway for working these two library together?

**Comment by curiousdustin** [comment]
You could test out various settings for `iosCategory`, `iosCategoryOptions`, and `iosCategoryMode`. 

https://react-native-track-player.js.org/documentation/#setupplayeroptions

Not sure if they will help.

**Comment by mtalhagaoglu** [comment]
i think this will help me. but i didn't understand how to setup options with these. can you explain? thanks
https://developer.apple.com/documentation/avfoundation/avaudiosession/category/1616509-playback

**Comment by mtalhagaoglu** [comment]
mixWithOthers option worked like a charm. thanks
