### ISSUE TITLE
Can't play local mp3 on IOS with RNFS

### ISSUE THREAD

**Issue by TheMax98000** [react-native-kit/react-native-track-player#947]
Hello, my app is a webradio, i have 2 tabs ("Online mode" and "Offline mode").

On "Online mode" i just add 1 track to the queue with the url on the stream of my webradio, it work well on Android and IOS.

On "Offline mode" i use React Native FS to first download all songs into app cache, then generate a playlist from theses files to play them locally.

It works well on Android, but in IOS i tried many things but TrackPlayer stuck at buffering state ^^'

There is my code to adding tracks to queue : 

if (Platform.OS === 'android') {

      var filePrefix = 'file://';

    } else {

      var filePrefix = 'file://';

    }

TrackPlayer.add({
        id: id_musique,
        url: filePrefix + RNFS.CachesDirectoryPath + '/songs/' + encodeURI(musiqueName) + '.mp3',
        title: musiqueName,
        artist: '',
      }).catch(err => {
        console.log(err);
});

I tried without "file://", i also tried with "file:///", but it doesn't work :/

I want to specify that i tested all of this on real device (i don't think it's a simulator issue)

Thank in advance,
Kind Regards.

**Comment by curiousdustin** [comment]
To narrow this down, if you include an mp3 file in your app when you build it, does it have the same behavior?

**Comment by TheMax98000** [comment]
If i play a file that i put manually on my app files like this : 

import localTrack from '../assets/test.mp3';

TrackPlayer.add({
id: id_musique,
url: localTrack,
title: musiqueName,
artist: '',
}).catch(err => {
console.log(err);
});

It work fine :/

**Comment by curiousdustin** [comment]
What if you use a `file://` path instead of import/require?

**Comment by TheMax98000** [comment]
where am i supposed to put my test file ? And more important, what filepath must i use ?

Thank you for helping me ^^

**Comment by TheMax98000** [comment]
Hello, i tried fews things and i managed to make it work but it's not what i want.

I use React Native FS to manage files and filepaths : https://github.com/itinance/react-native-fs#API

As you can see on "constants" section there are fews constants to get filepaths.

I tried to play a test mp3 file that i manually copy on the desired filepath on my simulator via terminal.

I tried this : 

var localTrack = 'file://' + RNFS.CachesDirectoryPath + '/test.mp3'; --> It doesn't work
var localTrack = 'file://' + RNFS. MainBundlePath + '/test.mp3'; --> It doesn't work
var localTrack = 'file://' + RNFS. DocumentDirectoryPath + '/test.mp3'; --> It work !!!

The problem was i store my mp3s on RNFS.CachesDirectoryPath and i really can't store them on Document Directory...

Why Trackplayer won't play files in cache directory ? It work on Android... :/

**Comment by curiousdustin** [comment]
When it doesn't work with the CachesDirectoryPath, what is an example of the full path?

Are there any errors or other logs in Xcode when it does not play?

**Comment by TheMax98000** [comment]
There is the full path that it try to load : 

file:///Users/user173395/Library/Developer/CoreSimulator/Devices/104590AC-E7C1-48FC-A5F0-A06440278444/data/Containers/Data/Application/9B06E475-988B-4C5A-B42F-F694810E2FB6/Library/Caches/songs/test.mp3

BUT when i just retested i discovered what is the true problem, it now worked with my test file, but not with my true files and the only difference i see is my true files have spaces in their name...

I tried this : 

var localTrack = 'file://' + RNFS.CachesDirectoryPath + '/songs/kuraberarekko - Tsuyu.mp3';

TrackPlayer.add({
        id: id_musique,
        //url: filePrefix + RNFS.CachesDirectoryPath + '/songs/' + encodeURI(musiqueName) + '.mp3',
        url: encodeURI(localTrack),
        title: musiqueName,
        artist: '',
      }).catch(err => {
        console.log(err);
      });

But it doesn't work, xcode say to me "Starting/Resuming playback" like all work fine (but definitely no XD)

The generated full path of this song with spaces in her name is : 

file:///Users/user173395/Library/Developer/CoreSimulator/Devices/104590AC-E7C1-48FC-A5F0-A06440278444/data/Containers/Data/Application/66D20310-A9B3-44CB-AF3B-7FDA67BE19D6/Library/Caches/songs/kuraberarekko%20-%20Tsuyu.mp3

**Comment by curiousdustin** [comment]
Are you able to test that theory another way? By converting spaces to underscores (or whatever) when you initially download the track?

**Comment by TheMax98000** [comment]
Just tested now, this don't work :  

Code : 

var localTrack = 'file://' + RNFS.CachesDirectoryPath + '/songs/test file.mp3';

TrackPlayer.add({
id: id_musique,
//url: filePrefix + RNFS.CachesDirectoryPath + '/songs/' + encodeURI(musiqueName) + '.mp3',
url: encodeURI(localTrack),
title: musiqueName,
artist: '',
}).catch(err => {
console.log(err);
});

Filepath : 

file:///Users/user173395/Library/Developer/CoreSimulator/Devices/104590AC-E7C1-48FC-A5F0-A06440278444/data/Containers/Data/Application/A4270DD8-465E-496C-AE03-50ECC920543C/Library/Caches/songs/test%20file.mp3

------------------------------

And this work : 

Code : 

var localTrack = 'file://' + RNFS.CachesDirectoryPath + '/songs/test-file.mp3';

TrackPlayer.add({
id: id_musique,
//url: filePrefix + RNFS.CachesDirectoryPath + '/songs/' + encodeURI(musiqueName) + '.mp3',
url: encodeURI(localTrack),
title: musiqueName,
artist: '',
}).catch(err => {
console.log(err);
});

Filepath : 

file:///Users/user173395/Library/Developer/CoreSimulator/Devices/104590AC-E7C1-48FC-A5F0-A06440278444/data/Containers/Data/Application/423CDBAA-5B47-45A3-A22E-EE46F01BA273/Library/Caches/songs/test-file.mp3

----------------------

I'm really confused, why spaces causes so many problem ? ^^

**Comment by curiousdustin** [comment]
This is sounding like a bug on iOS. 

Until a fix is found, I would recommend saving your files without spaces.

**Comment by TheMax98000** [comment]
Oh...... ok, thank you for your help :)

**Comment by TheMax98000** [comment]
After others tests, i want to add th fact that is bug not only with space in names but also [ and ]

**Comment by curiousdustin** [comment]
@TheMax98000 , are you able to test this change #950?
