### ISSUE TITLE
Cast button not working?

### ISSUE THREAD

**Issue by pmagnussen** [react-native-kit/react-native-track-player#95]
Has anyone experienced the cast button not working? Or do you know what might be wrong with my code?

My render method looks like this:
    `render() {
            var resource = require('../resources/play.png')
            if (this.state.playing) {
                resource = require('../resources/pause.png')
            }

        return (
            <View style={styles.background}>
                <ListView
                    enableEmptySections={true}
                    style={styles.listView}
                    dataSource={this.state.dataSource}
                    renderRow={(rowData) => <MyListItem onPressItem={this._onPressItem} song={rowData}></MyListItem>} />

                <View style={styles.bottomView}>
                    <TouchableHighlight onPress={this.onPressBackwardsButton} underlayColor="transparent">
                        <Image
                            style={styles.backwardButton}
                            source={require('../resources/backward.png')}
                        />
                    </TouchableHighlight>

                    <TouchableHighlight onPress={this.onPressPlayPauseButton} underlayColor="transparent">
                        <Image
                            style={styles.playButton}
                            source={resource}
                        />
                    </TouchableHighlight>

                    <TouchableHighlight onPress={this.onPressForwardButton} underlayColor="transparent">
                        <Image
                            style={styles.forwardButton}
                            source={require('../resources/forward.png')}
                        />
                    </TouchableHighlight>

                    <CastButton ref="myCastButton"/>
                    
                </View> 
            </View>
        );
    }`

CastButton calls this method:
`openDialog() {
        Alert.alert('Alert Title');
        this.refs['myCastButton'].showDialog();
    }`

As a sanity check, the other buttons in the same view are working. E.g. onPressPlayPauseButton gets called.

**Comment by Guichaguri** [comment]
React Native still uses an older version of the support library, and because of that, we have to use an older version of the Cast SDK. Turns out this old version has a lot of weird bugs, sometimes it works and sometimes it doesn't.

We want split the Cast support into an addon module so we can fix all these issues and also add support to iOS and UWP.

**Comment by Guichaguri** [comment]
This issue don't belongs to this project anymore. The cast integration is being moved to [react-native-track-casting](https://github.com/react-native-kit/react-native-track-casting)
