### ISSUE TITLE
When I will Clicked a song that song will play. Is it possible?

### ISSUE THREAD

**Issue by TechAsif** [react-native-kit/react-native-track-player#954]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by curiousdustin** [comment]
Yes, this is possible.

```js
await TrackPlayer.skip('track-id');
await TrackPlayer.play();
```

If you still have questions, please fill out the issue template.

**Comment by TechAsif** [comment]
Thank you very much, Sorry for not filling issue template.
