### ISSUE TITLE
TrackPlayer.STATE_NONE (undefined is not an object)

### ISSUE THREAD

**Issue by chrissbendel** [react-native-kit/react-native-track-player#96]
Hey there devs - This library perfectly fits the bill for what I need in my app. Unfortunately haven't been able to get past this step. Some information:

React native version: 0.51.0
react-native-track-player version: tried on both latest and dev build
building on iOS - Tried both iOS 8 and 11

This error happens when I simply import it using 
```import TrackPlayer from 'react-native-track-player';```

Can't even get past this step to test out any other functionality. This is happening from lib/index.js line 95 (```module.exports.STATE_NONE = TrackPlayer.STATE_NONE;```), and I imagine this would happen on every other module.exports.{THING} is happening as well.

Let me know if you've got anything in mind for this issue - Happy to provide more information if you need it too.

![screen shot 2017-12-17 at 7 02 31 pm](https://user-images.githubusercontent.com/8879108/34085338-11f79d70-e35d-11e7-839e-ce593877e328.png)

*Editing here and leaving the original post as is*
Tried this on v 0.2.0, 0.2.1, 0.2.2, and dev branch. react-native linked as well - Still nothing, same error

**Comment by Guichaguri** [comment]
The issue is probably `TrackPlayer` being undefined for some reason. Can you send the code that can reproduce this problem?

**Comment by chrissbendel** [comment]
hey @Guichaguri , the repo I'm using this in is here https://github.com/chrissbendel/hosemobile . I just pushed up all my changes to master with the track-player integration

**Comment by Guichaguri** [comment]
Does it only happen on iOS?

**Comment by chrissbendel** [comment]
@Guichaguri personally have not tried android yet - Moved over to a new computer and have not yet been able to install android studio. However if you'd like me to test there I can get that spun up now and report back. I am also chatting to you in gitter chat if you'd like to move this conversation there

**Comment by chrissbendel** [comment]
@Guichaguri looks like everything is A-okay on android 

Notice in the android console I console.logged the trackplayer object and things seem to be fine and the app loads up no problem. Must be an ios specific issue. Let me know if you need anymore information to dig into this bug
![screen shot 2017-12-17 at 9 15 58 pm](https://user-images.githubusercontent.com/8879108/34087217-87670890-e36f-11e7-9975-07d4fdd79a85.png)

**Comment by Guichaguri** [comment]
@dcvz can you take a look at this?

**Comment by chrissbendel** [comment]
@Guichaguri  @dcvz  Quick update from this morning - Seems to be working now (at least the project compiles and I can open the app without errors while importing the track player).

Couple things you guys may want to be aware of for iOS users.

1) React-native link seemed to be the cause of the problems - Seems that ```libRNTrackPlayer.a``` was not being added to the build phases automatically from react-native link.
2) This is working for me using the dev branch.
3) You may want to update something in the installation wiki for instructions on how to manually link this library through xcode. I'm assuming you guys know how to do this, but a quick step by step is 
    a) Check if RNTrackPlayer.xcodeproj is in Libraries folder. If not, add this file from node_modules/react-native-track-player/ios/RNTrackPlayer.xcodeproj
    b) in project's Build Settings -> Link Binary with Libraries check if libRNTrackPlayer.a is in the list. If not, press the "+" button and find it in the list and add it.

If you want to update the docs, here are some screenshots of the process so people can have a visual aid.

![screen shot 2017-12-18 at 9 26 35 am](https://user-images.githubusercontent.com/8879108/34110821-cd23bc3c-e3d5-11e7-8e46-32076ca575bf.png)
![screen shot 2017-12-18 at 9 27 16 am](https://user-images.githubusercontent.com/8879108/34110822-cd410dd2-e3d5-11e7-9aa3-8f5bfbaa559a.png)
![screen shot 2017-12-18 at 9 27 23 am](https://user-images.githubusercontent.com/8879108/34110824-cd6bc82e-e3d5-11e7-993a-b46652983786.png)

Just so you know - everything seems to be working fine now. I would advise against using "react-native link" in the docs in case this issue happens for anybody else, or add a caveat saying if you run into a trackplayer undefined error - do the steps manually as that is what fixed it for me.

**Comment by SatoshiInoue** [comment]
I'm having a similar issue. I have dummy.swift and also 'react-native link' linked the library fine. However, if I do react-native run-ios, build fails with the following message:
`=== BUILD TARGET RNTrackPlayer OF PROJECT RNTrackPlayer WITH CONFIGURATION Debug ===
Check dependencies
Swift is not supported for static libraries.
** BUILD FAILED **`

**Comment by SatoshiInoue** [comment]
Please disregard my comment. As I commented on #102, I had XCode 8 and I had to upgrade to Xcode 9 to resolve this issue. It works now and I can stream both HLS and IceCast successfully on the iOS Simulator.
