### ISSUE TITLE
Error: Track is missing a required key

### ISSUE THREAD

**Issue by chrissbendel** [react-native-kit/react-native-track-player#97]
Hi there - Running into an issue loading up an array of tracks into the player. Here's some information.

Checking the docs it looks like I have all of the required keys for the track object structure.
I am mapping an array of data I have into the format the player wants like so
```
const mapTracksForPlayer = (show) => {
  return show.tracks.map(track => ({
    id: track.id,
    url: track.mp3,
    title: track.title,
    artist: 'Phish',
    album: show.date,
    genre: 'Phish',
    artwork: 'https://s3.amazonaws.com/hose/images/' + show.date + '.jpg'
  }));
}
```

I am then passing the returned array of data into the trackplayer methods like so
```
    TrackPlayer.setupPlayer().then(() => {
      TrackPlayer.add(tracksForPlayer).then(() => {
        // TrackPlayer.skip(track.id);
        TrackPlayer.play();
      });
    })
```

Wondering if i'm going crazy and misspelled something but cannot seem to find any small issues like that in my code. Some screenshots for what one of the objects in the array looks like, as well as the error message from the console.

![screen shot 2017-12-18 at 11 35 08 am](https://user-images.githubusercontent.com/8879108/34116821-b02b89c2-e3e7-11e7-8e5d-5feda625b235.png)
![screen shot 2017-12-18 at 11 35 17 am](https://user-images.githubusercontent.com/8879108/34116822-b03aeaac-e3e7-11e7-847a-ab1ae5425c13.png)

**Comment by chrissbendel** [comment]
Found the problem - Closing this issue as I followed the example in the readme (using await and async). This should be added to the docs if add is an asynchronous call.

**Comment by viveksri96** [comment]
@chrisbendel I'm encountering the same issue.Can you please share the fix you did to solve this error.Also this only persists in iOS.Android works well

**Comment by jeffreyrajanofficial** [comment]
@chrisbendel Can you please post the solution here? @viveksri96  Have you fixed this issue?

**Comment by jasongaare** [comment]
For me, my track id was NOT a string... once I changed it to a string this error went away

**Comment by saintograph** [comment]
On the iOS, the `title` key is required.

**Comment by anhhh11** [comment]
Digging code; id, title, artist, url required.
 ```
  init?(dictionary: [String: Any]) {
        guard let id = dictionary["id"] as? String,
            let title = dictionary["title"] as? String,
            let artist = dictionary["artist"] as? String,
            let url = MediaURL(object: dictionary["url"])
            else { return nil }
     
```

**Comment by Guichaguri** [comment]
You don't need to dig code, it's right [in the Track Object](https://react-native-kit.github.io/react-native-track-player/documentation/#track-object) documentation.

> Only the `id`, `url`, `title` and `artist` properties are required for basic playback

**Comment by AgustinJimenez** [comment]
> Digging code; id, title, artist, url required.
> 
> ```
>  init?(dictionary: [String: Any]) {
>        guard let id = dictionary["id"] as? String,
>            let title = dictionary["title"] as? String,
>            let artist = dictionary["artist"] as? String,
>            let url = MediaURL(object: dictionary["url"])
>            else { return nil }
>     
> ```

this helped me

**Comment by fukemy** [comment]
i got this error when play local file
***/Users/thehe/Library/Developer/CoreSimulator/Devices/04366B0E-21E7-4F70-8F8B-C92B210331B3/data/Containers/Data/Application/4342AF29-F7F6-442F-A812-AB20AB671F13/Documents/audio.wav***

**Comment by luis-antonio-dev** [comment]
Using 

> "react-native": "0.65.1",
"react-native-track-player": "^2.1.2"

`id` isn't required

![image](https://user-images.githubusercontent.com/35160032/180831954-3fd91297-1bdd-4f8b-8028-b5eb02304dc3.png)

**Comment by karltaylor** [comment]
> You don't need to dig code, it's right [in the Track Object](https://react-native-kit.github.io/react-native-track-player/documentation/#track-object) documentation.
> 
> > Only the `id`, `url`, `title` and `artist` properties are required for basic playback

@Guichaguri do you mind updating doc link?

**Comment by jameno** [comment]
According to the [3.2 documentation](https://react-native-track-player.js.org/docs/api/objects/track) only the `url`, `title` and `artist` properties are required for basic playback
