### ISSUE TITLE
No compact player nor notification player showing

### ISSUE THREAD

**Issue by PaulExina** [react-native-kit/react-native-track-player#984]
# Configuration

`react: 16.11.0 => 16.11.0`
`react-native: 0.62.2 => 0.62.2` 

What react-native-track-player version are you using?

`react-native-track-player => 2.0.0-rc13`

# Issue
The notification player is not showing while the track is still playing.

# Code
####Setup
```js
const App = () => {
  useEffect(() => {
    TrackPlayer.setupPlayer();

    TrackPlayer.updateOptions({
      stopWithApp: false,
      alwaysPauseOnInterruption: true,
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_JUMP_FORWARD,
        TrackPlayer.CAPABILITY_JUMP_BACKWARD
      ],
      compactCapabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_JUMP_FORWARD,
        TrackPlayer.CAPABILITY_JUMP_BACKWARD
      ]
    });
  });
```

### Actual use 
```js
      TrackPlayer.reset();
      TrackPlayer.add({
        id: track.id,
        url: mediaURL,
        title: track.title,
        artist: track.artist,
        artwork: track.artwork,
        programID: track.programID,
        status: track.status,
        questions: track.questions
      }).then(() => {
        TrackPlayer.play();
      });
```

What more do I need to do to display the locked screen player ?

**Comment by Guichaguri** [comment]
Which platform are you seeing this issue? What is the version of the OS? Is there any crash logs?

**Comment by PaulExina** [comment]
I see this on iOS 13. There is no crash logs.

**Comment by curiousdustin** [comment]
Are you testing on a real device? The recent versions of the iOS simulators do not show the lock screen controls or other notification center features.

**Comment by PaulExina** [comment]
That makes more sense now. Thanks for your time and answers.
