### ISSUE TITLE
Failed on Bundle/Assemble Release (Android)

### ISSUE THREAD

**Issue by shiroze** [react-native-kit/react-native-track-player#988]
**Describe the bug**

> Execution failed for task ':app:bundleReleaseJsAndAssets'.
> > Could not list contents of '.../node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/_Pods.xcodeproj'. Couldn't follow symbolic link.

**To Reproduce**
`cd android && ./gradlew bundleRelease && cd ..`

**Environment (please complete the following information):**

> 
>     "react": "16.8.6",
>     "react-native": "0.60.5",
>     "react-native-track-player": "^2.0.0-rc13",
> 

**Code**
Everything works fine on debug

**Current Solution I apply**

Delete file `_Pods.xcodeproj`in path

> .../node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/

**Comment by gitsad** [comment]
I have the same issue, @shiroze doesn't your workaround crash building iOS?
